#!/usr/bin/env python3
"""IDA decl header(s) -> markdown field tables (offset, size, type, name, evidence comment) and enum tables.
usage: gen_md_tables.py out.md in1.h [in2.h ...]   (same input format as gen_cpp_types.py)"""
import re, sys
text = ''.join(open(p, encoding='utf-8').read() + '\n' for p in sys.argv[2:])
out = ['<!-- GENERATED by tools/ida/gen_md_tables.py from docs/formats/ida/*_types.h. DO NOT EDIT. -->', '']
for m in re.finditer(r'enum\s+(\w+)\s*:\s*([\w ]+?)\s*\{(.*?)\};', text, re.S):
    out.append('### enum `%s` (%s)' % (m.group(1), m.group(2).strip())); out.append('')
    out.append('| value | name |'); out.append('|---|---|')
    for it in m.group(3).split(','):
        it = it.strip()
        if '=' in it:
            n, v = [x.strip() for x in it.split('=')]
            out.append('| %s | `%s` |' % (v, n))
    out.append('')
for m in re.finditer(r'struct\s+(\w+)\s*\{(.*?)\n\};', text, re.S):
    out.append('### struct `%s`' % m.group(1)); out.append('')
    out.append('| offset | type | field | evidence |'); out.append('|---|---|---|---|')
    for line in m.group(2).split('\n'):
        line = line.strip()
        mm = re.match(r'(.+?)\s+(\*?\w+(?:\[\w+\])?);\s*//\s*(.*)$', line)
        if not mm: continue
        cm = mm.group(3); mo = re.match(r'\+(0x[0-9A-Fa-f]+)\s*(.*)', cm)
        off, ev = (mo.group(1), mo.group(2)) if mo else ('', cm)
        out.append('| %s | `%s` | `%s` | %s |' % (off, mm.group(1), mm.group(2), ev.replace('|', '/')))
    out.append('')
open(sys.argv[1], 'w', encoding='utf-8').write('\n'.join(out) + '\n')
