// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"


#pragma pack(push, 1)
struct DmpScriptFuncEntry {
	char name[32];  // +0x00 T D: NUL-terminated; bytes after the NUL are stale writer junk (keep raw for byte-exact output)
	uint32_t pc;  // +0x20 T D: byte offset into the code image
};
struct DmpScriptBank {
	char name[260];  // +0x000 T: upper-cased path string given to Script_LoadBank (full ".\data\script\..." path, not the basename)
	uint32_t codeImage;  // +0x104 T: malloc(codeSize + 2), last 2 bytes zero; also the scripts' mutable global memory
	int32_t codeImageBytes;  // +0x108 T: codeSize + 2
	int32_t funcCount;  // +0x10C T: nFuncs
	uint32_t funcTable;  // +0x110 T: malloc(36 * nFuncs), copied verbatim from the file
};
struct DmpScriptThread {
	int32_t allocated;  // +0x000 T
	char name[64];  // +0x004 T: only copied up to the NUL (rest keeps the previous occupant)
	int32_t stack[512];  // +0x044 T: element 0 unused; stack[sp] is the top; values and tags are separate dwords
	int32_t sp;  // +0x844 T
	uint32_t codeImage;  // +0x848 T: copy of g_ScriptBanks[bank].codeImage taken at bind time (Script_RebindThreadImage refreshes it)
	int32_t pc;  // +0x84C T: byte offset into codeImage
	int32_t bank;  // +0x850 T
	int32_t line;  // +0x854 T
	int32_t waitFlag;  // +0x858 T
	int32_t waitStartMs;  // +0x85C T
	int32_t waitDurMs;  // +0x860 T
};
struct DmpPackEntry {
	char name[56];  // +0x00 T: stored as (name[j] ^ (3*(j*i-28)) & 0xFF) for entry i
	uint32_t sizeXorKey;  // +0x38 T D: payload size ^ 0xFA261EFB
	uint32_t dataOffset;  // +0x3C T D: absolute file offset (stored plain)
};
struct DmpPackArchive {
	uint32_t hFile;  // +0x00 T
	int32_t entryCount;  // +0x04 T: second u32 of the file ^ 0xFA261EFB
	uint32_t entries;  // +0x08 T: malloc(64 * entryCount) decoded index
	uint32_t plainFlag;  // +0x0C T D: first u32 of the file; nonzero = payload stored plain, 0 = first 9696 bytes XOR-enciphered with the entry name (PackArchive_ReadEntry)
	uint32_t unused_10;  // +0x10 X: no reader found (PackArchive_Open does not write it; memset 0 only)
	uint32_t dataBase;  // +0x14 T: added by PackArchive_EntryDataOffset
};
struct DmpImgFileHeader {
	uint32_t reserved0;  // +0x00 T: read and discarded; 0 in every file
	uint32_t version;  // +0x04 T D: switch in Img_OpenAndReadHeader: 0..2 -> Img_ReadV0to2, 3..4 -> Img_ReadV3to4, 6 -> Img_ReadV6 (all 68 shipped files are 6)
	uint32_t paletteFlag;  // +0x08 T D: 0 in all files; if 0 the reader sets bitdepth 16
	uint32_t width;  // +0x0C T D
	uint32_t height;  // +0x10 T D
};
struct DmpImgBuffer {
	uint32_t pixels;  // +0x00 T
	int32_t hasAlphaPlane;  // +0x04 T
	uint32_t palette;  // +0x08 T
	int32_t rowBytes;  // +0x0C T: -1 for raw 16-bit data (selects Tex_CopyRaw16Pixels)
	int32_t bitDepth;  // +0x10 T: 16
	int32_t bottomUp;  // +0x14 T
	int32_t width;  // +0x18 T
	int32_t height;  // +0x1C T
};
struct DmpGfxImageSlot {
	char path[260];  // +0x000 T: IMG path set by GFX_SET_IMAGE (e.g. ".\\Data\\BG\\bg00.img")
	int32_t d3dFormat;  // +0x104 T: 25 (type 0) or 26 (type 1)
	uint32_t texture;  // +0x108 T: IDirect3DTexture8*, released by Tex_ReleaseSlot
	int32_t width;  // +0x10C T: GFX_SET_IMAGE argument 4 (used as the UV divisor)
	int32_t height;  // +0x110 T: GFX_SET_IMAGE argument 5
};
struct DmpGfxSpriteRect {
	float u0;  // +0x00 T: srcX / texW
	float v0;  // +0x04 T: srcY / texH
	float u1;  // +0x08 T: (srcX + srcW) / texW
	float v1;  // +0x0C T: (srcY + srcH) / texH
	float ofsX;  // +0x10 T
	float ofsY;  // +0x14 T
	float ofsZ;  // +0x18 T: GFX_DEFINE_SPRITE argument 5
	float ofsW;  // +0x1C T: argument 6
	float halfTexelU;  // +0x20 T: 0.1 / texW
	float halfTexelV;  // +0x24 T: 0.1 / texH
	float texWidth;  // +0x28 T
	float texHeight;  // +0x2C T
};
struct DmpEnemyType {
	int32_t id;  // +0x00 T: matches the ids pushed by STAGE_ENEMY_LIST
	uint32_t loadScripts;  // +0x04 T: GameMain_Init: Event_LoadResources (ENEMYnnn.FOB, InitFunction + InitPatternData x48)
	uint32_t loadTextures;  // +0x08 T: GameMain_Load: Event_LoadTextures (ZakoTextureLoad.fob LoadTextureCallBack(i) -> g_TexEnemy[i], format 25)
	uint32_t releaseAssets;  // +0x0C T: GameMain_Release
	uint32_t spawn;  // +0x10 T: script op ENEMY_SPAWN
	uint32_t onLevelCheck;  // +0x14 U: Event_CheckLevel for ids 0..39
};
struct DmpMatchSetup {
	int32_t reserved0;  // +0x00 T D: zeroed before Replay_WriteFileAtMatchEnd; 0 in all demos
	int32_t seed;  // +0x04 T D: Setup_GetSeed -> Rng_Seed in GameMain_Init (0 in all demos)
	int32_t lives;  // +0x08 T D: Setup field 0xBF7F80 (Player_SetLives value)
	int32_t scoreAttackTimeSel;  // +0x0C T D: Setup_GetScoreAttackTimeSel (1/2/3 -> 3600/10800/18000 frames)
	int32_t configC;  // +0x10 T D: Setup field 0xBF7F88 (Setup_SnapshotConfig copies 0x96B190..19C into 0xBF7F80..8C)
	int32_t configD;  // +0x14 T D: Setup field 0xBF7F8C
	int32_t stageScriptSet;  // +0x18 T D: Setup_SetStageScriptSet -> STAGEnn.FOB number
	int32_t entryKind;  // +0x1C T D: Setup_SetEntryKind
	int32_t gameMode;  // +0x20 T D
	int32_t stage;  // +0x24 T D: passed as arg0 of the stage script "Init"
	int32_t playerCount;  // +0x28 T D
	int32_t slotChara[6];  // +0x2C T D: Setup_GetSlotChara(i), -1 = empty seat; CHARAnn = value + 1
};
struct DmpReplayFrame {
	uint32_t rawInput[6];  // +0x00 T D: g_FrameInput[seat] = Input_GetRawWord(seat) for seats 0..5
};
struct DmpReplayFile {
	DmpMatchSetup setup;  // +0x00 T D: g_MatchSetup 0xBF7F78
	uint32_t header;  // +0x44 T D: g_ReplayHeader 0x96B3A8, 0 in every file
	uint32_t frameCount;  // +0x48 T D: g_ReplayFrameCount (= recorded frames; capacity 108000; demos 7615..17008)
	uint32_t frameCursor;  // +0x4C T D: g_ReplayFrameCursor at save time (== frameCount); Replay_LoadFile resets it to 0
	DmpReplayFrame frames[108001];  // +0x50 T D: g_ReplayInputFrames 0x96B3B4; frames beyond frameCount are zero (the extra 24 bytes are the 108001st row)
};
struct DmpPatternData {
	int32_t scriptArg9;  // +0x00 T: g_ScriptArgs[9] after InitPatternData(i)
	int32_t scriptArg8;  // +0x04 T: g_ScriptArgs[8]
	int32_t scriptArg10;  // +0x08 T: g_ScriptArgs[10]
	int32_t scriptArg11;  // +0x0C T: g_ScriptArgs[11]
	uint32_t spriteRects;  // +0x10 T: malloc(48 * count), count = g_ScriptArgs[0]; built from g_ScriptArgs[1] -> script rows of 10 ints {texW,texH,u0px,v0px,u1px,v1px,ofsX,ofsY,ofsZ,ofsW}
	uint32_t intTable2;  // +0x14 T: malloc(4 * count), copy of the script int array g_ScriptArgs[2]
	uint32_t intTable3;  // +0x18 T: malloc(4 * count), copy of g_ScriptArgs[3]
	uint32_t records6;  // +0x1C T: malloc(24 * g_ScriptArgs[4]) of 6-int records copied from g_ScriptArgs[5] (only when g_ScriptArgs[4] > 0)
	uint32_t records5;  // +0x20 T: malloc(24 * g_ScriptArgs[6]) holding 5-int (20-byte stride) records copied from g_ScriptArgs[7]
};
struct DmpPlayerCharaInfo {
	int32_t buttonInfo[126];  // +0x000 T: InitCharaButtonInfo(0/1/2) copied by sub_42A2E0 (mode in dword 2)
	int32_t zeroInit_1F8[2];  // +0x1F8 T: written 0 by Player_LoadAll after the three InitCharaButtonInfo calls
	int32_t charaInfo[4];  // +0x200 T: g_ScriptArgs[0..3] after InitCharaInfo
	int32_t unwritten_210[4];  // +0x210 U: not written by Player_LoadAll
	int32_t zeroInit_220;  // +0x220 T: written 0
};
#pragma pack(pop)

static_assert(sizeof(DmpScriptFuncEntry) == 0x24, "DmpScriptFuncEntry size");
static_assert(offsetof(DmpScriptFuncEntry, name) == 0x0, "DmpScriptFuncEntry.name");
static_assert(offsetof(DmpScriptFuncEntry, pc) == 0x20, "DmpScriptFuncEntry.pc");
static_assert(sizeof(DmpScriptBank) == 0x114, "DmpScriptBank size");
static_assert(offsetof(DmpScriptBank, name) == 0x0, "DmpScriptBank.name");
static_assert(offsetof(DmpScriptBank, codeImage) == 0x104, "DmpScriptBank.codeImage");
static_assert(offsetof(DmpScriptBank, codeImageBytes) == 0x108, "DmpScriptBank.codeImageBytes");
static_assert(offsetof(DmpScriptBank, funcCount) == 0x10C, "DmpScriptBank.funcCount");
static_assert(offsetof(DmpScriptBank, funcTable) == 0x110, "DmpScriptBank.funcTable");
static_assert(sizeof(DmpScriptThread) == 0x864, "DmpScriptThread size");
static_assert(offsetof(DmpScriptThread, allocated) == 0x0, "DmpScriptThread.allocated");
static_assert(offsetof(DmpScriptThread, name) == 0x4, "DmpScriptThread.name");
static_assert(offsetof(DmpScriptThread, stack) == 0x44, "DmpScriptThread.stack");
static_assert(offsetof(DmpScriptThread, sp) == 0x844, "DmpScriptThread.sp");
static_assert(offsetof(DmpScriptThread, codeImage) == 0x848, "DmpScriptThread.codeImage");
static_assert(offsetof(DmpScriptThread, pc) == 0x84C, "DmpScriptThread.pc");
static_assert(offsetof(DmpScriptThread, bank) == 0x850, "DmpScriptThread.bank");
static_assert(offsetof(DmpScriptThread, line) == 0x854, "DmpScriptThread.line");
static_assert(offsetof(DmpScriptThread, waitFlag) == 0x858, "DmpScriptThread.waitFlag");
static_assert(offsetof(DmpScriptThread, waitStartMs) == 0x85C, "DmpScriptThread.waitStartMs");
static_assert(offsetof(DmpScriptThread, waitDurMs) == 0x860, "DmpScriptThread.waitDurMs");
static_assert(sizeof(DmpPackEntry) == 0x40, "DmpPackEntry size");
static_assert(offsetof(DmpPackEntry, name) == 0x0, "DmpPackEntry.name");
static_assert(offsetof(DmpPackEntry, sizeXorKey) == 0x38, "DmpPackEntry.sizeXorKey");
static_assert(offsetof(DmpPackEntry, dataOffset) == 0x3C, "DmpPackEntry.dataOffset");
static_assert(sizeof(DmpPackArchive) == 0x18, "DmpPackArchive size");
static_assert(offsetof(DmpPackArchive, hFile) == 0x0, "DmpPackArchive.hFile");
static_assert(offsetof(DmpPackArchive, entryCount) == 0x4, "DmpPackArchive.entryCount");
static_assert(offsetof(DmpPackArchive, entries) == 0x8, "DmpPackArchive.entries");
static_assert(offsetof(DmpPackArchive, plainFlag) == 0xC, "DmpPackArchive.plainFlag");
static_assert(offsetof(DmpPackArchive, unused_10) == 0x10, "DmpPackArchive.unused_10");
static_assert(offsetof(DmpPackArchive, dataBase) == 0x14, "DmpPackArchive.dataBase");
static_assert(sizeof(DmpImgFileHeader) == 0x14, "DmpImgFileHeader size");
static_assert(offsetof(DmpImgFileHeader, reserved0) == 0x0, "DmpImgFileHeader.reserved0");
static_assert(offsetof(DmpImgFileHeader, version) == 0x4, "DmpImgFileHeader.version");
static_assert(offsetof(DmpImgFileHeader, paletteFlag) == 0x8, "DmpImgFileHeader.paletteFlag");
static_assert(offsetof(DmpImgFileHeader, width) == 0xC, "DmpImgFileHeader.width");
static_assert(offsetof(DmpImgFileHeader, height) == 0x10, "DmpImgFileHeader.height");
static_assert(sizeof(DmpImgBuffer) == 0x20, "DmpImgBuffer size");
static_assert(offsetof(DmpImgBuffer, pixels) == 0x0, "DmpImgBuffer.pixels");
static_assert(offsetof(DmpImgBuffer, hasAlphaPlane) == 0x4, "DmpImgBuffer.hasAlphaPlane");
static_assert(offsetof(DmpImgBuffer, palette) == 0x8, "DmpImgBuffer.palette");
static_assert(offsetof(DmpImgBuffer, rowBytes) == 0xC, "DmpImgBuffer.rowBytes");
static_assert(offsetof(DmpImgBuffer, bitDepth) == 0x10, "DmpImgBuffer.bitDepth");
static_assert(offsetof(DmpImgBuffer, bottomUp) == 0x14, "DmpImgBuffer.bottomUp");
static_assert(offsetof(DmpImgBuffer, width) == 0x18, "DmpImgBuffer.width");
static_assert(offsetof(DmpImgBuffer, height) == 0x1C, "DmpImgBuffer.height");
static_assert(sizeof(DmpGfxImageSlot) == 0x114, "DmpGfxImageSlot size");
static_assert(offsetof(DmpGfxImageSlot, path) == 0x0, "DmpGfxImageSlot.path");
static_assert(offsetof(DmpGfxImageSlot, d3dFormat) == 0x104, "DmpGfxImageSlot.d3dFormat");
static_assert(offsetof(DmpGfxImageSlot, texture) == 0x108, "DmpGfxImageSlot.texture");
static_assert(offsetof(DmpGfxImageSlot, width) == 0x10C, "DmpGfxImageSlot.width");
static_assert(offsetof(DmpGfxImageSlot, height) == 0x110, "DmpGfxImageSlot.height");
static_assert(sizeof(DmpGfxSpriteRect) == 0x30, "DmpGfxSpriteRect size");
static_assert(offsetof(DmpGfxSpriteRect, u0) == 0x0, "DmpGfxSpriteRect.u0");
static_assert(offsetof(DmpGfxSpriteRect, v0) == 0x4, "DmpGfxSpriteRect.v0");
static_assert(offsetof(DmpGfxSpriteRect, u1) == 0x8, "DmpGfxSpriteRect.u1");
static_assert(offsetof(DmpGfxSpriteRect, v1) == 0xC, "DmpGfxSpriteRect.v1");
static_assert(offsetof(DmpGfxSpriteRect, ofsX) == 0x10, "DmpGfxSpriteRect.ofsX");
static_assert(offsetof(DmpGfxSpriteRect, ofsY) == 0x14, "DmpGfxSpriteRect.ofsY");
static_assert(offsetof(DmpGfxSpriteRect, ofsZ) == 0x18, "DmpGfxSpriteRect.ofsZ");
static_assert(offsetof(DmpGfxSpriteRect, ofsW) == 0x1C, "DmpGfxSpriteRect.ofsW");
static_assert(offsetof(DmpGfxSpriteRect, halfTexelU) == 0x20, "DmpGfxSpriteRect.halfTexelU");
static_assert(offsetof(DmpGfxSpriteRect, halfTexelV) == 0x24, "DmpGfxSpriteRect.halfTexelV");
static_assert(offsetof(DmpGfxSpriteRect, texWidth) == 0x28, "DmpGfxSpriteRect.texWidth");
static_assert(offsetof(DmpGfxSpriteRect, texHeight) == 0x2C, "DmpGfxSpriteRect.texHeight");
static_assert(sizeof(DmpEnemyType) == 0x18, "DmpEnemyType size");
static_assert(offsetof(DmpEnemyType, id) == 0x0, "DmpEnemyType.id");
static_assert(offsetof(DmpEnemyType, loadScripts) == 0x4, "DmpEnemyType.loadScripts");
static_assert(offsetof(DmpEnemyType, loadTextures) == 0x8, "DmpEnemyType.loadTextures");
static_assert(offsetof(DmpEnemyType, releaseAssets) == 0xC, "DmpEnemyType.releaseAssets");
static_assert(offsetof(DmpEnemyType, spawn) == 0x10, "DmpEnemyType.spawn");
static_assert(offsetof(DmpEnemyType, onLevelCheck) == 0x14, "DmpEnemyType.onLevelCheck");
static_assert(sizeof(DmpMatchSetup) == 0x44, "DmpMatchSetup size");
static_assert(offsetof(DmpMatchSetup, reserved0) == 0x0, "DmpMatchSetup.reserved0");
static_assert(offsetof(DmpMatchSetup, seed) == 0x4, "DmpMatchSetup.seed");
static_assert(offsetof(DmpMatchSetup, lives) == 0x8, "DmpMatchSetup.lives");
static_assert(offsetof(DmpMatchSetup, scoreAttackTimeSel) == 0xC, "DmpMatchSetup.scoreAttackTimeSel");
static_assert(offsetof(DmpMatchSetup, configC) == 0x10, "DmpMatchSetup.configC");
static_assert(offsetof(DmpMatchSetup, configD) == 0x14, "DmpMatchSetup.configD");
static_assert(offsetof(DmpMatchSetup, stageScriptSet) == 0x18, "DmpMatchSetup.stageScriptSet");
static_assert(offsetof(DmpMatchSetup, entryKind) == 0x1C, "DmpMatchSetup.entryKind");
static_assert(offsetof(DmpMatchSetup, gameMode) == 0x20, "DmpMatchSetup.gameMode");
static_assert(offsetof(DmpMatchSetup, stage) == 0x24, "DmpMatchSetup.stage");
static_assert(offsetof(DmpMatchSetup, playerCount) == 0x28, "DmpMatchSetup.playerCount");
static_assert(offsetof(DmpMatchSetup, slotChara) == 0x2C, "DmpMatchSetup.slotChara");
static_assert(sizeof(DmpReplayFrame) == 0x18, "DmpReplayFrame size");
static_assert(offsetof(DmpReplayFrame, rawInput) == 0x0, "DmpReplayFrame.rawInput");
static_assert(sizeof(DmpReplayFile) == 0x278D68, "DmpReplayFile size");
static_assert(offsetof(DmpReplayFile, setup) == 0x0, "DmpReplayFile.setup");
static_assert(offsetof(DmpReplayFile, header) == 0x44, "DmpReplayFile.header");
static_assert(offsetof(DmpReplayFile, frameCount) == 0x48, "DmpReplayFile.frameCount");
static_assert(offsetof(DmpReplayFile, frameCursor) == 0x4C, "DmpReplayFile.frameCursor");
static_assert(offsetof(DmpReplayFile, frames) == 0x50, "DmpReplayFile.frames");
static_assert(sizeof(DmpPatternData) == 0x24, "DmpPatternData size");
static_assert(offsetof(DmpPatternData, scriptArg9) == 0x0, "DmpPatternData.scriptArg9");
static_assert(offsetof(DmpPatternData, scriptArg8) == 0x4, "DmpPatternData.scriptArg8");
static_assert(offsetof(DmpPatternData, scriptArg10) == 0x8, "DmpPatternData.scriptArg10");
static_assert(offsetof(DmpPatternData, scriptArg11) == 0xC, "DmpPatternData.scriptArg11");
static_assert(offsetof(DmpPatternData, spriteRects) == 0x10, "DmpPatternData.spriteRects");
static_assert(offsetof(DmpPatternData, intTable2) == 0x14, "DmpPatternData.intTable2");
static_assert(offsetof(DmpPatternData, intTable3) == 0x18, "DmpPatternData.intTable3");
static_assert(offsetof(DmpPatternData, records6) == 0x1C, "DmpPatternData.records6");
static_assert(offsetof(DmpPatternData, records5) == 0x20, "DmpPatternData.records5");
static_assert(sizeof(DmpPlayerCharaInfo) == 0x224, "DmpPlayerCharaInfo size");
static_assert(offsetof(DmpPlayerCharaInfo, buttonInfo) == 0x0, "DmpPlayerCharaInfo.buttonInfo");
static_assert(offsetof(DmpPlayerCharaInfo, zeroInit_1F8) == 0x1F8, "DmpPlayerCharaInfo.zeroInit_1F8");
static_assert(offsetof(DmpPlayerCharaInfo, charaInfo) == 0x200, "DmpPlayerCharaInfo.charaInfo");
static_assert(offsetof(DmpPlayerCharaInfo, unwritten_210) == 0x210, "DmpPlayerCharaInfo.unwritten_210");
static_assert(offsetof(DmpPlayerCharaInfo, zeroInit_220) == 0x220, "DmpPlayerCharaInfo.zeroInit_220");

static const Han2EnumInfo kDmpTypesEnums[] = {
};

static const Han2FieldInfo kDmpScriptFuncEntryFields[] = {
	{"name", 0x0, 1, 32, 5, nullptr, "+0x00 T D: NUL-terminated; bytes after the NUL are stale writer junk (keep raw for byte-exact output)"},
	{"pc", 0x20, 4, 1, 0, nullptr, "+0x20 T D: byte offset into the code image"},
};
static const Han2FieldInfo kDmpScriptBankFields[] = {
	{"name", 0x0, 1, 260, 5, nullptr, "+0x000 T: upper-cased path string given to Script_LoadBank (full \".\\data\\script\\...\" path, not the basename)"},
	{"codeImage", 0x104, 4, 1, 0, nullptr, "+0x104 T: malloc(codeSize + 2), last 2 bytes zero; also the scripts' mutable global memory"},
	{"codeImageBytes", 0x108, 4, 1, 1, nullptr, "+0x108 T: codeSize + 2"},
	{"funcCount", 0x10C, 4, 1, 1, nullptr, "+0x10C T: nFuncs"},
	{"funcTable", 0x110, 4, 1, 4, nullptr, "+0x110 T: malloc(36 * nFuncs), copied verbatim from the file"},
};
static const Han2FieldInfo kDmpScriptThreadFields[] = {
	{"allocated", 0x0, 4, 1, 1, nullptr, "+0x000 T"},
	{"name", 0x4, 1, 64, 5, nullptr, "+0x004 T: only copied up to the NUL (rest keeps the previous occupant)"},
	{"stack", 0x44, 4, 512, 1, nullptr, "+0x044 T: element 0 unused; stack[sp] is the top; values and tags are separate dwords"},
	{"sp", 0x844, 4, 1, 1, nullptr, "+0x844 T"},
	{"codeImage", 0x848, 4, 1, 0, nullptr, "+0x848 T: copy of g_ScriptBanks[bank].codeImage taken at bind time (Script_RebindThreadImage refreshes it)"},
	{"pc", 0x84C, 4, 1, 1, nullptr, "+0x84C T: byte offset into codeImage"},
	{"bank", 0x850, 4, 1, 1, nullptr, "+0x850 T"},
	{"line", 0x854, 4, 1, 1, nullptr, "+0x854 T"},
	{"waitFlag", 0x858, 4, 1, 1, nullptr, "+0x858 T"},
	{"waitStartMs", 0x85C, 4, 1, 1, nullptr, "+0x85C T"},
	{"waitDurMs", 0x860, 4, 1, 1, nullptr, "+0x860 T"},
};
static const Han2FieldInfo kDmpPackEntryFields[] = {
	{"name", 0x0, 1, 56, 5, nullptr, "+0x00 T: stored as (name[j] ^ (3*(j*i-28)) & 0xFF) for entry i"},
	{"sizeXorKey", 0x38, 4, 1, 0, nullptr, "+0x38 T D: payload size ^ 0xFA261EFB"},
	{"dataOffset", 0x3C, 4, 1, 0, nullptr, "+0x3C T D: absolute file offset (stored plain)"},
};
static const Han2FieldInfo kDmpPackArchiveFields[] = {
	{"hFile", 0x0, 4, 1, 4, nullptr, "+0x00 T"},
	{"entryCount", 0x4, 4, 1, 1, nullptr, "+0x04 T: second u32 of the file ^ 0xFA261EFB"},
	{"entries", 0x8, 4, 1, 4, nullptr, "+0x08 T: malloc(64 * entryCount) decoded index"},
	{"plainFlag", 0xC, 4, 1, 0, nullptr, "+0x0C T D: first u32 of the file; nonzero = payload stored plain, 0 = first 9696 bytes XOR-enciphered with the entry name (PackArchive_ReadEntry)"},
	{"unused_10", 0x10, 4, 1, 0, nullptr, "+0x10 X: no reader found (PackArchive_Open does not write it; memset 0 only)"},
	{"dataBase", 0x14, 4, 1, 0, nullptr, "+0x14 T: added by PackArchive_EntryDataOffset"},
};
static const Han2FieldInfo kDmpImgFileHeaderFields[] = {
	{"reserved0", 0x0, 4, 1, 0, nullptr, "+0x00 T: read and discarded; 0 in every file"},
	{"version", 0x4, 4, 1, 0, nullptr, "+0x04 T D: switch in Img_OpenAndReadHeader: 0..2 -> Img_ReadV0to2, 3..4 -> Img_ReadV3to4, 6 -> Img_ReadV6 (all 68 shipped files are 6)"},
	{"paletteFlag", 0x8, 4, 1, 0, nullptr, "+0x08 T D: 0 in all files; if 0 the reader sets bitdepth 16"},
	{"width", 0xC, 4, 1, 0, nullptr, "+0x0C T D"},
	{"height", 0x10, 4, 1, 0, nullptr, "+0x10 T D"},
};
static const Han2FieldInfo kDmpImgBufferFields[] = {
	{"pixels", 0x0, 4, 1, 0, nullptr, "+0x00 T"},
	{"hasAlphaPlane", 0x4, 4, 1, 1, nullptr, "+0x04 T"},
	{"palette", 0x8, 4, 1, 4, nullptr, "+0x08 T"},
	{"rowBytes", 0xC, 4, 1, 1, nullptr, "+0x0C T: -1 for raw 16-bit data (selects Tex_CopyRaw16Pixels)"},
	{"bitDepth", 0x10, 4, 1, 1, nullptr, "+0x10 T: 16"},
	{"bottomUp", 0x14, 4, 1, 1, nullptr, "+0x14 T"},
	{"width", 0x18, 4, 1, 1, nullptr, "+0x18 T"},
	{"height", 0x1C, 4, 1, 1, nullptr, "+0x1C T"},
};
static const Han2FieldInfo kDmpGfxImageSlotFields[] = {
	{"path", 0x0, 1, 260, 5, nullptr, "+0x000 T: IMG path set by GFX_SET_IMAGE (e.g. \".\\\\Data\\\\BG\\\\bg00.img\")"},
	{"d3dFormat", 0x104, 4, 1, 1, nullptr, "+0x104 T: 25 (type 0) or 26 (type 1)"},
	{"texture", 0x108, 4, 1, 4, nullptr, "+0x108 T: IDirect3DTexture8*, released by Tex_ReleaseSlot"},
	{"width", 0x10C, 4, 1, 1, nullptr, "+0x10C T: GFX_SET_IMAGE argument 4 (used as the UV divisor)"},
	{"height", 0x110, 4, 1, 1, nullptr, "+0x110 T: GFX_SET_IMAGE argument 5"},
};
static const Han2FieldInfo kDmpGfxSpriteRectFields[] = {
	{"u0", 0x0, 4, 1, 6, nullptr, "+0x00 T: srcX / texW"},
	{"v0", 0x4, 4, 1, 6, nullptr, "+0x04 T: srcY / texH"},
	{"u1", 0x8, 4, 1, 6, nullptr, "+0x08 T: (srcX + srcW) / texW"},
	{"v1", 0xC, 4, 1, 6, nullptr, "+0x0C T: (srcY + srcH) / texH"},
	{"ofsX", 0x10, 4, 1, 6, nullptr, "+0x10 T"},
	{"ofsY", 0x14, 4, 1, 6, nullptr, "+0x14 T"},
	{"ofsZ", 0x18, 4, 1, 6, nullptr, "+0x18 T: GFX_DEFINE_SPRITE argument 5"},
	{"ofsW", 0x1C, 4, 1, 6, nullptr, "+0x1C T: argument 6"},
	{"halfTexelU", 0x20, 4, 1, 6, nullptr, "+0x20 T: 0.1 / texW"},
	{"halfTexelV", 0x24, 4, 1, 6, nullptr, "+0x24 T: 0.1 / texH"},
	{"texWidth", 0x28, 4, 1, 6, nullptr, "+0x28 T"},
	{"texHeight", 0x2C, 4, 1, 6, nullptr, "+0x2C T"},
};
static const Han2FieldInfo kDmpEnemyTypeFields[] = {
	{"id", 0x0, 4, 1, 1, nullptr, "+0x00 T: matches the ids pushed by STAGE_ENEMY_LIST"},
	{"loadScripts", 0x4, 4, 1, 0, nullptr, "+0x04 T: GameMain_Init: Event_LoadResources (ENEMYnnn.FOB, InitFunction + InitPatternData x48)"},
	{"loadTextures", 0x8, 4, 1, 0, nullptr, "+0x08 T: GameMain_Load: Event_LoadTextures (ZakoTextureLoad.fob LoadTextureCallBack(i) -> g_TexEnemy[i], format 25)"},
	{"releaseAssets", 0xC, 4, 1, 0, nullptr, "+0x0C T: GameMain_Release"},
	{"spawn", 0x10, 4, 1, 0, nullptr, "+0x10 T: script op ENEMY_SPAWN"},
	{"onLevelCheck", 0x14, 4, 1, 0, nullptr, "+0x14 U: Event_CheckLevel for ids 0..39"},
};
static const Han2FieldInfo kDmpMatchSetupFields[] = {
	{"reserved0", 0x0, 4, 1, 1, nullptr, "+0x00 T D: zeroed before Replay_WriteFileAtMatchEnd; 0 in all demos"},
	{"seed", 0x4, 4, 1, 1, nullptr, "+0x04 T D: Setup_GetSeed -> Rng_Seed in GameMain_Init (0 in all demos)"},
	{"lives", 0x8, 4, 1, 1, nullptr, "+0x08 T D: Setup field 0xBF7F80 (Player_SetLives value)"},
	{"scoreAttackTimeSel", 0xC, 4, 1, 1, nullptr, "+0x0C T D: Setup_GetScoreAttackTimeSel (1/2/3 -> 3600/10800/18000 frames)"},
	{"configC", 0x10, 4, 1, 1, nullptr, "+0x10 T D: Setup field 0xBF7F88 (Setup_SnapshotConfig copies 0x96B190..19C into 0xBF7F80..8C)"},
	{"configD", 0x14, 4, 1, 1, nullptr, "+0x14 T D: Setup field 0xBF7F8C"},
	{"stageScriptSet", 0x18, 4, 1, 1, nullptr, "+0x18 T D: Setup_SetStageScriptSet -> STAGEnn.FOB number"},
	{"entryKind", 0x1C, 4, 1, 1, nullptr, "+0x1C T D: Setup_SetEntryKind"},
	{"gameMode", 0x20, 4, 1, 1, nullptr, "+0x20 T D"},
	{"stage", 0x24, 4, 1, 1, nullptr, "+0x24 T D: passed as arg0 of the stage script \"Init\""},
	{"playerCount", 0x28, 4, 1, 1, nullptr, "+0x28 T D"},
	{"slotChara", 0x2C, 4, 6, 1, nullptr, "+0x2C T D: Setup_GetSlotChara(i), -1 = empty seat; CHARAnn = value + 1"},
};
static const Han2FieldInfo kDmpReplayFrameFields[] = {
	{"rawInput", 0x0, 4, 6, 0, nullptr, "+0x00 T D: g_FrameInput[seat] = Input_GetRawWord(seat) for seats 0..5"},
};
static const Han2FieldInfo kDmpReplayFileFields[] = {
	{"setup", 0x0, 68, 1, 4, nullptr, "+0x00 T D: g_MatchSetup 0xBF7F78"},
	{"header", 0x44, 4, 1, 0, nullptr, "+0x44 T D: g_ReplayHeader 0x96B3A8, 0 in every file"},
	{"frameCount", 0x48, 4, 1, 0, nullptr, "+0x48 T D: g_ReplayFrameCount (= recorded frames; capacity 108000; demos 7615..17008)"},
	{"frameCursor", 0x4C, 4, 1, 0, nullptr, "+0x4C T D: g_ReplayFrameCursor at save time (== frameCount); Replay_LoadFile resets it to 0"},
	{"frames", 0x50, 24, 108001, 4, nullptr, "+0x50 T D: g_ReplayInputFrames 0x96B3B4; frames beyond frameCount are zero (the extra 24 bytes are the 108001st row)"},
};
static const Han2FieldInfo kDmpPatternDataFields[] = {
	{"scriptArg9", 0x0, 4, 1, 1, nullptr, "+0x00 T: g_ScriptArgs[9] after InitPatternData(i)"},
	{"scriptArg8", 0x4, 4, 1, 1, nullptr, "+0x04 T: g_ScriptArgs[8]"},
	{"scriptArg10", 0x8, 4, 1, 1, nullptr, "+0x08 T: g_ScriptArgs[10]"},
	{"scriptArg11", 0xC, 4, 1, 1, nullptr, "+0x0C T: g_ScriptArgs[11]"},
	{"spriteRects", 0x10, 4, 1, 4, nullptr, "+0x10 T: malloc(48 * count), count = g_ScriptArgs[0]; built from g_ScriptArgs[1] -> script rows of 10 ints {texW,texH,u0px,v0px,u1px,v1px,ofsX,ofsY,ofsZ,ofsW}"},
	{"intTable2", 0x14, 4, 1, 1, nullptr, "+0x14 T: malloc(4 * count), copy of the script int array g_ScriptArgs[2]"},
	{"intTable3", 0x18, 4, 1, 1, nullptr, "+0x18 T: malloc(4 * count), copy of g_ScriptArgs[3]"},
	{"records6", 0x1C, 4, 1, 1, nullptr, "+0x1C T: malloc(24 * g_ScriptArgs[4]) of 6-int records copied from g_ScriptArgs[5] (only when g_ScriptArgs[4] > 0)"},
	{"records5", 0x20, 4, 1, 1, nullptr, "+0x20 T: malloc(24 * g_ScriptArgs[6]) holding 5-int (20-byte stride) records copied from g_ScriptArgs[7]"},
};
static const Han2FieldInfo kDmpPlayerCharaInfoFields[] = {
	{"buttonInfo", 0x0, 4, 126, 1, nullptr, "+0x000 T: InitCharaButtonInfo(0/1/2) copied by sub_42A2E0 (mode in dword 2)"},
	{"zeroInit_1F8", 0x1F8, 4, 2, 1, nullptr, "+0x1F8 T: written 0 by Player_LoadAll after the three InitCharaButtonInfo calls"},
	{"charaInfo", 0x200, 4, 4, 1, nullptr, "+0x200 T: g_ScriptArgs[0..3] after InitCharaInfo"},
	{"unwritten_210", 0x210, 4, 4, 1, nullptr, "+0x210 U: not written by Player_LoadAll"},
	{"zeroInit_220", 0x220, 4, 1, 1, nullptr, "+0x220 T: written 0"},
};
