// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"

enum Gof1AniFlag : uint8_t {
	G1ANI_END_TO_PATTERN = 0,
	G1ANI_NEXT = 1,
	G1ANI_JUMP_TO_FRAME = 2,
	G1ANI_NEXT_LAND_TO_PATTERN = 3,
	G1ANI_JUMP_TO_FRAME_LAND_TO_PATTERN = 4,
	G1ANI_LOOP_COUNTED = 5,
};
enum Gof1DrawMode : uint8_t {
	G1DRAW_NORMAL = 0,
	G1DRAW_FLIP_H = 1,
	G1DRAW_FLIP_V = 2,
	G1DRAW_ROT_90 = 3,
	G1DRAW_ROT_180 = 4,
	G1DRAW_ROT_270 = 5,
	G1DRAW_FLIP_H_ROT_90 = 6,
	G1DRAW_FLIP_H_ROT_270 = 7,
	G1DRAW_ROT_FREE = 8,
	G1DRAW_ROT_FREE_FLIPPED = 9,
};
enum Gof1BlendMode : uint8_t {
	G1BLEND_OPAQUE = 0,
	G1BLEND_ALPHA = 1,
};
enum Gof1Stance : uint8_t {
	G1STANCE_GROUND = 0,
	G1STANCE_AIR = 1,
	G1STANCE_CROUCH = 2,
};
enum Gof1CancelPermission : uint8_t {
	G1CANCEL_NONE = 0,
	G1CANCEL_ON_HIT_OR_GUARD = 1,
	G1CANCEL_ALWAYS = 2,
};
enum Gof1FrameFlags1 : uint32_t {
	G1FF1_CARRY_VELOCITY_AS_INERTIA = 1,
	G1FF1_CLEAR_INERTIA = 2,
	G1FF1_MOTION_ONLY_ON_FIRST_ENTRY = 0x80000000,
};
enum Gof1FrameFlags2 : uint32_t {
	G1FF2_THROW_TECHABLE = 2,
	G1FF2_UNREAD_BIT2 = 4,
	G1FF2_INVULN_MASK = 0xF0000,
	G1FF2_COUNTER_MASK = 0xF00000,
};
enum Gof1InvulnClass : uint8_t {
	G1INVULN_NONE = 0,
	G1INVULN_EVADE_HIGH = 1,
	G1INVULN_EVADE_LOW = 2,
	G1INVULN_STRIKE = 3,
	G1INVULN_THROW = 4,
};
enum Gof1CounterCommand : uint8_t {
	G1COUNTER_NONE = 0,
	G1COUNTER_STATE_1 = 1,
	G1COUNTER_STATE_2 = 2,
	G1COUNTER_CLEAR = 3,
};
enum Gof1MoveInfo : uint8_t {
	G1MOVEINFO_TYPE_MASK = 0x0F,
	G1MOVEINFO_LINEAR_FILTER = 0x40,
	G1MOVEINFO_CG_DOUBLE_RES = 0x80,
};
enum Gof1AtFlagsA : uint8_t {
	G1ATA_CHIP_DAMAGE = 1,
	G1ATA_NO_KO = 2,
	G1ATA_STANDING_REACTION = 8,
	G1ATA_KNOCKBACK_TOWARD_ATTACKER = 0x10,
	G1ATA_NOT_REFLECTABLE = 0x20,
	G1ATA_AIR_GUARD_RULE = 0x40,
	G1ATA_BASE_KNOCKBACK_ROW = 0x80,
};
enum Gof1AtFlagsB : uint8_t {
	G1ATB_EXTRA_HIT_SPARK = 1,
	G1ATB_NO_HORIZONTAL_KNOCKBACK = 2,
	G1ATB_NO_COMBO_COUNT = 4,
	G1ATB_SCREEN_SHAKE = 8,
	G1ATB_AIR_COMBO_STARTER = 0x10,
	G1ATB_NO_THROW_TECH = 0x20,
	G1ATB_HITS_OWN_TEAM = 0x40,
};
enum Gof1AtHitClass : uint16_t {
	G1ATCLASS_HIGH_STRIKE = 0,
	G1ATCLASS_LOW_STRIKE = 1,
	G1ATCLASS_HIGH_THROW = 2,
	G1ATCLASS_LOW_THROW = 3,
	G1ATCLASS_UNGUARDABLE = 4,
};
enum Gof1StatusEffect : uint8_t {
	G1STATUS_NONE = 0,
	G1STATUS_RED_FLICKER = 1,
	G1STATUS_BLUE_FLICKER = 2,
	G1STATUS_YELLOW_BLACK_GREY_CYCLE = 3,
};
enum Gof1IfType : uint8_t {
	G1IF_DIRECTION_JUMP = 1,
	G1IF_END_CONDITION = 2,
	G1IF_HIT_RESULT_JUMP = 3,
	G1IF_VELOCITY_SIGN_JUMP = 4,
	G1IF_INVINCIBLE_JUMP = 5,
	G1IF_INPUT_JUMP = 6,
	G1IF_INPUT_ACTION = 7,
	G1IF_RANDOM_JUMP = 8,
	G1IF_SET_LOOP_COUNTER = 9,
	G1IF_LOOP_ZERO_JUMP = 10,
	G1IF_COMMAND_MOVE_ACTION = 11,
	G1IF_NEAREST_DISTANCE_JUMP = 12,
	G1IF_SCREEN_EDGE_ACTION = 13,
	G1IF_BOX_HIT_JUMP = 14,
	G1IF_BOX_GRAB_JUMP = 15,
	G1IF_CAMERA_FOLLOW = 16,
	G1IF_HIT_COUNT_JUMP = 17,
	G1IF_PARENT_ACTION_JUMP = 18,
	G1IF_REFLECT_OBJECT = 19,
	G1IF_BOX_ENEMY_JUMP = 20,
	G1IF_FIGHTER_PRESENT_JUMP = 21,
	G1IF_STAGE_JUMP = 22,
	G1IF_GAME_MODE_JUMP = 23,
	G1IF_COUNTER_AT_LEAST_JUMP = 24,
	G1IF_VARIABLE_COMPARE_JUMP = 25,
	G1IF_ADJUST_VELOCITY_BY_INPUT = 26,
	G1IF_PARENT_GRABBED_JUMP = 27,
	G1IF_ROUND_END_JUMP = 28,
	G1IF_X_LIMIT_JUMP = 29,
	G1IF_FACING_JUMP = 30,
	G1IF_COMMAND_MOVE_JUMP = 31,
	G1IF_CPU_PLAYER_JUMP = 32,
	G1IF_ALLY_BOX_JUMP = 50,
};
enum Gof1EfType : uint8_t {
	G1EF_SPAWN_CHILD_OBJECT = 1,
	G1EF_SPAWN_EFFECT = 2,
	G1EF_SPAWN_PARTICLES = 3,
	G1EF_CONTROL_GRABBED = 4,
	G1EF_THROW_DAMAGE = 5,
	G1EF_ACTOR_OP = 6,
	G1EF_SYSTEM_PARTICLE = 7,
	G1EF_SPAWN_COMMON_OBJECT = 8,
	G1EF_PLAY_SOUND = 9,
	G1EF_SET_ACTOR_PARAMS = 30,
	G1EF_SPAWN_CHILD_FROM_PARENT = 50,
};
enum Gof1EfActorOp : uint8_t {
	G1OP_SET_TRAIL_EFFECT = 0,
	G1OP_SCREEN_SHAKE_FREEZE = 1,
	G1OP_SET_FREEZE_TIMERS = 2,
	G1OP_SET_PERIODIC_PARAMS = 3,
	G1OP_ADD_LIFE_METER_GAUGE = 4,
	G1OP_FLIP_FACING = 5,
	G1OP_SET_VELOCITY_RANGE = 6,
	G1OP_SPAWN_FRAME_GHOST = 7,
	G1OP_AIM_AT_OPPONENT = 8,
	G1OP_SET_FLAG_215 = 9,
	G1OP_SET_WORD_VAR_236 = 10,
	G1OP_SET_HITSTOP = 11,
	G1OP_MOVE_AND_FLASH = 12,
	G1OP_FLASH = 13,
	G1OP_ADD_COUNTER = 100,
	G1OP_SUB_COUNTER = 101,
	G1OP_ADD_BYTE_278 = 102,
	G1OP_SUB_BYTE_278 = 103,
	G1OP_SET_OR_ADD_WORD_VAR_280 = 105,
	G1OP_SET_BYTE_218 = 252,
	G1OP_FORCE_ROUND_END = 253,
	G1OP_SET_FLAG_261 = 254,
	G1OP_SET_FLAG_260 = 255,
};
enum Gof1PartFlipMode : uint8_t {
	G1PARTFLIP_NONE = 0,
	G1PARTFLIP_H = 1,
	G1PARTFLIP_V = 2,
	G1PARTFLIP_HV = 3,
};

#pragma pack(push, 1)
struct Gof1ArchiveFileHeader {
	uint32_t plainFlag;  // +0x00 T: 0 = file data is enciphered, non-zero = plain (Archive_XOR_Decrypt_With_Filename returns early when a1+12 != 0); 0 in gof_00/01/03, 1 in gof_02
	uint32_t entryCountXorKey;  // +0x04 T: entry count ^ 0xFA261EFB
};
struct Gof1ArchiveEntry {
	char name[56];  // +0x00 T: CP932, NUL padded; byte j ^= (3*(j*i - 28)) & 0xFF
	uint32_t sizeXorKey;  // +0x38 T: size ^ 0xFA261EFB; Archive_Find_File_Get_Size reads +56
	uint32_t offset;  // +0x3C T: absolute file offset of the data (data start = 8 + 64*count; entries are contiguous); Archive_XOR_Decrypt_With_Filename seeks +60
};
struct Gof1ArchiveHandle {
	uint32_t hFile;  // +0x00 T: File_Open handle
	uint32_t hMapping;  // +0x04 T: CreateFileMappingA
	uint32_t view;  // +0x08 T: MapViewOfFile
	uint32_t plainFlag;  // +0x0C T: first dword of the file (a2+12)
	int32_t entryCount;  // +0x10 T: decoded entry count (a2+16)
	uint32_t unused_14;  // +0x14 never written or read
	uint32_t entries;  // +0x18 T: GlobalAlloc(count << 6) holding the decoded index (a2+24)
};
struct Gof1FileHeader {
	char signature[8];  // +0x00 E: CP932 "備前長船" (94 F5 91 4F 92 B7 91 44) in all 51 files; never read or compared by the game
	uint8_t unused_08[8];  // +0x08 zero in all files, not read
	uint32_t version;  // +0x10 V: must be 18 (SpriteDataSlot_LoadCharacterDat: v10[4] != 18 -> return 0)
	uint32_t patternAreaEnd;  // +0x14 T: byte size of header + pattern area = start of the parts blob; the loader copies [0, patternAreaEnd) as the pattern block (GlobalAlloc(v5[5]))
	uint32_t partsSize;  // +0x18 T: size of the parts blob (old PAT v2); 0 = none; the loader allocates size+0x4000 and copies [patternAreaEnd, +partsSize)
	uint32_t cgOffset;  // +0x1C T: start of the CG blob = patternAreaEnd + partsSize (checked by gof1_dat.py; the loader reads file+cgOffset)
	uint32_t cgSize;  // +0x20 T: size of the CG blob; 0 in all 51 shipped files (no CG bank is stored; every sprite is a parts pattern)
	uint8_t unused_24[32];  // +0x24 zero in all files, not read
};
struct Gof1CharDatHead {
	Gof1FileHeader header;  // +0x00 T: see above
	int32_t patternOffset[256];  // +0x44 T: absolute offset of pattern p inside this block, -1 = absent (Actor_ResolveFrameDataPointers 0x424590: dword at data + 4*pattern + 68)
};
struct Gof1PatternHeader {
	uint8_t frameCount;  // +0x00 T: Actor_ResolveFrameDataPointers compares the frame index against this byte (*v3 <= frame -> error box); 1..100 in the data
	Gof1MoveInfo moveInfo;  // +0x01 T: low nibble = move type (Pattern_GetMoveType 0x425D60), bit 0x40 = linear filter and bit 0x80 = double-resolution CG (Pattern_IsCgDoubleRes 0x425D80, Pattern_GetLinearFilterBit 0x425DA0)
	uint8_t moveLevel;  // +0x02 T: move priority/level (Pattern_GetMoveLevel 0x425D40, compared < 100 by Actor_RequestLocomotionFromInput 0x425FC0); 0, 100 or 255 in the data
	uint8_t frameSizeTag;  // +0x03 E: 0 in the 9 retail files, 116 (the frame size) in the 17 LAST*.DAT backup files; no reader
	int32_t boxTableOffset;  // +0x04 T: offset (relative to the pattern start) of the box table (8-byte rects), -1 = none (Actor_ResolveFrameDataPointers -> actor+596)
	int32_t atTableOffset;  // +0x08 T: offset of the AT table (26-byte records), -1 = none (ObjCheckAttackVsFighters 0x43B070: pattern + [+8] + 26*frame.atIndex)
	int32_t ifTableOffset;  // +0x0C T: offset of the IF table (28-byte records), -1 = none (-> actor+620, ObjRunFrameEventsForPhase 0x427130)
	int32_t efTableOffset;  // +0x10 T: offset of the EF table (20-byte records), -1 = none (-> actor+624, Actor_RunFrameEFs 0x413750)
};
struct Gof1AnimFrame {
	int16_t spriteId;  // +0x00 T: parts-pattern index when < 10000, CG image id-10000 otherwise (DrawFighterSprite 0x432150 -> sub_42FFE0 reads parts at +24+4*id; ObjBoxToWorld 0x42E4D0 tests < 10000); always < 512 in the data
	int16_t offsetX;  // +0x02 T: draw offset X (DrawFighterSprite v3[1])
	int16_t offsetY;  // +0x04 T: draw offset Y (v3[2])
	uint16_t duration;  // +0x06 T: ticks before advancing (ObjRunActionScript 0x424A20 compares a1+14 against it; also the interpolation divisor in sub_42FFE0)
	Gof1DrawMode drawMode;  // +0x08 T: indexes g_DrawModeTransformTable 0x4640F8 (DrawFighterSprite), mode 8 shifts the origin by 100 (ObjBoxToWorld); 0 or 1 in the data
	Gof1BlendMode blendMode;  // +0x09 T: non-zero = alpha-blended draw using alpha (DrawFighterSprite v35); the blend code of sub_42FFE0 never reads a9
	uint8_t alpha;  // +0x0A T: alpha 0..255, only used when blendMode != 0 (DrawFighterSprite v37)
	Gof1AniFlag aniFlag;  // +0x0B T: ObjRunActionScript / ObjEnterCurrentAction switch (0 end->pattern, 1 next, 2 jump, 3/4 same + land->pattern, 5 counted loop)
	uint8_t jumpTarget;  // +0x0C T: pattern (aniFlag 0) or frame (2, 4, 5) to go to
	uint8_t landJumpTarget;  // +0x0D T: frame (or pattern for aniFlag 3/4) entered when the actor lands (ObjRunActionScript landing branch)
	uint8_t drawPriority;  // +0x0E T: ObjEnterCurrentAction -> Actor_ApplyDrawPriority 0x425B80 (1 = front, 2 = back among the fighters)
	uint8_t unused_0F;  // +0x0F zero in all frames, not read
	uint16_t zoom;  // +0x10 T: 256 = 1.0 (DrawFighterSprite v3[8]); 0 = no zoom; constant 0 in the data
	uint8_t loopCount;  // +0x12 T: loaded into actor+20 when non-zero (ObjEnterCurrentAction v1[18]); aniFlag 5 repeat count
	uint8_t loopEndFrame;  // +0x13 T: frame entered when the aniFlag 5 counter reaches 0 (ObjRunActionScript case 5 reads +19)
	uint8_t unused_14[4];  // +0x14 zero in all frames, not read
	uint8_t interpolateToNext;  // +0x18 T: non-zero = tween toward the next frame's parts pattern (sub_42FFE0: *(a22+24))
	uint8_t unused_19[15];  // +0x19 zero in all frames, not read
};
struct Gof1StateFrame {
	uint8_t clearVelX;  // +0x00 T: zero X velocity, X accel and X max (Actor_ApplyFrameMotionFlags 0x425310: *(_BYTE*)v1)
	uint8_t clearVelY;  // +0x01 T: zero Y velocity and accel
	uint8_t addVelX;  // +0x02 T: add velX/accelX/maxX facing-aware (sub_425310)
	uint8_t addVelY;  // +0x03 T: add velY/accelY
	uint8_t unused_04[4];  // +0x04 zero in all frames, not read
	int16_t velX;  // +0x08 T: added to actor velX when addVelX (sub_425310 v1+8)
	int16_t velY;  // +0x0A T: added to velY when addVelY (v1+10)
	int16_t accelX;  // +0x0C T: added to accelX when addVelX (v1+12)
	int16_t accelY;  // +0x0E T: added to accelY when addVelY (v1+14)
	Gof1Stance stance;  // +0x10 T: copied to actor+594 (ObjRunActionScript), air physics test in ObjIntegrateMotion 0x4257D0; Actor_DispatchInputByStance 0x4263E0 builds stance | canAct<<4
	Gof1CancelPermission normalCancel;  // +0x11 T: Actor_RequestLocomotionFromInput 0x425FC0 (2 always, 1 when the actor has hit/been guarded: a1+205 & 0xF)
	Gof1CancelPermission specialCancel;  // +0x12 E: no reader in gof.exe (RBO/HA4 read it); 0/1/2 in the data (21 frames use 2)
	uint8_t attackHitCount;  // +0x13 T: loaded into actor+220 on frame entry (ObjEnterCurrentAction v3 = +19); attack boxes are ignored when it is 0 (ObjCheckAttackVsFighters 0x43B070)
	uint8_t canAct;  // +0x14 T: 1 = actor may act (ObjRunActionScript v23+20 == 1, ObjFighterStateAndHitReaction 0x43BF40); combined with stance in Actor_DispatchInputByStance 0x4263E0
	uint8_t unused_15[3];  // +0x15 zero in all frames, not read
	Gof1FrameFlags1 flags1;  // +0x18 T: ObjIntegrateMotion / sub_425310 (bit0 carry velocity as inertia, bit1 clear inertia, bit31 motion only on first entry)
	Gof1FrameFlags2 flags2;  // +0x1C T: bit1 sub_425E10 throw tech; bits 16..19 invulnerability class (ObjCheckAttackVsFighters reads byte +0x1E & 0xF); bits 20..23 counter command (ObjEnterCurrentAction (dword>>20)&0xF)
	int16_t maxVelX;  // +0x20 T: subtracted/added to actor maxVelX with addVelX (sub_425310 v1+32); 0 except 1 frame
	uint8_t unused_22[6];  // +0x22 zero in all frames, not read
};
struct Gof1FrameRecord {
	Gof1AnimFrame anim;  // +0x00 T: see Gof1AnimFrame (actor+612)
	Gof1StateFrame state;  // +0x28 T: see Gof1StateFrame (actor+616)
	uint8_t atIndex;  // +0x50 T: signed char index into the AT table (26*idx), 0xFF = none (ObjCheckAttackVsFighters, ObjCheckAttackVsObjects, sub_43A740 read *(char*)(frame+80))
	uint8_t atIndexHighByte;  // +0x51 E: 0, 0xFF or stack garbage (45 distinct values); the engine reads atIndex as a signed char and never touches this byte
	int16_t ifIndex[3];  // +0x52 T: IF table indices, -1 = empty (ObjRunFrameEventsForPhase loop i = 82; i < 88; i += 2)
	int16_t efIndex[4];  // +0x58 T: EF table indices, -1 = empty (Actor_RunFrameEFs loop i = 88; i < 96; i += 2)
	int16_t boxIndex[10];  // +0x60 T: box table indices, -1 = empty (actor+628): [0] pushbox (ObjResolvePushboxCollision), [1..3] hurt boxes (ObjCheckAttackVsFighters loop at +2), [4] grab/probe box (own kind 6 of Actor_FindOverlappingTarget, IF 14/15/19/20), [5] special2 (read by Actor_GetBoxSlotIndex only; 1 frame uses it), [6] reflect/clash box (ObjCheckReflectBoxVsAttacks +12), [7] projectile hurt box (target kind 6 of IF 19; never present in the data), [8..9] attack boxes (+16, +18); slot 9 is never present
};
struct Gof1Box {
	int16_t x1;  // +0x00 T: ObjResolvePushboxCollision reads *(__int16*)(box + 8*idx)
	int16_t y1;  // +0x02 T: +2
	int16_t x2;  // +0x04 T: +4
	int16_t y2;  // +0x06 T: +6
};
struct Gof1RectI32 {
	int32_t x1;  // +0x00 T: ObjBoxToWorld a2[0]
	int32_t y1;  // +0x04 T: a2[1]
	int32_t x2;  // +0x08 T: a2[2]
	int32_t y2;  // +0x0C T: a2[3]
};
struct Gof1AtRecord {
	uint8_t hitReaction;  // +0x00 T: ObjFighterStateAndHitReaction 0x43BF40 v87 -> g_HitReactionClassTable / g_HitReactionActionByStance (what the victim plays); 0..5 in the data
	uint8_t hitstopLevel;  // +0x01 T: index into g_HitstopFramesByLevel (byte_1622408, loaded from vector.txt by sub_42C1D0) -> sub_43BEF0 hitstop and screen shake
	uint8_t hitSparkClass;  // +0x02 T: hit spark/sound class; < 14 selects the spark and word_4650D8[6*class] default sound
	uint8_t attackKind;  // +0x03 T: g_AtKindTargetsObjectsOnly[kind] / g_AtKindImmunityChannel[kind] (ObjCheckAttackVs*), and the switch in ObjFighterStateAndHitReaction; 0 or 7 in the data
	uint8_t hitSoundOverride;  // +0x04 T: Se_RequestPlay(this) when non-zero, else the class default sound
	Gof1AtFlagsA flagsA;  // +0x05 T: see Gof1AtFlagsA
	int16_t damage;  // +0x06 T: sub_43FA70 / sub_43F9E0 (damage scaling), chip damage = scaled >> 3
	int16_t meterGain;  // +0x08 T: AddSuperMeter(attacker, +8) and (victim, +8 >> 1 / >> 2)
	int16_t guardBreakValue;  // +0x0A T: added to the guarding victim's guard gauge (actor+108) (ObjFighterStateAndHitReaction v6+10); 0 in the data
	uint8_t unused_0C[3];  // +0x0C zero in all records, not read
	Gof1StatusEffect statusEffect;  // +0x0F T: written to actor+248 when non-zero (ObjFighterStateAndHitReaction v108); DrawFighterSprite tints the victim: 1 red pulse, 2 blue random shimmer, 3 yellow/black/grey cycle; 0 in the data
	Gof1AtFlagsB flagsB;  // +0x10 T: see Gof1AtFlagsB
	uint8_t unused_11;  // +0x11 zero in all records, not read
	Gof1AtHitClass hitClass;  // +0x12 T: row of g_AtClassVsInvulnHitTable (sub_43B050) and guard-height check (ObjFighterStateAndHitReaction v32); 0..4
	uint8_t unused_14[6];  // +0x14 zero in all records, not read
};
struct Gof1IfRecord {
	Gof1IfType type;  // +0x00 T: switch in Actor_RunFrameIfRecord; g_IfTypePhaseTable[type] picks the phase it runs in (14, 15, 19, 20 run in phase 1)
	uint8_t unused_01[3];  // +0x01 zero in all records, not read
	int32_t param[4];  // +0x04 T: *(a2+4), +8, +12, +16 (type dependent: target frame/action, mask, counter, ...); +20/+24 are never read
	uint8_t unused_14[8];  // +0x14 zero in all records, not read
};
struct Gof1EfRecord {
	Gof1EfType type;  // +0x00 T: switch in Actor_RunFrameEFs
	uint8_t subType;  // +0x01 T: effect/pattern id, sound bank or Gof1EfActorOp (type 6) depending on the type
	int16_t arg[5];  // +0x02 T: five signed words (x, y, speeds, flags...) read at +2, +4, +6, +8, +10 by the type handlers (InitChildObject 0x414710, sub_414DC0, sub_41DF00, ...)
	uint8_t unused_0C[8];  // +0x0C zero in all records, not read by any handler
};
struct Gof1PartsHeader {
	uint32_t version;  // +0x00 E: 2 (the loader never checks it)
	uint32_t magic;  // +0x04 E: 0x01234567
	uint8_t unused_08[16];  // +0x08 zero in all files, not read
	uint32_t patternOffset[1000];  // +0x18 T: blob-relative offset of the parts pattern, 0 = absent (UploadPartsAndCG v8 + 6 dwords; patterns are 3680 bytes apart)
	char patternName[32000];  // +0xFB8 E: CP932 part-pattern names such as "000_00"; not read
	uint32_t textureRegionOffset;  // +0x8CB8 T: v8[9006] = blob offset of the texture region (right after the last parts pattern)
};
struct Gof1Part {
	int32_t x;  // +0x00 T: position X (sub_42FFE0 *(v43+v24))
	int32_t y;  // +0x04 T: position Y
	int32_t width;  // +0x08 T: destination width before scaling
	int32_t height;  // +0x0C T: destination height before scaling
	Gof1PartFlipMode flipMode;  // +0x10 T: 1 = flip X, 2 = flip Y, 3 = both (sub_42FFE0 v76 switch on byte +16)
	uint8_t linearMagFilter;  // +0x11 T: non-zero = sub_4073E0(2) sets the magnification filter flag byte_4A8F80 to 2 (linear) for this part (sub_42FFE0); 3 parts of 96480
	uint8_t editorFlag_12;  // +0x12 E: 1 in 29% of the parts; no reader (the renderer reads bytes +16/+17 only)
	uint8_t unused_13;  // +0x13 zero in all parts, not read
	int32_t scaleX;  // +0x14 T: scale in 1/1000 (1000 = 1.0)
	int32_t scaleY;  // +0x18 T: scale in 1/1000
	int32_t rotation;  // +0x1C T: 1/10000 turn, x0.036 degrees (sub_42FEF0 / flt_15F0858)
	uint8_t colorA;  // +0x20 T: modulation alpha (x HIBYTE(a10))
	uint8_t colorR;  // +0x21 T: modulation red
	uint8_t colorG;  // +0x22 T: modulation green
	uint8_t colorB;  // +0x23 T: modulation blue
	uint8_t addR;  // +0x24 T: additive red (+ dword_1864EDC)
	uint8_t addG;  // +0x25 T: additive green
	uint8_t addB;  // +0x26 T: additive blue
	uint8_t unused_27;  // +0x27 zero in all parts, not read
	int32_t textureSlot;  // +0x28 T: texture index inside the region; UploadPartsAndCG adds the character's slot base (50*char + 2)
	int32_t srcX;  // +0x2C T: cut-out x in the texture (*(v43+v24+44))
	int32_t srcY;  // +0x30 T: cut-out y
	int32_t srcWidth;  // +0x34 T: cut-out width (0 = part not drawn)
	int32_t srcHeight;  // +0x38 T: cut-out height
	uint8_t drawOrder;  // +0x3C T: draw pass number; the renderer collects parts per value 0..255 (sub_42FFE0 byte at v30 = part + 60)
	uint8_t unused_3D[3];  // +0x3D zero in all parts, not read
	int32_t scaleOriginX;  // +0x40 T: fixed point of the scale (sub_42FFE0 *(v43+v24+64))
	int32_t scaleOriginY;  // +0x44 T: fixed point of the scale (+68)
	uint8_t unused_48[20];  // +0x48 zero in all parts, not read
};
struct Gof1PartsPattern {
	Gof1Part part[40];  // +0x00 T: UploadPartsAndCG / sub_42FFE0 loop 40 x 92 bytes
};
struct Gof1TextureRegion {
	uint8_t unused_00[20];  // +0x00 zero in all files, not read
	uint32_t version;  // +0x14 E: 1 in all files, not read
	uint32_t textureCount;  // +0x18 E: 3..7; the loader walks all 50 slots instead
	uint32_t textureOffset[50];  // +0x1C T: region-relative offset of each raster, 0 = unused slot (UploadPartsAndCG v10 = region + 28)
	char textureName[3200];  // +0xE4 E: source bitmap names such as "ayu00.bmp"; not read
	uint32_t textureSize[50];  // +0xD64 T: edge length in pixels of the square raster (v10[850]); 512 in the data
	uint8_t unused_E2C[8196];  // +0xE2C zero in all files, not read (padding up to the first raster at +0x2E30)
};
struct Gof1PatternName {
	char name[64];  // +0x00 E: CP932 pattern name, e.g. "立ち弱攻撃"; editor-only, the game never reads the tail
};
#pragma pack(pop)

static_assert(sizeof(Gof1ArchiveFileHeader) == 0x8, "Gof1ArchiveFileHeader size");
static_assert(offsetof(Gof1ArchiveFileHeader, plainFlag) == 0x0, "Gof1ArchiveFileHeader.plainFlag");
static_assert(offsetof(Gof1ArchiveFileHeader, entryCountXorKey) == 0x4, "Gof1ArchiveFileHeader.entryCountXorKey");
static_assert(sizeof(Gof1ArchiveEntry) == 0x40, "Gof1ArchiveEntry size");
static_assert(offsetof(Gof1ArchiveEntry, name) == 0x0, "Gof1ArchiveEntry.name");
static_assert(offsetof(Gof1ArchiveEntry, sizeXorKey) == 0x38, "Gof1ArchiveEntry.sizeXorKey");
static_assert(offsetof(Gof1ArchiveEntry, offset) == 0x3C, "Gof1ArchiveEntry.offset");
static_assert(sizeof(Gof1ArchiveHandle) == 0x1C, "Gof1ArchiveHandle size");
static_assert(offsetof(Gof1ArchiveHandle, hFile) == 0x0, "Gof1ArchiveHandle.hFile");
static_assert(offsetof(Gof1ArchiveHandle, hMapping) == 0x4, "Gof1ArchiveHandle.hMapping");
static_assert(offsetof(Gof1ArchiveHandle, view) == 0x8, "Gof1ArchiveHandle.view");
static_assert(offsetof(Gof1ArchiveHandle, plainFlag) == 0xC, "Gof1ArchiveHandle.plainFlag");
static_assert(offsetof(Gof1ArchiveHandle, entryCount) == 0x10, "Gof1ArchiveHandle.entryCount");
static_assert(offsetof(Gof1ArchiveHandle, unused_14) == 0x14, "Gof1ArchiveHandle.unused_14");
static_assert(offsetof(Gof1ArchiveHandle, entries) == 0x18, "Gof1ArchiveHandle.entries");
static_assert(sizeof(Gof1FileHeader) == 0x44, "Gof1FileHeader size");
static_assert(offsetof(Gof1FileHeader, signature) == 0x0, "Gof1FileHeader.signature");
static_assert(offsetof(Gof1FileHeader, unused_08) == 0x8, "Gof1FileHeader.unused_08");
static_assert(offsetof(Gof1FileHeader, version) == 0x10, "Gof1FileHeader.version");
static_assert(offsetof(Gof1FileHeader, patternAreaEnd) == 0x14, "Gof1FileHeader.patternAreaEnd");
static_assert(offsetof(Gof1FileHeader, partsSize) == 0x18, "Gof1FileHeader.partsSize");
static_assert(offsetof(Gof1FileHeader, cgOffset) == 0x1C, "Gof1FileHeader.cgOffset");
static_assert(offsetof(Gof1FileHeader, cgSize) == 0x20, "Gof1FileHeader.cgSize");
static_assert(offsetof(Gof1FileHeader, unused_24) == 0x24, "Gof1FileHeader.unused_24");
static_assert(sizeof(Gof1CharDatHead) == 0x444, "Gof1CharDatHead size");
static_assert(offsetof(Gof1CharDatHead, header) == 0x0, "Gof1CharDatHead.header");
static_assert(offsetof(Gof1CharDatHead, patternOffset) == 0x44, "Gof1CharDatHead.patternOffset");
static_assert(sizeof(Gof1PatternHeader) == 0x14, "Gof1PatternHeader size");
static_assert(offsetof(Gof1PatternHeader, frameCount) == 0x0, "Gof1PatternHeader.frameCount");
static_assert(offsetof(Gof1PatternHeader, moveInfo) == 0x1, "Gof1PatternHeader.moveInfo");
static_assert(offsetof(Gof1PatternHeader, moveLevel) == 0x2, "Gof1PatternHeader.moveLevel");
static_assert(offsetof(Gof1PatternHeader, frameSizeTag) == 0x3, "Gof1PatternHeader.frameSizeTag");
static_assert(offsetof(Gof1PatternHeader, boxTableOffset) == 0x4, "Gof1PatternHeader.boxTableOffset");
static_assert(offsetof(Gof1PatternHeader, atTableOffset) == 0x8, "Gof1PatternHeader.atTableOffset");
static_assert(offsetof(Gof1PatternHeader, ifTableOffset) == 0xC, "Gof1PatternHeader.ifTableOffset");
static_assert(offsetof(Gof1PatternHeader, efTableOffset) == 0x10, "Gof1PatternHeader.efTableOffset");
static_assert(sizeof(Gof1AnimFrame) == 0x28, "Gof1AnimFrame size");
static_assert(offsetof(Gof1AnimFrame, spriteId) == 0x0, "Gof1AnimFrame.spriteId");
static_assert(offsetof(Gof1AnimFrame, offsetX) == 0x2, "Gof1AnimFrame.offsetX");
static_assert(offsetof(Gof1AnimFrame, offsetY) == 0x4, "Gof1AnimFrame.offsetY");
static_assert(offsetof(Gof1AnimFrame, duration) == 0x6, "Gof1AnimFrame.duration");
static_assert(offsetof(Gof1AnimFrame, drawMode) == 0x8, "Gof1AnimFrame.drawMode");
static_assert(offsetof(Gof1AnimFrame, blendMode) == 0x9, "Gof1AnimFrame.blendMode");
static_assert(offsetof(Gof1AnimFrame, alpha) == 0xA, "Gof1AnimFrame.alpha");
static_assert(offsetof(Gof1AnimFrame, aniFlag) == 0xB, "Gof1AnimFrame.aniFlag");
static_assert(offsetof(Gof1AnimFrame, jumpTarget) == 0xC, "Gof1AnimFrame.jumpTarget");
static_assert(offsetof(Gof1AnimFrame, landJumpTarget) == 0xD, "Gof1AnimFrame.landJumpTarget");
static_assert(offsetof(Gof1AnimFrame, drawPriority) == 0xE, "Gof1AnimFrame.drawPriority");
static_assert(offsetof(Gof1AnimFrame, unused_0F) == 0xF, "Gof1AnimFrame.unused_0F");
static_assert(offsetof(Gof1AnimFrame, zoom) == 0x10, "Gof1AnimFrame.zoom");
static_assert(offsetof(Gof1AnimFrame, loopCount) == 0x12, "Gof1AnimFrame.loopCount");
static_assert(offsetof(Gof1AnimFrame, loopEndFrame) == 0x13, "Gof1AnimFrame.loopEndFrame");
static_assert(offsetof(Gof1AnimFrame, unused_14) == 0x14, "Gof1AnimFrame.unused_14");
static_assert(offsetof(Gof1AnimFrame, interpolateToNext) == 0x18, "Gof1AnimFrame.interpolateToNext");
static_assert(offsetof(Gof1AnimFrame, unused_19) == 0x19, "Gof1AnimFrame.unused_19");
static_assert(sizeof(Gof1StateFrame) == 0x28, "Gof1StateFrame size");
static_assert(offsetof(Gof1StateFrame, clearVelX) == 0x0, "Gof1StateFrame.clearVelX");
static_assert(offsetof(Gof1StateFrame, clearVelY) == 0x1, "Gof1StateFrame.clearVelY");
static_assert(offsetof(Gof1StateFrame, addVelX) == 0x2, "Gof1StateFrame.addVelX");
static_assert(offsetof(Gof1StateFrame, addVelY) == 0x3, "Gof1StateFrame.addVelY");
static_assert(offsetof(Gof1StateFrame, unused_04) == 0x4, "Gof1StateFrame.unused_04");
static_assert(offsetof(Gof1StateFrame, velX) == 0x8, "Gof1StateFrame.velX");
static_assert(offsetof(Gof1StateFrame, velY) == 0xA, "Gof1StateFrame.velY");
static_assert(offsetof(Gof1StateFrame, accelX) == 0xC, "Gof1StateFrame.accelX");
static_assert(offsetof(Gof1StateFrame, accelY) == 0xE, "Gof1StateFrame.accelY");
static_assert(offsetof(Gof1StateFrame, stance) == 0x10, "Gof1StateFrame.stance");
static_assert(offsetof(Gof1StateFrame, normalCancel) == 0x11, "Gof1StateFrame.normalCancel");
static_assert(offsetof(Gof1StateFrame, specialCancel) == 0x12, "Gof1StateFrame.specialCancel");
static_assert(offsetof(Gof1StateFrame, attackHitCount) == 0x13, "Gof1StateFrame.attackHitCount");
static_assert(offsetof(Gof1StateFrame, canAct) == 0x14, "Gof1StateFrame.canAct");
static_assert(offsetof(Gof1StateFrame, unused_15) == 0x15, "Gof1StateFrame.unused_15");
static_assert(offsetof(Gof1StateFrame, flags1) == 0x18, "Gof1StateFrame.flags1");
static_assert(offsetof(Gof1StateFrame, flags2) == 0x1C, "Gof1StateFrame.flags2");
static_assert(offsetof(Gof1StateFrame, maxVelX) == 0x20, "Gof1StateFrame.maxVelX");
static_assert(offsetof(Gof1StateFrame, unused_22) == 0x22, "Gof1StateFrame.unused_22");
static_assert(sizeof(Gof1FrameRecord) == 0x74, "Gof1FrameRecord size");
static_assert(offsetof(Gof1FrameRecord, anim) == 0x0, "Gof1FrameRecord.anim");
static_assert(offsetof(Gof1FrameRecord, state) == 0x28, "Gof1FrameRecord.state");
static_assert(offsetof(Gof1FrameRecord, atIndex) == 0x50, "Gof1FrameRecord.atIndex");
static_assert(offsetof(Gof1FrameRecord, atIndexHighByte) == 0x51, "Gof1FrameRecord.atIndexHighByte");
static_assert(offsetof(Gof1FrameRecord, ifIndex) == 0x52, "Gof1FrameRecord.ifIndex");
static_assert(offsetof(Gof1FrameRecord, efIndex) == 0x58, "Gof1FrameRecord.efIndex");
static_assert(offsetof(Gof1FrameRecord, boxIndex) == 0x60, "Gof1FrameRecord.boxIndex");
static_assert(sizeof(Gof1Box) == 0x8, "Gof1Box size");
static_assert(offsetof(Gof1Box, x1) == 0x0, "Gof1Box.x1");
static_assert(offsetof(Gof1Box, y1) == 0x2, "Gof1Box.y1");
static_assert(offsetof(Gof1Box, x2) == 0x4, "Gof1Box.x2");
static_assert(offsetof(Gof1Box, y2) == 0x6, "Gof1Box.y2");
static_assert(sizeof(Gof1RectI32) == 0x10, "Gof1RectI32 size");
static_assert(offsetof(Gof1RectI32, x1) == 0x0, "Gof1RectI32.x1");
static_assert(offsetof(Gof1RectI32, y1) == 0x4, "Gof1RectI32.y1");
static_assert(offsetof(Gof1RectI32, x2) == 0x8, "Gof1RectI32.x2");
static_assert(offsetof(Gof1RectI32, y2) == 0xC, "Gof1RectI32.y2");
static_assert(sizeof(Gof1AtRecord) == 0x1A, "Gof1AtRecord size");
static_assert(offsetof(Gof1AtRecord, hitReaction) == 0x0, "Gof1AtRecord.hitReaction");
static_assert(offsetof(Gof1AtRecord, hitstopLevel) == 0x1, "Gof1AtRecord.hitstopLevel");
static_assert(offsetof(Gof1AtRecord, hitSparkClass) == 0x2, "Gof1AtRecord.hitSparkClass");
static_assert(offsetof(Gof1AtRecord, attackKind) == 0x3, "Gof1AtRecord.attackKind");
static_assert(offsetof(Gof1AtRecord, hitSoundOverride) == 0x4, "Gof1AtRecord.hitSoundOverride");
static_assert(offsetof(Gof1AtRecord, flagsA) == 0x5, "Gof1AtRecord.flagsA");
static_assert(offsetof(Gof1AtRecord, damage) == 0x6, "Gof1AtRecord.damage");
static_assert(offsetof(Gof1AtRecord, meterGain) == 0x8, "Gof1AtRecord.meterGain");
static_assert(offsetof(Gof1AtRecord, guardBreakValue) == 0xA, "Gof1AtRecord.guardBreakValue");
static_assert(offsetof(Gof1AtRecord, unused_0C) == 0xC, "Gof1AtRecord.unused_0C");
static_assert(offsetof(Gof1AtRecord, statusEffect) == 0xF, "Gof1AtRecord.statusEffect");
static_assert(offsetof(Gof1AtRecord, flagsB) == 0x10, "Gof1AtRecord.flagsB");
static_assert(offsetof(Gof1AtRecord, unused_11) == 0x11, "Gof1AtRecord.unused_11");
static_assert(offsetof(Gof1AtRecord, hitClass) == 0x12, "Gof1AtRecord.hitClass");
static_assert(offsetof(Gof1AtRecord, unused_14) == 0x14, "Gof1AtRecord.unused_14");
static_assert(sizeof(Gof1IfRecord) == 0x1C, "Gof1IfRecord size");
static_assert(offsetof(Gof1IfRecord, type) == 0x0, "Gof1IfRecord.type");
static_assert(offsetof(Gof1IfRecord, unused_01) == 0x1, "Gof1IfRecord.unused_01");
static_assert(offsetof(Gof1IfRecord, param) == 0x4, "Gof1IfRecord.param");
static_assert(offsetof(Gof1IfRecord, unused_14) == 0x14, "Gof1IfRecord.unused_14");
static_assert(sizeof(Gof1EfRecord) == 0x14, "Gof1EfRecord size");
static_assert(offsetof(Gof1EfRecord, type) == 0x0, "Gof1EfRecord.type");
static_assert(offsetof(Gof1EfRecord, subType) == 0x1, "Gof1EfRecord.subType");
static_assert(offsetof(Gof1EfRecord, arg) == 0x2, "Gof1EfRecord.arg");
static_assert(offsetof(Gof1EfRecord, unused_0C) == 0xC, "Gof1EfRecord.unused_0C");
static_assert(sizeof(Gof1PartsHeader) == 0x8CBC, "Gof1PartsHeader size");
static_assert(offsetof(Gof1PartsHeader, version) == 0x0, "Gof1PartsHeader.version");
static_assert(offsetof(Gof1PartsHeader, magic) == 0x4, "Gof1PartsHeader.magic");
static_assert(offsetof(Gof1PartsHeader, unused_08) == 0x8, "Gof1PartsHeader.unused_08");
static_assert(offsetof(Gof1PartsHeader, patternOffset) == 0x18, "Gof1PartsHeader.patternOffset");
static_assert(offsetof(Gof1PartsHeader, patternName) == 0xFB8, "Gof1PartsHeader.patternName");
static_assert(offsetof(Gof1PartsHeader, textureRegionOffset) == 0x8CB8, "Gof1PartsHeader.textureRegionOffset");
static_assert(sizeof(Gof1Part) == 0x5C, "Gof1Part size");
static_assert(offsetof(Gof1Part, x) == 0x0, "Gof1Part.x");
static_assert(offsetof(Gof1Part, y) == 0x4, "Gof1Part.y");
static_assert(offsetof(Gof1Part, width) == 0x8, "Gof1Part.width");
static_assert(offsetof(Gof1Part, height) == 0xC, "Gof1Part.height");
static_assert(offsetof(Gof1Part, flipMode) == 0x10, "Gof1Part.flipMode");
static_assert(offsetof(Gof1Part, linearMagFilter) == 0x11, "Gof1Part.linearMagFilter");
static_assert(offsetof(Gof1Part, editorFlag_12) == 0x12, "Gof1Part.editorFlag_12");
static_assert(offsetof(Gof1Part, unused_13) == 0x13, "Gof1Part.unused_13");
static_assert(offsetof(Gof1Part, scaleX) == 0x14, "Gof1Part.scaleX");
static_assert(offsetof(Gof1Part, scaleY) == 0x18, "Gof1Part.scaleY");
static_assert(offsetof(Gof1Part, rotation) == 0x1C, "Gof1Part.rotation");
static_assert(offsetof(Gof1Part, colorA) == 0x20, "Gof1Part.colorA");
static_assert(offsetof(Gof1Part, colorR) == 0x21, "Gof1Part.colorR");
static_assert(offsetof(Gof1Part, colorG) == 0x22, "Gof1Part.colorG");
static_assert(offsetof(Gof1Part, colorB) == 0x23, "Gof1Part.colorB");
static_assert(offsetof(Gof1Part, addR) == 0x24, "Gof1Part.addR");
static_assert(offsetof(Gof1Part, addG) == 0x25, "Gof1Part.addG");
static_assert(offsetof(Gof1Part, addB) == 0x26, "Gof1Part.addB");
static_assert(offsetof(Gof1Part, unused_27) == 0x27, "Gof1Part.unused_27");
static_assert(offsetof(Gof1Part, textureSlot) == 0x28, "Gof1Part.textureSlot");
static_assert(offsetof(Gof1Part, srcX) == 0x2C, "Gof1Part.srcX");
static_assert(offsetof(Gof1Part, srcY) == 0x30, "Gof1Part.srcY");
static_assert(offsetof(Gof1Part, srcWidth) == 0x34, "Gof1Part.srcWidth");
static_assert(offsetof(Gof1Part, srcHeight) == 0x38, "Gof1Part.srcHeight");
static_assert(offsetof(Gof1Part, drawOrder) == 0x3C, "Gof1Part.drawOrder");
static_assert(offsetof(Gof1Part, unused_3D) == 0x3D, "Gof1Part.unused_3D");
static_assert(offsetof(Gof1Part, scaleOriginX) == 0x40, "Gof1Part.scaleOriginX");
static_assert(offsetof(Gof1Part, scaleOriginY) == 0x44, "Gof1Part.scaleOriginY");
static_assert(offsetof(Gof1Part, unused_48) == 0x48, "Gof1Part.unused_48");
static_assert(sizeof(Gof1PartsPattern) == 0xE60, "Gof1PartsPattern size");
static_assert(offsetof(Gof1PartsPattern, part) == 0x0, "Gof1PartsPattern.part");
static_assert(sizeof(Gof1TextureRegion) == 0x2E30, "Gof1TextureRegion size");
static_assert(offsetof(Gof1TextureRegion, unused_00) == 0x0, "Gof1TextureRegion.unused_00");
static_assert(offsetof(Gof1TextureRegion, version) == 0x14, "Gof1TextureRegion.version");
static_assert(offsetof(Gof1TextureRegion, textureCount) == 0x18, "Gof1TextureRegion.textureCount");
static_assert(offsetof(Gof1TextureRegion, textureOffset) == 0x1C, "Gof1TextureRegion.textureOffset");
static_assert(offsetof(Gof1TextureRegion, textureName) == 0xE4, "Gof1TextureRegion.textureName");
static_assert(offsetof(Gof1TextureRegion, textureSize) == 0xD64, "Gof1TextureRegion.textureSize");
static_assert(offsetof(Gof1TextureRegion, unused_E2C) == 0xE2C, "Gof1TextureRegion.unused_E2C");
static_assert(sizeof(Gof1PatternName) == 0x40, "Gof1PatternName size");
static_assert(offsetof(Gof1PatternName, name) == 0x0, "Gof1PatternName.name");

static const Han2EnumValue kGof1AniFlagValues[] = {
	{"G1ANI_END_TO_PATTERN", (int64_t)(0)},
	{"G1ANI_NEXT", (int64_t)(1)},
	{"G1ANI_JUMP_TO_FRAME", (int64_t)(2)},
	{"G1ANI_NEXT_LAND_TO_PATTERN", (int64_t)(3)},
	{"G1ANI_JUMP_TO_FRAME_LAND_TO_PATTERN", (int64_t)(4)},
	{"G1ANI_LOOP_COUNTED", (int64_t)(5)},
};
static const Han2EnumValue kGof1DrawModeValues[] = {
	{"G1DRAW_NORMAL", (int64_t)(0)},
	{"G1DRAW_FLIP_H", (int64_t)(1)},
	{"G1DRAW_FLIP_V", (int64_t)(2)},
	{"G1DRAW_ROT_90", (int64_t)(3)},
	{"G1DRAW_ROT_180", (int64_t)(4)},
	{"G1DRAW_ROT_270", (int64_t)(5)},
	{"G1DRAW_FLIP_H_ROT_90", (int64_t)(6)},
	{"G1DRAW_FLIP_H_ROT_270", (int64_t)(7)},
	{"G1DRAW_ROT_FREE", (int64_t)(8)},
	{"G1DRAW_ROT_FREE_FLIPPED", (int64_t)(9)},
};
static const Han2EnumValue kGof1BlendModeValues[] = {
	{"G1BLEND_OPAQUE", (int64_t)(0)},
	{"G1BLEND_ALPHA", (int64_t)(1)},
};
static const Han2EnumValue kGof1StanceValues[] = {
	{"G1STANCE_GROUND", (int64_t)(0)},
	{"G1STANCE_AIR", (int64_t)(1)},
	{"G1STANCE_CROUCH", (int64_t)(2)},
};
static const Han2EnumValue kGof1CancelPermissionValues[] = {
	{"G1CANCEL_NONE", (int64_t)(0)},
	{"G1CANCEL_ON_HIT_OR_GUARD", (int64_t)(1)},
	{"G1CANCEL_ALWAYS", (int64_t)(2)},
};
static const Han2EnumValue kGof1FrameFlags1Values[] = {
	{"G1FF1_CARRY_VELOCITY_AS_INERTIA", (int64_t)(1)},
	{"G1FF1_CLEAR_INERTIA", (int64_t)(2)},
	{"G1FF1_MOTION_ONLY_ON_FIRST_ENTRY", (int64_t)(0x80000000)},
};
static const Han2EnumValue kGof1FrameFlags2Values[] = {
	{"G1FF2_THROW_TECHABLE", (int64_t)(2)},
	{"G1FF2_UNREAD_BIT2", (int64_t)(4)},
	{"G1FF2_INVULN_MASK", (int64_t)(0xF0000)},
	{"G1FF2_COUNTER_MASK", (int64_t)(0xF00000)},
};
static const Han2EnumValue kGof1InvulnClassValues[] = {
	{"G1INVULN_NONE", (int64_t)(0)},
	{"G1INVULN_EVADE_HIGH", (int64_t)(1)},
	{"G1INVULN_EVADE_LOW", (int64_t)(2)},
	{"G1INVULN_STRIKE", (int64_t)(3)},
	{"G1INVULN_THROW", (int64_t)(4)},
};
static const Han2EnumValue kGof1CounterCommandValues[] = {
	{"G1COUNTER_NONE", (int64_t)(0)},
	{"G1COUNTER_STATE_1", (int64_t)(1)},
	{"G1COUNTER_STATE_2", (int64_t)(2)},
	{"G1COUNTER_CLEAR", (int64_t)(3)},
};
static const Han2EnumValue kGof1MoveInfoValues[] = {
	{"G1MOVEINFO_TYPE_MASK", (int64_t)(0x0F)},
	{"G1MOVEINFO_LINEAR_FILTER", (int64_t)(0x40)},
	{"G1MOVEINFO_CG_DOUBLE_RES", (int64_t)(0x80)},
};
static const Han2EnumValue kGof1AtFlagsAValues[] = {
	{"G1ATA_CHIP_DAMAGE", (int64_t)(1)},
	{"G1ATA_NO_KO", (int64_t)(2)},
	{"G1ATA_STANDING_REACTION", (int64_t)(8)},
	{"G1ATA_KNOCKBACK_TOWARD_ATTACKER", (int64_t)(0x10)},
	{"G1ATA_NOT_REFLECTABLE", (int64_t)(0x20)},
	{"G1ATA_AIR_GUARD_RULE", (int64_t)(0x40)},
	{"G1ATA_BASE_KNOCKBACK_ROW", (int64_t)(0x80)},
};
static const Han2EnumValue kGof1AtFlagsBValues[] = {
	{"G1ATB_EXTRA_HIT_SPARK", (int64_t)(1)},
	{"G1ATB_NO_HORIZONTAL_KNOCKBACK", (int64_t)(2)},
	{"G1ATB_NO_COMBO_COUNT", (int64_t)(4)},
	{"G1ATB_SCREEN_SHAKE", (int64_t)(8)},
	{"G1ATB_AIR_COMBO_STARTER", (int64_t)(0x10)},
	{"G1ATB_NO_THROW_TECH", (int64_t)(0x20)},
	{"G1ATB_HITS_OWN_TEAM", (int64_t)(0x40)},
};
static const Han2EnumValue kGof1AtHitClassValues[] = {
	{"G1ATCLASS_HIGH_STRIKE", (int64_t)(0)},
	{"G1ATCLASS_LOW_STRIKE", (int64_t)(1)},
	{"G1ATCLASS_HIGH_THROW", (int64_t)(2)},
	{"G1ATCLASS_LOW_THROW", (int64_t)(3)},
	{"G1ATCLASS_UNGUARDABLE", (int64_t)(4)},
};
static const Han2EnumValue kGof1StatusEffectValues[] = {
	{"G1STATUS_NONE", (int64_t)(0)},
	{"G1STATUS_RED_FLICKER", (int64_t)(1)},
	{"G1STATUS_BLUE_FLICKER", (int64_t)(2)},
	{"G1STATUS_YELLOW_BLACK_GREY_CYCLE", (int64_t)(3)},
};
static const Han2EnumValue kGof1IfTypeValues[] = {
	{"G1IF_DIRECTION_JUMP", (int64_t)(1)},
	{"G1IF_END_CONDITION", (int64_t)(2)},
	{"G1IF_HIT_RESULT_JUMP", (int64_t)(3)},
	{"G1IF_VELOCITY_SIGN_JUMP", (int64_t)(4)},
	{"G1IF_INVINCIBLE_JUMP", (int64_t)(5)},
	{"G1IF_INPUT_JUMP", (int64_t)(6)},
	{"G1IF_INPUT_ACTION", (int64_t)(7)},
	{"G1IF_RANDOM_JUMP", (int64_t)(8)},
	{"G1IF_SET_LOOP_COUNTER", (int64_t)(9)},
	{"G1IF_LOOP_ZERO_JUMP", (int64_t)(10)},
	{"G1IF_COMMAND_MOVE_ACTION", (int64_t)(11)},
	{"G1IF_NEAREST_DISTANCE_JUMP", (int64_t)(12)},
	{"G1IF_SCREEN_EDGE_ACTION", (int64_t)(13)},
	{"G1IF_BOX_HIT_JUMP", (int64_t)(14)},
	{"G1IF_BOX_GRAB_JUMP", (int64_t)(15)},
	{"G1IF_CAMERA_FOLLOW", (int64_t)(16)},
	{"G1IF_HIT_COUNT_JUMP", (int64_t)(17)},
	{"G1IF_PARENT_ACTION_JUMP", (int64_t)(18)},
	{"G1IF_REFLECT_OBJECT", (int64_t)(19)},
	{"G1IF_BOX_ENEMY_JUMP", (int64_t)(20)},
	{"G1IF_FIGHTER_PRESENT_JUMP", (int64_t)(21)},
	{"G1IF_STAGE_JUMP", (int64_t)(22)},
	{"G1IF_GAME_MODE_JUMP", (int64_t)(23)},
	{"G1IF_COUNTER_AT_LEAST_JUMP", (int64_t)(24)},
	{"G1IF_VARIABLE_COMPARE_JUMP", (int64_t)(25)},
	{"G1IF_ADJUST_VELOCITY_BY_INPUT", (int64_t)(26)},
	{"G1IF_PARENT_GRABBED_JUMP", (int64_t)(27)},
	{"G1IF_ROUND_END_JUMP", (int64_t)(28)},
	{"G1IF_X_LIMIT_JUMP", (int64_t)(29)},
	{"G1IF_FACING_JUMP", (int64_t)(30)},
	{"G1IF_COMMAND_MOVE_JUMP", (int64_t)(31)},
	{"G1IF_CPU_PLAYER_JUMP", (int64_t)(32)},
	{"G1IF_ALLY_BOX_JUMP", (int64_t)(50)},
};
static const Han2EnumValue kGof1EfTypeValues[] = {
	{"G1EF_SPAWN_CHILD_OBJECT", (int64_t)(1)},
	{"G1EF_SPAWN_EFFECT", (int64_t)(2)},
	{"G1EF_SPAWN_PARTICLES", (int64_t)(3)},
	{"G1EF_CONTROL_GRABBED", (int64_t)(4)},
	{"G1EF_THROW_DAMAGE", (int64_t)(5)},
	{"G1EF_ACTOR_OP", (int64_t)(6)},
	{"G1EF_SYSTEM_PARTICLE", (int64_t)(7)},
	{"G1EF_SPAWN_COMMON_OBJECT", (int64_t)(8)},
	{"G1EF_PLAY_SOUND", (int64_t)(9)},
	{"G1EF_SET_ACTOR_PARAMS", (int64_t)(30)},
	{"G1EF_SPAWN_CHILD_FROM_PARENT", (int64_t)(50)},
};
static const Han2EnumValue kGof1EfActorOpValues[] = {
	{"G1OP_SET_TRAIL_EFFECT", (int64_t)(0)},
	{"G1OP_SCREEN_SHAKE_FREEZE", (int64_t)(1)},
	{"G1OP_SET_FREEZE_TIMERS", (int64_t)(2)},
	{"G1OP_SET_PERIODIC_PARAMS", (int64_t)(3)},
	{"G1OP_ADD_LIFE_METER_GAUGE", (int64_t)(4)},
	{"G1OP_FLIP_FACING", (int64_t)(5)},
	{"G1OP_SET_VELOCITY_RANGE", (int64_t)(6)},
	{"G1OP_SPAWN_FRAME_GHOST", (int64_t)(7)},
	{"G1OP_AIM_AT_OPPONENT", (int64_t)(8)},
	{"G1OP_SET_FLAG_215", (int64_t)(9)},
	{"G1OP_SET_WORD_VAR_236", (int64_t)(10)},
	{"G1OP_SET_HITSTOP", (int64_t)(11)},
	{"G1OP_MOVE_AND_FLASH", (int64_t)(12)},
	{"G1OP_FLASH", (int64_t)(13)},
	{"G1OP_ADD_COUNTER", (int64_t)(100)},
	{"G1OP_SUB_COUNTER", (int64_t)(101)},
	{"G1OP_ADD_BYTE_278", (int64_t)(102)},
	{"G1OP_SUB_BYTE_278", (int64_t)(103)},
	{"G1OP_SET_OR_ADD_WORD_VAR_280", (int64_t)(105)},
	{"G1OP_SET_BYTE_218", (int64_t)(252)},
	{"G1OP_FORCE_ROUND_END", (int64_t)(253)},
	{"G1OP_SET_FLAG_261", (int64_t)(254)},
	{"G1OP_SET_FLAG_260", (int64_t)(255)},
};
static const Han2EnumValue kGof1PartFlipModeValues[] = {
	{"G1PARTFLIP_NONE", (int64_t)(0)},
	{"G1PARTFLIP_H", (int64_t)(1)},
	{"G1PARTFLIP_V", (int64_t)(2)},
	{"G1PARTFLIP_HV", (int64_t)(3)},
};
static const Han2EnumInfo kGof1TypesEnums[] = {
	{"Gof1AniFlag", kGof1AniFlagValues, 6, false},
	{"Gof1DrawMode", kGof1DrawModeValues, 10, false},
	{"Gof1BlendMode", kGof1BlendModeValues, 2, false},
	{"Gof1Stance", kGof1StanceValues, 3, false},
	{"Gof1CancelPermission", kGof1CancelPermissionValues, 3, false},
	{"Gof1FrameFlags1", kGof1FrameFlags1Values, 3, true},
	{"Gof1FrameFlags2", kGof1FrameFlags2Values, 4, true},
	{"Gof1InvulnClass", kGof1InvulnClassValues, 5, false},
	{"Gof1CounterCommand", kGof1CounterCommandValues, 4, false},
	{"Gof1MoveInfo", kGof1MoveInfoValues, 3, false},
	{"Gof1AtFlagsA", kGof1AtFlagsAValues, 7, true},
	{"Gof1AtFlagsB", kGof1AtFlagsBValues, 7, true},
	{"Gof1AtHitClass", kGof1AtHitClassValues, 5, false},
	{"Gof1StatusEffect", kGof1StatusEffectValues, 4, false},
	{"Gof1IfType", kGof1IfTypeValues, 33, false},
	{"Gof1EfType", kGof1EfTypeValues, 11, false},
	{"Gof1EfActorOp", kGof1EfActorOpValues, 23, false},
	{"Gof1PartFlipMode", kGof1PartFlipModeValues, 4, false},
};

static const Han2FieldInfo kGof1ArchiveFileHeaderFields[] = {
	{"plainFlag", 0x0, 4, 1, 0, nullptr, "+0x00 T: 0 = file data is enciphered, non-zero = plain (Archive_XOR_Decrypt_With_Filename returns early when a1+12 != 0); 0 in gof_00/01/03, 1 in gof_02"},
	{"entryCountXorKey", 0x4, 4, 1, 0, nullptr, "+0x04 T: entry count ^ 0xFA261EFB"},
};
static const Han2FieldInfo kGof1ArchiveEntryFields[] = {
	{"name", 0x0, 1, 56, 0, nullptr, "+0x00 T: CP932, NUL padded; byte j ^= (3*(j*i - 28)) & 0xFF"},
	{"sizeXorKey", 0x38, 4, 1, 0, nullptr, "+0x38 T: size ^ 0xFA261EFB; Archive_Find_File_Get_Size reads +56"},
	{"offset", 0x3C, 4, 1, 0, nullptr, "+0x3C T: absolute file offset of the data (data start = 8 + 64*count; entries are contiguous); Archive_XOR_Decrypt_With_Filename seeks +60"},
};
static const Han2FieldInfo kGof1ArchiveHandleFields[] = {
	{"hFile", 0x0, 4, 1, 4, nullptr, "+0x00 T: File_Open handle"},
	{"hMapping", 0x4, 4, 1, 4, nullptr, "+0x04 T: CreateFileMappingA"},
	{"view", 0x8, 4, 1, 4, nullptr, "+0x08 T: MapViewOfFile"},
	{"plainFlag", 0xC, 4, 1, 0, nullptr, "+0x0C T: first dword of the file (a2+12)"},
	{"entryCount", 0x10, 4, 1, 1, nullptr, "+0x10 T: decoded entry count (a2+16)"},
	{"unused_14", 0x14, 4, 1, 0, nullptr, "+0x14 never written or read"},
	{"entries", 0x18, 4, 1, 4, nullptr, "+0x18 T: GlobalAlloc(count << 6) holding the decoded index (a2+24)"},
};
static const Han2FieldInfo kGof1FileHeaderFields[] = {
	{"signature", 0x0, 1, 8, 0, nullptr, "+0x00 E: CP932 \"備前長船\" (94 F5 91 4F 92 B7 91 44) in all 51 files; never read or compared by the game"},
	{"unused_08", 0x8, 1, 8, 0, nullptr, "+0x08 zero in all files, not read"},
	{"version", 0x10, 4, 1, 0, nullptr, "+0x10 V: must be 18 (SpriteDataSlot_LoadCharacterDat: v10[4] != 18 -> return 0)"},
	{"patternAreaEnd", 0x14, 4, 1, 0, nullptr, "+0x14 T: byte size of header + pattern area = start of the parts blob; the loader copies [0, patternAreaEnd) as the pattern block (GlobalAlloc(v5[5]))"},
	{"partsSize", 0x18, 4, 1, 0, nullptr, "+0x18 T: size of the parts blob (old PAT v2); 0 = none; the loader allocates size+0x4000 and copies [patternAreaEnd, +partsSize)"},
	{"cgOffset", 0x1C, 4, 1, 0, nullptr, "+0x1C T: start of the CG blob = patternAreaEnd + partsSize (checked by gof1_dat.py; the loader reads file+cgOffset)"},
	{"cgSize", 0x20, 4, 1, 0, nullptr, "+0x20 T: size of the CG blob; 0 in all 51 shipped files (no CG bank is stored; every sprite is a parts pattern)"},
	{"unused_24", 0x24, 1, 32, 0, nullptr, "+0x24 zero in all files, not read"},
};
static const Han2FieldInfo kGof1CharDatHeadFields[] = {
	{"header", 0x0, 68, 1, 4, nullptr, "+0x00 T: see above"},
	{"patternOffset", 0x44, 4, 256, 1, nullptr, "+0x44 T: absolute offset of pattern p inside this block, -1 = absent (Actor_ResolveFrameDataPointers 0x424590: dword at data + 4*pattern + 68)"},
};
static const Han2FieldInfo kGof1PatternHeaderFields[] = {
	{"frameCount", 0x0, 1, 1, 0, nullptr, "+0x00 T: Actor_ResolveFrameDataPointers compares the frame index against this byte (*v3 <= frame -> error box); 1..100 in the data"},
	{"moveInfo", 0x1, 1, 1, 2, "Gof1MoveInfo", "+0x01 T: low nibble = move type (Pattern_GetMoveType 0x425D60), bit 0x40 = linear filter and bit 0x80 = double-resolution CG (Pattern_IsCgDoubleRes 0x425D80, Pattern_GetLinearFilterBit 0x425DA0)"},
	{"moveLevel", 0x2, 1, 1, 0, nullptr, "+0x02 T: move priority/level (Pattern_GetMoveLevel 0x425D40, compared < 100 by Actor_RequestLocomotionFromInput 0x425FC0); 0, 100 or 255 in the data"},
	{"frameSizeTag", 0x3, 1, 1, 0, nullptr, "+0x03 E: 0 in the 9 retail files, 116 (the frame size) in the 17 LAST*.DAT backup files; no reader"},
	{"boxTableOffset", 0x4, 4, 1, 1, nullptr, "+0x04 T: offset (relative to the pattern start) of the box table (8-byte rects), -1 = none (Actor_ResolveFrameDataPointers -> actor+596)"},
	{"atTableOffset", 0x8, 4, 1, 1, nullptr, "+0x08 T: offset of the AT table (26-byte records), -1 = none (ObjCheckAttackVsFighters 0x43B070: pattern + [+8] + 26*frame.atIndex)"},
	{"ifTableOffset", 0xC, 4, 1, 1, nullptr, "+0x0C T: offset of the IF table (28-byte records), -1 = none (-> actor+620, ObjRunFrameEventsForPhase 0x427130)"},
	{"efTableOffset", 0x10, 4, 1, 1, nullptr, "+0x10 T: offset of the EF table (20-byte records), -1 = none (-> actor+624, Actor_RunFrameEFs 0x413750)"},
};
static const Han2FieldInfo kGof1AnimFrameFields[] = {
	{"spriteId", 0x0, 2, 1, 1, nullptr, "+0x00 T: parts-pattern index when < 10000, CG image id-10000 otherwise (DrawFighterSprite 0x432150 -> sub_42FFE0 reads parts at +24+4*id; ObjBoxToWorld 0x42E4D0 tests < 10000); always < 512 in the data"},
	{"offsetX", 0x2, 2, 1, 1, nullptr, "+0x02 T: draw offset X (DrawFighterSprite v3[1])"},
	{"offsetY", 0x4, 2, 1, 1, nullptr, "+0x04 T: draw offset Y (v3[2])"},
	{"duration", 0x6, 2, 1, 0, nullptr, "+0x06 T: ticks before advancing (ObjRunActionScript 0x424A20 compares a1+14 against it; also the interpolation divisor in sub_42FFE0)"},
	{"drawMode", 0x8, 1, 1, 2, "Gof1DrawMode", "+0x08 T: indexes g_DrawModeTransformTable 0x4640F8 (DrawFighterSprite), mode 8 shifts the origin by 100 (ObjBoxToWorld); 0 or 1 in the data"},
	{"blendMode", 0x9, 1, 1, 2, "Gof1BlendMode", "+0x09 T: non-zero = alpha-blended draw using alpha (DrawFighterSprite v35); the blend code of sub_42FFE0 never reads a9"},
	{"alpha", 0xA, 1, 1, 0, nullptr, "+0x0A T: alpha 0..255, only used when blendMode != 0 (DrawFighterSprite v37)"},
	{"aniFlag", 0xB, 1, 1, 2, "Gof1AniFlag", "+0x0B T: ObjRunActionScript / ObjEnterCurrentAction switch (0 end->pattern, 1 next, 2 jump, 3/4 same + land->pattern, 5 counted loop)"},
	{"jumpTarget", 0xC, 1, 1, 0, nullptr, "+0x0C T: pattern (aniFlag 0) or frame (2, 4, 5) to go to"},
	{"landJumpTarget", 0xD, 1, 1, 0, nullptr, "+0x0D T: frame (or pattern for aniFlag 3/4) entered when the actor lands (ObjRunActionScript landing branch)"},
	{"drawPriority", 0xE, 1, 1, 0, nullptr, "+0x0E T: ObjEnterCurrentAction -> Actor_ApplyDrawPriority 0x425B80 (1 = front, 2 = back among the fighters)"},
	{"unused_0F", 0xF, 1, 1, 0, nullptr, "+0x0F zero in all frames, not read"},
	{"zoom", 0x10, 2, 1, 0, nullptr, "+0x10 T: 256 = 1.0 (DrawFighterSprite v3[8]); 0 = no zoom; constant 0 in the data"},
	{"loopCount", 0x12, 1, 1, 0, nullptr, "+0x12 T: loaded into actor+20 when non-zero (ObjEnterCurrentAction v1[18]); aniFlag 5 repeat count"},
	{"loopEndFrame", 0x13, 1, 1, 0, nullptr, "+0x13 T: frame entered when the aniFlag 5 counter reaches 0 (ObjRunActionScript case 5 reads +19)"},
	{"unused_14", 0x14, 1, 4, 0, nullptr, "+0x14 zero in all frames, not read"},
	{"interpolateToNext", 0x18, 1, 1, 0, nullptr, "+0x18 T: non-zero = tween toward the next frame's parts pattern (sub_42FFE0: *(a22+24))"},
	{"unused_19", 0x19, 1, 15, 0, nullptr, "+0x19 zero in all frames, not read"},
};
static const Han2FieldInfo kGof1StateFrameFields[] = {
	{"clearVelX", 0x0, 1, 1, 0, nullptr, "+0x00 T: zero X velocity, X accel and X max (Actor_ApplyFrameMotionFlags 0x425310: *(_BYTE*)v1)"},
	{"clearVelY", 0x1, 1, 1, 0, nullptr, "+0x01 T: zero Y velocity and accel"},
	{"addVelX", 0x2, 1, 1, 0, nullptr, "+0x02 T: add velX/accelX/maxX facing-aware (sub_425310)"},
	{"addVelY", 0x3, 1, 1, 0, nullptr, "+0x03 T: add velY/accelY"},
	{"unused_04", 0x4, 1, 4, 0, nullptr, "+0x04 zero in all frames, not read"},
	{"velX", 0x8, 2, 1, 1, nullptr, "+0x08 T: added to actor velX when addVelX (sub_425310 v1+8)"},
	{"velY", 0xA, 2, 1, 1, nullptr, "+0x0A T: added to velY when addVelY (v1+10)"},
	{"accelX", 0xC, 2, 1, 1, nullptr, "+0x0C T: added to accelX when addVelX (v1+12)"},
	{"accelY", 0xE, 2, 1, 1, nullptr, "+0x0E T: added to accelY when addVelY (v1+14)"},
	{"stance", 0x10, 1, 1, 2, "Gof1Stance", "+0x10 T: copied to actor+594 (ObjRunActionScript), air physics test in ObjIntegrateMotion 0x4257D0; Actor_DispatchInputByStance 0x4263E0 builds stance | canAct<<4"},
	{"normalCancel", 0x11, 1, 1, 2, "Gof1CancelPermission", "+0x11 T: Actor_RequestLocomotionFromInput 0x425FC0 (2 always, 1 when the actor has hit/been guarded: a1+205 & 0xF)"},
	{"specialCancel", 0x12, 1, 1, 2, "Gof1CancelPermission", "+0x12 E: no reader in gof.exe (RBO/HA4 read it); 0/1/2 in the data (21 frames use 2)"},
	{"attackHitCount", 0x13, 1, 1, 0, nullptr, "+0x13 T: loaded into actor+220 on frame entry (ObjEnterCurrentAction v3 = +19); attack boxes are ignored when it is 0 (ObjCheckAttackVsFighters 0x43B070)"},
	{"canAct", 0x14, 1, 1, 0, nullptr, "+0x14 T: 1 = actor may act (ObjRunActionScript v23+20 == 1, ObjFighterStateAndHitReaction 0x43BF40); combined with stance in Actor_DispatchInputByStance 0x4263E0"},
	{"unused_15", 0x15, 1, 3, 0, nullptr, "+0x15 zero in all frames, not read"},
	{"flags1", 0x18, 4, 1, 2, "Gof1FrameFlags1", "+0x18 T: ObjIntegrateMotion / sub_425310 (bit0 carry velocity as inertia, bit1 clear inertia, bit31 motion only on first entry)"},
	{"flags2", 0x1C, 4, 1, 2, "Gof1FrameFlags2", "+0x1C T: bit1 sub_425E10 throw tech; bits 16..19 invulnerability class (ObjCheckAttackVsFighters reads byte +0x1E & 0xF); bits 20..23 counter command (ObjEnterCurrentAction (dword>>20)&0xF)"},
	{"maxVelX", 0x20, 2, 1, 1, nullptr, "+0x20 T: subtracted/added to actor maxVelX with addVelX (sub_425310 v1+32); 0 except 1 frame"},
	{"unused_22", 0x22, 1, 6, 0, nullptr, "+0x22 zero in all frames, not read"},
};
static const Han2FieldInfo kGof1FrameRecordFields[] = {
	{"anim", 0x0, 40, 1, 4, nullptr, "+0x00 T: see Gof1AnimFrame (actor+612)"},
	{"state", 0x28, 40, 1, 4, nullptr, "+0x28 T: see Gof1StateFrame (actor+616)"},
	{"atIndex", 0x50, 1, 1, 0, nullptr, "+0x50 T: signed char index into the AT table (26*idx), 0xFF = none (ObjCheckAttackVsFighters, ObjCheckAttackVsObjects, sub_43A740 read *(char*)(frame+80))"},
	{"atIndexHighByte", 0x51, 1, 1, 0, nullptr, "+0x51 E: 0, 0xFF or stack garbage (45 distinct values); the engine reads atIndex as a signed char and never touches this byte"},
	{"ifIndex", 0x52, 2, 3, 1, nullptr, "+0x52 T: IF table indices, -1 = empty (ObjRunFrameEventsForPhase loop i = 82; i < 88; i += 2)"},
	{"efIndex", 0x58, 2, 4, 1, nullptr, "+0x58 T: EF table indices, -1 = empty (Actor_RunFrameEFs loop i = 88; i < 96; i += 2)"},
	{"boxIndex", 0x60, 2, 10, 1, nullptr, "+0x60 T: box table indices, -1 = empty (actor+628): [0] pushbox (ObjResolvePushboxCollision), [1..3] hurt boxes (ObjCheckAttackVsFighters loop at +2), [4] grab/probe box (own kind 6 of Actor_FindOverlappingTarget, IF 14/15/19/20), [5] special2 (read by Actor_GetBoxSlotIndex only; 1 frame uses it), [6] reflect/clash box (ObjCheckReflectBoxVsAttacks +12), [7] projectile hurt box (target kind 6 of IF 19; never present in the data), [8..9] attack boxes (+16, +18); slot 9 is never present"},
};
static const Han2FieldInfo kGof1BoxFields[] = {
	{"x1", 0x0, 2, 1, 1, nullptr, "+0x00 T: ObjResolvePushboxCollision reads *(__int16*)(box + 8*idx)"},
	{"y1", 0x2, 2, 1, 1, nullptr, "+0x02 T: +2"},
	{"x2", 0x4, 2, 1, 1, nullptr, "+0x04 T: +4"},
	{"y2", 0x6, 2, 1, 1, nullptr, "+0x06 T: +6"},
};
static const Han2FieldInfo kGof1RectI32Fields[] = {
	{"x1", 0x0, 4, 1, 1, nullptr, "+0x00 T: ObjBoxToWorld a2[0]"},
	{"y1", 0x4, 4, 1, 1, nullptr, "+0x04 T: a2[1]"},
	{"x2", 0x8, 4, 1, 1, nullptr, "+0x08 T: a2[2]"},
	{"y2", 0xC, 4, 1, 1, nullptr, "+0x0C T: a2[3]"},
};
static const Han2FieldInfo kGof1AtRecordFields[] = {
	{"hitReaction", 0x0, 1, 1, 0, nullptr, "+0x00 T: ObjFighterStateAndHitReaction 0x43BF40 v87 -> g_HitReactionClassTable / g_HitReactionActionByStance (what the victim plays); 0..5 in the data"},
	{"hitstopLevel", 0x1, 1, 1, 0, nullptr, "+0x01 T: index into g_HitstopFramesByLevel (byte_1622408, loaded from vector.txt by sub_42C1D0) -> sub_43BEF0 hitstop and screen shake"},
	{"hitSparkClass", 0x2, 1, 1, 0, nullptr, "+0x02 T: hit spark/sound class; < 14 selects the spark and word_4650D8[6*class] default sound"},
	{"attackKind", 0x3, 1, 1, 0, nullptr, "+0x03 T: g_AtKindTargetsObjectsOnly[kind] / g_AtKindImmunityChannel[kind] (ObjCheckAttackVs*), and the switch in ObjFighterStateAndHitReaction; 0 or 7 in the data"},
	{"hitSoundOverride", 0x4, 1, 1, 0, nullptr, "+0x04 T: Se_RequestPlay(this) when non-zero, else the class default sound"},
	{"flagsA", 0x5, 1, 1, 2, "Gof1AtFlagsA", "+0x05 T: see Gof1AtFlagsA"},
	{"damage", 0x6, 2, 1, 1, nullptr, "+0x06 T: sub_43FA70 / sub_43F9E0 (damage scaling), chip damage = scaled >> 3"},
	{"meterGain", 0x8, 2, 1, 1, nullptr, "+0x08 T: AddSuperMeter(attacker, +8) and (victim, +8 >> 1 / >> 2)"},
	{"guardBreakValue", 0xA, 2, 1, 1, nullptr, "+0x0A T: added to the guarding victim's guard gauge (actor+108) (ObjFighterStateAndHitReaction v6+10); 0 in the data"},
	{"unused_0C", 0xC, 1, 3, 0, nullptr, "+0x0C zero in all records, not read"},
	{"statusEffect", 0xF, 1, 1, 2, "Gof1StatusEffect", "+0x0F T: written to actor+248 when non-zero (ObjFighterStateAndHitReaction v108); DrawFighterSprite tints the victim: 1 red pulse, 2 blue random shimmer, 3 yellow/black/grey cycle; 0 in the data"},
	{"flagsB", 0x10, 1, 1, 2, "Gof1AtFlagsB", "+0x10 T: see Gof1AtFlagsB"},
	{"unused_11", 0x11, 1, 1, 0, nullptr, "+0x11 zero in all records, not read"},
	{"hitClass", 0x12, 2, 1, 2, "Gof1AtHitClass", "+0x12 T: row of g_AtClassVsInvulnHitTable (sub_43B050) and guard-height check (ObjFighterStateAndHitReaction v32); 0..4"},
	{"unused_14", 0x14, 1, 6, 0, nullptr, "+0x14 zero in all records, not read"},
};
static const Han2FieldInfo kGof1IfRecordFields[] = {
	{"type", 0x0, 1, 1, 2, "Gof1IfType", "+0x00 T: switch in Actor_RunFrameIfRecord; g_IfTypePhaseTable[type] picks the phase it runs in (14, 15, 19, 20 run in phase 1)"},
	{"unused_01", 0x1, 1, 3, 0, nullptr, "+0x01 zero in all records, not read"},
	{"param", 0x4, 4, 4, 1, nullptr, "+0x04 T: *(a2+4), +8, +12, +16 (type dependent: target frame/action, mask, counter, ...); +20/+24 are never read"},
	{"unused_14", 0x14, 1, 8, 0, nullptr, "+0x14 zero in all records, not read"},
};
static const Han2FieldInfo kGof1EfRecordFields[] = {
	{"type", 0x0, 1, 1, 2, "Gof1EfType", "+0x00 T: switch in Actor_RunFrameEFs"},
	{"subType", 0x1, 1, 1, 0, nullptr, "+0x01 T: effect/pattern id, sound bank or Gof1EfActorOp (type 6) depending on the type"},
	{"arg", 0x2, 2, 5, 1, nullptr, "+0x02 T: five signed words (x, y, speeds, flags...) read at +2, +4, +6, +8, +10 by the type handlers (InitChildObject 0x414710, sub_414DC0, sub_41DF00, ...)"},
	{"unused_0C", 0xC, 1, 8, 0, nullptr, "+0x0C zero in all records, not read by any handler"},
};
static const Han2FieldInfo kGof1PartsHeaderFields[] = {
	{"version", 0x0, 4, 1, 0, nullptr, "+0x00 E: 2 (the loader never checks it)"},
	{"magic", 0x4, 4, 1, 0, nullptr, "+0x04 E: 0x01234567"},
	{"unused_08", 0x8, 1, 16, 0, nullptr, "+0x08 zero in all files, not read"},
	{"patternOffset", 0x18, 4, 1000, 0, nullptr, "+0x18 T: blob-relative offset of the parts pattern, 0 = absent (UploadPartsAndCG v8 + 6 dwords; patterns are 3680 bytes apart)"},
	{"patternName", 0xFB8, 1, 32000, 0, nullptr, "+0xFB8 E: CP932 part-pattern names such as \"000_00\"; not read"},
	{"textureRegionOffset", 0x8CB8, 4, 1, 0, nullptr, "+0x8CB8 T: v8[9006] = blob offset of the texture region (right after the last parts pattern)"},
};
static const Han2FieldInfo kGof1PartFields[] = {
	{"x", 0x0, 4, 1, 1, nullptr, "+0x00 T: position X (sub_42FFE0 *(v43+v24))"},
	{"y", 0x4, 4, 1, 1, nullptr, "+0x04 T: position Y"},
	{"width", 0x8, 4, 1, 1, nullptr, "+0x08 T: destination width before scaling"},
	{"height", 0xC, 4, 1, 1, nullptr, "+0x0C T: destination height before scaling"},
	{"flipMode", 0x10, 1, 1, 2, "Gof1PartFlipMode", "+0x10 T: 1 = flip X, 2 = flip Y, 3 = both (sub_42FFE0 v76 switch on byte +16)"},
	{"linearMagFilter", 0x11, 1, 1, 0, nullptr, "+0x11 T: non-zero = sub_4073E0(2) sets the magnification filter flag byte_4A8F80 to 2 (linear) for this part (sub_42FFE0); 3 parts of 96480"},
	{"editorFlag_12", 0x12, 1, 1, 0, nullptr, "+0x12 E: 1 in 29% of the parts; no reader (the renderer reads bytes +16/+17 only)"},
	{"unused_13", 0x13, 1, 1, 0, nullptr, "+0x13 zero in all parts, not read"},
	{"scaleX", 0x14, 4, 1, 1, nullptr, "+0x14 T: scale in 1/1000 (1000 = 1.0)"},
	{"scaleY", 0x18, 4, 1, 1, nullptr, "+0x18 T: scale in 1/1000"},
	{"rotation", 0x1C, 4, 1, 1, nullptr, "+0x1C T: 1/10000 turn, x0.036 degrees (sub_42FEF0 / flt_15F0858)"},
	{"colorA", 0x20, 1, 1, 0, nullptr, "+0x20 T: modulation alpha (x HIBYTE(a10))"},
	{"colorR", 0x21, 1, 1, 0, nullptr, "+0x21 T: modulation red"},
	{"colorG", 0x22, 1, 1, 0, nullptr, "+0x22 T: modulation green"},
	{"colorB", 0x23, 1, 1, 0, nullptr, "+0x23 T: modulation blue"},
	{"addR", 0x24, 1, 1, 0, nullptr, "+0x24 T: additive red (+ dword_1864EDC)"},
	{"addG", 0x25, 1, 1, 0, nullptr, "+0x25 T: additive green"},
	{"addB", 0x26, 1, 1, 0, nullptr, "+0x26 T: additive blue"},
	{"unused_27", 0x27, 1, 1, 0, nullptr, "+0x27 zero in all parts, not read"},
	{"textureSlot", 0x28, 4, 1, 1, nullptr, "+0x28 T: texture index inside the region; UploadPartsAndCG adds the character's slot base (50*char + 2)"},
	{"srcX", 0x2C, 4, 1, 1, nullptr, "+0x2C T: cut-out x in the texture (*(v43+v24+44))"},
	{"srcY", 0x30, 4, 1, 1, nullptr, "+0x30 T: cut-out y"},
	{"srcWidth", 0x34, 4, 1, 1, nullptr, "+0x34 T: cut-out width (0 = part not drawn)"},
	{"srcHeight", 0x38, 4, 1, 1, nullptr, "+0x38 T: cut-out height"},
	{"drawOrder", 0x3C, 1, 1, 0, nullptr, "+0x3C T: draw pass number; the renderer collects parts per value 0..255 (sub_42FFE0 byte at v30 = part + 60)"},
	{"unused_3D", 0x3D, 1, 3, 0, nullptr, "+0x3D zero in all parts, not read"},
	{"scaleOriginX", 0x40, 4, 1, 1, nullptr, "+0x40 T: fixed point of the scale (sub_42FFE0 *(v43+v24+64))"},
	{"scaleOriginY", 0x44, 4, 1, 1, nullptr, "+0x44 T: fixed point of the scale (+68)"},
	{"unused_48", 0x48, 1, 20, 0, nullptr, "+0x48 zero in all parts, not read"},
};
static const Han2FieldInfo kGof1PartsPatternFields[] = {
	{"part", 0x0, 92, 40, 4, nullptr, "+0x00 T: UploadPartsAndCG / sub_42FFE0 loop 40 x 92 bytes"},
};
static const Han2FieldInfo kGof1TextureRegionFields[] = {
	{"unused_00", 0x0, 1, 20, 0, nullptr, "+0x00 zero in all files, not read"},
	{"version", 0x14, 4, 1, 0, nullptr, "+0x14 E: 1 in all files, not read"},
	{"textureCount", 0x18, 4, 1, 0, nullptr, "+0x18 E: 3..7; the loader walks all 50 slots instead"},
	{"textureOffset", 0x1C, 4, 50, 0, nullptr, "+0x1C T: region-relative offset of each raster, 0 = unused slot (UploadPartsAndCG v10 = region + 28)"},
	{"textureName", 0xE4, 1, 3200, 0, nullptr, "+0xE4 E: source bitmap names such as \"ayu00.bmp\"; not read"},
	{"textureSize", 0xD64, 4, 50, 0, nullptr, "+0xD64 T: edge length in pixels of the square raster (v10[850]); 512 in the data"},
	{"unused_E2C", 0xE2C, 1, 8196, 0, nullptr, "+0xE2C zero in all files, not read (padding up to the first raster at +0x2E30)"},
};
static const Han2FieldInfo kGof1PatternNameFields[] = {
	{"name", 0x0, 1, 64, 0, nullptr, "+0x00 E: CP932 pattern name, e.g. \"立ち弱攻撃\"; editor-only, the game never reads the tail"},
};
