// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"


#pragma pack(push, 1)
struct SideHudPopup {
	int32_t state;  // +0x00 0 = hidden, 1 = shown (slides in, then holds), 2 = fading out (alpha -32/tick). Writers: ShowIfComboActive (=1), Tick (->2, ->0), ResetAll. Readers: DrawAll (skip when 0), Tick, ShowIfComboActive, ClearSideBits
	int32_t slideX;  // +0x04 screen X slide offset: starts -32 (ShowIfComboActive), +8/tick to 0; +8/tick while fading. DrawOne adds it to the base X (0 side) or 592 (mirrored side)
	int32_t alpha;  // +0x08 0..255 popup alpha: 255 on show, -32/tick in state 2 (state -> 0 at <= 0). DrawOne alpha for hits and damage
	int32_t holdTimer;  // +0x0C frames the popup stays at state 1 once the combo broke: -1 = held while combo runs, set to 60 by ShowIfComboActive/ClearSideBits/sub_4A0750 on combo end; Tick counts down, 0 -> state 2
	int32_t shownHits;  // +0x10 hit count drawn (copy of runningHits when combo >= 2, DrawOne clamps to 999)
	int32_t shownDamage;  // +0x14 damage drawn (copy of runningDamage, DrawOne clamps to 99999)
	int32_t shownFlag6;  // +0x18 1 = draw the banner quad (HudPopup_AddBannerQuad); written 1 by ShowIfComboActive (=armed) and ArmSidePopupOnce, 0 on reset
	int32_t bannerSlideX;  // +0x1C banner X slide: -64 on arm (ArmSidePopupOnce / ApplyHit), Tick adds 8/tick up to 0 while shownFlag6 == 1; DrawOne adds it to slideX+200
	int32_t flowAlphaScale;  // +0x20 0..255 alpha scale of the flow counter (DrawOne: alpha*flowAlphaScale/255); 255 on RegisterHit when flowRunHits >= 2, TickAll subtracts 4/tick while flowTimer > 0
	int32_t flowTimer;  // +0x24 -1 = flow counter held, 60 = start fading (set by RegisterHit/ClearHitLatches/ClearSideBits/sub_4A0750), TickAll counts it down while fading flowAlphaScale
	int32_t flowHits;  // +0x28 flow (hits since this side was last hit) drawn by DrawOne (clamped to 999); copy of flowRunHits
	int32_t flowDamage;  // +0x2C copy of flowRunDamage on RegisterHit; no reader (DrawOne draws flowHits only)
	int32_t comboEndedLatch;  // +0x30 was flag30. 1 = this combo just ended (set by ShowIfComboActive else-branch when state==1, ClearSideBits when the victim mask empties, sub_4A0750); 0 when a >=2 combo starts. Only reader: HudPopupBoard_SyncSidePopup (of the opposing board) which then clears its +0xA8 cell flag and zeroes the latch
	int32_t lastDamageDealt[5];  // +0x34 was hist[0..4]. Shift history of RegisterHit arg a2 (applied damage); [0] newest. WRITE-ONLY: shifted in RegisterHit, cleared in ResetAll; no reader anywhere
	int32_t lastAttackBaseDamage[5];  // +0x48 was hist[5..9]. Shift history of RegisterHit arg a4 (attackRecord->damage of the hit, Gof2AtRecord+0x10); [0] newest. WRITE-ONLY, no reader
	uint32_t victimSideMask;  // +0x5C was attackerMask. Bit per VICTIM side hit by this combo (RegisterHit |= 1<<victimSide); HudPopup_ClearSideBitsForPlayerChara clears a victim's bit when it recovers; empty mask ends the combo (clears +0x5C..+0x68)
	int32_t armed;  // +0x60 1 once the air-hit banner was armed (ArmSidePopupOnce, ApplyHit airHitLatch path); cleared on mask empty; guards re-arming
	int32_t runningHits;  // +0x64 combo hit count (saturating at -1 on wrap); readers: ShowIfComboActive (>=2 shows popup), HudPopupBoard_Tick, sub_47E980, AddAttackerGaugeOnHitByAttackKind
	int32_t runningDamage;  // +0x68 combo damage total (saturating at -1)
	int32_t gotHitLatch;  // +0x6C was unk6C. Set 1 on the VICTIM side's popup by HitJudge_RegisterHitForHudPopupAndCounters (this side was hit this tick). Only consumer: ClearHitLatches, which clears flowRunHits/flowRunDamage, starts flowTimer=60 if -1, then zeroes it
	int32_t flowRunHits;  // +0x70 was hitsB. Hits strung since this side was last hit; ++ in RegisterHit, zeroed by ClearHitLatches when gotHitLatch; copied into flowHits when >= 2
	int32_t flowRunDamage;  // +0x74 was damageB. Damage dealt since this side was last hit; += a2 in RegisterHit, zeroed with flowRunHits
	int32_t hitContactLatch;  // +0x78 was unk78. Set 1 when a hit resolves involving this side's player chara (ResolveHitsOnGuardingVictim: guarding victim; ApplyHit: attacker and victim; Obj_ExecCmdListBetween: defender). Only consumer: ClearHitLatches (gates the guardedHitsDealt clear), then zeroes it. No other reader
	uint32_t guardedHitsDealt;  // +0x7C was unk7C. Count of guarded hits this side's player chara landed (ResolveHitsOnGuardingVictim: ++ on the ATTACKER's popup, saturating at -1). Only reader/consumer: none (cleared in ClearHitLatches when hitContactLatch, and ResetAll); never read for a decision
};
#pragma pack(pop)

static_assert(sizeof(SideHudPopup) == 0x80, "SideHudPopup size");
static_assert(offsetof(SideHudPopup, state) == 0x0, "SideHudPopup.state");
static_assert(offsetof(SideHudPopup, slideX) == 0x4, "SideHudPopup.slideX");
static_assert(offsetof(SideHudPopup, alpha) == 0x8, "SideHudPopup.alpha");
static_assert(offsetof(SideHudPopup, holdTimer) == 0xC, "SideHudPopup.holdTimer");
static_assert(offsetof(SideHudPopup, shownHits) == 0x10, "SideHudPopup.shownHits");
static_assert(offsetof(SideHudPopup, shownDamage) == 0x14, "SideHudPopup.shownDamage");
static_assert(offsetof(SideHudPopup, shownFlag6) == 0x18, "SideHudPopup.shownFlag6");
static_assert(offsetof(SideHudPopup, bannerSlideX) == 0x1C, "SideHudPopup.bannerSlideX");
static_assert(offsetof(SideHudPopup, flowAlphaScale) == 0x20, "SideHudPopup.flowAlphaScale");
static_assert(offsetof(SideHudPopup, flowTimer) == 0x24, "SideHudPopup.flowTimer");
static_assert(offsetof(SideHudPopup, flowHits) == 0x28, "SideHudPopup.flowHits");
static_assert(offsetof(SideHudPopup, flowDamage) == 0x2C, "SideHudPopup.flowDamage");
static_assert(offsetof(SideHudPopup, comboEndedLatch) == 0x30, "SideHudPopup.comboEndedLatch");
static_assert(offsetof(SideHudPopup, lastDamageDealt) == 0x34, "SideHudPopup.lastDamageDealt");
static_assert(offsetof(SideHudPopup, lastAttackBaseDamage) == 0x48, "SideHudPopup.lastAttackBaseDamage");
static_assert(offsetof(SideHudPopup, victimSideMask) == 0x5C, "SideHudPopup.victimSideMask");
static_assert(offsetof(SideHudPopup, armed) == 0x60, "SideHudPopup.armed");
static_assert(offsetof(SideHudPopup, runningHits) == 0x64, "SideHudPopup.runningHits");
static_assert(offsetof(SideHudPopup, runningDamage) == 0x68, "SideHudPopup.runningDamage");
static_assert(offsetof(SideHudPopup, gotHitLatch) == 0x6C, "SideHudPopup.gotHitLatch");
static_assert(offsetof(SideHudPopup, flowRunHits) == 0x70, "SideHudPopup.flowRunHits");
static_assert(offsetof(SideHudPopup, flowRunDamage) == 0x74, "SideHudPopup.flowRunDamage");
static_assert(offsetof(SideHudPopup, hitContactLatch) == 0x78, "SideHudPopup.hitContactLatch");
static_assert(offsetof(SideHudPopup, guardedHitsDealt) == 0x7C, "SideHudPopup.guardedHitsDealt");

static const Han2EnumInfo kGof2HudEnums[] = {
};

static const Han2FieldInfo kSideHudPopupFields[] = {
	{"state", 0x0, 4, 1, 1, nullptr, "+0x00 0 = hidden, 1 = shown (slides in, then holds), 2 = fading out (alpha -32/tick). Writers: ShowIfComboActive (=1), Tick (->2, ->0), ResetAll. Readers: DrawAll (skip when 0), Tick, ShowIfComboActive, ClearSideBits"},
	{"slideX", 0x4, 4, 1, 1, nullptr, "+0x04 screen X slide offset: starts -32 (ShowIfComboActive), +8/tick to 0; +8/tick while fading. DrawOne adds it to the base X (0 side) or 592 (mirrored side)"},
	{"alpha", 0x8, 4, 1, 1, nullptr, "+0x08 0..255 popup alpha: 255 on show, -32/tick in state 2 (state -> 0 at <= 0). DrawOne alpha for hits and damage"},
	{"holdTimer", 0xC, 4, 1, 1, nullptr, "+0x0C frames the popup stays at state 1 once the combo broke: -1 = held while combo runs, set to 60 by ShowIfComboActive/ClearSideBits/sub_4A0750 on combo end; Tick counts down, 0 -> state 2"},
	{"shownHits", 0x10, 4, 1, 1, nullptr, "+0x10 hit count drawn (copy of runningHits when combo >= 2, DrawOne clamps to 999)"},
	{"shownDamage", 0x14, 4, 1, 1, nullptr, "+0x14 damage drawn (copy of runningDamage, DrawOne clamps to 99999)"},
	{"shownFlag6", 0x18, 4, 1, 1, nullptr, "+0x18 1 = draw the banner quad (HudPopup_AddBannerQuad); written 1 by ShowIfComboActive (=armed) and ArmSidePopupOnce, 0 on reset"},
	{"bannerSlideX", 0x1C, 4, 1, 1, nullptr, "+0x1C banner X slide: -64 on arm (ArmSidePopupOnce / ApplyHit), Tick adds 8/tick up to 0 while shownFlag6 == 1; DrawOne adds it to slideX+200"},
	{"flowAlphaScale", 0x20, 4, 1, 1, nullptr, "+0x20 0..255 alpha scale of the flow counter (DrawOne: alpha*flowAlphaScale/255); 255 on RegisterHit when flowRunHits >= 2, TickAll subtracts 4/tick while flowTimer > 0"},
	{"flowTimer", 0x24, 4, 1, 1, nullptr, "+0x24 -1 = flow counter held, 60 = start fading (set by RegisterHit/ClearHitLatches/ClearSideBits/sub_4A0750), TickAll counts it down while fading flowAlphaScale"},
	{"flowHits", 0x28, 4, 1, 1, nullptr, "+0x28 flow (hits since this side was last hit) drawn by DrawOne (clamped to 999); copy of flowRunHits"},
	{"flowDamage", 0x2C, 4, 1, 1, nullptr, "+0x2C copy of flowRunDamage on RegisterHit; no reader (DrawOne draws flowHits only)"},
	{"comboEndedLatch", 0x30, 4, 1, 1, nullptr, "+0x30 was flag30. 1 = this combo just ended (set by ShowIfComboActive else-branch when state==1, ClearSideBits when the victim mask empties, sub_4A0750); 0 when a >=2 combo starts. Only reader: HudPopupBoard_SyncSidePopup (of the opposing board) which then clears its +0xA8 cell flag and zeroes the latch"},
	{"lastDamageDealt", 0x34, 4, 5, 1, nullptr, "+0x34 was hist[0..4]. Shift history of RegisterHit arg a2 (applied damage); [0] newest. WRITE-ONLY: shifted in RegisterHit, cleared in ResetAll; no reader anywhere"},
	{"lastAttackBaseDamage", 0x48, 4, 5, 1, nullptr, "+0x48 was hist[5..9]. Shift history of RegisterHit arg a4 (attackRecord->damage of the hit, Gof2AtRecord+0x10); [0] newest. WRITE-ONLY, no reader"},
	{"victimSideMask", 0x5C, 4, 1, 0, nullptr, "+0x5C was attackerMask. Bit per VICTIM side hit by this combo (RegisterHit |= 1<<victimSide); HudPopup_ClearSideBitsForPlayerChara clears a victim's bit when it recovers; empty mask ends the combo (clears +0x5C..+0x68)"},
	{"armed", 0x60, 4, 1, 1, nullptr, "+0x60 1 once the air-hit banner was armed (ArmSidePopupOnce, ApplyHit airHitLatch path); cleared on mask empty; guards re-arming"},
	{"runningHits", 0x64, 4, 1, 1, nullptr, "+0x64 combo hit count (saturating at -1 on wrap); readers: ShowIfComboActive (>=2 shows popup), HudPopupBoard_Tick, sub_47E980, AddAttackerGaugeOnHitByAttackKind"},
	{"runningDamage", 0x68, 4, 1, 1, nullptr, "+0x68 combo damage total (saturating at -1)"},
	{"gotHitLatch", 0x6C, 4, 1, 1, nullptr, "+0x6C was unk6C. Set 1 on the VICTIM side's popup by HitJudge_RegisterHitForHudPopupAndCounters (this side was hit this tick). Only consumer: ClearHitLatches, which clears flowRunHits/flowRunDamage, starts flowTimer=60 if -1, then zeroes it"},
	{"flowRunHits", 0x70, 4, 1, 1, nullptr, "+0x70 was hitsB. Hits strung since this side was last hit; ++ in RegisterHit, zeroed by ClearHitLatches when gotHitLatch; copied into flowHits when >= 2"},
	{"flowRunDamage", 0x74, 4, 1, 1, nullptr, "+0x74 was damageB. Damage dealt since this side was last hit; += a2 in RegisterHit, zeroed with flowRunHits"},
	{"hitContactLatch", 0x78, 4, 1, 1, nullptr, "+0x78 was unk78. Set 1 when a hit resolves involving this side's player chara (ResolveHitsOnGuardingVictim: guarding victim; ApplyHit: attacker and victim; Obj_ExecCmdListBetween: defender). Only consumer: ClearHitLatches (gates the guardedHitsDealt clear), then zeroes it. No other reader"},
	{"guardedHitsDealt", 0x7C, 4, 1, 0, nullptr, "+0x7C was unk7C. Count of guarded hits this side's player chara landed (ResolveHitsOnGuardingVictim: ++ on the ATTACKER's popup, saturating at -1). Only reader/consumer: none (cleared in ClearHitLatches when hitContactLatch, and ResetAll); never read for a decision"},
};
