// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"

enum Gof2AtHitClass : uint32_t {
	G2AT_HC_LIGHT_0 = 0,
	G2AT_HC_LIGHT_1 = 1,
	G2AT_HC_LIGHT_2 = 2,
	G2AT_HC_MEDIUM_3 = 3,
	G2AT_HC_MEDIUM_4 = 4,
	G2AT_HC_MEDIUM_5 = 5,
	G2AT_HC_HEAVY_6 = 6,
	G2AT_HC_HEAVY_7 = 7,
	G2AT_HC_CRUMPLE_8 = 8,
	G2AT_HC_SWEEP_9 = 9,
	G2AT_HC_LAUNCH_10 = 10,
	G2AT_HC_LAUNCH_11 = 11,
	G2AT_HC_LAUNCH_12 = 12,
	G2AT_HC_LAUNCH_13 = 13,
	G2AT_HC_MEDIUM_14 = 14,
	G2AT_HC_LAUNCH_15 = 15,
	G2AT_HC_LIGHT_16 = 16,
	G2AT_HC_NO_REACTION = 17,
};
enum Gof2AtSparkKind : uint32_t {
	G2AT_SPARK_DEFAULT_0 = 0,
	G2AT_SPARK_DEFAULT_1 = 1,
	G2AT_SPARK_DEFAULT_2 = 2,
	G2AT_SPARK_DEFAULT_6 = 6,
	G2AT_SPARK_BIG_ROTATING = 8,
	G2AT_SPARK_DEFAULT_11 = 11,
};
enum Gof2AtDrawOrderMode : uint32_t {
	G2AT_DRAWORD_VICTIM_FRONT = 0,
	G2AT_DRAWORD_VICTIM_FRONT_ANCHORED = 1,
	G2AT_DRAWORD_ATTACKER_FRONT = 2,
	G2AT_DRAWORD_RESET_ONLY = 300,
	G2AT_DRAWORD_NONE = 0xFFFFFFFF,
};
enum Gof2AtHitEffectKind : uint32_t {
	G2AT_HITFX_FROM_ATTACKER_FLAGS = 0,
	G2AT_HITFX_KIND_1 = 1,
	G2AT_HITFX_KIND_2 = 2,
	G2AT_HITFX_KIND_3 = 3,
	G2AT_HITFX_KIND_4 = 4,
	G2AT_HITFX_KIND_5 = 5,
};
enum Gof2AtKnockDirMode : uint32_t {
	G2AT_KDIR_ATTACKER_FACING = 0,
	G2AT_KDIR_ATTACKER_FACING_REVERSED = 1,
	G2AT_KDIR_BY_POSITION = 2,
	G2AT_KDIR_BY_POSITION_REVERSED = 3,
	G2AT_KDIR_NONE = 4,
};
enum Gof2AtFacingMode : uint32_t {
	G2AT_FACE_BY_POSITION = 0,
	G2AT_FACE_BY_POSITION_REVERSED = 1,
	G2AT_FACE_ATTACKER_FACING = 2,
	G2AT_FACE_ATTACKER_FACING_REVERSED = 3,
	G2AT_FACE_KEEP_VICTIM = 4,
};
enum Gof2AtHitFlags : uint32_t {
	G2AT_HF_SCREEN_SHAKE = 0x1,
	G2AT_HF_NO_HUD_DAMAGE_TRACE = 0x2,
	G2AT_HF_IGNORE_HIT_PROTECTION = 0x4000,
	G2AT_HF_NO_HITSTOP = 0x10000,
};
enum Gof2AtReactionFlags : uint32_t {
	G2AT_RF_SUPPRESS_SPECIAL_DAMAGE_FLAG = 0x2,
	G2AT_RF_BLOCK_RECOVER_A = 0x10,
	G2AT_RF_BLOCK_RECOVER_B = 0x20,
	G2AT_RF_UNREAD_0200 = 0x200,
	G2AT_RF_NO_SPARK_NO_POPUP = 0x1000000,
	G2AT_RF_HALVE_KNOCK_SCALE = 0x8000000,
};
enum Gof2AtGuardMask : uint32_t {
	G2AT_GM_STAND = 0x1,
	G2AT_GM_CROUCH = 0x2,
	G2AT_GM_BIT4 = 0x4,
	G2AT_GM_UNGUARDABLE_IN_MAIN_PASS = 0x10000,
};
enum Gof2AtKind : uint32_t {
	G2AT_KIND_NORMAL = 0,
	G2AT_KIND_SPECIAL = 1,
};
enum Gof2AtTargetStance : uint32_t {
	G2AT_TS_GROUND = 0x1,
	G2AT_TS_CROUCH = 0x2,
	G2AT_TS_AIR = 0x4,
	G2AT_TS_HIT_REACTION_STATES = 0x8,
};
enum Gof2EffFacingCmd : uint32_t {
	G2EFF_FACE_KEEP = 0,
	G2EFF_FACE_OPPOSITE_ATTACKER = 1,
	G2EFF_FACE_SAME_AS_ATTACKER = 2,
	G2EFF_FACE_FORCE_0 = 3,
	G2EFF_FACE_FORCE_1 = 4,
};
enum Gof2EffStateMode : uint32_t {
	G2EFF_STATE_FROM_YARARE_TABLE = 0,
	G2EFF_STATE_EXPLICIT = 1,
	G2EFF_STATE_HIT_REACTION = 2,
};
enum Gof2EffLinkMode : uint32_t {
	G2EFF_LINK_NONE = 0,
	G2EFF_LINK_COPY_CONTEXT = 1,
	G2EFF_LINK_FLAG_ON = 2,
	G2EFF_LINK_MODE0 = 3,
	G2EFF_LINK_MODE1 = 4,
	G2EFF_LINK_MODE2 = 5,
	G2EFF_LINK_MODE3 = 6,
};
enum Gof2PatPartFlip : uint32_t {
	G2PAT_FLIP_X = 0x1,
	G2PAT_FLIP_Y = 0x2,
	G2PAT_FORCE_ADDITIVE_BLEND = 0x100,
	G2PAT_UNREAD_10000 = 0x10000,
};

#pragma pack(push, 1)
struct Gof2AtRecord {
	Gof2AtHitClass hitClass;  // +0x00 T: victim reaction class (HitJudge_StartVictimReaction -> HitClass_ToStandReactionState picks victim pattern 28..39; 17 = no reaction/no damage scaling: HitJudge_ApplyHit, sub_495890)
	uint32_t hitStopLevel;  // +0x04 T: 0..6 index into the hit-stop tables g_ControllerManage[78] (attacker) / [79] (victim) / [82] (counter bonus) in HitJudge_ApplyHitStop 0x496CE0
	Gof2AtSparkKind sparkKind;  // +0x08 I: only ==8 is tested (HitJudge_ApplyHit, HitJudge_CollectPairs): selects the big rotating spark (Effect_SpawnHitSpark kind 2); every other value uses kind (attackKind != 0)
	uint32_t unused_0C;  // +0x0C U: zero in all 997 records, no reader (RBO had the gate mode here)
	uint32_t damage;  // +0x10 T: base damage; HitJudge_ComputeDamage 0x494FF0 uses -damage as the HP delta, HitJudge_ApplyHit scores it and feeds the HUD trace (0..1800 in data)
	uint32_t editorOnly_14;  // +0x14 E: 0x64 in 6 records, no reader
	uint32_t editorOnly_18;  // +0x18 E: nonzero in 590 records (0..800, RBO guard damage), no reader in GOF2 (chip damage is derived from damage)
	Gof2AtDrawOrderMode drawOrderMode;  // +0x1C I: != -1 resets the victim link context and calls SideDrawOrder_BringToFront (0/1 victim front, 2 attacker front); ==1 also anchors the victim (HitJudge_ApplyHit tail)
	Gof2AtHitEffectKind hitEffectKind;  // +0x20 I: 0 = derive 1..3 from attacker flag bits 1/2/4 else 1..5 selects the effect started by HitJudge_StartHitEffect 0x4317D0 (HitJudge_ResolveTick)
	uint32_t editorOnly_24;  // +0x24 E: 1 in 9 records, no reader
	uint32_t hitSoundBankSelect;  // +0x28 I: 0 = SystemSE bank (g_SystemSeScriptBank), nonzero = attacker character bank (HitJudge_RunHitSoundCommand 0x49D1A0); 0 in all data
	int32_t hitSoundId;  // +0x2C I: >= 0 triggers ScriptVm kind 2 / id 2 whose command record is executed on the attacker (HitJudge_RunHitSoundCommand); -1 = none
	uint32_t hitSoundVariant;  // +0x30 I: second argument of the same script call (0 or 2 in data)
	Gof2AtKnockDirMode knockDirMode;  // +0x34 T: HitJudge_SetKnockDirection 0x435A80 (via HitJudge_ApplyKnockDirAndFacing): victim knock direction sign
	Gof2AtFacingMode victimFacingMode;  // +0x38 T: HitJudge_SetVictimFacing 0x4359E0: victim pending facing (a3[477]); 4 keeps the victim facing
	uint32_t unused_3C[4];  // +0x3C U: zero in all records, no reader (RBO element/damage-type fields)
	Gof2AtHitFlags hitFlags;  // +0x4C T: bit0 screen shake (HitJudge_ApplyHit), bit1 skips HUD damage trace sub_4A05B0, 0x4000 bypasses victim hit protection (HitJudge_CollectPairs), 0x10000 skips hit-stop (HitJudge_ApplyHitStop)
	Gof2AtReactionFlags reactionFlags;  // +0x50 T: bit1 (HitJudge_ApplyHit v29, HitJudge_StartVictimReaction), 0x10/0x20 -> Victim_SetRecoverBlockFlags, 0x1000000 no spark/popup (HitJudge_ApplyHit), 0x8000000 -> HitJudge_ApplyKnockDirAndFacing; 0x200 present in data but unread
	uint32_t editorOnly_54;  // +0x54 E: 0x645 in 3 records, no reader (RBO hit-script enable)
	uint32_t unused_58[5];  // +0x58 U: zero in all records, no reader (+0x58..+0x6B)
	uint32_t clashRecoilState;  // +0x6C T: decimal packed frame*1000+pattern; the attacker enters it after a secondary-box contact (HitJudge_ResolveSecondaryBoxClashes 0x49ACB0); word +0x6E != 0 moves the boxes to the secondary list (CAppHanteiKougeki_BuildFromFrame)
	uint32_t unused_70[2];  // +0x70 U: zero in all records, no reader (RBO hit skill id)
	uint32_t hitScriptId;  // +0x78 T: ScriptVm kind 4 id of the on-hit command list run by HitJudge_ApplyHit (0 = none; 1 in one record)
	Gof2AtGuardMask guardMask;  // +0x7C T: bit0 stand-guardable, bit1 crouch-guardable, bit2 extra armor bit, 0x10000 not guardable in the main pass (HitJudge_DefenderGuardsAttack 0x496930, HitJudge_DefenderArmorAbsorbs 0x497180, ObjScan_StoreAttackGuardInfo, sub_43BA00)
	Gof2AtKind attackKind;  // +0x80 T: 0 normal, 1 special: damage class tables (HitJudge_ComputeDamage), armor check, guard rule, script condition (sub_43BA00), spark kind
	uint32_t screenShakeId;  // +0x84 T: ScreenYure script entry (g_ScreenYureScriptBank) started by HitJudge_ApplyHit when hitFlags.SCREEN_SHAKE (100/102/105 in data)
	uint32_t unused_88[2];  // +0x88 U: zero in all records, no reader
	Gof2AtTargetStance targetStanceMask;  // +0x90 T: victim stance classes this attack may hit (victim obj+660 & mask); bit3 also hits victims already in hit-reaction states 28..39 (HitJudge_CollectPairs, HitJudge_ResolveSecondaryBoxClashes)
	uint32_t unused_94[12];  // +0x94 U: zero in all records, no reader (+0x94..+0xC3)
	uint32_t hitScriptGate;  // +0xC4 T: read by HitJudge_CollectPairs (non-zero runs the kind-4 list for a fixed-damage override); zero in all 997 records
	uint32_t unused_C8[9];  // +0xC8 U: zero in all records, no reader (+0xC8..+0xEB)
};
struct Gof2Section4Record {
	uint32_t kind;  // +0x00 E: 1 (chr_select files) or 0xFF (SYSTEMEFFECT)
	uint32_t valueA;  // +0x04 E: 0, 0x100 or 0x200 (looks like a start zoom, 256 = 1.0)
	uint32_t valueB;  // +0x08 E: 0 or 0x100 (looks like an end zoom)
	uint32_t ticks;  // +0x0C E: 0, 1 or 30 (looks like a duration)
	uint32_t unused_10[3];  // +0x10 U: zero in all 7 records, no reader
};
struct Gof2Section5Record {
	uint32_t kind;  // +0x00 E: 1 in all 3 records
	uint32_t unused_04[4];  // +0x04 U: zero in all records, no reader
};
struct Gof2ScriptListEntry {
	uint32_t scriptId[5];  // +0x00 T: Obj_CollectFrameEnterEvents 0x43E1B0 (section 6, ScriptVm kind 0) / Obj_CollectTransitionRuleEvents 0x43E030 (section 7, kind 1) read slots 0..4 in order; id indexes the character .FOB index table of that kind
};
struct Gof2EffectSpawnRecord {
	uint32_t enable;  // +0x00 T: non-zero = record active (gate in Obj_SetActionAndRunScript); 1 in all 729 records
	int32_t targetOffsetX;  // +0x04 T: held target X offset from the attacker hold point (multiplied by the facing sign)
	int32_t targetOffsetY;  // +0x08 T: held target Y offset
	Gof2EffFacingCmd facingCmd;  // +0x0C T: target facing change (switch in Obj_SpawnFrameEffectRecord; 0 keep, 1 opposite, 2 same, 3/4 force)
	Gof2EffStateMode stateMode;  // +0x10 T: how the target state is chosen; modes 1 and 2 also detach the link after the spawn
	int32_t stateArg0;  // +0x14 T: mode 0 YarareData table index, mode 1 target pattern, mode 2 hit class (sub_435E10)
	int32_t stateArg1;  // +0x18 T: mode 1 target frame (-1 = start), mode 2 victim facing mode (HitJudge_SetVictimFacing)
	int32_t stateArg2;  // +0x1C T: mode 2 knock direction mode (HitJudge_SetKnockDirection); read only in mode 2
	uint32_t unused_20[3];  // +0x20 U: zero in all records, no reader
	Gof2EffLinkMode linkMode;  // +0x2C T: switch after the state change (copy link context / set flags on the target obj+472/+476)
	uint32_t unused_30[5];  // +0x30 U: zero in all records, no reader
	int32_t throwDamage;  // +0x44 T: non-zero runs Obj_ApplyEffectRecordThrowDamage 0x4326C0: damage handed to the target through the ScriptVm kind-0/id-7 table (500/400/50/900 in data)
	uint32_t eventScriptId;  // +0x48 T: ScriptVm kind 5 id; the returned list is only skipped over (no effect); 1 in 3 records
	int32_t throwScriptArg;  // +0x4C T: argument of the kind-0/id-7 call (Obj_ApplyEffectRecordThrowDamage); zero in all records
	uint32_t unused_50[4];  // +0x50 U: zero in all records, no reader
};
struct Gof2PatHeader {
	uint32_t version;  // +0x00 E: 4 in all 64 PATs (RBO 3)
	uint32_t byteOrderMarker;  // +0x04 E: 0x01234567 in all 64 PATs
	uint32_t unused_08[4];  // +0x08 U: zero, not read
};
struct Gof2PatFileHead {
	Gof2PatHeader header;  // +0x0000 E: see Gof2PatHeader
	uint32_t poseOffset[2000];  // +0x0018 T: absolute PAT offset of the pose's first part; 0 = absent; part index = (off-72028)/92 (CharacterLoad state 6 loop to 8068 = 4*2000+68)
	char poseName[64000];  // +0x1F58 E: 2000 x 32-byte CP932 labels, never read
	uint32_t imageAreaOffset;  // +0x11958 T: PAT offset of the texture area; poses occupy [72028, imageAreaOffset) packed in 3680-byte blocks (CharacterLoad state 6 stores size-72028 at chara+60)
};
struct Gof2PatPart {
	int32_t x;  // +0x00 T: PosePart_ComputeGeometry 0x43FE50 (lerped toward the next pose)
	int32_t y;  // +0x04 T: same
	int32_t destWidth;  // +0x08 T: same (current part only)
	int32_t destHeight;  // +0x0C T: same
	Gof2PatPartFlip flipFlags;  // +0x10 T: bit0/1 mirror (PosePart_GetFlippedSrcRect 0x4402A0); byte +0x11 != 0 forces the additive blend state (DrawSort_Run); 0x10000 never read
	int32_t scaleXPermille;  // +0x14 T: PosePart_ComputeGeometry
	int32_t scaleYPermille;  // +0x18 T: same
	int32_t rotation10000;  // +0x1C T: same (10000 = full turn, Math_LerpAngle10000ToDeg 0x43FD00)
	uint32_t modulateArgb;  // +0x20 T: PosePart_ModulateColor 0x440000 (bytes A,R,G,B in memory order; 0xFFFFFFFF = unchanged)
	uint32_t addRgb;  // +0x24 T: PosePart_AddColor 0x440170 (bytes R,G,B; +0x27 never read, zero)
	int32_t textureIndex;  // +0x28 T: DrawSort_Run texture slot lookup (0xFFFF = clip part, skipped by DrawSort_BubbleByPriority)
	int32_t srcX;  // +0x2C T: full dword read (RBO int16 + unused hi word); 1/256 of the texture
	int32_t srcY;  // +0x30 T: same
	int32_t srcW;  // +0x34 T: dword; 0 = part slot unused (DrawSort_BubbleByPriority)
	int32_t srcH;  // +0x38 T: dword; 0 = part slot unused
	uint32_t layer;  // +0x3C T: full dword << 8 is the sort key (RBO byte)
	int32_t originX;  // +0x40 T: PosePart_ComputeGeometry pivot X
	int32_t originY;  // +0x44 T: pivot Y
	uint32_t unused_48[5];  // +0x48 U: zero in all 1233240 parts, no reader
};
struct Gof2AttackBoxSetPrefix {
	uint32_t vtable;  // +0x00 T: vf0 returns the primary box count (this+4), vf8 the secondary count (this+8)
	uint32_t primaryCount;  // +0x04 T: attack boxes that hit through HitJudge_CollectPairs; moved to secondaryCount when the record word +0x6E != 0 (CAppHanteiKougeki_BuildFromFrame)
	uint32_t secondaryCount;  // +0x08 T: boxes tested by HitJudge_ResolveSecondaryBoxClashes
	uint32_t record;  // +0x0C T: attackRecords + 236*frame.attackRecordIdx (read through Obj+0x620 = obj+1568 by every hit routine)
};
#pragma pack(pop)

static_assert(sizeof(Gof2AtRecord) == 0xEC, "Gof2AtRecord size");
static_assert(offsetof(Gof2AtRecord, hitClass) == 0x0, "Gof2AtRecord.hitClass");
static_assert(offsetof(Gof2AtRecord, hitStopLevel) == 0x4, "Gof2AtRecord.hitStopLevel");
static_assert(offsetof(Gof2AtRecord, sparkKind) == 0x8, "Gof2AtRecord.sparkKind");
static_assert(offsetof(Gof2AtRecord, unused_0C) == 0xC, "Gof2AtRecord.unused_0C");
static_assert(offsetof(Gof2AtRecord, damage) == 0x10, "Gof2AtRecord.damage");
static_assert(offsetof(Gof2AtRecord, editorOnly_14) == 0x14, "Gof2AtRecord.editorOnly_14");
static_assert(offsetof(Gof2AtRecord, editorOnly_18) == 0x18, "Gof2AtRecord.editorOnly_18");
static_assert(offsetof(Gof2AtRecord, drawOrderMode) == 0x1C, "Gof2AtRecord.drawOrderMode");
static_assert(offsetof(Gof2AtRecord, hitEffectKind) == 0x20, "Gof2AtRecord.hitEffectKind");
static_assert(offsetof(Gof2AtRecord, editorOnly_24) == 0x24, "Gof2AtRecord.editorOnly_24");
static_assert(offsetof(Gof2AtRecord, hitSoundBankSelect) == 0x28, "Gof2AtRecord.hitSoundBankSelect");
static_assert(offsetof(Gof2AtRecord, hitSoundId) == 0x2C, "Gof2AtRecord.hitSoundId");
static_assert(offsetof(Gof2AtRecord, hitSoundVariant) == 0x30, "Gof2AtRecord.hitSoundVariant");
static_assert(offsetof(Gof2AtRecord, knockDirMode) == 0x34, "Gof2AtRecord.knockDirMode");
static_assert(offsetof(Gof2AtRecord, victimFacingMode) == 0x38, "Gof2AtRecord.victimFacingMode");
static_assert(offsetof(Gof2AtRecord, unused_3C) == 0x3C, "Gof2AtRecord.unused_3C");
static_assert(offsetof(Gof2AtRecord, hitFlags) == 0x4C, "Gof2AtRecord.hitFlags");
static_assert(offsetof(Gof2AtRecord, reactionFlags) == 0x50, "Gof2AtRecord.reactionFlags");
static_assert(offsetof(Gof2AtRecord, editorOnly_54) == 0x54, "Gof2AtRecord.editorOnly_54");
static_assert(offsetof(Gof2AtRecord, unused_58) == 0x58, "Gof2AtRecord.unused_58");
static_assert(offsetof(Gof2AtRecord, clashRecoilState) == 0x6C, "Gof2AtRecord.clashRecoilState");
static_assert(offsetof(Gof2AtRecord, unused_70) == 0x70, "Gof2AtRecord.unused_70");
static_assert(offsetof(Gof2AtRecord, hitScriptId) == 0x78, "Gof2AtRecord.hitScriptId");
static_assert(offsetof(Gof2AtRecord, guardMask) == 0x7C, "Gof2AtRecord.guardMask");
static_assert(offsetof(Gof2AtRecord, attackKind) == 0x80, "Gof2AtRecord.attackKind");
static_assert(offsetof(Gof2AtRecord, screenShakeId) == 0x84, "Gof2AtRecord.screenShakeId");
static_assert(offsetof(Gof2AtRecord, unused_88) == 0x88, "Gof2AtRecord.unused_88");
static_assert(offsetof(Gof2AtRecord, targetStanceMask) == 0x90, "Gof2AtRecord.targetStanceMask");
static_assert(offsetof(Gof2AtRecord, unused_94) == 0x94, "Gof2AtRecord.unused_94");
static_assert(offsetof(Gof2AtRecord, hitScriptGate) == 0xC4, "Gof2AtRecord.hitScriptGate");
static_assert(offsetof(Gof2AtRecord, unused_C8) == 0xC8, "Gof2AtRecord.unused_C8");
static_assert(sizeof(Gof2Section4Record) == 0x1C, "Gof2Section4Record size");
static_assert(offsetof(Gof2Section4Record, kind) == 0x0, "Gof2Section4Record.kind");
static_assert(offsetof(Gof2Section4Record, valueA) == 0x4, "Gof2Section4Record.valueA");
static_assert(offsetof(Gof2Section4Record, valueB) == 0x8, "Gof2Section4Record.valueB");
static_assert(offsetof(Gof2Section4Record, ticks) == 0xC, "Gof2Section4Record.ticks");
static_assert(offsetof(Gof2Section4Record, unused_10) == 0x10, "Gof2Section4Record.unused_10");
static_assert(sizeof(Gof2Section5Record) == 0x14, "Gof2Section5Record size");
static_assert(offsetof(Gof2Section5Record, kind) == 0x0, "Gof2Section5Record.kind");
static_assert(offsetof(Gof2Section5Record, unused_04) == 0x4, "Gof2Section5Record.unused_04");
static_assert(sizeof(Gof2ScriptListEntry) == 0x14, "Gof2ScriptListEntry size");
static_assert(offsetof(Gof2ScriptListEntry, scriptId) == 0x0, "Gof2ScriptListEntry.scriptId");
static_assert(sizeof(Gof2EffectSpawnRecord) == 0x60, "Gof2EffectSpawnRecord size");
static_assert(offsetof(Gof2EffectSpawnRecord, enable) == 0x0, "Gof2EffectSpawnRecord.enable");
static_assert(offsetof(Gof2EffectSpawnRecord, targetOffsetX) == 0x4, "Gof2EffectSpawnRecord.targetOffsetX");
static_assert(offsetof(Gof2EffectSpawnRecord, targetOffsetY) == 0x8, "Gof2EffectSpawnRecord.targetOffsetY");
static_assert(offsetof(Gof2EffectSpawnRecord, facingCmd) == 0xC, "Gof2EffectSpawnRecord.facingCmd");
static_assert(offsetof(Gof2EffectSpawnRecord, stateMode) == 0x10, "Gof2EffectSpawnRecord.stateMode");
static_assert(offsetof(Gof2EffectSpawnRecord, stateArg0) == 0x14, "Gof2EffectSpawnRecord.stateArg0");
static_assert(offsetof(Gof2EffectSpawnRecord, stateArg1) == 0x18, "Gof2EffectSpawnRecord.stateArg1");
static_assert(offsetof(Gof2EffectSpawnRecord, stateArg2) == 0x1C, "Gof2EffectSpawnRecord.stateArg2");
static_assert(offsetof(Gof2EffectSpawnRecord, unused_20) == 0x20, "Gof2EffectSpawnRecord.unused_20");
static_assert(offsetof(Gof2EffectSpawnRecord, linkMode) == 0x2C, "Gof2EffectSpawnRecord.linkMode");
static_assert(offsetof(Gof2EffectSpawnRecord, unused_30) == 0x30, "Gof2EffectSpawnRecord.unused_30");
static_assert(offsetof(Gof2EffectSpawnRecord, throwDamage) == 0x44, "Gof2EffectSpawnRecord.throwDamage");
static_assert(offsetof(Gof2EffectSpawnRecord, eventScriptId) == 0x48, "Gof2EffectSpawnRecord.eventScriptId");
static_assert(offsetof(Gof2EffectSpawnRecord, throwScriptArg) == 0x4C, "Gof2EffectSpawnRecord.throwScriptArg");
static_assert(offsetof(Gof2EffectSpawnRecord, unused_50) == 0x50, "Gof2EffectSpawnRecord.unused_50");
static_assert(sizeof(Gof2PatHeader) == 0x18, "Gof2PatHeader size");
static_assert(offsetof(Gof2PatHeader, version) == 0x0, "Gof2PatHeader.version");
static_assert(offsetof(Gof2PatHeader, byteOrderMarker) == 0x4, "Gof2PatHeader.byteOrderMarker");
static_assert(offsetof(Gof2PatHeader, unused_08) == 0x8, "Gof2PatHeader.unused_08");
static_assert(sizeof(Gof2PatFileHead) == 0x1195C, "Gof2PatFileHead size");
static_assert(offsetof(Gof2PatFileHead, header) == 0x0, "Gof2PatFileHead.header");
static_assert(offsetof(Gof2PatFileHead, poseOffset) == 0x18, "Gof2PatFileHead.poseOffset");
static_assert(offsetof(Gof2PatFileHead, poseName) == 0x1F58, "Gof2PatFileHead.poseName");
static_assert(offsetof(Gof2PatFileHead, imageAreaOffset) == 0x11958, "Gof2PatFileHead.imageAreaOffset");
static_assert(sizeof(Gof2PatPart) == 0x5C, "Gof2PatPart size");
static_assert(offsetof(Gof2PatPart, x) == 0x0, "Gof2PatPart.x");
static_assert(offsetof(Gof2PatPart, y) == 0x4, "Gof2PatPart.y");
static_assert(offsetof(Gof2PatPart, destWidth) == 0x8, "Gof2PatPart.destWidth");
static_assert(offsetof(Gof2PatPart, destHeight) == 0xC, "Gof2PatPart.destHeight");
static_assert(offsetof(Gof2PatPart, flipFlags) == 0x10, "Gof2PatPart.flipFlags");
static_assert(offsetof(Gof2PatPart, scaleXPermille) == 0x14, "Gof2PatPart.scaleXPermille");
static_assert(offsetof(Gof2PatPart, scaleYPermille) == 0x18, "Gof2PatPart.scaleYPermille");
static_assert(offsetof(Gof2PatPart, rotation10000) == 0x1C, "Gof2PatPart.rotation10000");
static_assert(offsetof(Gof2PatPart, modulateArgb) == 0x20, "Gof2PatPart.modulateArgb");
static_assert(offsetof(Gof2PatPart, addRgb) == 0x24, "Gof2PatPart.addRgb");
static_assert(offsetof(Gof2PatPart, textureIndex) == 0x28, "Gof2PatPart.textureIndex");
static_assert(offsetof(Gof2PatPart, srcX) == 0x2C, "Gof2PatPart.srcX");
static_assert(offsetof(Gof2PatPart, srcY) == 0x30, "Gof2PatPart.srcY");
static_assert(offsetof(Gof2PatPart, srcW) == 0x34, "Gof2PatPart.srcW");
static_assert(offsetof(Gof2PatPart, srcH) == 0x38, "Gof2PatPart.srcH");
static_assert(offsetof(Gof2PatPart, layer) == 0x3C, "Gof2PatPart.layer");
static_assert(offsetof(Gof2PatPart, originX) == 0x40, "Gof2PatPart.originX");
static_assert(offsetof(Gof2PatPart, originY) == 0x44, "Gof2PatPart.originY");
static_assert(offsetof(Gof2PatPart, unused_48) == 0x48, "Gof2PatPart.unused_48");
static_assert(sizeof(Gof2AttackBoxSetPrefix) == 0x10, "Gof2AttackBoxSetPrefix size");
static_assert(offsetof(Gof2AttackBoxSetPrefix, vtable) == 0x0, "Gof2AttackBoxSetPrefix.vtable");
static_assert(offsetof(Gof2AttackBoxSetPrefix, primaryCount) == 0x4, "Gof2AttackBoxSetPrefix.primaryCount");
static_assert(offsetof(Gof2AttackBoxSetPrefix, secondaryCount) == 0x8, "Gof2AttackBoxSetPrefix.secondaryCount");
static_assert(offsetof(Gof2AttackBoxSetPrefix, record) == 0xC, "Gof2AttackBoxSetPrefix.record");

static const Han2EnumValue kGof2AtHitClassValues[] = {
	{"G2AT_HC_LIGHT_0", (int64_t)(0)},
	{"G2AT_HC_LIGHT_1", (int64_t)(1)},
	{"G2AT_HC_LIGHT_2", (int64_t)(2)},
	{"G2AT_HC_MEDIUM_3", (int64_t)(3)},
	{"G2AT_HC_MEDIUM_4", (int64_t)(4)},
	{"G2AT_HC_MEDIUM_5", (int64_t)(5)},
	{"G2AT_HC_HEAVY_6", (int64_t)(6)},
	{"G2AT_HC_HEAVY_7", (int64_t)(7)},
	{"G2AT_HC_CRUMPLE_8", (int64_t)(8)},
	{"G2AT_HC_SWEEP_9", (int64_t)(9)},
	{"G2AT_HC_LAUNCH_10", (int64_t)(10)},
	{"G2AT_HC_LAUNCH_11", (int64_t)(11)},
	{"G2AT_HC_LAUNCH_12", (int64_t)(12)},
	{"G2AT_HC_LAUNCH_13", (int64_t)(13)},
	{"G2AT_HC_MEDIUM_14", (int64_t)(14)},
	{"G2AT_HC_LAUNCH_15", (int64_t)(15)},
	{"G2AT_HC_LIGHT_16", (int64_t)(16)},
	{"G2AT_HC_NO_REACTION", (int64_t)(17)},
};
static const Han2EnumValue kGof2AtSparkKindValues[] = {
	{"G2AT_SPARK_DEFAULT_0", (int64_t)(0)},
	{"G2AT_SPARK_DEFAULT_1", (int64_t)(1)},
	{"G2AT_SPARK_DEFAULT_2", (int64_t)(2)},
	{"G2AT_SPARK_DEFAULT_6", (int64_t)(6)},
	{"G2AT_SPARK_BIG_ROTATING", (int64_t)(8)},
	{"G2AT_SPARK_DEFAULT_11", (int64_t)(11)},
};
static const Han2EnumValue kGof2AtDrawOrderModeValues[] = {
	{"G2AT_DRAWORD_VICTIM_FRONT", (int64_t)(0)},
	{"G2AT_DRAWORD_VICTIM_FRONT_ANCHORED", (int64_t)(1)},
	{"G2AT_DRAWORD_ATTACKER_FRONT", (int64_t)(2)},
	{"G2AT_DRAWORD_RESET_ONLY", (int64_t)(300)},
	{"G2AT_DRAWORD_NONE", (int64_t)(0xFFFFFFFF)},
};
static const Han2EnumValue kGof2AtHitEffectKindValues[] = {
	{"G2AT_HITFX_FROM_ATTACKER_FLAGS", (int64_t)(0)},
	{"G2AT_HITFX_KIND_1", (int64_t)(1)},
	{"G2AT_HITFX_KIND_2", (int64_t)(2)},
	{"G2AT_HITFX_KIND_3", (int64_t)(3)},
	{"G2AT_HITFX_KIND_4", (int64_t)(4)},
	{"G2AT_HITFX_KIND_5", (int64_t)(5)},
};
static const Han2EnumValue kGof2AtKnockDirModeValues[] = {
	{"G2AT_KDIR_ATTACKER_FACING", (int64_t)(0)},
	{"G2AT_KDIR_ATTACKER_FACING_REVERSED", (int64_t)(1)},
	{"G2AT_KDIR_BY_POSITION", (int64_t)(2)},
	{"G2AT_KDIR_BY_POSITION_REVERSED", (int64_t)(3)},
	{"G2AT_KDIR_NONE", (int64_t)(4)},
};
static const Han2EnumValue kGof2AtFacingModeValues[] = {
	{"G2AT_FACE_BY_POSITION", (int64_t)(0)},
	{"G2AT_FACE_BY_POSITION_REVERSED", (int64_t)(1)},
	{"G2AT_FACE_ATTACKER_FACING", (int64_t)(2)},
	{"G2AT_FACE_ATTACKER_FACING_REVERSED", (int64_t)(3)},
	{"G2AT_FACE_KEEP_VICTIM", (int64_t)(4)},
};
static const Han2EnumValue kGof2AtHitFlagsValues[] = {
	{"G2AT_HF_SCREEN_SHAKE", (int64_t)(0x1)},
	{"G2AT_HF_NO_HUD_DAMAGE_TRACE", (int64_t)(0x2)},
	{"G2AT_HF_IGNORE_HIT_PROTECTION", (int64_t)(0x4000)},
	{"G2AT_HF_NO_HITSTOP", (int64_t)(0x10000)},
};
static const Han2EnumValue kGof2AtReactionFlagsValues[] = {
	{"G2AT_RF_SUPPRESS_SPECIAL_DAMAGE_FLAG", (int64_t)(0x2)},
	{"G2AT_RF_BLOCK_RECOVER_A", (int64_t)(0x10)},
	{"G2AT_RF_BLOCK_RECOVER_B", (int64_t)(0x20)},
	{"G2AT_RF_UNREAD_0200", (int64_t)(0x200)},
	{"G2AT_RF_NO_SPARK_NO_POPUP", (int64_t)(0x1000000)},
	{"G2AT_RF_HALVE_KNOCK_SCALE", (int64_t)(0x8000000)},
};
static const Han2EnumValue kGof2AtGuardMaskValues[] = {
	{"G2AT_GM_STAND", (int64_t)(0x1)},
	{"G2AT_GM_CROUCH", (int64_t)(0x2)},
	{"G2AT_GM_BIT4", (int64_t)(0x4)},
	{"G2AT_GM_UNGUARDABLE_IN_MAIN_PASS", (int64_t)(0x10000)},
};
static const Han2EnumValue kGof2AtKindValues[] = {
	{"G2AT_KIND_NORMAL", (int64_t)(0)},
	{"G2AT_KIND_SPECIAL", (int64_t)(1)},
};
static const Han2EnumValue kGof2AtTargetStanceValues[] = {
	{"G2AT_TS_GROUND", (int64_t)(0x1)},
	{"G2AT_TS_CROUCH", (int64_t)(0x2)},
	{"G2AT_TS_AIR", (int64_t)(0x4)},
	{"G2AT_TS_HIT_REACTION_STATES", (int64_t)(0x8)},
};
static const Han2EnumValue kGof2EffFacingCmdValues[] = {
	{"G2EFF_FACE_KEEP", (int64_t)(0)},
	{"G2EFF_FACE_OPPOSITE_ATTACKER", (int64_t)(1)},
	{"G2EFF_FACE_SAME_AS_ATTACKER", (int64_t)(2)},
	{"G2EFF_FACE_FORCE_0", (int64_t)(3)},
	{"G2EFF_FACE_FORCE_1", (int64_t)(4)},
};
static const Han2EnumValue kGof2EffStateModeValues[] = {
	{"G2EFF_STATE_FROM_YARARE_TABLE", (int64_t)(0)},
	{"G2EFF_STATE_EXPLICIT", (int64_t)(1)},
	{"G2EFF_STATE_HIT_REACTION", (int64_t)(2)},
};
static const Han2EnumValue kGof2EffLinkModeValues[] = {
	{"G2EFF_LINK_NONE", (int64_t)(0)},
	{"G2EFF_LINK_COPY_CONTEXT", (int64_t)(1)},
	{"G2EFF_LINK_FLAG_ON", (int64_t)(2)},
	{"G2EFF_LINK_MODE0", (int64_t)(3)},
	{"G2EFF_LINK_MODE1", (int64_t)(4)},
	{"G2EFF_LINK_MODE2", (int64_t)(5)},
	{"G2EFF_LINK_MODE3", (int64_t)(6)},
};
static const Han2EnumValue kGof2PatPartFlipValues[] = {
	{"G2PAT_FLIP_X", (int64_t)(0x1)},
	{"G2PAT_FLIP_Y", (int64_t)(0x2)},
	{"G2PAT_FORCE_ADDITIVE_BLEND", (int64_t)(0x100)},
	{"G2PAT_UNREAD_10000", (int64_t)(0x10000)},
};
static const Han2EnumInfo kGof2AtEnums[] = {
	{"Gof2AtHitClass", kGof2AtHitClassValues, 18, false},
	{"Gof2AtSparkKind", kGof2AtSparkKindValues, 6, false},
	{"Gof2AtDrawOrderMode", kGof2AtDrawOrderModeValues, 5, false},
	{"Gof2AtHitEffectKind", kGof2AtHitEffectKindValues, 6, false},
	{"Gof2AtKnockDirMode", kGof2AtKnockDirModeValues, 5, false},
	{"Gof2AtFacingMode", kGof2AtFacingModeValues, 5, false},
	{"Gof2AtHitFlags", kGof2AtHitFlagsValues, 4, true},
	{"Gof2AtReactionFlags", kGof2AtReactionFlagsValues, 6, true},
	{"Gof2AtGuardMask", kGof2AtGuardMaskValues, 4, false},
	{"Gof2AtKind", kGof2AtKindValues, 2, false},
	{"Gof2AtTargetStance", kGof2AtTargetStanceValues, 4, false},
	{"Gof2EffFacingCmd", kGof2EffFacingCmdValues, 5, false},
	{"Gof2EffStateMode", kGof2EffStateModeValues, 3, false},
	{"Gof2EffLinkMode", kGof2EffLinkModeValues, 7, false},
	{"Gof2PatPartFlip", kGof2PatPartFlipValues, 4, false},
};

static const Han2FieldInfo kGof2AtRecordFields[] = {
	{"hitClass", 0x0, 4, 1, 2, "Gof2AtHitClass", "+0x00 T: victim reaction class (HitJudge_StartVictimReaction -> HitClass_ToStandReactionState picks victim pattern 28..39; 17 = no reaction/no damage scaling: HitJudge_ApplyHit, sub_495890)"},
	{"hitStopLevel", 0x4, 4, 1, 0, nullptr, "+0x04 T: 0..6 index into the hit-stop tables g_ControllerManage[78] (attacker) / [79] (victim) / [82] (counter bonus) in HitJudge_ApplyHitStop 0x496CE0"},
	{"sparkKind", 0x8, 4, 1, 2, "Gof2AtSparkKind", "+0x08 I: only ==8 is tested (HitJudge_ApplyHit, HitJudge_CollectPairs): selects the big rotating spark (Effect_SpawnHitSpark kind 2); every other value uses kind (attackKind != 0)"},
	{"unused_0C", 0xC, 4, 1, 0, nullptr, "+0x0C U: zero in all 997 records, no reader (RBO had the gate mode here)"},
	{"damage", 0x10, 4, 1, 0, nullptr, "+0x10 T: base damage; HitJudge_ComputeDamage 0x494FF0 uses -damage as the HP delta, HitJudge_ApplyHit scores it and feeds the HUD trace (0..1800 in data)"},
	{"editorOnly_14", 0x14, 4, 1, 0, nullptr, "+0x14 E: 0x64 in 6 records, no reader"},
	{"editorOnly_18", 0x18, 4, 1, 0, nullptr, "+0x18 E: nonzero in 590 records (0..800, RBO guard damage), no reader in GOF2 (chip damage is derived from damage)"},
	{"drawOrderMode", 0x1C, 4, 1, 2, "Gof2AtDrawOrderMode", "+0x1C I: != -1 resets the victim link context and calls SideDrawOrder_BringToFront (0/1 victim front, 2 attacker front); ==1 also anchors the victim (HitJudge_ApplyHit tail)"},
	{"hitEffectKind", 0x20, 4, 1, 2, "Gof2AtHitEffectKind", "+0x20 I: 0 = derive 1..3 from attacker flag bits 1/2/4 else 1..5 selects the effect started by HitJudge_StartHitEffect 0x4317D0 (HitJudge_ResolveTick)"},
	{"editorOnly_24", 0x24, 4, 1, 0, nullptr, "+0x24 E: 1 in 9 records, no reader"},
	{"hitSoundBankSelect", 0x28, 4, 1, 0, nullptr, "+0x28 I: 0 = SystemSE bank (g_SystemSeScriptBank), nonzero = attacker character bank (HitJudge_RunHitSoundCommand 0x49D1A0); 0 in all data"},
	{"hitSoundId", 0x2C, 4, 1, 1, nullptr, "+0x2C I: >= 0 triggers ScriptVm kind 2 / id 2 whose command record is executed on the attacker (HitJudge_RunHitSoundCommand); -1 = none"},
	{"hitSoundVariant", 0x30, 4, 1, 0, nullptr, "+0x30 I: second argument of the same script call (0 or 2 in data)"},
	{"knockDirMode", 0x34, 4, 1, 2, "Gof2AtKnockDirMode", "+0x34 T: HitJudge_SetKnockDirection 0x435A80 (via HitJudge_ApplyKnockDirAndFacing): victim knock direction sign"},
	{"victimFacingMode", 0x38, 4, 1, 2, "Gof2AtFacingMode", "+0x38 T: HitJudge_SetVictimFacing 0x4359E0: victim pending facing (a3[477]); 4 keeps the victim facing"},
	{"unused_3C", 0x3C, 4, 4, 0, nullptr, "+0x3C U: zero in all records, no reader (RBO element/damage-type fields)"},
	{"hitFlags", 0x4C, 4, 1, 2, "Gof2AtHitFlags", "+0x4C T: bit0 screen shake (HitJudge_ApplyHit), bit1 skips HUD damage trace sub_4A05B0, 0x4000 bypasses victim hit protection (HitJudge_CollectPairs), 0x10000 skips hit-stop (HitJudge_ApplyHitStop)"},
	{"reactionFlags", 0x50, 4, 1, 2, "Gof2AtReactionFlags", "+0x50 T: bit1 (HitJudge_ApplyHit v29, HitJudge_StartVictimReaction), 0x10/0x20 -> Victim_SetRecoverBlockFlags, 0x1000000 no spark/popup (HitJudge_ApplyHit), 0x8000000 -> HitJudge_ApplyKnockDirAndFacing; 0x200 present in data but unread"},
	{"editorOnly_54", 0x54, 4, 1, 0, nullptr, "+0x54 E: 0x645 in 3 records, no reader (RBO hit-script enable)"},
	{"unused_58", 0x58, 4, 5, 0, nullptr, "+0x58 U: zero in all records, no reader (+0x58..+0x6B)"},
	{"clashRecoilState", 0x6C, 4, 1, 0, nullptr, "+0x6C T: decimal packed frame*1000+pattern; the attacker enters it after a secondary-box contact (HitJudge_ResolveSecondaryBoxClashes 0x49ACB0); word +0x6E != 0 moves the boxes to the secondary list (CAppHanteiKougeki_BuildFromFrame)"},
	{"unused_70", 0x70, 4, 2, 0, nullptr, "+0x70 U: zero in all records, no reader (RBO hit skill id)"},
	{"hitScriptId", 0x78, 4, 1, 0, nullptr, "+0x78 T: ScriptVm kind 4 id of the on-hit command list run by HitJudge_ApplyHit (0 = none; 1 in one record)"},
	{"guardMask", 0x7C, 4, 1, 2, "Gof2AtGuardMask", "+0x7C T: bit0 stand-guardable, bit1 crouch-guardable, bit2 extra armor bit, 0x10000 not guardable in the main pass (HitJudge_DefenderGuardsAttack 0x496930, HitJudge_DefenderArmorAbsorbs 0x497180, ObjScan_StoreAttackGuardInfo, sub_43BA00)"},
	{"attackKind", 0x80, 4, 1, 2, "Gof2AtKind", "+0x80 T: 0 normal, 1 special: damage class tables (HitJudge_ComputeDamage), armor check, guard rule, script condition (sub_43BA00), spark kind"},
	{"screenShakeId", 0x84, 4, 1, 0, nullptr, "+0x84 T: ScreenYure script entry (g_ScreenYureScriptBank) started by HitJudge_ApplyHit when hitFlags.SCREEN_SHAKE (100/102/105 in data)"},
	{"unused_88", 0x88, 4, 2, 0, nullptr, "+0x88 U: zero in all records, no reader"},
	{"targetStanceMask", 0x90, 4, 1, 2, "Gof2AtTargetStance", "+0x90 T: victim stance classes this attack may hit (victim obj+660 & mask); bit3 also hits victims already in hit-reaction states 28..39 (HitJudge_CollectPairs, HitJudge_ResolveSecondaryBoxClashes)"},
	{"unused_94", 0x94, 4, 12, 0, nullptr, "+0x94 U: zero in all records, no reader (+0x94..+0xC3)"},
	{"hitScriptGate", 0xC4, 4, 1, 0, nullptr, "+0xC4 T: read by HitJudge_CollectPairs (non-zero runs the kind-4 list for a fixed-damage override); zero in all 997 records"},
	{"unused_C8", 0xC8, 4, 9, 0, nullptr, "+0xC8 U: zero in all records, no reader (+0xC8..+0xEB)"},
};
static const Han2FieldInfo kGof2Section4RecordFields[] = {
	{"kind", 0x0, 4, 1, 0, nullptr, "+0x00 E: 1 (chr_select files) or 0xFF (SYSTEMEFFECT)"},
	{"valueA", 0x4, 4, 1, 0, nullptr, "+0x04 E: 0, 0x100 or 0x200 (looks like a start zoom, 256 = 1.0)"},
	{"valueB", 0x8, 4, 1, 0, nullptr, "+0x08 E: 0 or 0x100 (looks like an end zoom)"},
	{"ticks", 0xC, 4, 1, 0, nullptr, "+0x0C E: 0, 1 or 30 (looks like a duration)"},
	{"unused_10", 0x10, 4, 3, 0, nullptr, "+0x10 U: zero in all 7 records, no reader"},
};
static const Han2FieldInfo kGof2Section5RecordFields[] = {
	{"kind", 0x0, 4, 1, 0, nullptr, "+0x00 E: 1 in all 3 records"},
	{"unused_04", 0x4, 4, 4, 0, nullptr, "+0x04 U: zero in all records, no reader"},
};
static const Han2FieldInfo kGof2ScriptListEntryFields[] = {
	{"scriptId", 0x0, 4, 5, 0, nullptr, "+0x00 T: Obj_CollectFrameEnterEvents 0x43E1B0 (section 6, ScriptVm kind 0) / Obj_CollectTransitionRuleEvents 0x43E030 (section 7, kind 1) read slots 0..4 in order; id indexes the character .FOB index table of that kind"},
};
static const Han2FieldInfo kGof2EffectSpawnRecordFields[] = {
	{"enable", 0x0, 4, 1, 0, nullptr, "+0x00 T: non-zero = record active (gate in Obj_SetActionAndRunScript); 1 in all 729 records"},
	{"targetOffsetX", 0x4, 4, 1, 1, nullptr, "+0x04 T: held target X offset from the attacker hold point (multiplied by the facing sign)"},
	{"targetOffsetY", 0x8, 4, 1, 1, nullptr, "+0x08 T: held target Y offset"},
	{"facingCmd", 0xC, 4, 1, 2, "Gof2EffFacingCmd", "+0x0C T: target facing change (switch in Obj_SpawnFrameEffectRecord; 0 keep, 1 opposite, 2 same, 3/4 force)"},
	{"stateMode", 0x10, 4, 1, 2, "Gof2EffStateMode", "+0x10 T: how the target state is chosen; modes 1 and 2 also detach the link after the spawn"},
	{"stateArg0", 0x14, 4, 1, 1, nullptr, "+0x14 T: mode 0 YarareData table index, mode 1 target pattern, mode 2 hit class (sub_435E10)"},
	{"stateArg1", 0x18, 4, 1, 1, nullptr, "+0x18 T: mode 1 target frame (-1 = start), mode 2 victim facing mode (HitJudge_SetVictimFacing)"},
	{"stateArg2", 0x1C, 4, 1, 1, nullptr, "+0x1C T: mode 2 knock direction mode (HitJudge_SetKnockDirection); read only in mode 2"},
	{"unused_20", 0x20, 4, 3, 0, nullptr, "+0x20 U: zero in all records, no reader"},
	{"linkMode", 0x2C, 4, 1, 2, "Gof2EffLinkMode", "+0x2C T: switch after the state change (copy link context / set flags on the target obj+472/+476)"},
	{"unused_30", 0x30, 4, 5, 0, nullptr, "+0x30 U: zero in all records, no reader"},
	{"throwDamage", 0x44, 4, 1, 1, nullptr, "+0x44 T: non-zero runs Obj_ApplyEffectRecordThrowDamage 0x4326C0: damage handed to the target through the ScriptVm kind-0/id-7 table (500/400/50/900 in data)"},
	{"eventScriptId", 0x48, 4, 1, 0, nullptr, "+0x48 T: ScriptVm kind 5 id; the returned list is only skipped over (no effect); 1 in 3 records"},
	{"throwScriptArg", 0x4C, 4, 1, 1, nullptr, "+0x4C T: argument of the kind-0/id-7 call (Obj_ApplyEffectRecordThrowDamage); zero in all records"},
	{"unused_50", 0x50, 4, 4, 0, nullptr, "+0x50 U: zero in all records, no reader"},
};
static const Han2FieldInfo kGof2PatHeaderFields[] = {
	{"version", 0x0, 4, 1, 0, nullptr, "+0x00 E: 4 in all 64 PATs (RBO 3)"},
	{"byteOrderMarker", 0x4, 4, 1, 0, nullptr, "+0x04 E: 0x01234567 in all 64 PATs"},
	{"unused_08", 0x8, 4, 4, 0, nullptr, "+0x08 U: zero, not read"},
};
static const Han2FieldInfo kGof2PatFileHeadFields[] = {
	{"header", 0x0, 24, 1, 4, nullptr, "+0x0000 E: see Gof2PatHeader"},
	{"poseOffset", 0x18, 4, 2000, 0, nullptr, "+0x0018 T: absolute PAT offset of the pose's first part; 0 = absent; part index = (off-72028)/92 (CharacterLoad state 6 loop to 8068 = 4*2000+68)"},
	{"poseName", 0x1F58, 1, 64000, 0, nullptr, "+0x1F58 E: 2000 x 32-byte CP932 labels, never read"},
	{"imageAreaOffset", 0x11958, 4, 1, 0, nullptr, "+0x11958 T: PAT offset of the texture area; poses occupy [72028, imageAreaOffset) packed in 3680-byte blocks (CharacterLoad state 6 stores size-72028 at chara+60)"},
};
static const Han2FieldInfo kGof2PatPartFields[] = {
	{"x", 0x0, 4, 1, 1, nullptr, "+0x00 T: PosePart_ComputeGeometry 0x43FE50 (lerped toward the next pose)"},
	{"y", 0x4, 4, 1, 1, nullptr, "+0x04 T: same"},
	{"destWidth", 0x8, 4, 1, 1, nullptr, "+0x08 T: same (current part only)"},
	{"destHeight", 0xC, 4, 1, 1, nullptr, "+0x0C T: same"},
	{"flipFlags", 0x10, 4, 1, 2, "Gof2PatPartFlip", "+0x10 T: bit0/1 mirror (PosePart_GetFlippedSrcRect 0x4402A0); byte +0x11 != 0 forces the additive blend state (DrawSort_Run); 0x10000 never read"},
	{"scaleXPermille", 0x14, 4, 1, 1, nullptr, "+0x14 T: PosePart_ComputeGeometry"},
	{"scaleYPermille", 0x18, 4, 1, 1, nullptr, "+0x18 T: same"},
	{"rotation10000", 0x1C, 4, 1, 1, nullptr, "+0x1C T: same (10000 = full turn, Math_LerpAngle10000ToDeg 0x43FD00)"},
	{"modulateArgb", 0x20, 4, 1, 0, nullptr, "+0x20 T: PosePart_ModulateColor 0x440000 (bytes A,R,G,B in memory order; 0xFFFFFFFF = unchanged)"},
	{"addRgb", 0x24, 4, 1, 0, nullptr, "+0x24 T: PosePart_AddColor 0x440170 (bytes R,G,B; +0x27 never read, zero)"},
	{"textureIndex", 0x28, 4, 1, 1, nullptr, "+0x28 T: DrawSort_Run texture slot lookup (0xFFFF = clip part, skipped by DrawSort_BubbleByPriority)"},
	{"srcX", 0x2C, 4, 1, 1, nullptr, "+0x2C T: full dword read (RBO int16 + unused hi word); 1/256 of the texture"},
	{"srcY", 0x30, 4, 1, 1, nullptr, "+0x30 T: same"},
	{"srcW", 0x34, 4, 1, 1, nullptr, "+0x34 T: dword; 0 = part slot unused (DrawSort_BubbleByPriority)"},
	{"srcH", 0x38, 4, 1, 1, nullptr, "+0x38 T: dword; 0 = part slot unused"},
	{"layer", 0x3C, 4, 1, 0, nullptr, "+0x3C T: full dword << 8 is the sort key (RBO byte)"},
	{"originX", 0x40, 4, 1, 1, nullptr, "+0x40 T: PosePart_ComputeGeometry pivot X"},
	{"originY", 0x44, 4, 1, 1, nullptr, "+0x44 T: pivot Y"},
	{"unused_48", 0x48, 4, 5, 0, nullptr, "+0x48 U: zero in all 1233240 parts, no reader"},
};
static const Han2FieldInfo kGof2AttackBoxSetPrefixFields[] = {
	{"vtable", 0x0, 4, 1, 4, nullptr, "+0x00 T: vf0 returns the primary box count (this+4), vf8 the secondary count (this+8)"},
	{"primaryCount", 0x4, 4, 1, 0, nullptr, "+0x04 T: attack boxes that hit through HitJudge_CollectPairs; moved to secondaryCount when the record word +0x6E != 0 (CAppHanteiKougeki_BuildFromFrame)"},
	{"secondaryCount", 0x8, 4, 1, 0, nullptr, "+0x08 T: boxes tested by HitJudge_ResolveSecondaryBoxClashes"},
	{"record", 0xC, 4, 1, 4, nullptr, "+0x0C T: attackRecords + 236*frame.attackRecordIdx (read through Obj+0x620 = obj+1568 by every hit routine)"},
};
