// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"

enum Gof2AniFlag : uint8_t {
	G2ANI_END_TO_PATTERN = 0,
	G2ANI_NEXT = 1,
	G2ANI_JUMP_TO_FRAME = 2,
	G2ANI_NEXT_LAND_TO_PATTERN = 3,
	G2ANI_JUMP_TO_FRAME_LAND_TO_PATTERN = 4,
	G2ANI_LOOP_COUNTED = 5,
	G2ANI_HOLD_FRAME_REPORT_END = 6,
	G2ANI_NEXT_WHILE_CALLBACK = 7,
	G2ANI_NEXT_WHILE_COUNTER = 8,
	G2ANI_NEXT_WHILE_CALLBACK_B = 9,
};
enum Gof2FlipMode : uint8_t {
	G2FLIP_NONE = 0,
	G2FLIP_H = 1,
	G2FLIP_V = 2,
	G2ROT_90 = 3,
	G2ROT_180 = 4,
	G2ROT_270 = 5,
	G2FLIP_H_ROT_90 = 6,
	G2FLIP_H_ROT_270 = 7,
};
enum Gof2BlendMode : uint8_t {
	G2BLEND_KEEP_PREVIOUS = 0,
	G2BLEND_ALPHA = 1,
	G2BLEND_ADDITIVE = 2,
	G2BLEND_SUBTRACTIVE = 3,
};
enum Gof2DrawStyle : uint8_t {
	G2DRAWSTYLE_DEFAULT = 0,
	G2DRAWSTYLE_1 = 1,
	G2DRAWSTYLE_2 = 2,
};
enum Gof2FrameFxFlags : uint8_t {
	G2FX_USE_ZOOM = 1,
	G2FX_USE_ALPHA_FADE = 2,
};
enum Gof2MoveFlags : uint8_t {
	G2MOVE_CLEAR_VEL_X = 1,
	G2MOVE_CLEAR_VEL_Y = 2,
	G2MOVE_ADD_X = 4,
	G2MOVE_ADD_Y = 8,
};
enum Gof2StanceClass : uint8_t {
	G2STANCE_NONE = 0,
	G2STANCE_GROUND = 1,
	G2STANCE_CROUCH = 2,
	G2STANCE_AIR = 4,
};
enum Gof2CancelPermission : uint8_t {
	G2CANCEL_NONE = 0,
	G2CANCEL_ON_INPUT_MATCH = 1,
	G2CANCEL_ALWAYS = 2,
};
enum Gof2AttackEventFlags : uint8_t {
	G2ATKEV_BEGIN = 1,
	G2ATKEV_END = 2,
	G2ATKEV_ETC_BEGIN = 4,
	G2ATKEV_ETC_END = 8,
	G2ATKEV_KEEP_HIT_MEMORY = 0x10,
	G2ATKEV_SOUSAI_BEGIN = 0x20,
	G2ATKEV_SOUSAI_END = 0x40,
};
enum Gof2HurtMaskFlags : uint32_t {
	G2HMF_KEEP_NO_BIT8 = 0x100,
	G2HMF_SET_BIT9 = 0x200,
	G2HMF_NO_CLASS_0 = 0x10000,
	G2HMF_NO_CLASS_1 = 0x20000,
	G2HMF_NO_CLASS_2 = 0x40000,
	G2HMF_NO_CLASS_3 = 0x80000,
	G2HMF_NO_CLASS_4 = 0x100000,
	G2HMF_NO_CLASS_5 = 0x400000,
	G2HMF_NO_CLASS_6 = 0x800000,
	G2HMF_ANIME_FLAG_A = 0x1000000,
	G2HMF_ANIME_FLAG_B = 0x2000000,
};
enum Gof2MotionFlags : uint8_t {
	G2MOTF_UNREAD_BIT0 = 1,
	G2MOTF_RESET_MOVE_TRACKS = 2,
	G2MOTF_BRAKE_ON_ENTER = 4,
};
enum Gof2FacingCommand : uint32_t {
	G2FACE_NONE = 0,
	G2FACE_TOWARD_TARGET = 1,
	G2FACE_AWAY_FROM_TARGET = 2,
	G2FACE_FLIP_CURRENT = 3,
	G2FACE_SET_DIR0 = 4,
	G2FACE_SET_DIR1 = 5,
	G2FACE_TOWARD_INPUT_DIR = 6,
	G2FACE_AWAY_FROM_INPUT_DIR = 7,
};
enum Gof2HitSuppressFlags : uint32_t {
	G2HITSUP_KEEP_BOX_OBJECTS = 0x10000000,
};
enum Gof2ScriptOrderFlags : uint8_t {
	G2SCRIPTORD_LIST_A_FIRST = 1,
};
enum Gof2GuardMode : uint32_t {
	G2GUARD_NONE = 0,
	G2GUARD_ATTACK_TYPE_BIT0 = 1,
	G2GUARD_ATTACK_TYPE_BIT1 = 2,
	G2GUARD_ANY_BOX_ATTACK = 3,
	G2GUARD_IF_ATTACK_QUERY = 4,
};
enum Gof2ArmorMode : uint32_t {
	G2ARMOR_NONE = 0,
	G2ARMOR_ATTACK_TYPE_BIT0_OR_BIT2 = 1,
	G2ARMOR_ATTACK_TYPE_BIT1 = 2,
	G2ARMOR_ANY = 3,
};
enum Gof2Han2Kind : uint32_t {
	G2HAN2_KIND_FULL_DAT = 0,
	G2HAN2_KIND_PATTERN_ONLY_DT2 = 3,
};

#pragma pack(push, 1)
struct Gof2FrameRecord {
	int16_t spriteId;  // +0x00 T: CG image = id-10000 when >=10000, else PAT pose index (DrawHelper_Draw 0x49EF60, CHanteiAnime_CacheNextFrame 0x448F70, CHanteiAnime_ResolveCgImage 0x448E60)
	int16_t offsetX;  // +0x02 T: draw offset X (DrawHelper_Draw, DrawHelper_EmitPolygons 0x440850)
	int16_t offsetY;  // +0x04 T: draw offset Y (DrawHelper_Draw, DrawHelper_EmitPolygons)
	uint16_t duration;  // +0x06 T: ticks before advance (Obj_ScriptTick 0x434AD0 compares anime ticks to it; DrawHelper_Draw uses it as the tween denominator)
	Gof2FlipMode flipMode;  // +0x08 T: DrawHelper_Draw indexes the flip table dword_5A18E0[2*flipMode]
	Gof2BlendMode blendMode;  // +0x09 T: Obj_ApplyFrameBlendAlphaZoom 0x435620 copies non-zero to obj+1504 (DrawSort_Run blend table dword_5A1AA4)
	uint8_t alpha;  // +0x0A T: alpha fade target when fxFlags.USE_ALPHA_FADE (Obj_ApplyFrameBlendAlphaZoom -> obj+1072/+1076)
	Gof2AniFlag aniFlag;  // +0x0B T: CHanteiAnime_StepAniFlag 0x4490A0, CHanteiAnime_CacheNextFrame 0x448F70, Obj_ScanAheadForAttackFrame 0x4324F0
	uint8_t jumpTarget;  // +0x0C T: pattern (ANI_END_TO_PATTERN) or frame to jump to (CHanteiAnime_StepAniFlag)
	uint8_t landJumpTarget;  // +0x0D T: Obj_ApplyLandingFrameJump 0x430A40 (frame for aniFlag 1/2, pattern for 3/4), Obj_ScanAheadForAttackFrame
	uint8_t drawPriorityCode;  // +0x0E T: Obj_ApplyFrameDrawPriority 0x432E30 switch over codes 1..49 (1..8 add a depth step, 9..18/26..35/41..49 set depth + default layer, 19..25 and 36..40 set draw-order slots; table dword_5A2398)
	uint8_t unused_0F;  // +0x0F U: zero in all 43991 frames, no reader of frame+15
	uint16_t zoom;  // +0x10 T: 256 = 1.0; Obj_ApplyFrameBlendAlphaZoom copies to obj+1112 when fxFlags.USE_ZOOM
	uint8_t loopCount;  // +0x12 T: loaded into the anime loop counter when non-zero (Obj_SetActionAndRunScript 0x431B90, Obj_ScanAheadForAttackFrame reads the low byte)
	uint8_t loopEndFrame;  // +0x13 T: frame jumped to when the loop counter is exhausted (aniFlag 5 and 8; CHanteiAnime_StepAniFlag)
	uint8_t unused_14[4];  // +0x14 U: zero in all frames, no reader
	uint8_t interpolationMode;  // +0x18 T: non-zero = tween toward the next frame (CHanteiAnime_CacheNextFrame gate; DrawHelper_Draw -> sub_49E9A0 blend factor ticks/duration)
	Gof2FrameFxFlags fxFlags;  // +0x19 T: Obj_ApplyFrameBlendAlphaZoom
	Gof2DrawStyle drawStyle;  // +0x1A I: non-zero copied to obj+1508, DrawSort_Run indexes dword_5A1AB4[style] (0/1/2 in data)
	uint8_t unused_1B[13];  // +0x1B..0x27 U: zero in all frames, no reader
	Gof2MoveFlags moveFlags;  // +0x28 T: Obj_ApplyFrameMoveFlags 0x434950, Obj_ScaleVelocityOnEnterFrame 0x42EC30
	uint8_t unused_29[3];  // +0x29 U: zero in all frames (the flags byte is never read as a dword), no reader
	int16_t speedX;  // +0x2C T: added to velocity X when MOVE_ADD_X (Obj_ApplyFrameMoveFlags, flip-aware via facing)
	int16_t speedY;  // +0x2E T: added to velocity Y when MOVE_ADD_Y
	int16_t accelX;  // +0x30 T: acceleration X when MOVE_ADD_X
	int16_t accelY;  // +0x32 T: acceleration Y when MOVE_ADD_Y
	Gof2StanceClass stanceClass;  // +0x34 T: CHanteiAnime__vf0 0x448EB0 copies the dword at +0x34 to anime+44; bit 4 = airborne (sub_42ED90, HitJudge); ScriptCond_MatchStanceAndCancel 0x42F6A0 masks it
	Gof2CancelPermission normalCancel;  // +0x35 T: Obj_GetNormalCancelState 0x4302E0, ScriptCond_MatchStanceAndCancel
	Gof2CancelPermission specialCancel;  // +0x36 T: Obj_IsSpecialCancelAllowed 0x430120, ScriptCond_MatchStanceAndCancel
	uint8_t unused_37;  // +0x37 U: zero in all frames, no reader
	Gof2AttackEventFlags attackEventFlags;  // +0x38 T: CAppHanteiKougeki_BuildFromFrame 0x449250 (1,2,0x10), CAppHanteiEtc__vf7 0x449750 (4,8), CAppHanteiSousai__vf6 0x449820 (0x20,0x40)
	uint8_t unused_39[3];  // +0x39 U: zero in all frames, no reader
	uint32_t hurtMaskEnable;  // +0x3C T: 0 = anime vulnerability mask forced to 0 (CHanteiAnime__vf0 0x448EB0 reads *(frame+60))
	Gof2HurtMaskFlags hurtMaskFlags;  // +0x40 T: CHanteiAnime__vf0 builds anime+48 (class mask) and anime+52/+56 (flags A/B) from it
	uint32_t editorOnly_44;  // +0x44 E: =1 in 4 of 43991 frames, no reader of frame+68
	uint32_t hitLimitFlags;  // +0x48 T: copied to the hit limiter on ATKEV_BEGIN (CAppHanteiKougeki_BuildFromFrame reads *(frame+72)); zero in all frames
	uint32_t hitLimitCount;  // +0x4C T: copied to the hit limiter count (same function, *(frame+76)); zero in all frames
	uint32_t editorOnly_50;  // +0x50 E: 0x01000000 in 10 frames and 1 in 2, no reader of frame+80
	uint32_t unused_54;  // +0x54 U: zero in all frames, no reader
	uint32_t editorOnly_58;  // +0x58 E: 0x01000000 in 8 frames, no reader of frame+88
	Gof2MotionFlags motionFlags;  // +0x5C T: Obj_ApplyFrameMoveFlags (&2 -> Obj_ResetMoveTracks 0x430E90), Obj_ApplyFrameBrake 0x435280 (&4)
	uint8_t unused_5D;  // +0x5D U: zero in all frames, no reader
	int16_t brakePercent;  // +0x5E T: Obj_ApplyFrameBrake: velocity * brakePercent / -1000 (50 in 43831 frames)
	uint32_t editorOnly_60;  // +0x60 E: 0x01000000 in 6 frames, no reader of frame+96
	Gof2FacingCommand facingCommand;  // +0x64 T: Obj_ApplyFrameFacingCommand 0x43CF70 switch (1..7), Obj_ApplyFacingKind 0x43CE50
	uint32_t editorOnly_68;  // +0x68 E: 0x01000000 in 10 frames, no reader of frame+104
	uint32_t unused_6C;  // +0x6C U: zero in all frames, no reader
	uint32_t editorOnly_70;  // +0x70 E: 0x01000000 in 6 frames, no reader of frame+112
	uint32_t unused_74;  // +0x74 U: zero in all frames, no reader
	uint32_t editorOnly_78;  // +0x78 E: 0x01000000 in 10 frames, no reader of frame+120
	uint32_t unused_7C;  // +0x7C U: zero in all frames, no reader
	Gof2HitSuppressFlags hitSuppressFlags;  // +0x80 T: Obj_ResetHanteiBoxObjects 0x4356A0 tests 0x10000000 (24 frames), keeps the box objects alive
	uint32_t unused_84;  // +0x84 U: zero in all frames, no reader
	uint32_t editorOnly_88;  // +0x88 E: 0x01000000 in 6 frames, no reader of frame+136
	uint32_t unused_8C;  // +0x8C U: zero in all frames, no reader
	uint32_t editorOnly_90;  // +0x90 E: 0x01000000 in 10 frames, no reader of frame+144
	uint32_t unused_94;  // +0x94 U: zero in all frames, no reader
	uint32_t editorOnly_98;  // +0x98 E: 0x01000000 in 4 frames, no reader of frame+152
	uint32_t unused_9C;  // +0x9C U: zero in all frames, no reader
	uint32_t editorOnly_A0;  // +0xA0 E: 0x01000000 in 8 frames, no reader of frame+160
	uint32_t unused_A4;  // +0xA4 U: zero in all frames, no reader
	uint32_t editorOnly_A8;  // +0xA8 E: 0x01000000 in 10 frames, no reader of frame+168
	uint32_t unused_AC;  // +0xAC U: zero in all frames, no reader
	uint32_t editorOnly_B0;  // +0xB0 E: 0x01000000 in 6 frames, no reader of frame+176
	uint32_t unused_B4;  // +0xB4 U: zero in all frames, no reader
	Gof2ScriptOrderFlags scriptOrderFlags;  // +0xB8 T: CHanteiAnime_GetFrameScriptLists 0x449A30 returns *(frame+184)&1
	uint8_t unused_B9[3];  // +0xB9 U: zero in all frames, no reader
	uint32_t scriptListIndexA;  // +0xBC T: index into section 6 (20-byte script id lists, run as ScriptVm kind 0 by sub_43E1B0), 0 = none (CHanteiAnime_GetFrameScriptLists)
	uint32_t scriptListIndexB;  // +0xC0 T: index into section 7 (run as ScriptVm kind 1 by sub_43E030), 0 = none
	uint32_t hasAttackRedundant;  // +0xC4 E: 1 iff attackBoxCount>0 (1895 frames); no reader of frame+196, the engine tests attackBoxCount
	int32_t attackRecordIdx;  // +0xC8 T: index into section 3 (236-byte attack records), -1 none (CAppHanteiKougeki_BuildFromFrame, ObjScan_StoreAttackGuardInfo 0x432480)
	int32_t attackScratchFill[7];  // +0xCC E: 0xCDCDCDCD (MSVC debug fill) in the 1895 attack frames, -1 in all others; no reader of frame+204..+231
	uint32_t legacyBoxGroupACount;  // +0xE8 E: 0/1 (1 in 10 frames); no reader of frame+232, its slots hold stale values outside the box table numbering
	int32_t legacyBoxGroupAIdx[3];  // +0xEC E: -1 except 10 frames (0..3); no reader
	uint32_t legacyBoxGroupBCount;  // +0xF8 E: 0/1 (1 in 6 frames); no reader of frame+248
	int32_t legacyBoxGroupBIdx[4];  // +0xFC E: -1 except +0x108 in 6 frames (0/1); no reader
	uint32_t kasanariBoxEnable;  // +0x10C T: CAppHanteiKasanari__vf5 0x449620 gate (== number of non -1 slots)
	int32_t kasanariBoxIdx;  // +0x110 T: section 2 box index (single slot), -1 = empty
	uint32_t hurtBoxCount;  // +0x114 T: CAppHanteiYarare__vf6 0x4494F0 gate
	int32_t hurtBoxIdx[6];  // +0x118 T: section 2 box indices (6 slots read by CAppHanteiYarare__vf6), -1 = empty
	uint32_t editorOnly_130;  // +0x130 E: 6 in 42369 frames, 0 in 1622; frame+304 is the Yarare parameter block (lea in CAppHanteiYarare__vf6) but nothing reads its first dword
	Gof2GuardMode guardMode;  // +0x134 I: HitJudge_DefenderGuardsAttack 0x496930 switches on *(yarare+4) = frame+308
	Gof2ArmorMode armorMode;  // +0x138 I: HitJudge_DefenderArmorAbsorbs 0x497180 switches on *(yarare+4+4) = frame+312
	uint32_t etcBoxCount;  // +0x13C T: CAppHanteiEtc__vf7 0x449750 gate
	int32_t etcBoxIdx[3];  // +0x140 T: 3 slots read; only the first is ever used in the data
	uint32_t sousaiBoxCount;  // +0x14C T: CAppHanteiSousai__vf6 0x449820 gate
	int32_t sousaiBoxIdx[3];  // +0x150 T: 3 slots read, only the first is ever used
	uint32_t tobiBoxCount;  // +0x15C T: CAppHanteiTobi__vf6 0x449910 gate
	int32_t tobiBoxIdx[3];  // +0x160 T: 3 slots read (RBO had 4)
	uint32_t attackBoxCount;  // +0x16C T: CAppHanteiKougeki_BuildFromFrame gate
	int32_t attackBoxIdx[8];  // +0x170 T: 8 slots read; slots 0..4 are used in the data
	uint32_t effectRecordIdx;  // +0x190 T: 1-based index into section 8 (96-byte records), 0 = none (Obj_SetActionAndRunScript -> Obj_SpawnFrameEffectRecord 0x4327F0)
};
struct Gof2PatternEntry {
	uint32_t frameCount;  // +0x0 T: 0 = pattern absent (CHanteiAnime_CacheNextFrame, sub_4334C0 test *(pattern+12*n))
	uint32_t flags;  // +0x4 E: zero in all 17408 entries of all 68 files; no reader of pattern+4
	uint32_t firstFrameIndex;  // +0x8 T: index into section 1 (frames are packed in pattern order)
};
struct Gof2BoxRect {
	int16_t x1;  // +0x0 T: CAppHanteiKasanari__vf6 0x449680 etc. read four shorts (left, top, right, bottom; mirrored when facing flips)
	int16_t y1;  // +0x2 T: see x1
	int16_t x2;  // +0x4 T: see x1
	int16_t y2;  // +0x6 T: see x1
};
struct Gof2HanteiAnime {
	uint32_t vtable;  // +0x00 T: CHanteiAnime vftable, embedded in the 0x1264-byte Obj at +616 (Obj_ConstructPoolSlot 0x435850)
	int32_t patternNo;  // +0x04 T: current pattern (CHanteiAnime_CacheNextFrame)
	int32_t frameNo;  // +0x08 T: frame inside the pattern
	int32_t frameTicks;  // +0x0C T: ticks spent on the frame (Obj_ScriptTick increments, compared to frame.duration)
	int32_t loopCounter;  // +0x10 T: aniFlag 5/8 counter (CHanteiAnime_StepAniFlag)
	uint32_t view;  // +0x14 T: pattern area view (obj+636 = chara record +12)
	uint32_t charaRecord;  // +0x18 T: chara data block (obj+640, holds the PAT parts bank at +52)
	uint32_t frame;  // +0x1C T: current frame read by the hit-box builders (obj+644)
	uint32_t frameTick;  // +0x20 T: same frame pointer read by the animation step and DrawHelper_Draw (obj+648)
	uint32_t aniCallback;  // +0x24 T: int (__cdecl *)(int) predicate for aniFlag 7/9 (CHanteiAnime_StepAniFlag)
	int32_t aniCallbackArg;  // +0x28 T
	uint32_t stanceDword;  // +0x2C T: copy of frame dword +0x34 (CHanteiAnime__vf0)
	uint32_t vulnerabilityMask;  // +0x30 T: class mask built from hurtMaskEnable/hurtMaskFlags (CHanteiAnime__vf0)
	int32_t flagA;  // +0x34 T: hurtMaskFlags & 0x1000000
	int32_t flagB;  // +0x38 T: hurtMaskFlags & 0x2000000
	int32_t nextSpriteId;  // +0x3C T: sprite id of the frame after this one (CHanteiAnime_CacheNextFrame), tween target
	uint32_t nextFrame;  // +0x40 T: frame after this one
};
struct Gof2Han2AreaRef {
	uint32_t offset;  // +0x0 absolute file offset (a .DT2 keeps the .DAT's offsets for areas it does not carry)
	uint32_t size;  // +0x4 0 = area absent
};
struct Gof2Han2FileHeader {
	char signature[8];  // +0x00 "HAN2RBO " (never checked by the game)
	Gof2Han2Kind kind;  // +0x08 E: not read; 3 in all 68 GOF2 files
	uint32_t unused_0C;  // +0x0C E: zero in all 68 files, not read
	uint32_t version;  // +0x10 E: 2 in all files, not read
	uint32_t unused_14;  // +0x14 E: zero in all files, not read
	uint32_t subVersion;  // +0x18 E: 2 = GOF2 layout (404-byte frames, 9 sections); not read by the game
	uint32_t xorFlag;  // +0x1C T: non-zero = header + sections 0..5 are XOR-obfuscated (State0_4_NextFile -> Gof2_XorDecryptBuffer); 0 in every shipped file
	Gof2Han2AreaRef patternArea;  // +0x20 T: read by State0_1 into a1[11..12], the area is loaded by State0_2 (AllocateAndReadFileData(path, offset, size))
	Gof2Han2AreaRef partsPat;  // +0x28 T: PAT parts bank, always from the .DAT (a1[13..14] -> chara block +52/+56)
	Gof2Han2AreaRef cgBank;  // +0x30 T: BMP Cutter3 bank, always from the .DAT
	Gof2Han2AreaRef patternNames;  // +0x38 E: 256 x 64-byte CP932 pattern names; editor data, not read
};
struct Gof2PatternAreaHeader {
	uint32_t mustBeZero_00;  // +0x00 V: must be 0 (State0_4_NextFile aborts the load otherwise)
	uint32_t mustBeEight_04;  // +0x04 V: must be 8 (RBO stores 3 here)
	uint32_t mustBeZero_08;  // +0x08 V: must be 0
	uint32_t mustBeFive_0C;  // +0x0C V: must be 5 (RBO stores 1)
	uint32_t mustBeZero_10[4];  // +0x10 V: +0x10..0x1F must be 0
	uint32_t editorMark_20;  // +0x20 E: 1 in all 68 files, not validated or read
	uint32_t unused_24[3];  // +0x24 E: zero in all files, not read
	uint32_t sectionSize[9];  // +0x30 T: section byte sizes (Gof2PatternArea_ComputeSectionPointers reads a2[12..20]); 0 = absent
	uint32_t unused_54[3];  // +0x54 E: zero in all files, not read
};
struct Gof2PatternAreaView {
	uint32_t base;  // +0x00 T: GlobalAlloc block holding the whole pattern area
	uint32_t patterns;  // +0x04 T: section 0, 256 x 12 bytes (CHanteiAnime_CacheNextFrame: 12*pattern + patterns)
	uint32_t frames;  // +0x08 T: section 1, 404-byte records (frames + 404*(first+frameNo))
	uint32_t boxes;  // +0x0C T: section 2, 8-byte rectangles (CAppHanteiKougeki_BuildFromFrame: boxes + 8*idx)
	uint32_t attackRecords;  // +0x10 T: section 3, 236-byte attack records (boxes' owner data: attackRecords + 236*frame.attackRecordIdx)
	uint32_t section4;  // +0x14 E: section 4 (28-byte records inferred from sizes 28/56/112), no reader of view+20
	uint32_t section5;  // +0x18 E: section 5 (20-byte records inferred from sizes 20/40), no reader of view+24
	uint32_t scriptListsA;  // +0x1C T: section 6, 20-byte lists of 5 script ids, ScriptVm kind 0 (CHanteiAnime_GetFrameScriptLists)
	uint32_t scriptListsB;  // +0x20 T: section 7, 20-byte lists of 5 script ids, ScriptVm kind 1
	uint32_t effectRecords;  // +0x24 T: section 8, 96-byte records (Obj_SetActionAndRunScript: view+36 + 96*frame.effectRecordIdx -> Obj_SpawnFrameEffectRecord)
};
struct Gof2CharaDataBlock {
	uint32_t reserved_00;  // +0x00 T: record+4, not touched by the pattern-area loader
	uint32_t xorFlag;  // +0x04 T: copy of file header xorFlag (State0_1_LoadPATandCHPFiles)
	Gof2PatternAreaView view;  // +0x08 T: filled by Gof2PatternArea_ComputeSectionPointers(&container+8, header)
	uint32_t reserved_30;  // +0x30 T: not touched by the pattern-area loader
	uint32_t partsPatOffset;  // +0x34 T: file offset of the PAT parts bank (sub_447B70 stores header partsPat.offset)
	uint32_t partsPatSize;  // +0x38 T: PAT bank size; the PAT section is outside this task (poseIndex table starts at +0x44)
};
#pragma pack(pop)

static_assert(sizeof(Gof2FrameRecord) == 0x194, "Gof2FrameRecord size");
static_assert(offsetof(Gof2FrameRecord, spriteId) == 0x0, "Gof2FrameRecord.spriteId");
static_assert(offsetof(Gof2FrameRecord, offsetX) == 0x2, "Gof2FrameRecord.offsetX");
static_assert(offsetof(Gof2FrameRecord, offsetY) == 0x4, "Gof2FrameRecord.offsetY");
static_assert(offsetof(Gof2FrameRecord, duration) == 0x6, "Gof2FrameRecord.duration");
static_assert(offsetof(Gof2FrameRecord, flipMode) == 0x8, "Gof2FrameRecord.flipMode");
static_assert(offsetof(Gof2FrameRecord, blendMode) == 0x9, "Gof2FrameRecord.blendMode");
static_assert(offsetof(Gof2FrameRecord, alpha) == 0xA, "Gof2FrameRecord.alpha");
static_assert(offsetof(Gof2FrameRecord, aniFlag) == 0xB, "Gof2FrameRecord.aniFlag");
static_assert(offsetof(Gof2FrameRecord, jumpTarget) == 0xC, "Gof2FrameRecord.jumpTarget");
static_assert(offsetof(Gof2FrameRecord, landJumpTarget) == 0xD, "Gof2FrameRecord.landJumpTarget");
static_assert(offsetof(Gof2FrameRecord, drawPriorityCode) == 0xE, "Gof2FrameRecord.drawPriorityCode");
static_assert(offsetof(Gof2FrameRecord, unused_0F) == 0xF, "Gof2FrameRecord.unused_0F");
static_assert(offsetof(Gof2FrameRecord, zoom) == 0x10, "Gof2FrameRecord.zoom");
static_assert(offsetof(Gof2FrameRecord, loopCount) == 0x12, "Gof2FrameRecord.loopCount");
static_assert(offsetof(Gof2FrameRecord, loopEndFrame) == 0x13, "Gof2FrameRecord.loopEndFrame");
static_assert(offsetof(Gof2FrameRecord, unused_14) == 0x14, "Gof2FrameRecord.unused_14");
static_assert(offsetof(Gof2FrameRecord, interpolationMode) == 0x18, "Gof2FrameRecord.interpolationMode");
static_assert(offsetof(Gof2FrameRecord, fxFlags) == 0x19, "Gof2FrameRecord.fxFlags");
static_assert(offsetof(Gof2FrameRecord, drawStyle) == 0x1A, "Gof2FrameRecord.drawStyle");
static_assert(offsetof(Gof2FrameRecord, unused_1B) == 0x1B, "Gof2FrameRecord.unused_1B");
static_assert(offsetof(Gof2FrameRecord, moveFlags) == 0x28, "Gof2FrameRecord.moveFlags");
static_assert(offsetof(Gof2FrameRecord, unused_29) == 0x29, "Gof2FrameRecord.unused_29");
static_assert(offsetof(Gof2FrameRecord, speedX) == 0x2C, "Gof2FrameRecord.speedX");
static_assert(offsetof(Gof2FrameRecord, speedY) == 0x2E, "Gof2FrameRecord.speedY");
static_assert(offsetof(Gof2FrameRecord, accelX) == 0x30, "Gof2FrameRecord.accelX");
static_assert(offsetof(Gof2FrameRecord, accelY) == 0x32, "Gof2FrameRecord.accelY");
static_assert(offsetof(Gof2FrameRecord, stanceClass) == 0x34, "Gof2FrameRecord.stanceClass");
static_assert(offsetof(Gof2FrameRecord, normalCancel) == 0x35, "Gof2FrameRecord.normalCancel");
static_assert(offsetof(Gof2FrameRecord, specialCancel) == 0x36, "Gof2FrameRecord.specialCancel");
static_assert(offsetof(Gof2FrameRecord, unused_37) == 0x37, "Gof2FrameRecord.unused_37");
static_assert(offsetof(Gof2FrameRecord, attackEventFlags) == 0x38, "Gof2FrameRecord.attackEventFlags");
static_assert(offsetof(Gof2FrameRecord, unused_39) == 0x39, "Gof2FrameRecord.unused_39");
static_assert(offsetof(Gof2FrameRecord, hurtMaskEnable) == 0x3C, "Gof2FrameRecord.hurtMaskEnable");
static_assert(offsetof(Gof2FrameRecord, hurtMaskFlags) == 0x40, "Gof2FrameRecord.hurtMaskFlags");
static_assert(offsetof(Gof2FrameRecord, editorOnly_44) == 0x44, "Gof2FrameRecord.editorOnly_44");
static_assert(offsetof(Gof2FrameRecord, hitLimitFlags) == 0x48, "Gof2FrameRecord.hitLimitFlags");
static_assert(offsetof(Gof2FrameRecord, hitLimitCount) == 0x4C, "Gof2FrameRecord.hitLimitCount");
static_assert(offsetof(Gof2FrameRecord, editorOnly_50) == 0x50, "Gof2FrameRecord.editorOnly_50");
static_assert(offsetof(Gof2FrameRecord, unused_54) == 0x54, "Gof2FrameRecord.unused_54");
static_assert(offsetof(Gof2FrameRecord, editorOnly_58) == 0x58, "Gof2FrameRecord.editorOnly_58");
static_assert(offsetof(Gof2FrameRecord, motionFlags) == 0x5C, "Gof2FrameRecord.motionFlags");
static_assert(offsetof(Gof2FrameRecord, unused_5D) == 0x5D, "Gof2FrameRecord.unused_5D");
static_assert(offsetof(Gof2FrameRecord, brakePercent) == 0x5E, "Gof2FrameRecord.brakePercent");
static_assert(offsetof(Gof2FrameRecord, editorOnly_60) == 0x60, "Gof2FrameRecord.editorOnly_60");
static_assert(offsetof(Gof2FrameRecord, facingCommand) == 0x64, "Gof2FrameRecord.facingCommand");
static_assert(offsetof(Gof2FrameRecord, editorOnly_68) == 0x68, "Gof2FrameRecord.editorOnly_68");
static_assert(offsetof(Gof2FrameRecord, unused_6C) == 0x6C, "Gof2FrameRecord.unused_6C");
static_assert(offsetof(Gof2FrameRecord, editorOnly_70) == 0x70, "Gof2FrameRecord.editorOnly_70");
static_assert(offsetof(Gof2FrameRecord, unused_74) == 0x74, "Gof2FrameRecord.unused_74");
static_assert(offsetof(Gof2FrameRecord, editorOnly_78) == 0x78, "Gof2FrameRecord.editorOnly_78");
static_assert(offsetof(Gof2FrameRecord, unused_7C) == 0x7C, "Gof2FrameRecord.unused_7C");
static_assert(offsetof(Gof2FrameRecord, hitSuppressFlags) == 0x80, "Gof2FrameRecord.hitSuppressFlags");
static_assert(offsetof(Gof2FrameRecord, unused_84) == 0x84, "Gof2FrameRecord.unused_84");
static_assert(offsetof(Gof2FrameRecord, editorOnly_88) == 0x88, "Gof2FrameRecord.editorOnly_88");
static_assert(offsetof(Gof2FrameRecord, unused_8C) == 0x8C, "Gof2FrameRecord.unused_8C");
static_assert(offsetof(Gof2FrameRecord, editorOnly_90) == 0x90, "Gof2FrameRecord.editorOnly_90");
static_assert(offsetof(Gof2FrameRecord, unused_94) == 0x94, "Gof2FrameRecord.unused_94");
static_assert(offsetof(Gof2FrameRecord, editorOnly_98) == 0x98, "Gof2FrameRecord.editorOnly_98");
static_assert(offsetof(Gof2FrameRecord, unused_9C) == 0x9C, "Gof2FrameRecord.unused_9C");
static_assert(offsetof(Gof2FrameRecord, editorOnly_A0) == 0xA0, "Gof2FrameRecord.editorOnly_A0");
static_assert(offsetof(Gof2FrameRecord, unused_A4) == 0xA4, "Gof2FrameRecord.unused_A4");
static_assert(offsetof(Gof2FrameRecord, editorOnly_A8) == 0xA8, "Gof2FrameRecord.editorOnly_A8");
static_assert(offsetof(Gof2FrameRecord, unused_AC) == 0xAC, "Gof2FrameRecord.unused_AC");
static_assert(offsetof(Gof2FrameRecord, editorOnly_B0) == 0xB0, "Gof2FrameRecord.editorOnly_B0");
static_assert(offsetof(Gof2FrameRecord, unused_B4) == 0xB4, "Gof2FrameRecord.unused_B4");
static_assert(offsetof(Gof2FrameRecord, scriptOrderFlags) == 0xB8, "Gof2FrameRecord.scriptOrderFlags");
static_assert(offsetof(Gof2FrameRecord, unused_B9) == 0xB9, "Gof2FrameRecord.unused_B9");
static_assert(offsetof(Gof2FrameRecord, scriptListIndexA) == 0xBC, "Gof2FrameRecord.scriptListIndexA");
static_assert(offsetof(Gof2FrameRecord, scriptListIndexB) == 0xC0, "Gof2FrameRecord.scriptListIndexB");
static_assert(offsetof(Gof2FrameRecord, hasAttackRedundant) == 0xC4, "Gof2FrameRecord.hasAttackRedundant");
static_assert(offsetof(Gof2FrameRecord, attackRecordIdx) == 0xC8, "Gof2FrameRecord.attackRecordIdx");
static_assert(offsetof(Gof2FrameRecord, attackScratchFill) == 0xCC, "Gof2FrameRecord.attackScratchFill");
static_assert(offsetof(Gof2FrameRecord, legacyBoxGroupACount) == 0xE8, "Gof2FrameRecord.legacyBoxGroupACount");
static_assert(offsetof(Gof2FrameRecord, legacyBoxGroupAIdx) == 0xEC, "Gof2FrameRecord.legacyBoxGroupAIdx");
static_assert(offsetof(Gof2FrameRecord, legacyBoxGroupBCount) == 0xF8, "Gof2FrameRecord.legacyBoxGroupBCount");
static_assert(offsetof(Gof2FrameRecord, legacyBoxGroupBIdx) == 0xFC, "Gof2FrameRecord.legacyBoxGroupBIdx");
static_assert(offsetof(Gof2FrameRecord, kasanariBoxEnable) == 0x10C, "Gof2FrameRecord.kasanariBoxEnable");
static_assert(offsetof(Gof2FrameRecord, kasanariBoxIdx) == 0x110, "Gof2FrameRecord.kasanariBoxIdx");
static_assert(offsetof(Gof2FrameRecord, hurtBoxCount) == 0x114, "Gof2FrameRecord.hurtBoxCount");
static_assert(offsetof(Gof2FrameRecord, hurtBoxIdx) == 0x118, "Gof2FrameRecord.hurtBoxIdx");
static_assert(offsetof(Gof2FrameRecord, editorOnly_130) == 0x130, "Gof2FrameRecord.editorOnly_130");
static_assert(offsetof(Gof2FrameRecord, guardMode) == 0x134, "Gof2FrameRecord.guardMode");
static_assert(offsetof(Gof2FrameRecord, armorMode) == 0x138, "Gof2FrameRecord.armorMode");
static_assert(offsetof(Gof2FrameRecord, etcBoxCount) == 0x13C, "Gof2FrameRecord.etcBoxCount");
static_assert(offsetof(Gof2FrameRecord, etcBoxIdx) == 0x140, "Gof2FrameRecord.etcBoxIdx");
static_assert(offsetof(Gof2FrameRecord, sousaiBoxCount) == 0x14C, "Gof2FrameRecord.sousaiBoxCount");
static_assert(offsetof(Gof2FrameRecord, sousaiBoxIdx) == 0x150, "Gof2FrameRecord.sousaiBoxIdx");
static_assert(offsetof(Gof2FrameRecord, tobiBoxCount) == 0x15C, "Gof2FrameRecord.tobiBoxCount");
static_assert(offsetof(Gof2FrameRecord, tobiBoxIdx) == 0x160, "Gof2FrameRecord.tobiBoxIdx");
static_assert(offsetof(Gof2FrameRecord, attackBoxCount) == 0x16C, "Gof2FrameRecord.attackBoxCount");
static_assert(offsetof(Gof2FrameRecord, attackBoxIdx) == 0x170, "Gof2FrameRecord.attackBoxIdx");
static_assert(offsetof(Gof2FrameRecord, effectRecordIdx) == 0x190, "Gof2FrameRecord.effectRecordIdx");
static_assert(sizeof(Gof2PatternEntry) == 0xC, "Gof2PatternEntry size");
static_assert(offsetof(Gof2PatternEntry, frameCount) == 0x0, "Gof2PatternEntry.frameCount");
static_assert(offsetof(Gof2PatternEntry, flags) == 0x4, "Gof2PatternEntry.flags");
static_assert(offsetof(Gof2PatternEntry, firstFrameIndex) == 0x8, "Gof2PatternEntry.firstFrameIndex");
static_assert(sizeof(Gof2BoxRect) == 0x8, "Gof2BoxRect size");
static_assert(offsetof(Gof2BoxRect, x1) == 0x0, "Gof2BoxRect.x1");
static_assert(offsetof(Gof2BoxRect, y1) == 0x2, "Gof2BoxRect.y1");
static_assert(offsetof(Gof2BoxRect, x2) == 0x4, "Gof2BoxRect.x2");
static_assert(offsetof(Gof2BoxRect, y2) == 0x6, "Gof2BoxRect.y2");
static_assert(sizeof(Gof2HanteiAnime) == 0x44, "Gof2HanteiAnime size");
static_assert(offsetof(Gof2HanteiAnime, vtable) == 0x0, "Gof2HanteiAnime.vtable");
static_assert(offsetof(Gof2HanteiAnime, patternNo) == 0x4, "Gof2HanteiAnime.patternNo");
static_assert(offsetof(Gof2HanteiAnime, frameNo) == 0x8, "Gof2HanteiAnime.frameNo");
static_assert(offsetof(Gof2HanteiAnime, frameTicks) == 0xC, "Gof2HanteiAnime.frameTicks");
static_assert(offsetof(Gof2HanteiAnime, loopCounter) == 0x10, "Gof2HanteiAnime.loopCounter");
static_assert(offsetof(Gof2HanteiAnime, view) == 0x14, "Gof2HanteiAnime.view");
static_assert(offsetof(Gof2HanteiAnime, charaRecord) == 0x18, "Gof2HanteiAnime.charaRecord");
static_assert(offsetof(Gof2HanteiAnime, frame) == 0x1C, "Gof2HanteiAnime.frame");
static_assert(offsetof(Gof2HanteiAnime, frameTick) == 0x20, "Gof2HanteiAnime.frameTick");
static_assert(offsetof(Gof2HanteiAnime, aniCallback) == 0x24, "Gof2HanteiAnime.aniCallback");
static_assert(offsetof(Gof2HanteiAnime, aniCallbackArg) == 0x28, "Gof2HanteiAnime.aniCallbackArg");
static_assert(offsetof(Gof2HanteiAnime, stanceDword) == 0x2C, "Gof2HanteiAnime.stanceDword");
static_assert(offsetof(Gof2HanteiAnime, vulnerabilityMask) == 0x30, "Gof2HanteiAnime.vulnerabilityMask");
static_assert(offsetof(Gof2HanteiAnime, flagA) == 0x34, "Gof2HanteiAnime.flagA");
static_assert(offsetof(Gof2HanteiAnime, flagB) == 0x38, "Gof2HanteiAnime.flagB");
static_assert(offsetof(Gof2HanteiAnime, nextSpriteId) == 0x3C, "Gof2HanteiAnime.nextSpriteId");
static_assert(offsetof(Gof2HanteiAnime, nextFrame) == 0x40, "Gof2HanteiAnime.nextFrame");
static_assert(sizeof(Gof2Han2AreaRef) == 0x8, "Gof2Han2AreaRef size");
static_assert(offsetof(Gof2Han2AreaRef, offset) == 0x0, "Gof2Han2AreaRef.offset");
static_assert(offsetof(Gof2Han2AreaRef, size) == 0x4, "Gof2Han2AreaRef.size");
static_assert(sizeof(Gof2Han2FileHeader) == 0x40, "Gof2Han2FileHeader size");
static_assert(offsetof(Gof2Han2FileHeader, signature) == 0x0, "Gof2Han2FileHeader.signature");
static_assert(offsetof(Gof2Han2FileHeader, kind) == 0x8, "Gof2Han2FileHeader.kind");
static_assert(offsetof(Gof2Han2FileHeader, unused_0C) == 0xC, "Gof2Han2FileHeader.unused_0C");
static_assert(offsetof(Gof2Han2FileHeader, version) == 0x10, "Gof2Han2FileHeader.version");
static_assert(offsetof(Gof2Han2FileHeader, unused_14) == 0x14, "Gof2Han2FileHeader.unused_14");
static_assert(offsetof(Gof2Han2FileHeader, subVersion) == 0x18, "Gof2Han2FileHeader.subVersion");
static_assert(offsetof(Gof2Han2FileHeader, xorFlag) == 0x1C, "Gof2Han2FileHeader.xorFlag");
static_assert(offsetof(Gof2Han2FileHeader, patternArea) == 0x20, "Gof2Han2FileHeader.patternArea");
static_assert(offsetof(Gof2Han2FileHeader, partsPat) == 0x28, "Gof2Han2FileHeader.partsPat");
static_assert(offsetof(Gof2Han2FileHeader, cgBank) == 0x30, "Gof2Han2FileHeader.cgBank");
static_assert(offsetof(Gof2Han2FileHeader, patternNames) == 0x38, "Gof2Han2FileHeader.patternNames");
static_assert(sizeof(Gof2PatternAreaHeader) == 0x60, "Gof2PatternAreaHeader size");
static_assert(offsetof(Gof2PatternAreaHeader, mustBeZero_00) == 0x0, "Gof2PatternAreaHeader.mustBeZero_00");
static_assert(offsetof(Gof2PatternAreaHeader, mustBeEight_04) == 0x4, "Gof2PatternAreaHeader.mustBeEight_04");
static_assert(offsetof(Gof2PatternAreaHeader, mustBeZero_08) == 0x8, "Gof2PatternAreaHeader.mustBeZero_08");
static_assert(offsetof(Gof2PatternAreaHeader, mustBeFive_0C) == 0xC, "Gof2PatternAreaHeader.mustBeFive_0C");
static_assert(offsetof(Gof2PatternAreaHeader, mustBeZero_10) == 0x10, "Gof2PatternAreaHeader.mustBeZero_10");
static_assert(offsetof(Gof2PatternAreaHeader, editorMark_20) == 0x20, "Gof2PatternAreaHeader.editorMark_20");
static_assert(offsetof(Gof2PatternAreaHeader, unused_24) == 0x24, "Gof2PatternAreaHeader.unused_24");
static_assert(offsetof(Gof2PatternAreaHeader, sectionSize) == 0x30, "Gof2PatternAreaHeader.sectionSize");
static_assert(offsetof(Gof2PatternAreaHeader, unused_54) == 0x54, "Gof2PatternAreaHeader.unused_54");
static_assert(sizeof(Gof2PatternAreaView) == 0x28, "Gof2PatternAreaView size");
static_assert(offsetof(Gof2PatternAreaView, base) == 0x0, "Gof2PatternAreaView.base");
static_assert(offsetof(Gof2PatternAreaView, patterns) == 0x4, "Gof2PatternAreaView.patterns");
static_assert(offsetof(Gof2PatternAreaView, frames) == 0x8, "Gof2PatternAreaView.frames");
static_assert(offsetof(Gof2PatternAreaView, boxes) == 0xC, "Gof2PatternAreaView.boxes");
static_assert(offsetof(Gof2PatternAreaView, attackRecords) == 0x10, "Gof2PatternAreaView.attackRecords");
static_assert(offsetof(Gof2PatternAreaView, section4) == 0x14, "Gof2PatternAreaView.section4");
static_assert(offsetof(Gof2PatternAreaView, section5) == 0x18, "Gof2PatternAreaView.section5");
static_assert(offsetof(Gof2PatternAreaView, scriptListsA) == 0x1C, "Gof2PatternAreaView.scriptListsA");
static_assert(offsetof(Gof2PatternAreaView, scriptListsB) == 0x20, "Gof2PatternAreaView.scriptListsB");
static_assert(offsetof(Gof2PatternAreaView, effectRecords) == 0x24, "Gof2PatternAreaView.effectRecords");
static_assert(sizeof(Gof2CharaDataBlock) == 0x3C, "Gof2CharaDataBlock size");
static_assert(offsetof(Gof2CharaDataBlock, reserved_00) == 0x0, "Gof2CharaDataBlock.reserved_00");
static_assert(offsetof(Gof2CharaDataBlock, xorFlag) == 0x4, "Gof2CharaDataBlock.xorFlag");
static_assert(offsetof(Gof2CharaDataBlock, view) == 0x8, "Gof2CharaDataBlock.view");
static_assert(offsetof(Gof2CharaDataBlock, reserved_30) == 0x30, "Gof2CharaDataBlock.reserved_30");
static_assert(offsetof(Gof2CharaDataBlock, partsPatOffset) == 0x34, "Gof2CharaDataBlock.partsPatOffset");
static_assert(offsetof(Gof2CharaDataBlock, partsPatSize) == 0x38, "Gof2CharaDataBlock.partsPatSize");

static const Han2EnumValue kGof2AniFlagValues[] = {
	{"G2ANI_END_TO_PATTERN", (int64_t)(0)},
	{"G2ANI_NEXT", (int64_t)(1)},
	{"G2ANI_JUMP_TO_FRAME", (int64_t)(2)},
	{"G2ANI_NEXT_LAND_TO_PATTERN", (int64_t)(3)},
	{"G2ANI_JUMP_TO_FRAME_LAND_TO_PATTERN", (int64_t)(4)},
	{"G2ANI_LOOP_COUNTED", (int64_t)(5)},
	{"G2ANI_HOLD_FRAME_REPORT_END", (int64_t)(6)},
	{"G2ANI_NEXT_WHILE_CALLBACK", (int64_t)(7)},
	{"G2ANI_NEXT_WHILE_COUNTER", (int64_t)(8)},
	{"G2ANI_NEXT_WHILE_CALLBACK_B", (int64_t)(9)},
};
static const Han2EnumValue kGof2FlipModeValues[] = {
	{"G2FLIP_NONE", (int64_t)(0)},
	{"G2FLIP_H", (int64_t)(1)},
	{"G2FLIP_V", (int64_t)(2)},
	{"G2ROT_90", (int64_t)(3)},
	{"G2ROT_180", (int64_t)(4)},
	{"G2ROT_270", (int64_t)(5)},
	{"G2FLIP_H_ROT_90", (int64_t)(6)},
	{"G2FLIP_H_ROT_270", (int64_t)(7)},
};
static const Han2EnumValue kGof2BlendModeValues[] = {
	{"G2BLEND_KEEP_PREVIOUS", (int64_t)(0)},
	{"G2BLEND_ALPHA", (int64_t)(1)},
	{"G2BLEND_ADDITIVE", (int64_t)(2)},
	{"G2BLEND_SUBTRACTIVE", (int64_t)(3)},
};
static const Han2EnumValue kGof2DrawStyleValues[] = {
	{"G2DRAWSTYLE_DEFAULT", (int64_t)(0)},
	{"G2DRAWSTYLE_1", (int64_t)(1)},
	{"G2DRAWSTYLE_2", (int64_t)(2)},
};
static const Han2EnumValue kGof2FrameFxFlagsValues[] = {
	{"G2FX_USE_ZOOM", (int64_t)(1)},
	{"G2FX_USE_ALPHA_FADE", (int64_t)(2)},
};
static const Han2EnumValue kGof2MoveFlagsValues[] = {
	{"G2MOVE_CLEAR_VEL_X", (int64_t)(1)},
	{"G2MOVE_CLEAR_VEL_Y", (int64_t)(2)},
	{"G2MOVE_ADD_X", (int64_t)(4)},
	{"G2MOVE_ADD_Y", (int64_t)(8)},
};
static const Han2EnumValue kGof2StanceClassValues[] = {
	{"G2STANCE_NONE", (int64_t)(0)},
	{"G2STANCE_GROUND", (int64_t)(1)},
	{"G2STANCE_CROUCH", (int64_t)(2)},
	{"G2STANCE_AIR", (int64_t)(4)},
};
static const Han2EnumValue kGof2CancelPermissionValues[] = {
	{"G2CANCEL_NONE", (int64_t)(0)},
	{"G2CANCEL_ON_INPUT_MATCH", (int64_t)(1)},
	{"G2CANCEL_ALWAYS", (int64_t)(2)},
};
static const Han2EnumValue kGof2AttackEventFlagsValues[] = {
	{"G2ATKEV_BEGIN", (int64_t)(1)},
	{"G2ATKEV_END", (int64_t)(2)},
	{"G2ATKEV_ETC_BEGIN", (int64_t)(4)},
	{"G2ATKEV_ETC_END", (int64_t)(8)},
	{"G2ATKEV_KEEP_HIT_MEMORY", (int64_t)(0x10)},
	{"G2ATKEV_SOUSAI_BEGIN", (int64_t)(0x20)},
	{"G2ATKEV_SOUSAI_END", (int64_t)(0x40)},
};
static const Han2EnumValue kGof2HurtMaskFlagsValues[] = {
	{"G2HMF_KEEP_NO_BIT8", (int64_t)(0x100)},
	{"G2HMF_SET_BIT9", (int64_t)(0x200)},
	{"G2HMF_NO_CLASS_0", (int64_t)(0x10000)},
	{"G2HMF_NO_CLASS_1", (int64_t)(0x20000)},
	{"G2HMF_NO_CLASS_2", (int64_t)(0x40000)},
	{"G2HMF_NO_CLASS_3", (int64_t)(0x80000)},
	{"G2HMF_NO_CLASS_4", (int64_t)(0x100000)},
	{"G2HMF_NO_CLASS_5", (int64_t)(0x400000)},
	{"G2HMF_NO_CLASS_6", (int64_t)(0x800000)},
	{"G2HMF_ANIME_FLAG_A", (int64_t)(0x1000000)},
	{"G2HMF_ANIME_FLAG_B", (int64_t)(0x2000000)},
};
static const Han2EnumValue kGof2MotionFlagsValues[] = {
	{"G2MOTF_UNREAD_BIT0", (int64_t)(1)},
	{"G2MOTF_RESET_MOVE_TRACKS", (int64_t)(2)},
	{"G2MOTF_BRAKE_ON_ENTER", (int64_t)(4)},
};
static const Han2EnumValue kGof2FacingCommandValues[] = {
	{"G2FACE_NONE", (int64_t)(0)},
	{"G2FACE_TOWARD_TARGET", (int64_t)(1)},
	{"G2FACE_AWAY_FROM_TARGET", (int64_t)(2)},
	{"G2FACE_FLIP_CURRENT", (int64_t)(3)},
	{"G2FACE_SET_DIR0", (int64_t)(4)},
	{"G2FACE_SET_DIR1", (int64_t)(5)},
	{"G2FACE_TOWARD_INPUT_DIR", (int64_t)(6)},
	{"G2FACE_AWAY_FROM_INPUT_DIR", (int64_t)(7)},
};
static const Han2EnumValue kGof2HitSuppressFlagsValues[] = {
	{"G2HITSUP_KEEP_BOX_OBJECTS", (int64_t)(0x10000000)},
};
static const Han2EnumValue kGof2ScriptOrderFlagsValues[] = {
	{"G2SCRIPTORD_LIST_A_FIRST", (int64_t)(1)},
};
static const Han2EnumValue kGof2GuardModeValues[] = {
	{"G2GUARD_NONE", (int64_t)(0)},
	{"G2GUARD_ATTACK_TYPE_BIT0", (int64_t)(1)},
	{"G2GUARD_ATTACK_TYPE_BIT1", (int64_t)(2)},
	{"G2GUARD_ANY_BOX_ATTACK", (int64_t)(3)},
	{"G2GUARD_IF_ATTACK_QUERY", (int64_t)(4)},
};
static const Han2EnumValue kGof2ArmorModeValues[] = {
	{"G2ARMOR_NONE", (int64_t)(0)},
	{"G2ARMOR_ATTACK_TYPE_BIT0_OR_BIT2", (int64_t)(1)},
	{"G2ARMOR_ATTACK_TYPE_BIT1", (int64_t)(2)},
	{"G2ARMOR_ANY", (int64_t)(3)},
};
static const Han2EnumValue kGof2Han2KindValues[] = {
	{"G2HAN2_KIND_FULL_DAT", (int64_t)(0)},
	{"G2HAN2_KIND_PATTERN_ONLY_DT2", (int64_t)(3)},
};
static const Han2EnumInfo kGof2TypesEnums[] = {
	{"Gof2AniFlag", kGof2AniFlagValues, 10, false},
	{"Gof2FlipMode", kGof2FlipModeValues, 8, false},
	{"Gof2BlendMode", kGof2BlendModeValues, 4, false},
	{"Gof2DrawStyle", kGof2DrawStyleValues, 3, false},
	{"Gof2FrameFxFlags", kGof2FrameFxFlagsValues, 2, true},
	{"Gof2MoveFlags", kGof2MoveFlagsValues, 4, true},
	{"Gof2StanceClass", kGof2StanceClassValues, 4, false},
	{"Gof2CancelPermission", kGof2CancelPermissionValues, 3, false},
	{"Gof2AttackEventFlags", kGof2AttackEventFlagsValues, 7, true},
	{"Gof2HurtMaskFlags", kGof2HurtMaskFlagsValues, 11, true},
	{"Gof2MotionFlags", kGof2MotionFlagsValues, 3, true},
	{"Gof2FacingCommand", kGof2FacingCommandValues, 8, false},
	{"Gof2HitSuppressFlags", kGof2HitSuppressFlagsValues, 1, true},
	{"Gof2ScriptOrderFlags", kGof2ScriptOrderFlagsValues, 1, true},
	{"Gof2GuardMode", kGof2GuardModeValues, 5, false},
	{"Gof2ArmorMode", kGof2ArmorModeValues, 4, false},
	{"Gof2Han2Kind", kGof2Han2KindValues, 2, false},
};

static const Han2FieldInfo kGof2FrameRecordFields[] = {
	{"spriteId", 0x0, 2, 1, 1, nullptr, "+0x00 T: CG image = id-10000 when >=10000, else PAT pose index (DrawHelper_Draw 0x49EF60, CHanteiAnime_CacheNextFrame 0x448F70, CHanteiAnime_ResolveCgImage 0x448E60)"},
	{"offsetX", 0x2, 2, 1, 1, nullptr, "+0x02 T: draw offset X (DrawHelper_Draw, DrawHelper_EmitPolygons 0x440850)"},
	{"offsetY", 0x4, 2, 1, 1, nullptr, "+0x04 T: draw offset Y (DrawHelper_Draw, DrawHelper_EmitPolygons)"},
	{"duration", 0x6, 2, 1, 0, nullptr, "+0x06 T: ticks before advance (Obj_ScriptTick 0x434AD0 compares anime ticks to it; DrawHelper_Draw uses it as the tween denominator)"},
	{"flipMode", 0x8, 1, 1, 2, "Gof2FlipMode", "+0x08 T: DrawHelper_Draw indexes the flip table dword_5A18E0[2*flipMode]"},
	{"blendMode", 0x9, 1, 1, 2, "Gof2BlendMode", "+0x09 T: Obj_ApplyFrameBlendAlphaZoom 0x435620 copies non-zero to obj+1504 (DrawSort_Run blend table dword_5A1AA4)"},
	{"alpha", 0xA, 1, 1, 0, nullptr, "+0x0A T: alpha fade target when fxFlags.USE_ALPHA_FADE (Obj_ApplyFrameBlendAlphaZoom -> obj+1072/+1076)"},
	{"aniFlag", 0xB, 1, 1, 2, "Gof2AniFlag", "+0x0B T: CHanteiAnime_StepAniFlag 0x4490A0, CHanteiAnime_CacheNextFrame 0x448F70, Obj_ScanAheadForAttackFrame 0x4324F0"},
	{"jumpTarget", 0xC, 1, 1, 0, nullptr, "+0x0C T: pattern (ANI_END_TO_PATTERN) or frame to jump to (CHanteiAnime_StepAniFlag)"},
	{"landJumpTarget", 0xD, 1, 1, 0, nullptr, "+0x0D T: Obj_ApplyLandingFrameJump 0x430A40 (frame for aniFlag 1/2, pattern for 3/4), Obj_ScanAheadForAttackFrame"},
	{"drawPriorityCode", 0xE, 1, 1, 0, nullptr, "+0x0E T: Obj_ApplyFrameDrawPriority 0x432E30 switch over codes 1..49 (1..8 add a depth step, 9..18/26..35/41..49 set depth + default layer, 19..25 and 36..40 set draw-order slots; table dword_5A2398)"},
	{"unused_0F", 0xF, 1, 1, 0, nullptr, "+0x0F U: zero in all 43991 frames, no reader of frame+15"},
	{"zoom", 0x10, 2, 1, 0, nullptr, "+0x10 T: 256 = 1.0; Obj_ApplyFrameBlendAlphaZoom copies to obj+1112 when fxFlags.USE_ZOOM"},
	{"loopCount", 0x12, 1, 1, 0, nullptr, "+0x12 T: loaded into the anime loop counter when non-zero (Obj_SetActionAndRunScript 0x431B90, Obj_ScanAheadForAttackFrame reads the low byte)"},
	{"loopEndFrame", 0x13, 1, 1, 0, nullptr, "+0x13 T: frame jumped to when the loop counter is exhausted (aniFlag 5 and 8; CHanteiAnime_StepAniFlag)"},
	{"unused_14", 0x14, 1, 4, 0, nullptr, "+0x14 U: zero in all frames, no reader"},
	{"interpolationMode", 0x18, 1, 1, 0, nullptr, "+0x18 T: non-zero = tween toward the next frame (CHanteiAnime_CacheNextFrame gate; DrawHelper_Draw -> sub_49E9A0 blend factor ticks/duration)"},
	{"fxFlags", 0x19, 1, 1, 2, "Gof2FrameFxFlags", "+0x19 T: Obj_ApplyFrameBlendAlphaZoom"},
	{"drawStyle", 0x1A, 1, 1, 2, "Gof2DrawStyle", "+0x1A I: non-zero copied to obj+1508, DrawSort_Run indexes dword_5A1AB4[style] (0/1/2 in data)"},
	{"unused_1B", 0x1B, 1, 13, 0, nullptr, "+0x1B..0x27 U: zero in all frames, no reader"},
	{"moveFlags", 0x28, 1, 1, 2, "Gof2MoveFlags", "+0x28 T: Obj_ApplyFrameMoveFlags 0x434950, Obj_ScaleVelocityOnEnterFrame 0x42EC30"},
	{"unused_29", 0x29, 1, 3, 0, nullptr, "+0x29 U: zero in all frames (the flags byte is never read as a dword), no reader"},
	{"speedX", 0x2C, 2, 1, 1, nullptr, "+0x2C T: added to velocity X when MOVE_ADD_X (Obj_ApplyFrameMoveFlags, flip-aware via facing)"},
	{"speedY", 0x2E, 2, 1, 1, nullptr, "+0x2E T: added to velocity Y when MOVE_ADD_Y"},
	{"accelX", 0x30, 2, 1, 1, nullptr, "+0x30 T: acceleration X when MOVE_ADD_X"},
	{"accelY", 0x32, 2, 1, 1, nullptr, "+0x32 T: acceleration Y when MOVE_ADD_Y"},
	{"stanceClass", 0x34, 1, 1, 2, "Gof2StanceClass", "+0x34 T: CHanteiAnime__vf0 0x448EB0 copies the dword at +0x34 to anime+44; bit 4 = airborne (sub_42ED90, HitJudge); ScriptCond_MatchStanceAndCancel 0x42F6A0 masks it"},
	{"normalCancel", 0x35, 1, 1, 2, "Gof2CancelPermission", "+0x35 T: Obj_GetNormalCancelState 0x4302E0, ScriptCond_MatchStanceAndCancel"},
	{"specialCancel", 0x36, 1, 1, 2, "Gof2CancelPermission", "+0x36 T: Obj_IsSpecialCancelAllowed 0x430120, ScriptCond_MatchStanceAndCancel"},
	{"unused_37", 0x37, 1, 1, 0, nullptr, "+0x37 U: zero in all frames, no reader"},
	{"attackEventFlags", 0x38, 1, 1, 2, "Gof2AttackEventFlags", "+0x38 T: CAppHanteiKougeki_BuildFromFrame 0x449250 (1,2,0x10), CAppHanteiEtc__vf7 0x449750 (4,8), CAppHanteiSousai__vf6 0x449820 (0x20,0x40)"},
	{"unused_39", 0x39, 1, 3, 0, nullptr, "+0x39 U: zero in all frames, no reader"},
	{"hurtMaskEnable", 0x3C, 4, 1, 0, nullptr, "+0x3C T: 0 = anime vulnerability mask forced to 0 (CHanteiAnime__vf0 0x448EB0 reads *(frame+60))"},
	{"hurtMaskFlags", 0x40, 4, 1, 2, "Gof2HurtMaskFlags", "+0x40 T: CHanteiAnime__vf0 builds anime+48 (class mask) and anime+52/+56 (flags A/B) from it"},
	{"editorOnly_44", 0x44, 4, 1, 0, nullptr, "+0x44 E: =1 in 4 of 43991 frames, no reader of frame+68"},
	{"hitLimitFlags", 0x48, 4, 1, 0, nullptr, "+0x48 T: copied to the hit limiter on ATKEV_BEGIN (CAppHanteiKougeki_BuildFromFrame reads *(frame+72)); zero in all frames"},
	{"hitLimitCount", 0x4C, 4, 1, 0, nullptr, "+0x4C T: copied to the hit limiter count (same function, *(frame+76)); zero in all frames"},
	{"editorOnly_50", 0x50, 4, 1, 0, nullptr, "+0x50 E: 0x01000000 in 10 frames and 1 in 2, no reader of frame+80"},
	{"unused_54", 0x54, 4, 1, 0, nullptr, "+0x54 U: zero in all frames, no reader"},
	{"editorOnly_58", 0x58, 4, 1, 0, nullptr, "+0x58 E: 0x01000000 in 8 frames, no reader of frame+88"},
	{"motionFlags", 0x5C, 1, 1, 2, "Gof2MotionFlags", "+0x5C T: Obj_ApplyFrameMoveFlags (&2 -> Obj_ResetMoveTracks 0x430E90), Obj_ApplyFrameBrake 0x435280 (&4)"},
	{"unused_5D", 0x5D, 1, 1, 0, nullptr, "+0x5D U: zero in all frames, no reader"},
	{"brakePercent", 0x5E, 2, 1, 1, nullptr, "+0x5E T: Obj_ApplyFrameBrake: velocity * brakePercent / -1000 (50 in 43831 frames)"},
	{"editorOnly_60", 0x60, 4, 1, 0, nullptr, "+0x60 E: 0x01000000 in 6 frames, no reader of frame+96"},
	{"facingCommand", 0x64, 4, 1, 2, "Gof2FacingCommand", "+0x64 T: Obj_ApplyFrameFacingCommand 0x43CF70 switch (1..7), Obj_ApplyFacingKind 0x43CE50"},
	{"editorOnly_68", 0x68, 4, 1, 0, nullptr, "+0x68 E: 0x01000000 in 10 frames, no reader of frame+104"},
	{"unused_6C", 0x6C, 4, 1, 0, nullptr, "+0x6C U: zero in all frames, no reader"},
	{"editorOnly_70", 0x70, 4, 1, 0, nullptr, "+0x70 E: 0x01000000 in 6 frames, no reader of frame+112"},
	{"unused_74", 0x74, 4, 1, 0, nullptr, "+0x74 U: zero in all frames, no reader"},
	{"editorOnly_78", 0x78, 4, 1, 0, nullptr, "+0x78 E: 0x01000000 in 10 frames, no reader of frame+120"},
	{"unused_7C", 0x7C, 4, 1, 0, nullptr, "+0x7C U: zero in all frames, no reader"},
	{"hitSuppressFlags", 0x80, 4, 1, 2, "Gof2HitSuppressFlags", "+0x80 T: Obj_ResetHanteiBoxObjects 0x4356A0 tests 0x10000000 (24 frames), keeps the box objects alive"},
	{"unused_84", 0x84, 4, 1, 0, nullptr, "+0x84 U: zero in all frames, no reader"},
	{"editorOnly_88", 0x88, 4, 1, 0, nullptr, "+0x88 E: 0x01000000 in 6 frames, no reader of frame+136"},
	{"unused_8C", 0x8C, 4, 1, 0, nullptr, "+0x8C U: zero in all frames, no reader"},
	{"editorOnly_90", 0x90, 4, 1, 0, nullptr, "+0x90 E: 0x01000000 in 10 frames, no reader of frame+144"},
	{"unused_94", 0x94, 4, 1, 0, nullptr, "+0x94 U: zero in all frames, no reader"},
	{"editorOnly_98", 0x98, 4, 1, 0, nullptr, "+0x98 E: 0x01000000 in 4 frames, no reader of frame+152"},
	{"unused_9C", 0x9C, 4, 1, 0, nullptr, "+0x9C U: zero in all frames, no reader"},
	{"editorOnly_A0", 0xA0, 4, 1, 0, nullptr, "+0xA0 E: 0x01000000 in 8 frames, no reader of frame+160"},
	{"unused_A4", 0xA4, 4, 1, 0, nullptr, "+0xA4 U: zero in all frames, no reader"},
	{"editorOnly_A8", 0xA8, 4, 1, 0, nullptr, "+0xA8 E: 0x01000000 in 10 frames, no reader of frame+168"},
	{"unused_AC", 0xAC, 4, 1, 0, nullptr, "+0xAC U: zero in all frames, no reader"},
	{"editorOnly_B0", 0xB0, 4, 1, 0, nullptr, "+0xB0 E: 0x01000000 in 6 frames, no reader of frame+176"},
	{"unused_B4", 0xB4, 4, 1, 0, nullptr, "+0xB4 U: zero in all frames, no reader"},
	{"scriptOrderFlags", 0xB8, 1, 1, 2, "Gof2ScriptOrderFlags", "+0xB8 T: CHanteiAnime_GetFrameScriptLists 0x449A30 returns *(frame+184)&1"},
	{"unused_B9", 0xB9, 1, 3, 0, nullptr, "+0xB9 U: zero in all frames, no reader"},
	{"scriptListIndexA", 0xBC, 4, 1, 0, nullptr, "+0xBC T: index into section 6 (20-byte script id lists, run as ScriptVm kind 0 by sub_43E1B0), 0 = none (CHanteiAnime_GetFrameScriptLists)"},
	{"scriptListIndexB", 0xC0, 4, 1, 0, nullptr, "+0xC0 T: index into section 7 (run as ScriptVm kind 1 by sub_43E030), 0 = none"},
	{"hasAttackRedundant", 0xC4, 4, 1, 0, nullptr, "+0xC4 E: 1 iff attackBoxCount>0 (1895 frames); no reader of frame+196, the engine tests attackBoxCount"},
	{"attackRecordIdx", 0xC8, 4, 1, 1, nullptr, "+0xC8 T: index into section 3 (236-byte attack records), -1 none (CAppHanteiKougeki_BuildFromFrame, ObjScan_StoreAttackGuardInfo 0x432480)"},
	{"attackScratchFill", 0xCC, 4, 7, 1, nullptr, "+0xCC E: 0xCDCDCDCD (MSVC debug fill) in the 1895 attack frames, -1 in all others; no reader of frame+204..+231"},
	{"legacyBoxGroupACount", 0xE8, 4, 1, 0, nullptr, "+0xE8 E: 0/1 (1 in 10 frames); no reader of frame+232, its slots hold stale values outside the box table numbering"},
	{"legacyBoxGroupAIdx", 0xEC, 4, 3, 1, nullptr, "+0xEC E: -1 except 10 frames (0..3); no reader"},
	{"legacyBoxGroupBCount", 0xF8, 4, 1, 0, nullptr, "+0xF8 E: 0/1 (1 in 6 frames); no reader of frame+248"},
	{"legacyBoxGroupBIdx", 0xFC, 4, 4, 1, nullptr, "+0xFC E: -1 except +0x108 in 6 frames (0/1); no reader"},
	{"kasanariBoxEnable", 0x10C, 4, 1, 0, nullptr, "+0x10C T: CAppHanteiKasanari__vf5 0x449620 gate (== number of non -1 slots)"},
	{"kasanariBoxIdx", 0x110, 4, 1, 1, nullptr, "+0x110 T: section 2 box index (single slot), -1 = empty"},
	{"hurtBoxCount", 0x114, 4, 1, 0, nullptr, "+0x114 T: CAppHanteiYarare__vf6 0x4494F0 gate"},
	{"hurtBoxIdx", 0x118, 4, 6, 1, nullptr, "+0x118 T: section 2 box indices (6 slots read by CAppHanteiYarare__vf6), -1 = empty"},
	{"editorOnly_130", 0x130, 4, 1, 0, nullptr, "+0x130 E: 6 in 42369 frames, 0 in 1622; frame+304 is the Yarare parameter block (lea in CAppHanteiYarare__vf6) but nothing reads its first dword"},
	{"guardMode", 0x134, 4, 1, 2, "Gof2GuardMode", "+0x134 I: HitJudge_DefenderGuardsAttack 0x496930 switches on *(yarare+4) = frame+308"},
	{"armorMode", 0x138, 4, 1, 2, "Gof2ArmorMode", "+0x138 I: HitJudge_DefenderArmorAbsorbs 0x497180 switches on *(yarare+4+4) = frame+312"},
	{"etcBoxCount", 0x13C, 4, 1, 0, nullptr, "+0x13C T: CAppHanteiEtc__vf7 0x449750 gate"},
	{"etcBoxIdx", 0x140, 4, 3, 1, nullptr, "+0x140 T: 3 slots read; only the first is ever used in the data"},
	{"sousaiBoxCount", 0x14C, 4, 1, 0, nullptr, "+0x14C T: CAppHanteiSousai__vf6 0x449820 gate"},
	{"sousaiBoxIdx", 0x150, 4, 3, 1, nullptr, "+0x150 T: 3 slots read, only the first is ever used"},
	{"tobiBoxCount", 0x15C, 4, 1, 0, nullptr, "+0x15C T: CAppHanteiTobi__vf6 0x449910 gate"},
	{"tobiBoxIdx", 0x160, 4, 3, 1, nullptr, "+0x160 T: 3 slots read (RBO had 4)"},
	{"attackBoxCount", 0x16C, 4, 1, 0, nullptr, "+0x16C T: CAppHanteiKougeki_BuildFromFrame gate"},
	{"attackBoxIdx", 0x170, 4, 8, 1, nullptr, "+0x170 T: 8 slots read; slots 0..4 are used in the data"},
	{"effectRecordIdx", 0x190, 4, 1, 0, nullptr, "+0x190 T: 1-based index into section 8 (96-byte records), 0 = none (Obj_SetActionAndRunScript -> Obj_SpawnFrameEffectRecord 0x4327F0)"},
};
static const Han2FieldInfo kGof2PatternEntryFields[] = {
	{"frameCount", 0x0, 4, 1, 0, nullptr, "+0x0 T: 0 = pattern absent (CHanteiAnime_CacheNextFrame, sub_4334C0 test *(pattern+12*n))"},
	{"flags", 0x4, 4, 1, 0, nullptr, "+0x4 E: zero in all 17408 entries of all 68 files; no reader of pattern+4"},
	{"firstFrameIndex", 0x8, 4, 1, 0, nullptr, "+0x8 T: index into section 1 (frames are packed in pattern order)"},
};
static const Han2FieldInfo kGof2BoxRectFields[] = {
	{"x1", 0x0, 2, 1, 1, nullptr, "+0x0 T: CAppHanteiKasanari__vf6 0x449680 etc. read four shorts (left, top, right, bottom; mirrored when facing flips)"},
	{"y1", 0x2, 2, 1, 1, nullptr, "+0x2 T: see x1"},
	{"x2", 0x4, 2, 1, 1, nullptr, "+0x4 T: see x1"},
	{"y2", 0x6, 2, 1, 1, nullptr, "+0x6 T: see x1"},
};
static const Han2FieldInfo kGof2HanteiAnimeFields[] = {
	{"vtable", 0x0, 4, 1, 4, nullptr, "+0x00 T: CHanteiAnime vftable, embedded in the 0x1264-byte Obj at +616 (Obj_ConstructPoolSlot 0x435850)"},
	{"patternNo", 0x4, 4, 1, 1, nullptr, "+0x04 T: current pattern (CHanteiAnime_CacheNextFrame)"},
	{"frameNo", 0x8, 4, 1, 1, nullptr, "+0x08 T: frame inside the pattern"},
	{"frameTicks", 0xC, 4, 1, 1, nullptr, "+0x0C T: ticks spent on the frame (Obj_ScriptTick increments, compared to frame.duration)"},
	{"loopCounter", 0x10, 4, 1, 1, nullptr, "+0x10 T: aniFlag 5/8 counter (CHanteiAnime_StepAniFlag)"},
	{"view", 0x14, 4, 1, 4, nullptr, "+0x14 T: pattern area view (obj+636 = chara record +12)"},
	{"charaRecord", 0x18, 4, 1, 4, nullptr, "+0x18 T: chara data block (obj+640, holds the PAT parts bank at +52)"},
	{"frame", 0x1C, 4, 1, 4, nullptr, "+0x1C T: current frame read by the hit-box builders (obj+644)"},
	{"frameTick", 0x20, 4, 1, 4, nullptr, "+0x20 T: same frame pointer read by the animation step and DrawHelper_Draw (obj+648)"},
	{"aniCallback", 0x24, 4, 1, 4, nullptr, "+0x24 T: int (__cdecl *)(int) predicate for aniFlag 7/9 (CHanteiAnime_StepAniFlag)"},
	{"aniCallbackArg", 0x28, 4, 1, 1, nullptr, "+0x28 T"},
	{"stanceDword", 0x2C, 4, 1, 0, nullptr, "+0x2C T: copy of frame dword +0x34 (CHanteiAnime__vf0)"},
	{"vulnerabilityMask", 0x30, 4, 1, 0, nullptr, "+0x30 T: class mask built from hurtMaskEnable/hurtMaskFlags (CHanteiAnime__vf0)"},
	{"flagA", 0x34, 4, 1, 1, nullptr, "+0x34 T: hurtMaskFlags & 0x1000000"},
	{"flagB", 0x38, 4, 1, 1, nullptr, "+0x38 T: hurtMaskFlags & 0x2000000"},
	{"nextSpriteId", 0x3C, 4, 1, 1, nullptr, "+0x3C T: sprite id of the frame after this one (CHanteiAnime_CacheNextFrame), tween target"},
	{"nextFrame", 0x40, 4, 1, 4, nullptr, "+0x40 T: frame after this one"},
};
static const Han2FieldInfo kGof2Han2AreaRefFields[] = {
	{"offset", 0x0, 4, 1, 0, nullptr, "+0x0 absolute file offset (a .DT2 keeps the .DAT's offsets for areas it does not carry)"},
	{"size", 0x4, 4, 1, 0, nullptr, "+0x4 0 = area absent"},
};
static const Han2FieldInfo kGof2Han2FileHeaderFields[] = {
	{"signature", 0x0, 1, 8, 0, nullptr, "+0x00 \"HAN2RBO \" (never checked by the game)"},
	{"kind", 0x8, 4, 1, 2, "Gof2Han2Kind", "+0x08 E: not read; 3 in all 68 GOF2 files"},
	{"unused_0C", 0xC, 4, 1, 0, nullptr, "+0x0C E: zero in all 68 files, not read"},
	{"version", 0x10, 4, 1, 0, nullptr, "+0x10 E: 2 in all files, not read"},
	{"unused_14", 0x14, 4, 1, 0, nullptr, "+0x14 E: zero in all files, not read"},
	{"subVersion", 0x18, 4, 1, 0, nullptr, "+0x18 E: 2 = GOF2 layout (404-byte frames, 9 sections); not read by the game"},
	{"xorFlag", 0x1C, 4, 1, 0, nullptr, "+0x1C T: non-zero = header + sections 0..5 are XOR-obfuscated (State0_4_NextFile -> Gof2_XorDecryptBuffer); 0 in every shipped file"},
	{"patternArea", 0x20, 8, 1, 4, nullptr, "+0x20 T: read by State0_1 into a1[11..12], the area is loaded by State0_2 (AllocateAndReadFileData(path, offset, size))"},
	{"partsPat", 0x28, 8, 1, 4, nullptr, "+0x28 T: PAT parts bank, always from the .DAT (a1[13..14] -> chara block +52/+56)"},
	{"cgBank", 0x30, 8, 1, 4, nullptr, "+0x30 T: BMP Cutter3 bank, always from the .DAT"},
	{"patternNames", 0x38, 8, 1, 4, nullptr, "+0x38 E: 256 x 64-byte CP932 pattern names; editor data, not read"},
};
static const Han2FieldInfo kGof2PatternAreaHeaderFields[] = {
	{"mustBeZero_00", 0x0, 4, 1, 0, nullptr, "+0x00 V: must be 0 (State0_4_NextFile aborts the load otherwise)"},
	{"mustBeEight_04", 0x4, 4, 1, 0, nullptr, "+0x04 V: must be 8 (RBO stores 3 here)"},
	{"mustBeZero_08", 0x8, 4, 1, 0, nullptr, "+0x08 V: must be 0"},
	{"mustBeFive_0C", 0xC, 4, 1, 0, nullptr, "+0x0C V: must be 5 (RBO stores 1)"},
	{"mustBeZero_10", 0x10, 4, 4, 0, nullptr, "+0x10 V: +0x10..0x1F must be 0"},
	{"editorMark_20", 0x20, 4, 1, 0, nullptr, "+0x20 E: 1 in all 68 files, not validated or read"},
	{"unused_24", 0x24, 4, 3, 0, nullptr, "+0x24 E: zero in all files, not read"},
	{"sectionSize", 0x30, 4, 9, 0, nullptr, "+0x30 T: section byte sizes (Gof2PatternArea_ComputeSectionPointers reads a2[12..20]); 0 = absent"},
	{"unused_54", 0x54, 4, 3, 0, nullptr, "+0x54 E: zero in all files, not read"},
};
static const Han2FieldInfo kGof2PatternAreaViewFields[] = {
	{"base", 0x0, 4, 1, 4, nullptr, "+0x00 T: GlobalAlloc block holding the whole pattern area"},
	{"patterns", 0x4, 4, 1, 4, nullptr, "+0x04 T: section 0, 256 x 12 bytes (CHanteiAnime_CacheNextFrame: 12*pattern + patterns)"},
	{"frames", 0x8, 4, 1, 4, nullptr, "+0x08 T: section 1, 404-byte records (frames + 404*(first+frameNo))"},
	{"boxes", 0xC, 4, 1, 4, nullptr, "+0x0C T: section 2, 8-byte rectangles (CAppHanteiKougeki_BuildFromFrame: boxes + 8*idx)"},
	{"attackRecords", 0x10, 4, 1, 4, nullptr, "+0x10 T: section 3, 236-byte attack records (boxes' owner data: attackRecords + 236*frame.attackRecordIdx)"},
	{"section4", 0x14, 4, 1, 4, nullptr, "+0x14 E: section 4 (28-byte records inferred from sizes 28/56/112), no reader of view+20"},
	{"section5", 0x18, 4, 1, 4, nullptr, "+0x18 E: section 5 (20-byte records inferred from sizes 20/40), no reader of view+24"},
	{"scriptListsA", 0x1C, 4, 1, 4, nullptr, "+0x1C T: section 6, 20-byte lists of 5 script ids, ScriptVm kind 0 (CHanteiAnime_GetFrameScriptLists)"},
	{"scriptListsB", 0x20, 4, 1, 4, nullptr, "+0x20 T: section 7, 20-byte lists of 5 script ids, ScriptVm kind 1"},
	{"effectRecords", 0x24, 4, 1, 4, nullptr, "+0x24 T: section 8, 96-byte records (Obj_SetActionAndRunScript: view+36 + 96*frame.effectRecordIdx -> Obj_SpawnFrameEffectRecord)"},
};
static const Han2FieldInfo kGof2CharaDataBlockFields[] = {
	{"reserved_00", 0x0, 4, 1, 0, nullptr, "+0x00 T: record+4, not touched by the pattern-area loader"},
	{"xorFlag", 0x4, 4, 1, 0, nullptr, "+0x04 T: copy of file header xorFlag (State0_1_LoadPATandCHPFiles)"},
	{"view", 0x8, 40, 1, 4, nullptr, "+0x08 T: filled by Gof2PatternArea_ComputeSectionPointers(&container+8, header)"},
	{"reserved_30", 0x30, 4, 1, 0, nullptr, "+0x30 T: not touched by the pattern-area loader"},
	{"partsPatOffset", 0x34, 4, 1, 0, nullptr, "+0x34 T: file offset of the PAT parts bank (sub_447B70 stores header partsPat.offset)"},
	{"partsPatSize", 0x38, 4, 1, 0, nullptr, "+0x38 T: PAT bank size; the PAT section is outside this task (poseIndex table starts at +0x44)"},
};
