// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"

enum QohTileXform : uint8_t {
	QXF_IDENTITY = 0,
	QXF_ROT_90_CW = 1,
	QXF_ROT_180 = 2,
	QXF_ROT_90_CCW = 3,
	QXF_FLIP_H = 4,
	QXF_TRANSPOSE = 5,
	QXF_FLIP_V = 6,
	QXF_ANTI_TRANSPOSE = 7,
};
enum QohFrameMoveFlags : uint8_t {
	QFM_SET_X_ACCEL = 1,
	QFM_SET_Y_ACCEL = 2,
	QFM_ON_LAND_JUMP_TO_FRAME = 4,
};
enum QohFrameFxFlags : uint32_t {
	QFX_SOUND_SLOT_MASK = 31,
	QFX_SOUND_BANK_MASK = 192,
	QFX_SPAWN_FX_1 = 65536,
	QFX_HIT_DAMAGE_PHASE0 = 131072,
	QFX_SET_SCREEN_MODE_4 = 262144,
	QFX_CLEAR_COMBO_STATE = 524288,
	QFX_SPAWN_FX_2 = 2097152,
	QFX_KO_EFFECT = 4194304,
	QFX_POSITIONED_FX = 8388608,
	QFX_HIT_DAMAGE_PHASE1 = 16777216,
};
enum QohAttackFlags : uint8_t {
	QAF_DAMAGING_HIT = 1,
};
enum QohFileKind : uint32_t {
	QFK_CHARACTER_SLOT_FIRST = 0,
	QFK_CHARACTER_SLOT_LAST = 36,
	QFK_OBJ1 = 37,
	QFK_RINA_CRA = 38,
};

#pragma pack(push, 1)
struct QohChrHeader {
	char nameBlock[16];  // +0x00 T: stem of the file name (upper-case) XOR runtime key PRIM_RT; the loader decodes it and compares it with the stem of the requested path (ValidateAndDecryptFileHeader 0x42C1F0)
	uint32_t revisionStamp;  // +0x10 T/D: high 16 bits = per-file revision compared with g_file_type_checksums[fileKind] by ValidateAndDecryptFileHeader (D: 0 for 24 files, 1 for 9, 2 for Corin, Kaede and Tiria, 5 for Yosie); low 16 bits = 0x000C in all 37 files (X)
	uint32_t imageCount;  // +0x14 T: c0 -> assets.imageCount; 12-byte image records
	uint32_t tileCount;  // +0x18 T: c1 -> assets.tileCount; 260-byte tiles
	uint32_t actionCount;  // +0x1C T: c2 -> assets.actionCount; 24-byte action records (256 in all 37 files)
	uint32_t frameCount;  // +0x20 T: c3 -> assets.frameCount; 64-byte frames
	uint32_t boxCount;  // +0x24 T: c4 -> assets.boxCount; 8-byte boxes
	uint32_t attackCount;  // +0x28 T: c5 -> assets.attackCount; 24-byte attack records
};
struct QohImageRecord {
	uint32_t firstTile;  // +0x00 T: first tile index (D: ranges are contiguous from 0 and sum to tileCount in every file)
	uint32_t tileCount;  // +0x04 T: number of tiles drawn for the image (D: 0 for 31 images)
	uint16_t width;  // +0x08 T: canvas width, passed to the sprite queue (D: 256 in 6923 records, 320 in the 15 O_Chizuru full-screen records)
	uint16_t height;  // +0x0A T: canvas height (D: 256, or 240 with width 320)
};
struct QohTile {
	uint16_t x;  // +0x00 T: column of the block inside the image canvas (D: multiple of 16, <= 240)
	uint16_t y;  // +0x02 T: row of the block (D: multiple of 16, <= 240)
	uint8_t pixels[256];  // +0x04 T: 16x16 palette indices, row-major (D: all values 0..15; 0 = transparent)
};
struct QohPaletteEntry {
	uint8_t blue;  // +0x00 T
	uint8_t green;  // +0x01 T
	uint8_t red;  // +0x02 T
	uint8_t reserved;  // +0x03 D: 0 in every entry of every file
};
struct QohChrPalette {
	QohPaletteEntry entries[256];  // +0x00 T: 16 banks of 16 colours (tile pixels 0..15 select a colour inside a bank; the bank is chosen at draw time)
};
struct QohAction {
	int32_t firstFrame;  // +0x00 T: index of the first frame, -1 = action unused (HandleCharacterMovement resets the actor to action 0) (D: ranges tile [0,frameCount) exactly in every file)
	int32_t frameCount;  // +0x04 T: frames in the action; the step code resets the frame cursor to 0 when frameCount < nextFrameIndex
	int32_t firstBox;  // +0x08 T: base index into the box table; frame.bodyBoxIndex/hurtBoxFirst/guardBoxFirst are offsets from it; -1 when none
	int32_t boxCount;  // +0x0C X/D: upper bound of the box offsets+counts of the action frames (violated only by 0xFF sentinels); never read
	int32_t firstAttack;  // +0x10 T: base index into the attack table; frame.attackFirst is an offset from it; -1 when none
	int32_t attackCount;  // +0x14 X/D: upper bound of the attack offsets+counts of the action frames; never read
};
struct QohFrame {
	int32_t imageIndex;  // +0x00 T: index into the image table; out of range draws nothing (GetAnimationFrameData)
	int16_t drawX;  // +0x04 T: x offset of the 256x256 canvas relative to the actor position (negated when facing left)
	int16_t drawY;  // +0x06 T: y offset (the shadow pass divides it by 3)
	int32_t duration;  // +0x08 T: copied to actor.frameTimer (D: 231 occurs 3290 times, values up to 400+)
	uint16_t nextFrame;  // +0x0C T: frame index inside the action that follows; 0xFFFF = frame+1, 0xFFFE = action ends and holds (actor.nextFrameIndex = 0xFFFE) (D: otherwise < action.frameCount except 4 frames)
	uint16_t attackLevelAndFlags;  // +0x0E T: low nibble -> actor.attackLevel; bit 0x10 arms the attack boxes (contactFlags |= 1, attackHitMask = 0xFF); bit 0x20 tested by the hit code (marks the opponent contactFlags |= 0x10)
	uint8_t moveFlags;  // +0x10 T: QohFrameMoveFlags (1 = load x accel/jerk, 2 = load y accel/jerk, 4 = on landing jump to frame landFrame)
	uint8_t clearVelX;  // +0x11 T: non-zero zeroes actor.velX
	uint8_t clearVelY;  // +0x12 T: non-zero zeroes actor.velY
	uint8_t xAccelAbsolute;  // +0x13 T: copied to actor.xAccelAbsolute (non-zero: velX is clamped to a sign change instead of free integration)
	uint8_t yAccelAbsolute;  // +0x14 T/D: copied to actor.yAccelAbsolute; 0 in all files
	uint8_t tileXform;  // +0x15 T: QohTileXform (D: values 0..7)
	uint8_t landFrame;  // +0x16 T: frame index entered on landing when moveFlags & 4 (actor.nextFrameIndex = this, else 0xFFFE)
	uint8_t bodyBoxIndex;  // +0x17 T: body (push) box, offset from action.firstBox; used for screen-edge / push alignment (CalculateCollisionBounds)
	uint8_t bodyBoxMode;  // +0x18 T: 0 or 0xFF = no body box (the actor is skipped by the camera / push code); otherwise 1 (D: 31383 of 40452 frames are 1)
	uint8_t hurtBoxFirst;  // +0x19 T: first vulnerable box, offset from action.firstBox
	uint8_t hurtBoxCount;  // +0x1A T: number of vulnerable boxes; 0 = cannot be hit
	uint8_t unused_1B;  // +0x1B D: 0 in all frames of all files, no reader
	uint8_t unused_1C;  // +0x1C D: 0 in all frames of all files, no reader
	uint8_t guardBoxFirst;  // +0x1D T: first projectile-guard box, offset from action.firstBox (CheckProjectileVsGuardBoxCollision)
	uint8_t guardBoxCount;  // +0x1E T: number of guard boxes; non-zero sets contactFlags |= 2 and guardHitMask = 0xFF
	uint8_t attackFirst;  // +0x1F T: first attack record, offset from action.firstAttack
	uint8_t attackCount;  // +0x20 T: number of attack records; 0 = none; 0xFF = special hit 1 (returns -1), 0xFE = special hit 2 (ProcessCharacterHitDetectionAndDamage)
	uint8_t stanceBits;  // +0x21 T: copied whole to actor.stanceBits (low 3 bits = stance class, 0x40 = turn toward the nearest opponent, 0x20/0x80 read by the hit code)
	int16_t xAccel;  // +0x22 T: actor.accelX when moveFlags & 1 (negated when facing left)
	int16_t yAccel;  // +0x24 T: actor.accelY when moveFlags & 2
	int16_t xJerk;  // +0x26 T: actor.jerkX when moveFlags & 1
	int16_t yJerk;  // +0x28 T: actor.jerkY when moveFlags & 2
	uint8_t unused_2A;  // +0x2A D: 0xCD (build fill) in 26694 frames, else 0; no reader
	uint8_t unused_2B;  // +0x2B D: same as unused_2A
	int32_t aiMoveClass;  // +0x2C T: copied to actor.aiMoveClass, read by the CPU player (D: 0..11 observed)
	uint32_t fxFlags;  // +0x30 T: QohFrameFxFlags; byte +0x31 is additionally read as a second sound id (QueueNetworkEventAndSound)
	uint32_t drawClass;  // +0x34 T: & 3 stored in actor.drawClass (D: 0, 1 or 3)
	uint8_t flickerFlags;  // +0x38 T: bit 0 = draw only every second tick (RenderCharacterSprite) (D: 0 or 1)
	uint8_t unused_39[7];  // +0x39 D: 0 in all frames of all files, no reader
};
struct QohBox {
	int16_t left;  // +0x00 T
	int16_t top;  // +0x02 T
	int16_t right;  // +0x04 T
	int16_t bottom;  // +0x06 T: D: right/bottom ranges are pixel offsets, bottom up to 215+
};
struct QohAttack {
	int16_t left;  // +0x00 T
	int16_t top;  // +0x02 T
	int16_t right;  // +0x04 T
	int16_t bottom;  // +0x06 T
	int16_t damage;  // +0x08 T: life removed (<= 0: no damage hit)
	int16_t unresolved_0A;  // +0x0A U/D: 34 non-zero values (1, 3, 4, 5, 10); no reader found
	int16_t guardDamage;  // +0x0C T: subtracted from the defender guard gauge on a guarded hit (ProcessCharacterBlockAndCounterAttack)
	int16_t meterGain;  // +0x0E T: passed to ManagePlayerSuperMeterGauge (attacker super gauge gain)
	uint8_t flags;  // +0x10 T: QohAttackFlags (bit 0 = damaging hit; tested with hitClass 10/11 when the defender is in state 1)
	uint8_t guardMask;  // +0x11 T: bit0/1/2 = which guard postures (defender state 7.. variants) may block it (ProcessCharacterBlockAndCounterAttack)
	uint8_t hitClass;  // +0x12 T: 0..15; 0..9 and 12 select the defender reaction pose, 10 and 11 special (action 36 / 35), 13..15 projectile clash rules
	uint8_t unresolved_13;  // +0x13 U/D: 0 in all but one record (value 68); no reader found
	uint16_t knockMode;  // +0x14 T: bits 0..1 -> defender.hitFacingMode (1 = turn the defender away); bit 2 / bit 3 tested in the hit code; the whole word is returned to the caller
	uint16_t hitEffectFlags;  // +0x16 T: bits 12..15 = screen flash type (SetScreenFlashEffectByHitType); bit 0 set in 3000 of 4733 records (U)
};
struct QohCharAssets {
	uint32_t tiles;  // +0x00 T: 260 * tileCount
	int32_t tileCount;  // +0x04 T: header c1
	uint32_t images;  // +0x08 T: 12 * imageCount
	int32_t imageCount;  // +0x0C T: header c0
	uint32_t actions;  // +0x10 T: 24 * actionCount
	int32_t actionCount;  // +0x14 T: header c2
	uint32_t frames;  // +0x18 T: 64 * frameCount
	int32_t frameCount;  // +0x1C T: header c3
	uint32_t boxes;  // +0x20 T: 8 * boxCount
	int32_t boxCount;  // +0x24 T: header c4
	uint32_t attacks;  // +0x28 T: 24 * attackCount
	int32_t attackCount;  // +0x2C T: header c5
};
struct QohTrailEntry {
	int32_t posX;  // +0x00 T
	int32_t posY;  // +0x04 T
	int32_t actionIndex;  // +0x08 T
	int32_t frameIndex;  // +0x0C T
	int32_t frameTimer;  // +0x10 T
	uint8_t facing;  // +0x14 T
	uint8_t stanceBits;  // +0x15 T
	int16_t impulseX;  // +0x16 T: restored to actor+108 by the partner copy
	int16_t impulseY;  // +0x18 T: actor+110
	int16_t impulseAccelX;  // +0x1A T: actor+112
	int16_t impulseAccelY;  // +0x1C T: actor+114
	int16_t impulseJerkX;  // +0x1E T: actor+116
	int16_t impulseJerkY;  // +0x20 T: actor+118
	uint8_t unresolved_22[2];  // +0x22 U: not accessed
};
struct QohCommandChild {
	uint8_t unresolved_00[4];  // +0x00 U: not accessed by any traced code path (see doc)
	int32_t resetMarker;  // +0x04 T: set to -1 when the actor buffer is re-initialised (InitializeCharacterBuffer)
	uint32_t dirRingValues[32];  // +0x08 T: direction history, masked & 0xF0000
	uint32_t dirRingHold[32];  // +0x88 T: hold counters
	uint8_t dirRingHead;  // +0x108 T: index, & 0x1F
	uint8_t unresolved_109[3];  // +0x109 U: not accessed by any traced code path (see doc)
	uint32_t btnRingValues[16];  // +0x10C T: button history, masked & 0xF
	uint32_t btnRingHold[16];  // +0x14C T: hold counters
	uint8_t btnRingHead;  // +0x18C T: index, & 0xF
	uint8_t unresolved_18D[15];  // +0x18D U: not accessed by any traced code path (see doc)
	int16_t resetMarker2;  // +0x19C T: set to -1 when the actor buffer is re-initialised
	uint8_t unresolved_19E[18];  // +0x19E U: not accessed by any traced code path (see doc)
	int32_t directionKill;  // +0x1B0 T: suppresses recorded directions across a native round transition; cleared on re-initialisation
	uint8_t unresolved_1B4[76];  // +0x1B4 U: not accessed
};
struct QohActor {
	QohCharAssets assets;  // +0x00 T: loaded .chr tables (pointers masked by the savestate)
	int32_t actionIndex;  // +0x30 T: current action id (index into assets.actions)
	int32_t nextFrameIndex;  // +0x34 T: frame to enter when frameTimer reaches 0; 65534 = hold the last frame (UpdateCharacterLogic marks animEnded)
	int32_t frameTimer;  // +0x38 T: ticks left in the frame, set from frame.duration; HandleCharacterMovement steps the animation when 0
	int32_t unresolved_3C;  // +0x3C U: not accessed
	int32_t frameIndex;  // +0x40 T: current frame inside the action (frame = assets.frames[action.firstFrame + frameIndex])
	int32_t unresolved_44;  // +0x44 U: not accessed
	int32_t requestedAction;  // +0x48 T: action the input state machine wants (written with requestFlag)
	int32_t requestFlag;  // +0x4C T: 1 = a transition request is pending
	int32_t unresolved_50;  // +0x50 U
	int32_t dispatchAction;  // +0x54 T: copy of the forced action taken by UpdateCharacterAnimation
	int32_t animEnded;  // +0x58 T: -1 reset marker, 1 = the action ran out (UpdateCharacterLogic)
	int32_t forcedAction;  // +0x5C T: action forced by the hit / engine code, -1 = none
	int16_t velX;  // +0x60 T: 8.8 fixed point, integrated by UpdateCharacterLogic
	int16_t velY;  // +0x62 T
	int16_t accelX;  // +0x64 T: added to velX each tick; loaded from frame.xAccel
	int16_t accelY;  // +0x66 T: loaded from frame.yAccel
	int16_t jerkX;  // +0x68 T: added to accelX; loaded from frame.xJerk
	int16_t jerkY;  // +0x6A T: loaded from frame.yJerk
	int16_t impulseX;  // +0x6C T: second x group (knock back); cleared by the hit code
	int16_t impulseY;  // +0x6E T
	int16_t impulseAccelX;  // +0x70 T
	int16_t impulseAccelY;  // +0x72 T
	int16_t impulseJerkX;  // +0x74 T
	int16_t impulseJerkY;  // +0x76 T
	int16_t slideVelX;  // +0x78 T: third x group with a countdown
	int16_t unresolved_7A;  // +0x7A U: not touched by UpdateCharacterLogic
	int16_t slideAccelX;  // +0x7C T
	int16_t unresolved_7E;  // +0x7E U
	int16_t slideJerkX;  // +0x80 T
	int16_t unresolved_82;  // +0x82 U
	int16_t slideTimer;  // +0x84 T: decremented each tick while non-zero
	int16_t unresolved_86;  // +0x86 U
	int32_t posX;  // +0x88 T: world x of the anchor; boxes are relative to it
	int32_t posY;  // +0x8C T: world y
	int32_t unresolved_90;  // +0x90 U
	int32_t unresolved_94;  // +0x94 U
	int32_t unresolved_98;  // +0x98 T: written by AutoFlipCharacterFacing, meaning unresolved
	uint8_t stanceBits;  // +0x9C T: frame.stanceBits copy (low nibble posture, bits 4..7 behaviour)
	uint8_t reactionHeight;  // +0x9D T: 0/1/2 written by the hit code (high / mid / low reaction)
	uint16_t attackLevel;  // +0x9E T: frame.attackLevelAndFlags & 0xF
	uint16_t contactFlags;  // +0xA0 T: bit0 = attack boxes armed (THE active latch, set from frame bit 0x10, survives later frames), bit1 = guard boxes present, bit4 set by the hit code
	uint8_t attackHitMask;  // +0xA2 T: bit n = player slot n may still be hit by the current attack; reset to 0xFF when the attack arms
	uint8_t guardHitMask;  // +0xA3 T: same for guard boxes
	uint32_t commandChild;  // +0xA4 T: input history object
	uint8_t xAccelAbsolute;  // +0xA8 T: frame.xAccelAbsolute
	uint8_t yAccelAbsolute;  // +0xA9 T: frame.yAccelAbsolute
	uint8_t facing;  // +0xAA T: 0 = faces right, 1 = faces left
	uint8_t team;  // +0xAB T: owning team / EX owner index (NOT the slot)
	uint8_t playerSlot;  // +0xAC T: player slot 0..3
	uint8_t playerSlotCopy;  // +0xAD T: equals playerSlot after InitializeCharacterBuffer
	uint8_t entityKind;  // +0xAE T: 0xFF = free pool slot; otherwise the state machine selector of InitializeCharacterAnimationFrame
	uint8_t paletteEntryBase;  // +0xAF T: palette entry index of the actor 16-colour bank (added to paletteTable as 4 * value by the renderers; saved/restored across the actor reset)
	uint8_t hitAttrib;  // +0xB0 T: set to 9 by the hit code
	uint8_t hitDirection;  // +0xB1 T: relative direction of the last hit
	uint8_t unresolved_B2[2];  // +0xB2 U: not accessed by any traced code path (see doc)
	int32_t unresolved_B4;  // +0xB4 T: ProcessCharacterAttackSequence
	int32_t unresolved_B8;  // +0xB8 T
	int32_t unresolved_BC;  // +0xBC T
	int32_t unresolved_C0;  // +0xC0 T
	int32_t unresolved_C4;  // +0xC4 T: 17 written by ProcessCharacterCollisionAndStates
	int32_t unresolved_C8;  // +0xC8 T
	uint8_t stateNibbles;  // +0xCC T: low/high nibble state bits (&0xF0 / &0xF), cleared with stateFlags
	uint8_t unresolved_CD[3];  // +0xCD U: not accessed by any traced code path (see doc)
	uint32_t stateFlags;  // +0xD0 T: 0x10000 = capture a pose snapshot into trail[0]; low byte cleared by the hit code
	int32_t tagTimer;  // +0xD4 T: counts down while the partner is tagged in (clears stateFlags bit 8 at 0)
	QohTrailEntry trail[30];  // +0xD8 T: pose history
	int32_t pendingHitDamage;  // +0x510 T: damage event consumed (and cleared) at the end of ProcessCharacterAnimationAndState
	int32_t lastHitPacked;  // +0x514 T: (hitTag << 4) | stance bits & 7 of the last hit
	int32_t lastHitStance;  // +0x518 T: defender stance bits & 7 at the last hit
	int32_t lastHitSlot;  // +0x51C T: player slot of the attacker of the last hit
	int32_t prevPosX;  // +0x520 T: previous x (ResolveCharacterPushCollision)
	int32_t unresolved_524;  // +0x524 T: InitializeSpecialSuperState165
	int32_t unresolved_528;  // +0x528 T: 0/1 flag written by spawn code
	uint32_t updateCallback;  // +0x52C T: code pointer, set to UpdateProjectileFromParentCharacter for parented projectiles
	int32_t unresolved_530;  // +0x530 T
	uint8_t unresolved_534[4];  // +0x534 U: not accessed by any traced code path (see doc)
	int32_t hitPendingFlags;  // +0x538 T: bit0 = normal hit pending, bit1 = guarded hit pending (HandleCharacterMovement)
	int32_t unresolved_53C;  // +0x53C T
	int32_t unresolved_540;  // +0x540 T: 4800 written by the Akari special state
	uint8_t unresolved_544[4];  // +0x544 U: not accessed by any traced code path (see doc)
	int32_t unresolved_548;  // +0x548 T: 10 written by the transition code
	uint8_t unresolved_54C[4];  // +0x54C U: not accessed by any traced code path (see doc)
	int32_t hitFacingMode;  // +0x550 T: attack.knockMode & 3 of the last hit (1 = turn away, 2 = zero the knock back)
	int32_t roundEndFlag;  // +0x554 T
	int32_t roundLostFlag;  // +0x558 T
	uint8_t unresolved_55C[4];  // +0x55C U: not accessed by any traced code path (see doc)
	int32_t fatalCause;  // +0x560 T: -1 at round start
	uint8_t unresolved_564[4];  // +0x564 U: not accessed by any traced code path (see doc)
	uint8_t unresolved_568;  // +0x568 T
	uint8_t unresolved_569;  // +0x569 T
	uint8_t landingMode;  // +0x56A T: 0 = normal landing at y == 0, 2 = KO bounce test (UpdateCharacterLogic)
	uint8_t unresolved_56B[1];  // +0x56B U: not accessed by any traced code path (see doc)
	uint16_t unresolved_56C;  // +0x56C T: non-zero stops projectile reflection
	uint16_t wallFlags;  // +0x56E T: screen-edge contact flags (UpdateCameraPositionWithClampingAndSmoothing)
	int32_t lastDamageResult;  // +0x570 T: result of CalculateDamageWithModifiers stashed on the defender
	int32_t unresolved_574;  // +0x574 T
	int32_t engineOwned;  // +0x578 T: != 0 means the engine owns this actor
	int32_t facingSnapshot;  // +0x57C T: facing copy compared on the next frame
	int32_t actionSnapshot;  // +0x580 T
	int32_t frameSnapshot;  // +0x584 T
	uint32_t paletteTable;  // +0x588 T: the player palette (256 entries, g_actor_palette_p1..p4) the renderers index with paletteEntryBase
	uint8_t unresolved_58C[4];  // +0x58C U: not accessed by any traced code path (see doc)
	uint16_t pendingDamageBonus;  // +0x590 T: added to pendingHitDamage
	uint16_t pendingDamagePenalty;  // +0x592 T: subtracted from pendingHitDamage
	int32_t subState;  // +0x594 T: state machine sub step, written by the Initialize*State functions
	uint32_t currentFrame;  // +0x598 T: frame pointer recomputed by HandleCharacterMovement every tick
	uint32_t lastContactActor;  // +0x59C T: the other party of the last hit (attacker for a defender, victim for an attacker)
	int32_t unresolved_5A0;  // +0x5A0 T
	int32_t unresolved_5A4;  // +0x5A4 T
	int32_t unresolved_5A8;  // +0x5A8 T
	int32_t unresolved_5AC;  // +0x5AC T
	int32_t formMode;  // +0x5B0 T: 1/2 = alternate form participating (hit code treats the partner as part of the actor), 2/3/4 per adapter
	uint8_t unresolved_5B4[4];  // +0x5B4 U: not accessed by any traced code path (see doc)
	int32_t unresolved_5B8;  // +0x5B8 T: set to 1 by the hit code
	int32_t unresolved_5BC;  // +0x5BC T: set to 1 by the hit code
	uint8_t unresolved_5C0[4];  // +0x5C0 U: not accessed by any traced code path (see doc)
	int32_t unresolved_5C4;  // +0x5C4 T: bit 1 halves incoming damage in the hit code
	int32_t unresolved_5C8;  // +0x5C8 T: set to 1 by ProcessCharacterAnimationAndState
	int32_t drawClass;  // +0x5CC T: frame.drawClass & 3
	int32_t unresolved_5D0;  // +0x5D0 T: 3 at spawn
	int32_t unresolved_5D4;  // +0x5D4 T
	int32_t unresolved_5D8;  // +0x5D8 T
	int32_t hitstopFrames;  // +0x5DC T: while non-zero the pose timers are frozen
	int32_t unresolved_5E0;  // +0x5E0 T
	uint8_t unresolved_5E4[8];  // +0x5E4 U: not accessed by any traced code path (see doc)
	int32_t ownerSlotCache;  // +0x5EC T: slot index of the owning player (ProcessCharacterCollisionAndStates)
	int32_t unresolved_5F0;  // +0x5F0 T: 1 at spawn
	int32_t aiMoveClass;  // +0x5F4 T: frame.aiMoveClass copy
	int32_t terminalReady;  // +0x5F8 T: written 0/1 by the transition code
};
struct QohFobFunc {
	char name[32];  // +0x00 T/D: NUL terminated; the bytes after the NUL are uninitialised build garbage (D: "1", "Mizuho_Idou", "Mizuho_Idou2")
	uint32_t entryPc;  // +0x20 T: byte offset into the code block (D: always an instruction start)
};
struct QohScriptBank {
	char path[260];  // +0x00 T: upper-cased path used as the cache key
	uint32_t code;  // +0x104 T: code block (codeSize + 2 zero bytes); 0 = slot free
	int32_t funcCount;  // +0x108 T: nFuncs
	uint32_t funcs;  // +0x10C T: 36 * nFuncs
};
struct QohImgHeader {
	uint32_t reserved;  // +0x00 T/D: read and (optionally) returned, 0 in all 553 files
	uint32_t paletteEntries;  // +0x04 T: 4 bytes each (blue, green, red, 0); 0 = 24-bit image
	uint32_t bitsPerPixel;  // +0x08 T/D: 4, 8 or 24 (24 only with paletteEntries == 0)
	uint32_t width;  // +0x0C T
	uint32_t height;  // +0x10 T
};
struct QohFobVmHead {
	uint8_t unresolved_00[4];  // +0x00 U: not accessed by any traced code path (see doc)
	int32_t currentLine;  // +0x04 T: written by opcode 0x3C (source line marker), printed in the "ScriptUnknown Code" error
	uint8_t unresolved_08[8];  // +0x08 U: not accessed
};
struct QohFobVmState {
	int32_t stackDepth;  // +0x00 T: index of the top of the value stack (0 = empty; pushes pre-increment; limit 0x10000)
	int32_t activeBank;  // +0x04 T: index of the running QohScriptBank
	uint32_t codeBase;  // +0x08 T: code of the running bank; the pc is a byte offset into it
	uint8_t unresolved_0C[20];  // +0x0C U: not accessed
};
#pragma pack(pop)

static_assert(sizeof(QohChrHeader) == 0x2C, "QohChrHeader size");
static_assert(offsetof(QohChrHeader, nameBlock) == 0x0, "QohChrHeader.nameBlock");
static_assert(offsetof(QohChrHeader, revisionStamp) == 0x10, "QohChrHeader.revisionStamp");
static_assert(offsetof(QohChrHeader, imageCount) == 0x14, "QohChrHeader.imageCount");
static_assert(offsetof(QohChrHeader, tileCount) == 0x18, "QohChrHeader.tileCount");
static_assert(offsetof(QohChrHeader, actionCount) == 0x1C, "QohChrHeader.actionCount");
static_assert(offsetof(QohChrHeader, frameCount) == 0x20, "QohChrHeader.frameCount");
static_assert(offsetof(QohChrHeader, boxCount) == 0x24, "QohChrHeader.boxCount");
static_assert(offsetof(QohChrHeader, attackCount) == 0x28, "QohChrHeader.attackCount");
static_assert(sizeof(QohImageRecord) == 0xC, "QohImageRecord size");
static_assert(offsetof(QohImageRecord, firstTile) == 0x0, "QohImageRecord.firstTile");
static_assert(offsetof(QohImageRecord, tileCount) == 0x4, "QohImageRecord.tileCount");
static_assert(offsetof(QohImageRecord, width) == 0x8, "QohImageRecord.width");
static_assert(offsetof(QohImageRecord, height) == 0xA, "QohImageRecord.height");
static_assert(sizeof(QohTile) == 0x104, "QohTile size");
static_assert(offsetof(QohTile, x) == 0x0, "QohTile.x");
static_assert(offsetof(QohTile, y) == 0x2, "QohTile.y");
static_assert(offsetof(QohTile, pixels) == 0x4, "QohTile.pixels");
static_assert(sizeof(QohPaletteEntry) == 0x4, "QohPaletteEntry size");
static_assert(offsetof(QohPaletteEntry, blue) == 0x0, "QohPaletteEntry.blue");
static_assert(offsetof(QohPaletteEntry, green) == 0x1, "QohPaletteEntry.green");
static_assert(offsetof(QohPaletteEntry, red) == 0x2, "QohPaletteEntry.red");
static_assert(offsetof(QohPaletteEntry, reserved) == 0x3, "QohPaletteEntry.reserved");
static_assert(sizeof(QohChrPalette) == 0x400, "QohChrPalette size");
static_assert(offsetof(QohChrPalette, entries) == 0x0, "QohChrPalette.entries");
static_assert(sizeof(QohAction) == 0x18, "QohAction size");
static_assert(offsetof(QohAction, firstFrame) == 0x0, "QohAction.firstFrame");
static_assert(offsetof(QohAction, frameCount) == 0x4, "QohAction.frameCount");
static_assert(offsetof(QohAction, firstBox) == 0x8, "QohAction.firstBox");
static_assert(offsetof(QohAction, boxCount) == 0xC, "QohAction.boxCount");
static_assert(offsetof(QohAction, firstAttack) == 0x10, "QohAction.firstAttack");
static_assert(offsetof(QohAction, attackCount) == 0x14, "QohAction.attackCount");
static_assert(sizeof(QohFrame) == 0x40, "QohFrame size");
static_assert(offsetof(QohFrame, imageIndex) == 0x0, "QohFrame.imageIndex");
static_assert(offsetof(QohFrame, drawX) == 0x4, "QohFrame.drawX");
static_assert(offsetof(QohFrame, drawY) == 0x6, "QohFrame.drawY");
static_assert(offsetof(QohFrame, duration) == 0x8, "QohFrame.duration");
static_assert(offsetof(QohFrame, nextFrame) == 0xC, "QohFrame.nextFrame");
static_assert(offsetof(QohFrame, attackLevelAndFlags) == 0xE, "QohFrame.attackLevelAndFlags");
static_assert(offsetof(QohFrame, moveFlags) == 0x10, "QohFrame.moveFlags");
static_assert(offsetof(QohFrame, clearVelX) == 0x11, "QohFrame.clearVelX");
static_assert(offsetof(QohFrame, clearVelY) == 0x12, "QohFrame.clearVelY");
static_assert(offsetof(QohFrame, xAccelAbsolute) == 0x13, "QohFrame.xAccelAbsolute");
static_assert(offsetof(QohFrame, yAccelAbsolute) == 0x14, "QohFrame.yAccelAbsolute");
static_assert(offsetof(QohFrame, tileXform) == 0x15, "QohFrame.tileXform");
static_assert(offsetof(QohFrame, landFrame) == 0x16, "QohFrame.landFrame");
static_assert(offsetof(QohFrame, bodyBoxIndex) == 0x17, "QohFrame.bodyBoxIndex");
static_assert(offsetof(QohFrame, bodyBoxMode) == 0x18, "QohFrame.bodyBoxMode");
static_assert(offsetof(QohFrame, hurtBoxFirst) == 0x19, "QohFrame.hurtBoxFirst");
static_assert(offsetof(QohFrame, hurtBoxCount) == 0x1A, "QohFrame.hurtBoxCount");
static_assert(offsetof(QohFrame, unused_1B) == 0x1B, "QohFrame.unused_1B");
static_assert(offsetof(QohFrame, unused_1C) == 0x1C, "QohFrame.unused_1C");
static_assert(offsetof(QohFrame, guardBoxFirst) == 0x1D, "QohFrame.guardBoxFirst");
static_assert(offsetof(QohFrame, guardBoxCount) == 0x1E, "QohFrame.guardBoxCount");
static_assert(offsetof(QohFrame, attackFirst) == 0x1F, "QohFrame.attackFirst");
static_assert(offsetof(QohFrame, attackCount) == 0x20, "QohFrame.attackCount");
static_assert(offsetof(QohFrame, stanceBits) == 0x21, "QohFrame.stanceBits");
static_assert(offsetof(QohFrame, xAccel) == 0x22, "QohFrame.xAccel");
static_assert(offsetof(QohFrame, yAccel) == 0x24, "QohFrame.yAccel");
static_assert(offsetof(QohFrame, xJerk) == 0x26, "QohFrame.xJerk");
static_assert(offsetof(QohFrame, yJerk) == 0x28, "QohFrame.yJerk");
static_assert(offsetof(QohFrame, unused_2A) == 0x2A, "QohFrame.unused_2A");
static_assert(offsetof(QohFrame, unused_2B) == 0x2B, "QohFrame.unused_2B");
static_assert(offsetof(QohFrame, aiMoveClass) == 0x2C, "QohFrame.aiMoveClass");
static_assert(offsetof(QohFrame, fxFlags) == 0x30, "QohFrame.fxFlags");
static_assert(offsetof(QohFrame, drawClass) == 0x34, "QohFrame.drawClass");
static_assert(offsetof(QohFrame, flickerFlags) == 0x38, "QohFrame.flickerFlags");
static_assert(offsetof(QohFrame, unused_39) == 0x39, "QohFrame.unused_39");
static_assert(sizeof(QohBox) == 0x8, "QohBox size");
static_assert(offsetof(QohBox, left) == 0x0, "QohBox.left");
static_assert(offsetof(QohBox, top) == 0x2, "QohBox.top");
static_assert(offsetof(QohBox, right) == 0x4, "QohBox.right");
static_assert(offsetof(QohBox, bottom) == 0x6, "QohBox.bottom");
static_assert(sizeof(QohAttack) == 0x18, "QohAttack size");
static_assert(offsetof(QohAttack, left) == 0x0, "QohAttack.left");
static_assert(offsetof(QohAttack, top) == 0x2, "QohAttack.top");
static_assert(offsetof(QohAttack, right) == 0x4, "QohAttack.right");
static_assert(offsetof(QohAttack, bottom) == 0x6, "QohAttack.bottom");
static_assert(offsetof(QohAttack, damage) == 0x8, "QohAttack.damage");
static_assert(offsetof(QohAttack, unresolved_0A) == 0xA, "QohAttack.unresolved_0A");
static_assert(offsetof(QohAttack, guardDamage) == 0xC, "QohAttack.guardDamage");
static_assert(offsetof(QohAttack, meterGain) == 0xE, "QohAttack.meterGain");
static_assert(offsetof(QohAttack, flags) == 0x10, "QohAttack.flags");
static_assert(offsetof(QohAttack, guardMask) == 0x11, "QohAttack.guardMask");
static_assert(offsetof(QohAttack, hitClass) == 0x12, "QohAttack.hitClass");
static_assert(offsetof(QohAttack, unresolved_13) == 0x13, "QohAttack.unresolved_13");
static_assert(offsetof(QohAttack, knockMode) == 0x14, "QohAttack.knockMode");
static_assert(offsetof(QohAttack, hitEffectFlags) == 0x16, "QohAttack.hitEffectFlags");
static_assert(sizeof(QohCharAssets) == 0x30, "QohCharAssets size");
static_assert(offsetof(QohCharAssets, tiles) == 0x0, "QohCharAssets.tiles");
static_assert(offsetof(QohCharAssets, tileCount) == 0x4, "QohCharAssets.tileCount");
static_assert(offsetof(QohCharAssets, images) == 0x8, "QohCharAssets.images");
static_assert(offsetof(QohCharAssets, imageCount) == 0xC, "QohCharAssets.imageCount");
static_assert(offsetof(QohCharAssets, actions) == 0x10, "QohCharAssets.actions");
static_assert(offsetof(QohCharAssets, actionCount) == 0x14, "QohCharAssets.actionCount");
static_assert(offsetof(QohCharAssets, frames) == 0x18, "QohCharAssets.frames");
static_assert(offsetof(QohCharAssets, frameCount) == 0x1C, "QohCharAssets.frameCount");
static_assert(offsetof(QohCharAssets, boxes) == 0x20, "QohCharAssets.boxes");
static_assert(offsetof(QohCharAssets, boxCount) == 0x24, "QohCharAssets.boxCount");
static_assert(offsetof(QohCharAssets, attacks) == 0x28, "QohCharAssets.attacks");
static_assert(offsetof(QohCharAssets, attackCount) == 0x2C, "QohCharAssets.attackCount");
static_assert(sizeof(QohTrailEntry) == 0x24, "QohTrailEntry size");
static_assert(offsetof(QohTrailEntry, posX) == 0x0, "QohTrailEntry.posX");
static_assert(offsetof(QohTrailEntry, posY) == 0x4, "QohTrailEntry.posY");
static_assert(offsetof(QohTrailEntry, actionIndex) == 0x8, "QohTrailEntry.actionIndex");
static_assert(offsetof(QohTrailEntry, frameIndex) == 0xC, "QohTrailEntry.frameIndex");
static_assert(offsetof(QohTrailEntry, frameTimer) == 0x10, "QohTrailEntry.frameTimer");
static_assert(offsetof(QohTrailEntry, facing) == 0x14, "QohTrailEntry.facing");
static_assert(offsetof(QohTrailEntry, stanceBits) == 0x15, "QohTrailEntry.stanceBits");
static_assert(offsetof(QohTrailEntry, impulseX) == 0x16, "QohTrailEntry.impulseX");
static_assert(offsetof(QohTrailEntry, impulseY) == 0x18, "QohTrailEntry.impulseY");
static_assert(offsetof(QohTrailEntry, impulseAccelX) == 0x1A, "QohTrailEntry.impulseAccelX");
static_assert(offsetof(QohTrailEntry, impulseAccelY) == 0x1C, "QohTrailEntry.impulseAccelY");
static_assert(offsetof(QohTrailEntry, impulseJerkX) == 0x1E, "QohTrailEntry.impulseJerkX");
static_assert(offsetof(QohTrailEntry, impulseJerkY) == 0x20, "QohTrailEntry.impulseJerkY");
static_assert(offsetof(QohTrailEntry, unresolved_22) == 0x22, "QohTrailEntry.unresolved_22");
static_assert(sizeof(QohCommandChild) == 0x200, "QohCommandChild size");
static_assert(offsetof(QohCommandChild, unresolved_00) == 0x0, "QohCommandChild.unresolved_00");
static_assert(offsetof(QohCommandChild, resetMarker) == 0x4, "QohCommandChild.resetMarker");
static_assert(offsetof(QohCommandChild, dirRingValues) == 0x8, "QohCommandChild.dirRingValues");
static_assert(offsetof(QohCommandChild, dirRingHold) == 0x88, "QohCommandChild.dirRingHold");
static_assert(offsetof(QohCommandChild, dirRingHead) == 0x108, "QohCommandChild.dirRingHead");
static_assert(offsetof(QohCommandChild, unresolved_109) == 0x109, "QohCommandChild.unresolved_109");
static_assert(offsetof(QohCommandChild, btnRingValues) == 0x10C, "QohCommandChild.btnRingValues");
static_assert(offsetof(QohCommandChild, btnRingHold) == 0x14C, "QohCommandChild.btnRingHold");
static_assert(offsetof(QohCommandChild, btnRingHead) == 0x18C, "QohCommandChild.btnRingHead");
static_assert(offsetof(QohCommandChild, unresolved_18D) == 0x18D, "QohCommandChild.unresolved_18D");
static_assert(offsetof(QohCommandChild, resetMarker2) == 0x19C, "QohCommandChild.resetMarker2");
static_assert(offsetof(QohCommandChild, unresolved_19E) == 0x19E, "QohCommandChild.unresolved_19E");
static_assert(offsetof(QohCommandChild, directionKill) == 0x1B0, "QohCommandChild.directionKill");
static_assert(offsetof(QohCommandChild, unresolved_1B4) == 0x1B4, "QohCommandChild.unresolved_1B4");
static_assert(sizeof(QohActor) == 0x5FC, "QohActor size");
static_assert(offsetof(QohActor, assets) == 0x0, "QohActor.assets");
static_assert(offsetof(QohActor, actionIndex) == 0x30, "QohActor.actionIndex");
static_assert(offsetof(QohActor, nextFrameIndex) == 0x34, "QohActor.nextFrameIndex");
static_assert(offsetof(QohActor, frameTimer) == 0x38, "QohActor.frameTimer");
static_assert(offsetof(QohActor, unresolved_3C) == 0x3C, "QohActor.unresolved_3C");
static_assert(offsetof(QohActor, frameIndex) == 0x40, "QohActor.frameIndex");
static_assert(offsetof(QohActor, unresolved_44) == 0x44, "QohActor.unresolved_44");
static_assert(offsetof(QohActor, requestedAction) == 0x48, "QohActor.requestedAction");
static_assert(offsetof(QohActor, requestFlag) == 0x4C, "QohActor.requestFlag");
static_assert(offsetof(QohActor, unresolved_50) == 0x50, "QohActor.unresolved_50");
static_assert(offsetof(QohActor, dispatchAction) == 0x54, "QohActor.dispatchAction");
static_assert(offsetof(QohActor, animEnded) == 0x58, "QohActor.animEnded");
static_assert(offsetof(QohActor, forcedAction) == 0x5C, "QohActor.forcedAction");
static_assert(offsetof(QohActor, velX) == 0x60, "QohActor.velX");
static_assert(offsetof(QohActor, velY) == 0x62, "QohActor.velY");
static_assert(offsetof(QohActor, accelX) == 0x64, "QohActor.accelX");
static_assert(offsetof(QohActor, accelY) == 0x66, "QohActor.accelY");
static_assert(offsetof(QohActor, jerkX) == 0x68, "QohActor.jerkX");
static_assert(offsetof(QohActor, jerkY) == 0x6A, "QohActor.jerkY");
static_assert(offsetof(QohActor, impulseX) == 0x6C, "QohActor.impulseX");
static_assert(offsetof(QohActor, impulseY) == 0x6E, "QohActor.impulseY");
static_assert(offsetof(QohActor, impulseAccelX) == 0x70, "QohActor.impulseAccelX");
static_assert(offsetof(QohActor, impulseAccelY) == 0x72, "QohActor.impulseAccelY");
static_assert(offsetof(QohActor, impulseJerkX) == 0x74, "QohActor.impulseJerkX");
static_assert(offsetof(QohActor, impulseJerkY) == 0x76, "QohActor.impulseJerkY");
static_assert(offsetof(QohActor, slideVelX) == 0x78, "QohActor.slideVelX");
static_assert(offsetof(QohActor, unresolved_7A) == 0x7A, "QohActor.unresolved_7A");
static_assert(offsetof(QohActor, slideAccelX) == 0x7C, "QohActor.slideAccelX");
static_assert(offsetof(QohActor, unresolved_7E) == 0x7E, "QohActor.unresolved_7E");
static_assert(offsetof(QohActor, slideJerkX) == 0x80, "QohActor.slideJerkX");
static_assert(offsetof(QohActor, unresolved_82) == 0x82, "QohActor.unresolved_82");
static_assert(offsetof(QohActor, slideTimer) == 0x84, "QohActor.slideTimer");
static_assert(offsetof(QohActor, unresolved_86) == 0x86, "QohActor.unresolved_86");
static_assert(offsetof(QohActor, posX) == 0x88, "QohActor.posX");
static_assert(offsetof(QohActor, posY) == 0x8C, "QohActor.posY");
static_assert(offsetof(QohActor, unresolved_90) == 0x90, "QohActor.unresolved_90");
static_assert(offsetof(QohActor, unresolved_94) == 0x94, "QohActor.unresolved_94");
static_assert(offsetof(QohActor, unresolved_98) == 0x98, "QohActor.unresolved_98");
static_assert(offsetof(QohActor, stanceBits) == 0x9C, "QohActor.stanceBits");
static_assert(offsetof(QohActor, reactionHeight) == 0x9D, "QohActor.reactionHeight");
static_assert(offsetof(QohActor, attackLevel) == 0x9E, "QohActor.attackLevel");
static_assert(offsetof(QohActor, contactFlags) == 0xA0, "QohActor.contactFlags");
static_assert(offsetof(QohActor, attackHitMask) == 0xA2, "QohActor.attackHitMask");
static_assert(offsetof(QohActor, guardHitMask) == 0xA3, "QohActor.guardHitMask");
static_assert(offsetof(QohActor, commandChild) == 0xA4, "QohActor.commandChild");
static_assert(offsetof(QohActor, xAccelAbsolute) == 0xA8, "QohActor.xAccelAbsolute");
static_assert(offsetof(QohActor, yAccelAbsolute) == 0xA9, "QohActor.yAccelAbsolute");
static_assert(offsetof(QohActor, facing) == 0xAA, "QohActor.facing");
static_assert(offsetof(QohActor, team) == 0xAB, "QohActor.team");
static_assert(offsetof(QohActor, playerSlot) == 0xAC, "QohActor.playerSlot");
static_assert(offsetof(QohActor, playerSlotCopy) == 0xAD, "QohActor.playerSlotCopy");
static_assert(offsetof(QohActor, entityKind) == 0xAE, "QohActor.entityKind");
static_assert(offsetof(QohActor, paletteEntryBase) == 0xAF, "QohActor.paletteEntryBase");
static_assert(offsetof(QohActor, hitAttrib) == 0xB0, "QohActor.hitAttrib");
static_assert(offsetof(QohActor, hitDirection) == 0xB1, "QohActor.hitDirection");
static_assert(offsetof(QohActor, unresolved_B2) == 0xB2, "QohActor.unresolved_B2");
static_assert(offsetof(QohActor, unresolved_B4) == 0xB4, "QohActor.unresolved_B4");
static_assert(offsetof(QohActor, unresolved_B8) == 0xB8, "QohActor.unresolved_B8");
static_assert(offsetof(QohActor, unresolved_BC) == 0xBC, "QohActor.unresolved_BC");
static_assert(offsetof(QohActor, unresolved_C0) == 0xC0, "QohActor.unresolved_C0");
static_assert(offsetof(QohActor, unresolved_C4) == 0xC4, "QohActor.unresolved_C4");
static_assert(offsetof(QohActor, unresolved_C8) == 0xC8, "QohActor.unresolved_C8");
static_assert(offsetof(QohActor, stateNibbles) == 0xCC, "QohActor.stateNibbles");
static_assert(offsetof(QohActor, unresolved_CD) == 0xCD, "QohActor.unresolved_CD");
static_assert(offsetof(QohActor, stateFlags) == 0xD0, "QohActor.stateFlags");
static_assert(offsetof(QohActor, tagTimer) == 0xD4, "QohActor.tagTimer");
static_assert(offsetof(QohActor, trail) == 0xD8, "QohActor.trail");
static_assert(offsetof(QohActor, pendingHitDamage) == 0x510, "QohActor.pendingHitDamage");
static_assert(offsetof(QohActor, lastHitPacked) == 0x514, "QohActor.lastHitPacked");
static_assert(offsetof(QohActor, lastHitStance) == 0x518, "QohActor.lastHitStance");
static_assert(offsetof(QohActor, lastHitSlot) == 0x51C, "QohActor.lastHitSlot");
static_assert(offsetof(QohActor, prevPosX) == 0x520, "QohActor.prevPosX");
static_assert(offsetof(QohActor, unresolved_524) == 0x524, "QohActor.unresolved_524");
static_assert(offsetof(QohActor, unresolved_528) == 0x528, "QohActor.unresolved_528");
static_assert(offsetof(QohActor, updateCallback) == 0x52C, "QohActor.updateCallback");
static_assert(offsetof(QohActor, unresolved_530) == 0x530, "QohActor.unresolved_530");
static_assert(offsetof(QohActor, unresolved_534) == 0x534, "QohActor.unresolved_534");
static_assert(offsetof(QohActor, hitPendingFlags) == 0x538, "QohActor.hitPendingFlags");
static_assert(offsetof(QohActor, unresolved_53C) == 0x53C, "QohActor.unresolved_53C");
static_assert(offsetof(QohActor, unresolved_540) == 0x540, "QohActor.unresolved_540");
static_assert(offsetof(QohActor, unresolved_544) == 0x544, "QohActor.unresolved_544");
static_assert(offsetof(QohActor, unresolved_548) == 0x548, "QohActor.unresolved_548");
static_assert(offsetof(QohActor, unresolved_54C) == 0x54C, "QohActor.unresolved_54C");
static_assert(offsetof(QohActor, hitFacingMode) == 0x550, "QohActor.hitFacingMode");
static_assert(offsetof(QohActor, roundEndFlag) == 0x554, "QohActor.roundEndFlag");
static_assert(offsetof(QohActor, roundLostFlag) == 0x558, "QohActor.roundLostFlag");
static_assert(offsetof(QohActor, unresolved_55C) == 0x55C, "QohActor.unresolved_55C");
static_assert(offsetof(QohActor, fatalCause) == 0x560, "QohActor.fatalCause");
static_assert(offsetof(QohActor, unresolved_564) == 0x564, "QohActor.unresolved_564");
static_assert(offsetof(QohActor, unresolved_568) == 0x568, "QohActor.unresolved_568");
static_assert(offsetof(QohActor, unresolved_569) == 0x569, "QohActor.unresolved_569");
static_assert(offsetof(QohActor, landingMode) == 0x56A, "QohActor.landingMode");
static_assert(offsetof(QohActor, unresolved_56B) == 0x56B, "QohActor.unresolved_56B");
static_assert(offsetof(QohActor, unresolved_56C) == 0x56C, "QohActor.unresolved_56C");
static_assert(offsetof(QohActor, wallFlags) == 0x56E, "QohActor.wallFlags");
static_assert(offsetof(QohActor, lastDamageResult) == 0x570, "QohActor.lastDamageResult");
static_assert(offsetof(QohActor, unresolved_574) == 0x574, "QohActor.unresolved_574");
static_assert(offsetof(QohActor, engineOwned) == 0x578, "QohActor.engineOwned");
static_assert(offsetof(QohActor, facingSnapshot) == 0x57C, "QohActor.facingSnapshot");
static_assert(offsetof(QohActor, actionSnapshot) == 0x580, "QohActor.actionSnapshot");
static_assert(offsetof(QohActor, frameSnapshot) == 0x584, "QohActor.frameSnapshot");
static_assert(offsetof(QohActor, paletteTable) == 0x588, "QohActor.paletteTable");
static_assert(offsetof(QohActor, unresolved_58C) == 0x58C, "QohActor.unresolved_58C");
static_assert(offsetof(QohActor, pendingDamageBonus) == 0x590, "QohActor.pendingDamageBonus");
static_assert(offsetof(QohActor, pendingDamagePenalty) == 0x592, "QohActor.pendingDamagePenalty");
static_assert(offsetof(QohActor, subState) == 0x594, "QohActor.subState");
static_assert(offsetof(QohActor, currentFrame) == 0x598, "QohActor.currentFrame");
static_assert(offsetof(QohActor, lastContactActor) == 0x59C, "QohActor.lastContactActor");
static_assert(offsetof(QohActor, unresolved_5A0) == 0x5A0, "QohActor.unresolved_5A0");
static_assert(offsetof(QohActor, unresolved_5A4) == 0x5A4, "QohActor.unresolved_5A4");
static_assert(offsetof(QohActor, unresolved_5A8) == 0x5A8, "QohActor.unresolved_5A8");
static_assert(offsetof(QohActor, unresolved_5AC) == 0x5AC, "QohActor.unresolved_5AC");
static_assert(offsetof(QohActor, formMode) == 0x5B0, "QohActor.formMode");
static_assert(offsetof(QohActor, unresolved_5B4) == 0x5B4, "QohActor.unresolved_5B4");
static_assert(offsetof(QohActor, unresolved_5B8) == 0x5B8, "QohActor.unresolved_5B8");
static_assert(offsetof(QohActor, unresolved_5BC) == 0x5BC, "QohActor.unresolved_5BC");
static_assert(offsetof(QohActor, unresolved_5C0) == 0x5C0, "QohActor.unresolved_5C0");
static_assert(offsetof(QohActor, unresolved_5C4) == 0x5C4, "QohActor.unresolved_5C4");
static_assert(offsetof(QohActor, unresolved_5C8) == 0x5C8, "QohActor.unresolved_5C8");
static_assert(offsetof(QohActor, drawClass) == 0x5CC, "QohActor.drawClass");
static_assert(offsetof(QohActor, unresolved_5D0) == 0x5D0, "QohActor.unresolved_5D0");
static_assert(offsetof(QohActor, unresolved_5D4) == 0x5D4, "QohActor.unresolved_5D4");
static_assert(offsetof(QohActor, unresolved_5D8) == 0x5D8, "QohActor.unresolved_5D8");
static_assert(offsetof(QohActor, hitstopFrames) == 0x5DC, "QohActor.hitstopFrames");
static_assert(offsetof(QohActor, unresolved_5E0) == 0x5E0, "QohActor.unresolved_5E0");
static_assert(offsetof(QohActor, unresolved_5E4) == 0x5E4, "QohActor.unresolved_5E4");
static_assert(offsetof(QohActor, ownerSlotCache) == 0x5EC, "QohActor.ownerSlotCache");
static_assert(offsetof(QohActor, unresolved_5F0) == 0x5F0, "QohActor.unresolved_5F0");
static_assert(offsetof(QohActor, aiMoveClass) == 0x5F4, "QohActor.aiMoveClass");
static_assert(offsetof(QohActor, terminalReady) == 0x5F8, "QohActor.terminalReady");
static_assert(sizeof(QohFobFunc) == 0x24, "QohFobFunc size");
static_assert(offsetof(QohFobFunc, name) == 0x0, "QohFobFunc.name");
static_assert(offsetof(QohFobFunc, entryPc) == 0x20, "QohFobFunc.entryPc");
static_assert(sizeof(QohScriptBank) == 0x110, "QohScriptBank size");
static_assert(offsetof(QohScriptBank, path) == 0x0, "QohScriptBank.path");
static_assert(offsetof(QohScriptBank, code) == 0x104, "QohScriptBank.code");
static_assert(offsetof(QohScriptBank, funcCount) == 0x108, "QohScriptBank.funcCount");
static_assert(offsetof(QohScriptBank, funcs) == 0x10C, "QohScriptBank.funcs");
static_assert(sizeof(QohImgHeader) == 0x14, "QohImgHeader size");
static_assert(offsetof(QohImgHeader, reserved) == 0x0, "QohImgHeader.reserved");
static_assert(offsetof(QohImgHeader, paletteEntries) == 0x4, "QohImgHeader.paletteEntries");
static_assert(offsetof(QohImgHeader, bitsPerPixel) == 0x8, "QohImgHeader.bitsPerPixel");
static_assert(offsetof(QohImgHeader, width) == 0xC, "QohImgHeader.width");
static_assert(offsetof(QohImgHeader, height) == 0x10, "QohImgHeader.height");
static_assert(sizeof(QohFobVmHead) == 0x10, "QohFobVmHead size");
static_assert(offsetof(QohFobVmHead, unresolved_00) == 0x0, "QohFobVmHead.unresolved_00");
static_assert(offsetof(QohFobVmHead, currentLine) == 0x4, "QohFobVmHead.currentLine");
static_assert(offsetof(QohFobVmHead, unresolved_08) == 0x8, "QohFobVmHead.unresolved_08");
static_assert(sizeof(QohFobVmState) == 0x20, "QohFobVmState size");
static_assert(offsetof(QohFobVmState, stackDepth) == 0x0, "QohFobVmState.stackDepth");
static_assert(offsetof(QohFobVmState, activeBank) == 0x4, "QohFobVmState.activeBank");
static_assert(offsetof(QohFobVmState, codeBase) == 0x8, "QohFobVmState.codeBase");
static_assert(offsetof(QohFobVmState, unresolved_0C) == 0xC, "QohFobVmState.unresolved_0C");

static const Han2EnumValue kQohTileXformValues[] = {
	{"QXF_IDENTITY", (int64_t)(0)},
	{"QXF_ROT_90_CW", (int64_t)(1)},
	{"QXF_ROT_180", (int64_t)(2)},
	{"QXF_ROT_90_CCW", (int64_t)(3)},
	{"QXF_FLIP_H", (int64_t)(4)},
	{"QXF_TRANSPOSE", (int64_t)(5)},
	{"QXF_FLIP_V", (int64_t)(6)},
	{"QXF_ANTI_TRANSPOSE", (int64_t)(7)},
};
static const Han2EnumValue kQohFrameMoveFlagsValues[] = {
	{"QFM_SET_X_ACCEL", (int64_t)(1)},
	{"QFM_SET_Y_ACCEL", (int64_t)(2)},
	{"QFM_ON_LAND_JUMP_TO_FRAME", (int64_t)(4)},
};
static const Han2EnumValue kQohFrameFxFlagsValues[] = {
	{"QFX_SOUND_SLOT_MASK", (int64_t)(31)},
	{"QFX_SOUND_BANK_MASK", (int64_t)(192)},
	{"QFX_SPAWN_FX_1", (int64_t)(65536)},
	{"QFX_HIT_DAMAGE_PHASE0", (int64_t)(131072)},
	{"QFX_SET_SCREEN_MODE_4", (int64_t)(262144)},
	{"QFX_CLEAR_COMBO_STATE", (int64_t)(524288)},
	{"QFX_SPAWN_FX_2", (int64_t)(2097152)},
	{"QFX_KO_EFFECT", (int64_t)(4194304)},
	{"QFX_POSITIONED_FX", (int64_t)(8388608)},
	{"QFX_HIT_DAMAGE_PHASE1", (int64_t)(16777216)},
};
static const Han2EnumValue kQohAttackFlagsValues[] = {
	{"QAF_DAMAGING_HIT", (int64_t)(1)},
};
static const Han2EnumValue kQohFileKindValues[] = {
	{"QFK_CHARACTER_SLOT_FIRST", (int64_t)(0)},
	{"QFK_CHARACTER_SLOT_LAST", (int64_t)(36)},
	{"QFK_OBJ1", (int64_t)(37)},
	{"QFK_RINA_CRA", (int64_t)(38)},
};
static const Han2EnumInfo kQoh99TypesEnums[] = {
	{"QohTileXform", kQohTileXformValues, 8, false},
	{"QohFrameMoveFlags", kQohFrameMoveFlagsValues, 3, true},
	{"QohFrameFxFlags", kQohFrameFxFlagsValues, 10, true},
	{"QohAttackFlags", kQohAttackFlagsValues, 1, true},
	{"QohFileKind", kQohFileKindValues, 4, false},
};

static const Han2FieldInfo kQohChrHeaderFields[] = {
	{"nameBlock", 0x0, 1, 16, 5, nullptr, "+0x00 T: stem of the file name (upper-case) XOR runtime key PRIM_RT; the loader decodes it and compares it with the stem of the requested path (ValidateAndDecryptFileHeader 0x42C1F0)"},
	{"revisionStamp", 0x10, 4, 1, 0, nullptr, "+0x10 T/D: high 16 bits = per-file revision compared with g_file_type_checksums[fileKind] by ValidateAndDecryptFileHeader (D: 0 for 24 files, 1 for 9, 2 for Corin, Kaede and Tiria, 5 for Yosie); low 16 bits = 0x000C in all 37 files (X)"},
	{"imageCount", 0x14, 4, 1, 0, nullptr, "+0x14 T: c0 -> assets.imageCount; 12-byte image records"},
	{"tileCount", 0x18, 4, 1, 0, nullptr, "+0x18 T: c1 -> assets.tileCount; 260-byte tiles"},
	{"actionCount", 0x1C, 4, 1, 0, nullptr, "+0x1C T: c2 -> assets.actionCount; 24-byte action records (256 in all 37 files)"},
	{"frameCount", 0x20, 4, 1, 0, nullptr, "+0x20 T: c3 -> assets.frameCount; 64-byte frames"},
	{"boxCount", 0x24, 4, 1, 0, nullptr, "+0x24 T: c4 -> assets.boxCount; 8-byte boxes"},
	{"attackCount", 0x28, 4, 1, 0, nullptr, "+0x28 T: c5 -> assets.attackCount; 24-byte attack records"},
};
static const Han2FieldInfo kQohImageRecordFields[] = {
	{"firstTile", 0x0, 4, 1, 0, nullptr, "+0x00 T: first tile index (D: ranges are contiguous from 0 and sum to tileCount in every file)"},
	{"tileCount", 0x4, 4, 1, 0, nullptr, "+0x04 T: number of tiles drawn for the image (D: 0 for 31 images)"},
	{"width", 0x8, 2, 1, 0, nullptr, "+0x08 T: canvas width, passed to the sprite queue (D: 256 in 6923 records, 320 in the 15 O_Chizuru full-screen records)"},
	{"height", 0xA, 2, 1, 0, nullptr, "+0x0A T: canvas height (D: 256, or 240 with width 320)"},
};
static const Han2FieldInfo kQohTileFields[] = {
	{"x", 0x0, 2, 1, 0, nullptr, "+0x00 T: column of the block inside the image canvas (D: multiple of 16, <= 240)"},
	{"y", 0x2, 2, 1, 0, nullptr, "+0x02 T: row of the block (D: multiple of 16, <= 240)"},
	{"pixels", 0x4, 1, 256, 0, nullptr, "+0x04 T: 16x16 palette indices, row-major (D: all values 0..15; 0 = transparent)"},
};
static const Han2FieldInfo kQohPaletteEntryFields[] = {
	{"blue", 0x0, 1, 1, 0, nullptr, "+0x00 T"},
	{"green", 0x1, 1, 1, 0, nullptr, "+0x01 T"},
	{"red", 0x2, 1, 1, 0, nullptr, "+0x02 T"},
	{"reserved", 0x3, 1, 1, 0, nullptr, "+0x03 D: 0 in every entry of every file"},
};
static const Han2FieldInfo kQohChrPaletteFields[] = {
	{"entries", 0x0, 4, 256, 4, nullptr, "+0x00 T: 16 banks of 16 colours (tile pixels 0..15 select a colour inside a bank; the bank is chosen at draw time)"},
};
static const Han2FieldInfo kQohActionFields[] = {
	{"firstFrame", 0x0, 4, 1, 1, nullptr, "+0x00 T: index of the first frame, -1 = action unused (HandleCharacterMovement resets the actor to action 0) (D: ranges tile [0,frameCount) exactly in every file)"},
	{"frameCount", 0x4, 4, 1, 1, nullptr, "+0x04 T: frames in the action; the step code resets the frame cursor to 0 when frameCount < nextFrameIndex"},
	{"firstBox", 0x8, 4, 1, 1, nullptr, "+0x08 T: base index into the box table; frame.bodyBoxIndex/hurtBoxFirst/guardBoxFirst are offsets from it; -1 when none"},
	{"boxCount", 0xC, 4, 1, 1, nullptr, "+0x0C X/D: upper bound of the box offsets+counts of the action frames (violated only by 0xFF sentinels); never read"},
	{"firstAttack", 0x10, 4, 1, 1, nullptr, "+0x10 T: base index into the attack table; frame.attackFirst is an offset from it; -1 when none"},
	{"attackCount", 0x14, 4, 1, 1, nullptr, "+0x14 X/D: upper bound of the attack offsets+counts of the action frames; never read"},
};
static const Han2FieldInfo kQohFrameFields[] = {
	{"imageIndex", 0x0, 4, 1, 1, nullptr, "+0x00 T: index into the image table; out of range draws nothing (GetAnimationFrameData)"},
	{"drawX", 0x4, 2, 1, 1, nullptr, "+0x04 T: x offset of the 256x256 canvas relative to the actor position (negated when facing left)"},
	{"drawY", 0x6, 2, 1, 1, nullptr, "+0x06 T: y offset (the shadow pass divides it by 3)"},
	{"duration", 0x8, 4, 1, 1, nullptr, "+0x08 T: copied to actor.frameTimer (D: 231 occurs 3290 times, values up to 400+)"},
	{"nextFrame", 0xC, 2, 1, 0, nullptr, "+0x0C T: frame index inside the action that follows; 0xFFFF = frame+1, 0xFFFE = action ends and holds (actor.nextFrameIndex = 0xFFFE) (D: otherwise < action.frameCount except 4 frames)"},
	{"attackLevelAndFlags", 0xE, 2, 1, 0, nullptr, "+0x0E T: low nibble -> actor.attackLevel; bit 0x10 arms the attack boxes (contactFlags |= 1, attackHitMask = 0xFF); bit 0x20 tested by the hit code (marks the opponent contactFlags |= 0x10)"},
	{"moveFlags", 0x10, 1, 1, 0, nullptr, "+0x10 T: QohFrameMoveFlags (1 = load x accel/jerk, 2 = load y accel/jerk, 4 = on landing jump to frame landFrame)"},
	{"clearVelX", 0x11, 1, 1, 0, nullptr, "+0x11 T: non-zero zeroes actor.velX"},
	{"clearVelY", 0x12, 1, 1, 0, nullptr, "+0x12 T: non-zero zeroes actor.velY"},
	{"xAccelAbsolute", 0x13, 1, 1, 0, nullptr, "+0x13 T: copied to actor.xAccelAbsolute (non-zero: velX is clamped to a sign change instead of free integration)"},
	{"yAccelAbsolute", 0x14, 1, 1, 0, nullptr, "+0x14 T/D: copied to actor.yAccelAbsolute; 0 in all files"},
	{"tileXform", 0x15, 1, 1, 0, nullptr, "+0x15 T: QohTileXform (D: values 0..7)"},
	{"landFrame", 0x16, 1, 1, 0, nullptr, "+0x16 T: frame index entered on landing when moveFlags & 4 (actor.nextFrameIndex = this, else 0xFFFE)"},
	{"bodyBoxIndex", 0x17, 1, 1, 0, nullptr, "+0x17 T: body (push) box, offset from action.firstBox; used for screen-edge / push alignment (CalculateCollisionBounds)"},
	{"bodyBoxMode", 0x18, 1, 1, 0, nullptr, "+0x18 T: 0 or 0xFF = no body box (the actor is skipped by the camera / push code); otherwise 1 (D: 31383 of 40452 frames are 1)"},
	{"hurtBoxFirst", 0x19, 1, 1, 0, nullptr, "+0x19 T: first vulnerable box, offset from action.firstBox"},
	{"hurtBoxCount", 0x1A, 1, 1, 0, nullptr, "+0x1A T: number of vulnerable boxes; 0 = cannot be hit"},
	{"unused_1B", 0x1B, 1, 1, 0, nullptr, "+0x1B D: 0 in all frames of all files, no reader"},
	{"unused_1C", 0x1C, 1, 1, 0, nullptr, "+0x1C D: 0 in all frames of all files, no reader"},
	{"guardBoxFirst", 0x1D, 1, 1, 0, nullptr, "+0x1D T: first projectile-guard box, offset from action.firstBox (CheckProjectileVsGuardBoxCollision)"},
	{"guardBoxCount", 0x1E, 1, 1, 0, nullptr, "+0x1E T: number of guard boxes; non-zero sets contactFlags |= 2 and guardHitMask = 0xFF"},
	{"attackFirst", 0x1F, 1, 1, 0, nullptr, "+0x1F T: first attack record, offset from action.firstAttack"},
	{"attackCount", 0x20, 1, 1, 0, nullptr, "+0x20 T: number of attack records; 0 = none; 0xFF = special hit 1 (returns -1), 0xFE = special hit 2 (ProcessCharacterHitDetectionAndDamage)"},
	{"stanceBits", 0x21, 1, 1, 0, nullptr, "+0x21 T: copied whole to actor.stanceBits (low 3 bits = stance class, 0x40 = turn toward the nearest opponent, 0x20/0x80 read by the hit code)"},
	{"xAccel", 0x22, 2, 1, 1, nullptr, "+0x22 T: actor.accelX when moveFlags & 1 (negated when facing left)"},
	{"yAccel", 0x24, 2, 1, 1, nullptr, "+0x24 T: actor.accelY when moveFlags & 2"},
	{"xJerk", 0x26, 2, 1, 1, nullptr, "+0x26 T: actor.jerkX when moveFlags & 1"},
	{"yJerk", 0x28, 2, 1, 1, nullptr, "+0x28 T: actor.jerkY when moveFlags & 2"},
	{"unused_2A", 0x2A, 1, 1, 0, nullptr, "+0x2A D: 0xCD (build fill) in 26694 frames, else 0; no reader"},
	{"unused_2B", 0x2B, 1, 1, 0, nullptr, "+0x2B D: same as unused_2A"},
	{"aiMoveClass", 0x2C, 4, 1, 1, nullptr, "+0x2C T: copied to actor.aiMoveClass, read by the CPU player (D: 0..11 observed)"},
	{"fxFlags", 0x30, 4, 1, 0, nullptr, "+0x30 T: QohFrameFxFlags; byte +0x31 is additionally read as a second sound id (QueueNetworkEventAndSound)"},
	{"drawClass", 0x34, 4, 1, 0, nullptr, "+0x34 T: & 3 stored in actor.drawClass (D: 0, 1 or 3)"},
	{"flickerFlags", 0x38, 1, 1, 0, nullptr, "+0x38 T: bit 0 = draw only every second tick (RenderCharacterSprite) (D: 0 or 1)"},
	{"unused_39", 0x39, 1, 7, 0, nullptr, "+0x39 D: 0 in all frames of all files, no reader"},
};
static const Han2FieldInfo kQohBoxFields[] = {
	{"left", 0x0, 2, 1, 1, nullptr, "+0x00 T"},
	{"top", 0x2, 2, 1, 1, nullptr, "+0x02 T"},
	{"right", 0x4, 2, 1, 1, nullptr, "+0x04 T"},
	{"bottom", 0x6, 2, 1, 1, nullptr, "+0x06 T: D: right/bottom ranges are pixel offsets, bottom up to 215+"},
};
static const Han2FieldInfo kQohAttackFields[] = {
	{"left", 0x0, 2, 1, 1, nullptr, "+0x00 T"},
	{"top", 0x2, 2, 1, 1, nullptr, "+0x02 T"},
	{"right", 0x4, 2, 1, 1, nullptr, "+0x04 T"},
	{"bottom", 0x6, 2, 1, 1, nullptr, "+0x06 T"},
	{"damage", 0x8, 2, 1, 1, nullptr, "+0x08 T: life removed (<= 0: no damage hit)"},
	{"unresolved_0A", 0xA, 2, 1, 1, nullptr, "+0x0A U/D: 34 non-zero values (1, 3, 4, 5, 10); no reader found"},
	{"guardDamage", 0xC, 2, 1, 1, nullptr, "+0x0C T: subtracted from the defender guard gauge on a guarded hit (ProcessCharacterBlockAndCounterAttack)"},
	{"meterGain", 0xE, 2, 1, 1, nullptr, "+0x0E T: passed to ManagePlayerSuperMeterGauge (attacker super gauge gain)"},
	{"flags", 0x10, 1, 1, 0, nullptr, "+0x10 T: QohAttackFlags (bit 0 = damaging hit; tested with hitClass 10/11 when the defender is in state 1)"},
	{"guardMask", 0x11, 1, 1, 0, nullptr, "+0x11 T: bit0/1/2 = which guard postures (defender state 7.. variants) may block it (ProcessCharacterBlockAndCounterAttack)"},
	{"hitClass", 0x12, 1, 1, 0, nullptr, "+0x12 T: 0..15; 0..9 and 12 select the defender reaction pose, 10 and 11 special (action 36 / 35), 13..15 projectile clash rules"},
	{"unresolved_13", 0x13, 1, 1, 0, nullptr, "+0x13 U/D: 0 in all but one record (value 68); no reader found"},
	{"knockMode", 0x14, 2, 1, 0, nullptr, "+0x14 T: bits 0..1 -> defender.hitFacingMode (1 = turn the defender away); bit 2 / bit 3 tested in the hit code; the whole word is returned to the caller"},
	{"hitEffectFlags", 0x16, 2, 1, 0, nullptr, "+0x16 T: bits 12..15 = screen flash type (SetScreenFlashEffectByHitType); bit 0 set in 3000 of 4733 records (U)"},
};
static const Han2FieldInfo kQohCharAssetsFields[] = {
	{"tiles", 0x0, 4, 1, 4, nullptr, "+0x00 T: 260 * tileCount"},
	{"tileCount", 0x4, 4, 1, 1, nullptr, "+0x04 T: header c1"},
	{"images", 0x8, 4, 1, 4, nullptr, "+0x08 T: 12 * imageCount"},
	{"imageCount", 0xC, 4, 1, 1, nullptr, "+0x0C T: header c0"},
	{"actions", 0x10, 4, 1, 4, nullptr, "+0x10 T: 24 * actionCount"},
	{"actionCount", 0x14, 4, 1, 1, nullptr, "+0x14 T: header c2"},
	{"frames", 0x18, 4, 1, 4, nullptr, "+0x18 T: 64 * frameCount"},
	{"frameCount", 0x1C, 4, 1, 1, nullptr, "+0x1C T: header c3"},
	{"boxes", 0x20, 4, 1, 4, nullptr, "+0x20 T: 8 * boxCount"},
	{"boxCount", 0x24, 4, 1, 1, nullptr, "+0x24 T: header c4"},
	{"attacks", 0x28, 4, 1, 4, nullptr, "+0x28 T: 24 * attackCount"},
	{"attackCount", 0x2C, 4, 1, 1, nullptr, "+0x2C T: header c5"},
};
static const Han2FieldInfo kQohTrailEntryFields[] = {
	{"posX", 0x0, 4, 1, 1, nullptr, "+0x00 T"},
	{"posY", 0x4, 4, 1, 1, nullptr, "+0x04 T"},
	{"actionIndex", 0x8, 4, 1, 1, nullptr, "+0x08 T"},
	{"frameIndex", 0xC, 4, 1, 1, nullptr, "+0x0C T"},
	{"frameTimer", 0x10, 4, 1, 1, nullptr, "+0x10 T"},
	{"facing", 0x14, 1, 1, 0, nullptr, "+0x14 T"},
	{"stanceBits", 0x15, 1, 1, 0, nullptr, "+0x15 T"},
	{"impulseX", 0x16, 2, 1, 1, nullptr, "+0x16 T: restored to actor+108 by the partner copy"},
	{"impulseY", 0x18, 2, 1, 1, nullptr, "+0x18 T: actor+110"},
	{"impulseAccelX", 0x1A, 2, 1, 1, nullptr, "+0x1A T: actor+112"},
	{"impulseAccelY", 0x1C, 2, 1, 1, nullptr, "+0x1C T: actor+114"},
	{"impulseJerkX", 0x1E, 2, 1, 1, nullptr, "+0x1E T: actor+116"},
	{"impulseJerkY", 0x20, 2, 1, 1, nullptr, "+0x20 T: actor+118"},
	{"unresolved_22", 0x22, 1, 2, 0, nullptr, "+0x22 U: not accessed"},
};
static const Han2FieldInfo kQohCommandChildFields[] = {
	{"unresolved_00", 0x0, 1, 4, 0, nullptr, "+0x00 U: not accessed by any traced code path (see doc)"},
	{"resetMarker", 0x4, 4, 1, 1, nullptr, "+0x04 T: set to -1 when the actor buffer is re-initialised (InitializeCharacterBuffer)"},
	{"dirRingValues", 0x8, 4, 32, 0, nullptr, "+0x08 T: direction history, masked & 0xF0000"},
	{"dirRingHold", 0x88, 4, 32, 0, nullptr, "+0x88 T: hold counters"},
	{"dirRingHead", 0x108, 1, 1, 0, nullptr, "+0x108 T: index, & 0x1F"},
	{"unresolved_109", 0x109, 1, 3, 0, nullptr, "+0x109 U: not accessed by any traced code path (see doc)"},
	{"btnRingValues", 0x10C, 4, 16, 0, nullptr, "+0x10C T: button history, masked & 0xF"},
	{"btnRingHold", 0x14C, 4, 16, 0, nullptr, "+0x14C T: hold counters"},
	{"btnRingHead", 0x18C, 1, 1, 0, nullptr, "+0x18C T: index, & 0xF"},
	{"unresolved_18D", 0x18D, 1, 15, 0, nullptr, "+0x18D U: not accessed by any traced code path (see doc)"},
	{"resetMarker2", 0x19C, 2, 1, 1, nullptr, "+0x19C T: set to -1 when the actor buffer is re-initialised"},
	{"unresolved_19E", 0x19E, 1, 18, 0, nullptr, "+0x19E U: not accessed by any traced code path (see doc)"},
	{"directionKill", 0x1B0, 4, 1, 1, nullptr, "+0x1B0 T: suppresses recorded directions across a native round transition; cleared on re-initialisation"},
	{"unresolved_1B4", 0x1B4, 1, 76, 0, nullptr, "+0x1B4 U: not accessed"},
};
static const Han2FieldInfo kQohActorFields[] = {
	{"assets", 0x0, 48, 1, 4, nullptr, "+0x00 T: loaded .chr tables (pointers masked by the savestate)"},
	{"actionIndex", 0x30, 4, 1, 1, nullptr, "+0x30 T: current action id (index into assets.actions)"},
	{"nextFrameIndex", 0x34, 4, 1, 1, nullptr, "+0x34 T: frame to enter when frameTimer reaches 0; 65534 = hold the last frame (UpdateCharacterLogic marks animEnded)"},
	{"frameTimer", 0x38, 4, 1, 1, nullptr, "+0x38 T: ticks left in the frame, set from frame.duration; HandleCharacterMovement steps the animation when 0"},
	{"unresolved_3C", 0x3C, 4, 1, 1, nullptr, "+0x3C U: not accessed"},
	{"frameIndex", 0x40, 4, 1, 1, nullptr, "+0x40 T: current frame inside the action (frame = assets.frames[action.firstFrame + frameIndex])"},
	{"unresolved_44", 0x44, 4, 1, 1, nullptr, "+0x44 U: not accessed"},
	{"requestedAction", 0x48, 4, 1, 1, nullptr, "+0x48 T: action the input state machine wants (written with requestFlag)"},
	{"requestFlag", 0x4C, 4, 1, 1, nullptr, "+0x4C T: 1 = a transition request is pending"},
	{"unresolved_50", 0x50, 4, 1, 1, nullptr, "+0x50 U"},
	{"dispatchAction", 0x54, 4, 1, 1, nullptr, "+0x54 T: copy of the forced action taken by UpdateCharacterAnimation"},
	{"animEnded", 0x58, 4, 1, 1, nullptr, "+0x58 T: -1 reset marker, 1 = the action ran out (UpdateCharacterLogic)"},
	{"forcedAction", 0x5C, 4, 1, 1, nullptr, "+0x5C T: action forced by the hit / engine code, -1 = none"},
	{"velX", 0x60, 2, 1, 1, nullptr, "+0x60 T: 8.8 fixed point, integrated by UpdateCharacterLogic"},
	{"velY", 0x62, 2, 1, 1, nullptr, "+0x62 T"},
	{"accelX", 0x64, 2, 1, 1, nullptr, "+0x64 T: added to velX each tick; loaded from frame.xAccel"},
	{"accelY", 0x66, 2, 1, 1, nullptr, "+0x66 T: loaded from frame.yAccel"},
	{"jerkX", 0x68, 2, 1, 1, nullptr, "+0x68 T: added to accelX; loaded from frame.xJerk"},
	{"jerkY", 0x6A, 2, 1, 1, nullptr, "+0x6A T: loaded from frame.yJerk"},
	{"impulseX", 0x6C, 2, 1, 1, nullptr, "+0x6C T: second x group (knock back); cleared by the hit code"},
	{"impulseY", 0x6E, 2, 1, 1, nullptr, "+0x6E T"},
	{"impulseAccelX", 0x70, 2, 1, 1, nullptr, "+0x70 T"},
	{"impulseAccelY", 0x72, 2, 1, 1, nullptr, "+0x72 T"},
	{"impulseJerkX", 0x74, 2, 1, 1, nullptr, "+0x74 T"},
	{"impulseJerkY", 0x76, 2, 1, 1, nullptr, "+0x76 T"},
	{"slideVelX", 0x78, 2, 1, 1, nullptr, "+0x78 T: third x group with a countdown"},
	{"unresolved_7A", 0x7A, 2, 1, 1, nullptr, "+0x7A U: not touched by UpdateCharacterLogic"},
	{"slideAccelX", 0x7C, 2, 1, 1, nullptr, "+0x7C T"},
	{"unresolved_7E", 0x7E, 2, 1, 1, nullptr, "+0x7E U"},
	{"slideJerkX", 0x80, 2, 1, 1, nullptr, "+0x80 T"},
	{"unresolved_82", 0x82, 2, 1, 1, nullptr, "+0x82 U"},
	{"slideTimer", 0x84, 2, 1, 1, nullptr, "+0x84 T: decremented each tick while non-zero"},
	{"unresolved_86", 0x86, 2, 1, 1, nullptr, "+0x86 U"},
	{"posX", 0x88, 4, 1, 1, nullptr, "+0x88 T: world x of the anchor; boxes are relative to it"},
	{"posY", 0x8C, 4, 1, 1, nullptr, "+0x8C T: world y"},
	{"unresolved_90", 0x90, 4, 1, 1, nullptr, "+0x90 U"},
	{"unresolved_94", 0x94, 4, 1, 1, nullptr, "+0x94 U"},
	{"unresolved_98", 0x98, 4, 1, 1, nullptr, "+0x98 T: written by AutoFlipCharacterFacing, meaning unresolved"},
	{"stanceBits", 0x9C, 1, 1, 0, nullptr, "+0x9C T: frame.stanceBits copy (low nibble posture, bits 4..7 behaviour)"},
	{"reactionHeight", 0x9D, 1, 1, 0, nullptr, "+0x9D T: 0/1/2 written by the hit code (high / mid / low reaction)"},
	{"attackLevel", 0x9E, 2, 1, 0, nullptr, "+0x9E T: frame.attackLevelAndFlags & 0xF"},
	{"contactFlags", 0xA0, 2, 1, 0, nullptr, "+0xA0 T: bit0 = attack boxes armed (THE active latch, set from frame bit 0x10, survives later frames), bit1 = guard boxes present, bit4 set by the hit code"},
	{"attackHitMask", 0xA2, 1, 1, 0, nullptr, "+0xA2 T: bit n = player slot n may still be hit by the current attack; reset to 0xFF when the attack arms"},
	{"guardHitMask", 0xA3, 1, 1, 0, nullptr, "+0xA3 T: same for guard boxes"},
	{"commandChild", 0xA4, 4, 1, 4, nullptr, "+0xA4 T: input history object"},
	{"xAccelAbsolute", 0xA8, 1, 1, 0, nullptr, "+0xA8 T: frame.xAccelAbsolute"},
	{"yAccelAbsolute", 0xA9, 1, 1, 0, nullptr, "+0xA9 T: frame.yAccelAbsolute"},
	{"facing", 0xAA, 1, 1, 0, nullptr, "+0xAA T: 0 = faces right, 1 = faces left"},
	{"team", 0xAB, 1, 1, 0, nullptr, "+0xAB T: owning team / EX owner index (NOT the slot)"},
	{"playerSlot", 0xAC, 1, 1, 0, nullptr, "+0xAC T: player slot 0..3"},
	{"playerSlotCopy", 0xAD, 1, 1, 0, nullptr, "+0xAD T: equals playerSlot after InitializeCharacterBuffer"},
	{"entityKind", 0xAE, 1, 1, 0, nullptr, "+0xAE T: 0xFF = free pool slot; otherwise the state machine selector of InitializeCharacterAnimationFrame"},
	{"paletteEntryBase", 0xAF, 1, 1, 0, nullptr, "+0xAF T: palette entry index of the actor 16-colour bank (added to paletteTable as 4 * value by the renderers; saved/restored across the actor reset)"},
	{"hitAttrib", 0xB0, 1, 1, 0, nullptr, "+0xB0 T: set to 9 by the hit code"},
	{"hitDirection", 0xB1, 1, 1, 0, nullptr, "+0xB1 T: relative direction of the last hit"},
	{"unresolved_B2", 0xB2, 1, 2, 0, nullptr, "+0xB2 U: not accessed by any traced code path (see doc)"},
	{"unresolved_B4", 0xB4, 4, 1, 1, nullptr, "+0xB4 T: ProcessCharacterAttackSequence"},
	{"unresolved_B8", 0xB8, 4, 1, 1, nullptr, "+0xB8 T"},
	{"unresolved_BC", 0xBC, 4, 1, 1, nullptr, "+0xBC T"},
	{"unresolved_C0", 0xC0, 4, 1, 1, nullptr, "+0xC0 T"},
	{"unresolved_C4", 0xC4, 4, 1, 1, nullptr, "+0xC4 T: 17 written by ProcessCharacterCollisionAndStates"},
	{"unresolved_C8", 0xC8, 4, 1, 1, nullptr, "+0xC8 T"},
	{"stateNibbles", 0xCC, 1, 1, 0, nullptr, "+0xCC T: low/high nibble state bits (&0xF0 / &0xF), cleared with stateFlags"},
	{"unresolved_CD", 0xCD, 1, 3, 0, nullptr, "+0xCD U: not accessed by any traced code path (see doc)"},
	{"stateFlags", 0xD0, 4, 1, 0, nullptr, "+0xD0 T: 0x10000 = capture a pose snapshot into trail[0]; low byte cleared by the hit code"},
	{"tagTimer", 0xD4, 4, 1, 1, nullptr, "+0xD4 T: counts down while the partner is tagged in (clears stateFlags bit 8 at 0)"},
	{"trail", 0xD8, 36, 30, 4, nullptr, "+0xD8 T: pose history"},
	{"pendingHitDamage", 0x510, 4, 1, 1, nullptr, "+0x510 T: damage event consumed (and cleared) at the end of ProcessCharacterAnimationAndState"},
	{"lastHitPacked", 0x514, 4, 1, 1, nullptr, "+0x514 T: (hitTag << 4) | stance bits & 7 of the last hit"},
	{"lastHitStance", 0x518, 4, 1, 1, nullptr, "+0x518 T: defender stance bits & 7 at the last hit"},
	{"lastHitSlot", 0x51C, 4, 1, 1, nullptr, "+0x51C T: player slot of the attacker of the last hit"},
	{"prevPosX", 0x520, 4, 1, 1, nullptr, "+0x520 T: previous x (ResolveCharacterPushCollision)"},
	{"unresolved_524", 0x524, 4, 1, 1, nullptr, "+0x524 T: InitializeSpecialSuperState165"},
	{"unresolved_528", 0x528, 4, 1, 1, nullptr, "+0x528 T: 0/1 flag written by spawn code"},
	{"updateCallback", 0x52C, 4, 1, 0, nullptr, "+0x52C T: code pointer, set to UpdateProjectileFromParentCharacter for parented projectiles"},
	{"unresolved_530", 0x530, 4, 1, 1, nullptr, "+0x530 T"},
	{"unresolved_534", 0x534, 1, 4, 0, nullptr, "+0x534 U: not accessed by any traced code path (see doc)"},
	{"hitPendingFlags", 0x538, 4, 1, 1, nullptr, "+0x538 T: bit0 = normal hit pending, bit1 = guarded hit pending (HandleCharacterMovement)"},
	{"unresolved_53C", 0x53C, 4, 1, 1, nullptr, "+0x53C T"},
	{"unresolved_540", 0x540, 4, 1, 1, nullptr, "+0x540 T: 4800 written by the Akari special state"},
	{"unresolved_544", 0x544, 1, 4, 0, nullptr, "+0x544 U: not accessed by any traced code path (see doc)"},
	{"unresolved_548", 0x548, 4, 1, 1, nullptr, "+0x548 T: 10 written by the transition code"},
	{"unresolved_54C", 0x54C, 1, 4, 0, nullptr, "+0x54C U: not accessed by any traced code path (see doc)"},
	{"hitFacingMode", 0x550, 4, 1, 1, nullptr, "+0x550 T: attack.knockMode & 3 of the last hit (1 = turn away, 2 = zero the knock back)"},
	{"roundEndFlag", 0x554, 4, 1, 1, nullptr, "+0x554 T"},
	{"roundLostFlag", 0x558, 4, 1, 1, nullptr, "+0x558 T"},
	{"unresolved_55C", 0x55C, 1, 4, 0, nullptr, "+0x55C U: not accessed by any traced code path (see doc)"},
	{"fatalCause", 0x560, 4, 1, 1, nullptr, "+0x560 T: -1 at round start"},
	{"unresolved_564", 0x564, 1, 4, 0, nullptr, "+0x564 U: not accessed by any traced code path (see doc)"},
	{"unresolved_568", 0x568, 1, 1, 0, nullptr, "+0x568 T"},
	{"unresolved_569", 0x569, 1, 1, 0, nullptr, "+0x569 T"},
	{"landingMode", 0x56A, 1, 1, 0, nullptr, "+0x56A T: 0 = normal landing at y == 0, 2 = KO bounce test (UpdateCharacterLogic)"},
	{"unresolved_56B", 0x56B, 1, 1, 0, nullptr, "+0x56B U: not accessed by any traced code path (see doc)"},
	{"unresolved_56C", 0x56C, 2, 1, 0, nullptr, "+0x56C T: non-zero stops projectile reflection"},
	{"wallFlags", 0x56E, 2, 1, 0, nullptr, "+0x56E T: screen-edge contact flags (UpdateCameraPositionWithClampingAndSmoothing)"},
	{"lastDamageResult", 0x570, 4, 1, 1, nullptr, "+0x570 T: result of CalculateDamageWithModifiers stashed on the defender"},
	{"unresolved_574", 0x574, 4, 1, 1, nullptr, "+0x574 T"},
	{"engineOwned", 0x578, 4, 1, 1, nullptr, "+0x578 T: != 0 means the engine owns this actor"},
	{"facingSnapshot", 0x57C, 4, 1, 1, nullptr, "+0x57C T: facing copy compared on the next frame"},
	{"actionSnapshot", 0x580, 4, 1, 1, nullptr, "+0x580 T"},
	{"frameSnapshot", 0x584, 4, 1, 1, nullptr, "+0x584 T"},
	{"paletteTable", 0x588, 4, 1, 4, nullptr, "+0x588 T: the player palette (256 entries, g_actor_palette_p1..p4) the renderers index with paletteEntryBase"},
	{"unresolved_58C", 0x58C, 1, 4, 0, nullptr, "+0x58C U: not accessed by any traced code path (see doc)"},
	{"pendingDamageBonus", 0x590, 2, 1, 0, nullptr, "+0x590 T: added to pendingHitDamage"},
	{"pendingDamagePenalty", 0x592, 2, 1, 0, nullptr, "+0x592 T: subtracted from pendingHitDamage"},
	{"subState", 0x594, 4, 1, 1, nullptr, "+0x594 T: state machine sub step, written by the Initialize*State functions"},
	{"currentFrame", 0x598, 4, 1, 4, nullptr, "+0x598 T: frame pointer recomputed by HandleCharacterMovement every tick"},
	{"lastContactActor", 0x59C, 4, 1, 4, nullptr, "+0x59C T: the other party of the last hit (attacker for a defender, victim for an attacker)"},
	{"unresolved_5A0", 0x5A0, 4, 1, 1, nullptr, "+0x5A0 T"},
	{"unresolved_5A4", 0x5A4, 4, 1, 1, nullptr, "+0x5A4 T"},
	{"unresolved_5A8", 0x5A8, 4, 1, 1, nullptr, "+0x5A8 T"},
	{"unresolved_5AC", 0x5AC, 4, 1, 1, nullptr, "+0x5AC T"},
	{"formMode", 0x5B0, 4, 1, 1, nullptr, "+0x5B0 T: 1/2 = alternate form participating (hit code treats the partner as part of the actor), 2/3/4 per adapter"},
	{"unresolved_5B4", 0x5B4, 1, 4, 0, nullptr, "+0x5B4 U: not accessed by any traced code path (see doc)"},
	{"unresolved_5B8", 0x5B8, 4, 1, 1, nullptr, "+0x5B8 T: set to 1 by the hit code"},
	{"unresolved_5BC", 0x5BC, 4, 1, 1, nullptr, "+0x5BC T: set to 1 by the hit code"},
	{"unresolved_5C0", 0x5C0, 1, 4, 0, nullptr, "+0x5C0 U: not accessed by any traced code path (see doc)"},
	{"unresolved_5C4", 0x5C4, 4, 1, 1, nullptr, "+0x5C4 T: bit 1 halves incoming damage in the hit code"},
	{"unresolved_5C8", 0x5C8, 4, 1, 1, nullptr, "+0x5C8 T: set to 1 by ProcessCharacterAnimationAndState"},
	{"drawClass", 0x5CC, 4, 1, 1, nullptr, "+0x5CC T: frame.drawClass & 3"},
	{"unresolved_5D0", 0x5D0, 4, 1, 1, nullptr, "+0x5D0 T: 3 at spawn"},
	{"unresolved_5D4", 0x5D4, 4, 1, 1, nullptr, "+0x5D4 T"},
	{"unresolved_5D8", 0x5D8, 4, 1, 1, nullptr, "+0x5D8 T"},
	{"hitstopFrames", 0x5DC, 4, 1, 1, nullptr, "+0x5DC T: while non-zero the pose timers are frozen"},
	{"unresolved_5E0", 0x5E0, 4, 1, 1, nullptr, "+0x5E0 T"},
	{"unresolved_5E4", 0x5E4, 1, 8, 0, nullptr, "+0x5E4 U: not accessed by any traced code path (see doc)"},
	{"ownerSlotCache", 0x5EC, 4, 1, 1, nullptr, "+0x5EC T: slot index of the owning player (ProcessCharacterCollisionAndStates)"},
	{"unresolved_5F0", 0x5F0, 4, 1, 1, nullptr, "+0x5F0 T: 1 at spawn"},
	{"aiMoveClass", 0x5F4, 4, 1, 1, nullptr, "+0x5F4 T: frame.aiMoveClass copy"},
	{"terminalReady", 0x5F8, 4, 1, 1, nullptr, "+0x5F8 T: written 0/1 by the transition code"},
};
static const Han2FieldInfo kQohFobFuncFields[] = {
	{"name", 0x0, 1, 32, 5, nullptr, "+0x00 T/D: NUL terminated; the bytes after the NUL are uninitialised build garbage (D: \"1\", \"Mizuho_Idou\", \"Mizuho_Idou2\")"},
	{"entryPc", 0x20, 4, 1, 0, nullptr, "+0x20 T: byte offset into the code block (D: always an instruction start)"},
};
static const Han2FieldInfo kQohScriptBankFields[] = {
	{"path", 0x0, 1, 260, 5, nullptr, "+0x00 T: upper-cased path used as the cache key"},
	{"code", 0x104, 4, 1, 4, nullptr, "+0x104 T: code block (codeSize + 2 zero bytes); 0 = slot free"},
	{"funcCount", 0x108, 4, 1, 1, nullptr, "+0x108 T: nFuncs"},
	{"funcs", 0x10C, 4, 1, 4, nullptr, "+0x10C T: 36 * nFuncs"},
};
static const Han2FieldInfo kQohImgHeaderFields[] = {
	{"reserved", 0x0, 4, 1, 0, nullptr, "+0x00 T/D: read and (optionally) returned, 0 in all 553 files"},
	{"paletteEntries", 0x4, 4, 1, 0, nullptr, "+0x04 T: 4 bytes each (blue, green, red, 0); 0 = 24-bit image"},
	{"bitsPerPixel", 0x8, 4, 1, 0, nullptr, "+0x08 T/D: 4, 8 or 24 (24 only with paletteEntries == 0)"},
	{"width", 0xC, 4, 1, 0, nullptr, "+0x0C T"},
	{"height", 0x10, 4, 1, 0, nullptr, "+0x10 T"},
};
static const Han2FieldInfo kQohFobVmHeadFields[] = {
	{"unresolved_00", 0x0, 1, 4, 0, nullptr, "+0x00 U: not accessed by any traced code path (see doc)"},
	{"currentLine", 0x4, 4, 1, 1, nullptr, "+0x04 T: written by opcode 0x3C (source line marker), printed in the \"ScriptUnknown Code\" error"},
	{"unresolved_08", 0x8, 1, 8, 0, nullptr, "+0x08 U: not accessed"},
};
static const Han2FieldInfo kQohFobVmStateFields[] = {
	{"stackDepth", 0x0, 4, 1, 1, nullptr, "+0x00 T: index of the top of the value stack (0 = empty; pushes pre-increment; limit 0x10000)"},
	{"activeBank", 0x4, 4, 1, 1, nullptr, "+0x04 T: index of the running QohScriptBank"},
	{"codeBase", 0x8, 4, 1, 4, nullptr, "+0x08 T: code of the running bank; the pc is a byte offset into it"},
	{"unresolved_0C", 0xC, 1, 20, 0, nullptr, "+0x0C U: not accessed"},
};
