// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"

enum Qoh98TileXform : uint8_t {
	Q98XF_IDENTITY = 0,
	Q98XF_ROT_90_CW = 1,
	Q98XF_ROT_180 = 2,
	Q98XF_ROT_90_CCW = 3,
	Q98XF_FLIP_H = 4,
	Q98XF_TRANSPOSE = 5,
	Q98XF_FLIP_V = 6,
	Q98XF_ANTI_TRANSPOSE = 7,
};
enum Qoh98SpriteMoveFlags : uint8_t {
	Q98SMF_SET_X_ACCEL = 1,
	Q98SMF_SET_Y_ACCEL = 2,
	Q98SMF_ON_LAND_JUMP_TO_ANIM = 4,
};
enum Qoh98SpriteFxFlags : uint32_t {
	Q98FX_SOUND_SLOT_MASK = 0xF,
	Q98FX_SOUND_BANK_MASK = 0xF0,
	Q98FX_SPAWN_FX_A = 0x10000,
	Q98FX_SPAWN_THROW_FX = 0x20000,
	Q98FX_SET_SCREEN_MODE_4 = 0x40000,
	Q98FX_CLEAR_COMBO_STATE = 0x80000,
	Q98FX_SPAWN_FX_B = 0x200000,
};

#pragma pack(push, 1)
struct Qoh98DatHeader {
	uint32_t version;  // +0x00 T: read into a throwaway buffer, never compared; 5 in all 14 files
	uint32_t imageCount;  // +0x04 T: c0 = TIM path entries = image table entries
	uint32_t tileCount;  // +0x08 T: c1 = 260-byte tile blocks
	uint32_t animCount;  // +0x0C T: c2 = 24-byte animation records (256 in every file)
	uint32_t spriteCount;  // +0x10 T: c3 = 52-byte sprite (frame) records
	uint32_t bodyRectCount;  // +0x14 T: c4 = 8-byte body/hurt rectangles
	uint32_t hitBoxCount;  // +0x18 T: c5 = 24-byte attack boxes
};
struct Qoh98TimPathEntry {
	char shortName[8];  // +0x00 D: NUL terminated "Aka0000", rest of the 8 bytes is 0xCD fill
	char sjisAndPath[252];  // +0x08 D: CP932 display text then the original build path ("...\AKARI\Aka0000.tim"), NUL then 0xCD fill; split not read by the game
};
struct Qoh98ImageTileRange {
	int32_t firstTile;  // +0x00 T: first tile index of this image (ranges are contiguous and sum to tileCount) (sub_416EB0: *(a2[2] + 8*img))
	int32_t tileCount;  // +0x04 T: number of tiles drawn for this image (a2[2] + 8*img + 4)
};
struct Qoh98Tile {
	int16_t x;  // +0x00 T: destination column of the tile inside the 256x256 sprite canvas (multiple of 16, 0..240)
	int16_t y;  // +0x02 T: destination row (multiple of 16, 0..240)
	uint8_t pixels[256];  // +0x04 T: 16x16 palette indices, row-major, values 0..15 (index 0 = transparent) D
};
struct Qoh98AnimRecord {
	int32_t firstSprite;  // +0x00 T: index of the first sprite record, -1 = animation unused
	int32_t frameCount;  // +0x04 T: number of sprite records; the step code resets to frame 0 when frameCount < nextFrame (sub_419470) D: next anim firstSprite == firstSprite + frameCount in order
	int32_t bodyRectBase;  // +0x08 T: base index into the body rectangle table; sprite fields +0x17/+0x19/+0x1D are offsets from it; -1 when none
	int32_t bodyRectCount;  // +0x0C D: rectangle count of this animation (contiguous ranges); not read by the game
	int32_t hitBoxBase;  // +0x10 T: base index into the hit box table; sprite field +0x1F is an offset from it; -1 when none
	int32_t hitBoxCount;  // +0x14 D: box count of this animation (contiguous ranges); not read by the game
};
struct Qoh98Sprite {
	int32_t imageIndex;  // +0x00 T: index into the image table (a2[2]); out of range = draw nothing (sub_416EB0: v13 < 0 || a2[3] <= v13)
	int16_t drawX;  // +0x04 T: x offset of the 256x256 canvas relative to the entity position (negated when facing left)
	int16_t drawY;  // +0x06 T: y offset (sub_416EB0 divides it by 3 for the shadow pass)
	int32_t duration;  // +0x08 T: copied to entity +0x38 frameTimer (sub_419470)
	uint16_t nextFrame;  // +0x0C T: next frame index inside the animation; 0xFFFF = frame+1, 0xFFFE = animation ends (entity +0x34 = 0xFFFE)
	uint16_t attackLevelAndFlags;  // +0x0E T: low nibble -> entity +0x9E; bit 0x10 arms the hit boxes (entity flags |= 1)
	uint8_t moveFlags;  // +0x10 T: Qoh98SpriteMoveFlags (1 = apply x accel +0x22/+0x26, 2 = apply y accel +0x24/+0x28, 4 = on landing jump to anim +0x16)
	uint8_t clearVelX;  // +0x11 T: non-zero zeroes entity velX
	uint8_t clearVelY;  // +0x12 T: non-zero zeroes entity velY
	uint8_t xAccelAbsolute;  // +0x13 T: copied to entity +0xAC
	uint8_t yAccelAbsolute;  // +0x14 T: copied to entity +0xAD
	uint8_t tileXform;  // +0x15 T: Qoh98TileXform applied to the tile positions (xor 4 when facing left)
	uint8_t landAnim;  // +0x16 T: animation entered on landing when moveFlags & 4 (entity nextFrame = this, else 0xFFFE)
	uint8_t anchorRect;  // +0x17 T: body rectangle offset (from anim bodyRectBase) used to align the entity when it turns or leaves the screen (sub_409850, sub_40A780)
	uint8_t anchorMode;  // +0x18 T: 0xFF = no anchor (sub_409850 returns 0); 0/1/2 observed
	uint8_t hurtRectFirst;  // +0x19 T: first hurt body rectangle, offset from anim bodyRectBase
	uint8_t hurtRectCount;  // +0x1A T: number of hurt rectangles; 0 = invulnerable to hits (sub_40BB30)
	uint8_t unused_1B;  // +0x1B D: 0 in all 14 files, never read
	uint8_t unused_1C;  // +0x1C D: 0 in all 14 files, never read
	uint8_t grabRectFirst;  // +0x1D T: first grab-vulnerable body rectangle, offset from anim bodyRectBase (sub_40B9B0)
	uint8_t grabRectCount;  // +0x1E T: number of grab rectangles; non-zero sets entity flags |= 2
	uint8_t hitBoxFirst;  // +0x1F T: first attack box, offset from anim hitBoxBase
	uint8_t hitBoxCountHere;  // +0x20 T: number of attack boxes (0 = none)
	uint8_t stanceBits;  // +0x21 T: copied whole to entity +0x9C (low 3 bits = stance class, 0x40 = turn toward opponent via sub_40A780, 0x20/0x80 read by the hit code)
	int16_t xAccel;  // +0x22 T: entity +0x64 when moveFlags & 1 (negated when facing left)
	int16_t yAccel;  // +0x24 T: entity +0x66 when moveFlags & 2
	int16_t xJerk;  // +0x26 T: entity +0x68 when moveFlags & 1
	int16_t yJerk;  // +0x28 T: entity +0x6A when moveFlags & 2
	uint8_t unused_2A;  // +0x2A D: 0xCD in 7106 of 8256 sprites, else 0 (uninitialised build fill), never read
	uint8_t unused_2B;  // +0x2B D: same as +0x2A
	int32_t aiMoveClass;  // +0x2C T: read by the CPU player code (sub_404300 and 21 more) through *(a2[6] + 52*frame + 44); values 0..11 observed
	uint32_t fxFlags;  // +0x30 T: Qoh98SpriteFxFlags: low nibble = sound slot (+16*side), bits 4..7 = second sound, high bits = effects (sub_419470)
};
struct Qoh98BodyRect {
	int16_t left;  // +0x00 T: sub_409550 (mirrored as 256 - left when facing left)
	int16_t top;  // +0x02 T
	int16_t right;  // +0x04 T
	int16_t bottom;  // +0x06 T
};
struct Qoh98HitBox {
	int16_t left;  // +0x00 T: sub_409630
	int16_t top;  // +0x02 T
	int16_t right;  // +0x04 T
	int16_t bottom;  // +0x06 T
	int16_t damage;  // +0x08 T: life removed (0 = no damage hit); stance 1 divides by 4, stance 2 multiplies by 125/100 (sub_40BF60)
	int16_t unresolved_0A;  // +0x0A D: 0..10 (999 of 1031 are 0); no reader found
	int16_t guardDamage;  // +0x0C T: subtracted from the defender's guard gauge (entity +0x380) on guard
	int16_t meterGain;  // +0x0E T: passed to sub_41C260 (super gauge gain of the attacker side)
	uint8_t flags;  // +0x10 T: bit0 = damaging hit (affects knock back / hit stop)
	uint8_t defenderStateMask;  // +0x11 T: bit0/bit1/bit2 = may hit a defender in state 0x12 / 0x13 / 0x14 (sub_40BF60 case 0x12..0x14)
	uint8_t hitClass;  // +0x12 T: 0..15; 0..9 select the reaction anim (21..25/33/36), 10 and 11 special (anim 36 / 35), 13..15 projectile clash rules (sub_40A8B0)
	uint8_t unused_13;  // +0x13 D: 0 in all 14 files, never read
	uint16_t knockMode;  // +0x14 T: bits 0..1 -> defender entity +0x38C (1 = turn defender away); bit0 also tested in sub_40BF60
	uint8_t unresolved_16;  // +0x16 D: 0 or 1 (102 of 1031 boxes), no reader found
	uint8_t unused_17;  // +0x17 D: 0 in all 14 files
};
struct Qoh98CharData {
	uint32_t tiles;  // +0x00 T: 260 * tileCount
	int32_t tileCount;  // +0x04 T: header c1
	uint32_t images;  // +0x08 T: 8 * imageCount
	int32_t imageCount;  // +0x0C T: header c0
	uint32_t anims;  // +0x10 T: 24 * animCount (a1[4])
	int32_t animCount;  // +0x14 T: header c2
	uint32_t sprites;  // +0x18 T: 52 * spriteCount (a1[6])
	int32_t spriteCount;  // +0x1C T: header c3
	uint32_t bodyRects;  // +0x20 T: 8 * bodyRectCount (a1[8])
	int32_t bodyRectCount;  // +0x24 T: header c4
	uint32_t hitBoxes;  // +0x28 T: 24 * hitBoxCount (a1[10])
	int32_t hitBoxCount;  // +0x2C T: header c5
};
struct Qoh98Entity {
	Qoh98CharData data;  // +0x00 T: sprite/animation data of the owner (copied by value into spawned objects)
	int32_t animId;  // +0x30 T: current animation (index into data.anims)
	int32_t nextFrame;  // +0x34 T: frame that follows the current one; 0xFFFE = animation ends (sub_419470)
	int32_t frameTimer;  // +0x38 T: counts down from sprite.duration
	int32_t unresolved_3C;  // +0x3C not traced
	int32_t frameIndex;  // +0x40 T: current frame inside the animation (sprite = anim.firstSprite + frameIndex)
	int32_t unresolved_44;  // +0x44 not traced
	int32_t unresolved_48;  // +0x48 T: switch value in sub_40BF60 (0, 0x12, 0x13, 0x14); meaning not resolved
	int32_t unresolved_4C;  // +0x4C T: read/written by 98 sites; meaning not resolved
	int32_t unresolved_50;  // +0x50 not traced
	int32_t unresolved_54;  // +0x54 T: 50 sites, value 34 compared in the hit code
	int32_t animEnded;  // +0x58 T: set to 1 when the animation ran out (sub_419A10)
	int32_t reactionAnim;  // +0x5C T: reaction animation requested by the hit code (21..25, 33, 35, 36)
	int16_t velX;  // +0x60 T: 8.8 fixed point, added to posX/256 each tick (sub_419A10)
	int16_t velY;  // +0x62 T: velY
	int16_t accelX;  // +0x64 T: added to velX; loaded from sprite.xAccel
	int16_t accelY;  // +0x66 T: loaded from sprite.yAccel
	int16_t jerkX;  // +0x68 T: added to accelX; loaded from sprite.xJerk
	int16_t jerkY;  // +0x6A T: loaded from sprite.yJerk
	int16_t pushVelX;  // +0x6C T: knock back x velocity group (cleared on hit)
	int16_t pushVelY;  // +0x6E T
	int16_t pushAccelX;  // +0x70 T
	int16_t pushAccelY;  // +0x72 T
	int16_t pushJerkX;  // +0x74 T
	int16_t pushJerkY;  // +0x76 T
	int16_t slideVelX;  // +0x78 T: second x group with a countdown
	int16_t unresolved_7A;  // +0x7A not touched by sub_419A10
	int16_t slideAccelX;  // +0x7C T
	int16_t unresolved_7E;  // +0x7E not touched by sub_419A10
	int16_t slideJerkX;  // +0x80 T
	int16_t unresolved_82;  // +0x82 not touched by sub_419A10
	int16_t slideTimer;  // +0x84 T: decremented each tick while non-zero
	int16_t unresolved_86;  // +0x86 not touched
	int32_t posX;  // +0x88 T: world x, rectangles are relative to this
	int32_t posY;  // +0x8C T: world y
	int32_t unresolved_90;  // +0x90 not traced
	int32_t unresolved_94;  // +0x94 not traced
	int32_t unresolved_98;  // +0x98 T: 1 site
	uint8_t stanceBits;  // +0x9C T: sprite.stanceBits copy
	uint8_t reactionHeight;  // +0x9D T: 0/1/2 written by the hit code (high / mid / low)
	uint16_t attackLevel;  // +0x9E T: sprite.attackLevelAndFlags & 0xF
	uint16_t boxFlags;  // +0xA0 T: bit0 = hit boxes armed, bit1 = grab rectangles present
	uint8_t unresolved_A2[2];  // +0xA2 not traced
	uint32_t controlBlock;  // +0xA4 T: pointer used by 275 sites (input/controller block of the owner); *(ptr+408) and *(ptr+412) cleared when an animation ends
	int32_t hitTaken;  // +0xA8 T: set to 1 once the entity has been hit (sub_40AF70)
	uint8_t xAccelAbsolute;  // +0xAC T: sprite.xAccelAbsolute
	uint8_t yAccelAbsolute;  // +0xAD T: sprite.yAccelAbsolute
	uint8_t facing;  // +0xAE T: 0 = faces right, 1 = faces left
	uint8_t side;  // +0xAF T: owner player 0 or 1
	uint8_t kind;  // +0xB0 T: 0xFF = free slot in the object pools; otherwise object/move kind
	uint8_t unresolved_B1;  // +0xB1 T: 6 sites
	uint8_t hitAttrib;  // +0xB2 T: set to 9 by the hit code (27 sites)
	uint8_t hitDirection;  // +0xB3 T: 0 / 3 / 1.. relative direction of the last hit
	uint8_t unresolved_B4[704];  // +0xB4 not resolved (fields around +0xD0..+0xE8 are read by the AI and hit code; +0x344..+0x370 hit-effect state)
	int32_t damageTaken;  // +0x374 T: accumulated by the hit code (+= damage); alive while unresolved life terms at +0x370/+0x378 minus this >= 0
	int32_t unresolved_378;  // +0x378 T: 3 sites, enters the life test
	int32_t unresolved_37C;  // +0x37C T: 7 sites (reduced by 6 on a guarded hit in some states)
	int32_t guardGauge;  // +0x380 T: decreased by hit.guardDamage
	uint8_t unresolved_384[4];  // +0x384
	int32_t unresolved_388;  // +0x388 T: set to 20 on a hit
	int32_t knockMode;  // +0x38C T: hit.knockMode & 3
	uint8_t unresolved_390[16];  // +0x390
	uint8_t edgeFlags;  // +0x3A0 T: bit0 set by Entity_ScreenEdgeCheck when the entity is pushed against the screen edge
	uint8_t unresolved_3A1[3];  // +0x3A1
	int32_t lastHitResult;  // +0x3A4 T: value returned by sub_40ACF0 (damage scaling result)
	uint8_t unresolved_3A8[8];  // +0x3A8 (+0x3A8 is read by 48 sites, meaning not resolved)
	int32_t previousFacing;  // +0x3B0 T: facing before the last turn (Entity_FlipFacingKeepAnchor)
	uint8_t unresolved_3B4[64];  // +0x3B4
};
#pragma pack(pop)

static_assert(sizeof(Qoh98DatHeader) == 0x1C, "Qoh98DatHeader size");
static_assert(offsetof(Qoh98DatHeader, version) == 0x0, "Qoh98DatHeader.version");
static_assert(offsetof(Qoh98DatHeader, imageCount) == 0x4, "Qoh98DatHeader.imageCount");
static_assert(offsetof(Qoh98DatHeader, tileCount) == 0x8, "Qoh98DatHeader.tileCount");
static_assert(offsetof(Qoh98DatHeader, animCount) == 0xC, "Qoh98DatHeader.animCount");
static_assert(offsetof(Qoh98DatHeader, spriteCount) == 0x10, "Qoh98DatHeader.spriteCount");
static_assert(offsetof(Qoh98DatHeader, bodyRectCount) == 0x14, "Qoh98DatHeader.bodyRectCount");
static_assert(offsetof(Qoh98DatHeader, hitBoxCount) == 0x18, "Qoh98DatHeader.hitBoxCount");
static_assert(sizeof(Qoh98TimPathEntry) == 0x104, "Qoh98TimPathEntry size");
static_assert(offsetof(Qoh98TimPathEntry, shortName) == 0x0, "Qoh98TimPathEntry.shortName");
static_assert(offsetof(Qoh98TimPathEntry, sjisAndPath) == 0x8, "Qoh98TimPathEntry.sjisAndPath");
static_assert(sizeof(Qoh98ImageTileRange) == 0x8, "Qoh98ImageTileRange size");
static_assert(offsetof(Qoh98ImageTileRange, firstTile) == 0x0, "Qoh98ImageTileRange.firstTile");
static_assert(offsetof(Qoh98ImageTileRange, tileCount) == 0x4, "Qoh98ImageTileRange.tileCount");
static_assert(sizeof(Qoh98Tile) == 0x104, "Qoh98Tile size");
static_assert(offsetof(Qoh98Tile, x) == 0x0, "Qoh98Tile.x");
static_assert(offsetof(Qoh98Tile, y) == 0x2, "Qoh98Tile.y");
static_assert(offsetof(Qoh98Tile, pixels) == 0x4, "Qoh98Tile.pixels");
static_assert(sizeof(Qoh98AnimRecord) == 0x18, "Qoh98AnimRecord size");
static_assert(offsetof(Qoh98AnimRecord, firstSprite) == 0x0, "Qoh98AnimRecord.firstSprite");
static_assert(offsetof(Qoh98AnimRecord, frameCount) == 0x4, "Qoh98AnimRecord.frameCount");
static_assert(offsetof(Qoh98AnimRecord, bodyRectBase) == 0x8, "Qoh98AnimRecord.bodyRectBase");
static_assert(offsetof(Qoh98AnimRecord, bodyRectCount) == 0xC, "Qoh98AnimRecord.bodyRectCount");
static_assert(offsetof(Qoh98AnimRecord, hitBoxBase) == 0x10, "Qoh98AnimRecord.hitBoxBase");
static_assert(offsetof(Qoh98AnimRecord, hitBoxCount) == 0x14, "Qoh98AnimRecord.hitBoxCount");
static_assert(sizeof(Qoh98Sprite) == 0x34, "Qoh98Sprite size");
static_assert(offsetof(Qoh98Sprite, imageIndex) == 0x0, "Qoh98Sprite.imageIndex");
static_assert(offsetof(Qoh98Sprite, drawX) == 0x4, "Qoh98Sprite.drawX");
static_assert(offsetof(Qoh98Sprite, drawY) == 0x6, "Qoh98Sprite.drawY");
static_assert(offsetof(Qoh98Sprite, duration) == 0x8, "Qoh98Sprite.duration");
static_assert(offsetof(Qoh98Sprite, nextFrame) == 0xC, "Qoh98Sprite.nextFrame");
static_assert(offsetof(Qoh98Sprite, attackLevelAndFlags) == 0xE, "Qoh98Sprite.attackLevelAndFlags");
static_assert(offsetof(Qoh98Sprite, moveFlags) == 0x10, "Qoh98Sprite.moveFlags");
static_assert(offsetof(Qoh98Sprite, clearVelX) == 0x11, "Qoh98Sprite.clearVelX");
static_assert(offsetof(Qoh98Sprite, clearVelY) == 0x12, "Qoh98Sprite.clearVelY");
static_assert(offsetof(Qoh98Sprite, xAccelAbsolute) == 0x13, "Qoh98Sprite.xAccelAbsolute");
static_assert(offsetof(Qoh98Sprite, yAccelAbsolute) == 0x14, "Qoh98Sprite.yAccelAbsolute");
static_assert(offsetof(Qoh98Sprite, tileXform) == 0x15, "Qoh98Sprite.tileXform");
static_assert(offsetof(Qoh98Sprite, landAnim) == 0x16, "Qoh98Sprite.landAnim");
static_assert(offsetof(Qoh98Sprite, anchorRect) == 0x17, "Qoh98Sprite.anchorRect");
static_assert(offsetof(Qoh98Sprite, anchorMode) == 0x18, "Qoh98Sprite.anchorMode");
static_assert(offsetof(Qoh98Sprite, hurtRectFirst) == 0x19, "Qoh98Sprite.hurtRectFirst");
static_assert(offsetof(Qoh98Sprite, hurtRectCount) == 0x1A, "Qoh98Sprite.hurtRectCount");
static_assert(offsetof(Qoh98Sprite, unused_1B) == 0x1B, "Qoh98Sprite.unused_1B");
static_assert(offsetof(Qoh98Sprite, unused_1C) == 0x1C, "Qoh98Sprite.unused_1C");
static_assert(offsetof(Qoh98Sprite, grabRectFirst) == 0x1D, "Qoh98Sprite.grabRectFirst");
static_assert(offsetof(Qoh98Sprite, grabRectCount) == 0x1E, "Qoh98Sprite.grabRectCount");
static_assert(offsetof(Qoh98Sprite, hitBoxFirst) == 0x1F, "Qoh98Sprite.hitBoxFirst");
static_assert(offsetof(Qoh98Sprite, hitBoxCountHere) == 0x20, "Qoh98Sprite.hitBoxCountHere");
static_assert(offsetof(Qoh98Sprite, stanceBits) == 0x21, "Qoh98Sprite.stanceBits");
static_assert(offsetof(Qoh98Sprite, xAccel) == 0x22, "Qoh98Sprite.xAccel");
static_assert(offsetof(Qoh98Sprite, yAccel) == 0x24, "Qoh98Sprite.yAccel");
static_assert(offsetof(Qoh98Sprite, xJerk) == 0x26, "Qoh98Sprite.xJerk");
static_assert(offsetof(Qoh98Sprite, yJerk) == 0x28, "Qoh98Sprite.yJerk");
static_assert(offsetof(Qoh98Sprite, unused_2A) == 0x2A, "Qoh98Sprite.unused_2A");
static_assert(offsetof(Qoh98Sprite, unused_2B) == 0x2B, "Qoh98Sprite.unused_2B");
static_assert(offsetof(Qoh98Sprite, aiMoveClass) == 0x2C, "Qoh98Sprite.aiMoveClass");
static_assert(offsetof(Qoh98Sprite, fxFlags) == 0x30, "Qoh98Sprite.fxFlags");
static_assert(sizeof(Qoh98BodyRect) == 0x8, "Qoh98BodyRect size");
static_assert(offsetof(Qoh98BodyRect, left) == 0x0, "Qoh98BodyRect.left");
static_assert(offsetof(Qoh98BodyRect, top) == 0x2, "Qoh98BodyRect.top");
static_assert(offsetof(Qoh98BodyRect, right) == 0x4, "Qoh98BodyRect.right");
static_assert(offsetof(Qoh98BodyRect, bottom) == 0x6, "Qoh98BodyRect.bottom");
static_assert(sizeof(Qoh98HitBox) == 0x18, "Qoh98HitBox size");
static_assert(offsetof(Qoh98HitBox, left) == 0x0, "Qoh98HitBox.left");
static_assert(offsetof(Qoh98HitBox, top) == 0x2, "Qoh98HitBox.top");
static_assert(offsetof(Qoh98HitBox, right) == 0x4, "Qoh98HitBox.right");
static_assert(offsetof(Qoh98HitBox, bottom) == 0x6, "Qoh98HitBox.bottom");
static_assert(offsetof(Qoh98HitBox, damage) == 0x8, "Qoh98HitBox.damage");
static_assert(offsetof(Qoh98HitBox, unresolved_0A) == 0xA, "Qoh98HitBox.unresolved_0A");
static_assert(offsetof(Qoh98HitBox, guardDamage) == 0xC, "Qoh98HitBox.guardDamage");
static_assert(offsetof(Qoh98HitBox, meterGain) == 0xE, "Qoh98HitBox.meterGain");
static_assert(offsetof(Qoh98HitBox, flags) == 0x10, "Qoh98HitBox.flags");
static_assert(offsetof(Qoh98HitBox, defenderStateMask) == 0x11, "Qoh98HitBox.defenderStateMask");
static_assert(offsetof(Qoh98HitBox, hitClass) == 0x12, "Qoh98HitBox.hitClass");
static_assert(offsetof(Qoh98HitBox, unused_13) == 0x13, "Qoh98HitBox.unused_13");
static_assert(offsetof(Qoh98HitBox, knockMode) == 0x14, "Qoh98HitBox.knockMode");
static_assert(offsetof(Qoh98HitBox, unresolved_16) == 0x16, "Qoh98HitBox.unresolved_16");
static_assert(offsetof(Qoh98HitBox, unused_17) == 0x17, "Qoh98HitBox.unused_17");
static_assert(sizeof(Qoh98CharData) == 0x30, "Qoh98CharData size");
static_assert(offsetof(Qoh98CharData, tiles) == 0x0, "Qoh98CharData.tiles");
static_assert(offsetof(Qoh98CharData, tileCount) == 0x4, "Qoh98CharData.tileCount");
static_assert(offsetof(Qoh98CharData, images) == 0x8, "Qoh98CharData.images");
static_assert(offsetof(Qoh98CharData, imageCount) == 0xC, "Qoh98CharData.imageCount");
static_assert(offsetof(Qoh98CharData, anims) == 0x10, "Qoh98CharData.anims");
static_assert(offsetof(Qoh98CharData, animCount) == 0x14, "Qoh98CharData.animCount");
static_assert(offsetof(Qoh98CharData, sprites) == 0x18, "Qoh98CharData.sprites");
static_assert(offsetof(Qoh98CharData, spriteCount) == 0x1C, "Qoh98CharData.spriteCount");
static_assert(offsetof(Qoh98CharData, bodyRects) == 0x20, "Qoh98CharData.bodyRects");
static_assert(offsetof(Qoh98CharData, bodyRectCount) == 0x24, "Qoh98CharData.bodyRectCount");
static_assert(offsetof(Qoh98CharData, hitBoxes) == 0x28, "Qoh98CharData.hitBoxes");
static_assert(offsetof(Qoh98CharData, hitBoxCount) == 0x2C, "Qoh98CharData.hitBoxCount");
static_assert(sizeof(Qoh98Entity) == 0x3F4, "Qoh98Entity size");
static_assert(offsetof(Qoh98Entity, data) == 0x0, "Qoh98Entity.data");
static_assert(offsetof(Qoh98Entity, animId) == 0x30, "Qoh98Entity.animId");
static_assert(offsetof(Qoh98Entity, nextFrame) == 0x34, "Qoh98Entity.nextFrame");
static_assert(offsetof(Qoh98Entity, frameTimer) == 0x38, "Qoh98Entity.frameTimer");
static_assert(offsetof(Qoh98Entity, unresolved_3C) == 0x3C, "Qoh98Entity.unresolved_3C");
static_assert(offsetof(Qoh98Entity, frameIndex) == 0x40, "Qoh98Entity.frameIndex");
static_assert(offsetof(Qoh98Entity, unresolved_44) == 0x44, "Qoh98Entity.unresolved_44");
static_assert(offsetof(Qoh98Entity, unresolved_48) == 0x48, "Qoh98Entity.unresolved_48");
static_assert(offsetof(Qoh98Entity, unresolved_4C) == 0x4C, "Qoh98Entity.unresolved_4C");
static_assert(offsetof(Qoh98Entity, unresolved_50) == 0x50, "Qoh98Entity.unresolved_50");
static_assert(offsetof(Qoh98Entity, unresolved_54) == 0x54, "Qoh98Entity.unresolved_54");
static_assert(offsetof(Qoh98Entity, animEnded) == 0x58, "Qoh98Entity.animEnded");
static_assert(offsetof(Qoh98Entity, reactionAnim) == 0x5C, "Qoh98Entity.reactionAnim");
static_assert(offsetof(Qoh98Entity, velX) == 0x60, "Qoh98Entity.velX");
static_assert(offsetof(Qoh98Entity, velY) == 0x62, "Qoh98Entity.velY");
static_assert(offsetof(Qoh98Entity, accelX) == 0x64, "Qoh98Entity.accelX");
static_assert(offsetof(Qoh98Entity, accelY) == 0x66, "Qoh98Entity.accelY");
static_assert(offsetof(Qoh98Entity, jerkX) == 0x68, "Qoh98Entity.jerkX");
static_assert(offsetof(Qoh98Entity, jerkY) == 0x6A, "Qoh98Entity.jerkY");
static_assert(offsetof(Qoh98Entity, pushVelX) == 0x6C, "Qoh98Entity.pushVelX");
static_assert(offsetof(Qoh98Entity, pushVelY) == 0x6E, "Qoh98Entity.pushVelY");
static_assert(offsetof(Qoh98Entity, pushAccelX) == 0x70, "Qoh98Entity.pushAccelX");
static_assert(offsetof(Qoh98Entity, pushAccelY) == 0x72, "Qoh98Entity.pushAccelY");
static_assert(offsetof(Qoh98Entity, pushJerkX) == 0x74, "Qoh98Entity.pushJerkX");
static_assert(offsetof(Qoh98Entity, pushJerkY) == 0x76, "Qoh98Entity.pushJerkY");
static_assert(offsetof(Qoh98Entity, slideVelX) == 0x78, "Qoh98Entity.slideVelX");
static_assert(offsetof(Qoh98Entity, unresolved_7A) == 0x7A, "Qoh98Entity.unresolved_7A");
static_assert(offsetof(Qoh98Entity, slideAccelX) == 0x7C, "Qoh98Entity.slideAccelX");
static_assert(offsetof(Qoh98Entity, unresolved_7E) == 0x7E, "Qoh98Entity.unresolved_7E");
static_assert(offsetof(Qoh98Entity, slideJerkX) == 0x80, "Qoh98Entity.slideJerkX");
static_assert(offsetof(Qoh98Entity, unresolved_82) == 0x82, "Qoh98Entity.unresolved_82");
static_assert(offsetof(Qoh98Entity, slideTimer) == 0x84, "Qoh98Entity.slideTimer");
static_assert(offsetof(Qoh98Entity, unresolved_86) == 0x86, "Qoh98Entity.unresolved_86");
static_assert(offsetof(Qoh98Entity, posX) == 0x88, "Qoh98Entity.posX");
static_assert(offsetof(Qoh98Entity, posY) == 0x8C, "Qoh98Entity.posY");
static_assert(offsetof(Qoh98Entity, unresolved_90) == 0x90, "Qoh98Entity.unresolved_90");
static_assert(offsetof(Qoh98Entity, unresolved_94) == 0x94, "Qoh98Entity.unresolved_94");
static_assert(offsetof(Qoh98Entity, unresolved_98) == 0x98, "Qoh98Entity.unresolved_98");
static_assert(offsetof(Qoh98Entity, stanceBits) == 0x9C, "Qoh98Entity.stanceBits");
static_assert(offsetof(Qoh98Entity, reactionHeight) == 0x9D, "Qoh98Entity.reactionHeight");
static_assert(offsetof(Qoh98Entity, attackLevel) == 0x9E, "Qoh98Entity.attackLevel");
static_assert(offsetof(Qoh98Entity, boxFlags) == 0xA0, "Qoh98Entity.boxFlags");
static_assert(offsetof(Qoh98Entity, unresolved_A2) == 0xA2, "Qoh98Entity.unresolved_A2");
static_assert(offsetof(Qoh98Entity, controlBlock) == 0xA4, "Qoh98Entity.controlBlock");
static_assert(offsetof(Qoh98Entity, hitTaken) == 0xA8, "Qoh98Entity.hitTaken");
static_assert(offsetof(Qoh98Entity, xAccelAbsolute) == 0xAC, "Qoh98Entity.xAccelAbsolute");
static_assert(offsetof(Qoh98Entity, yAccelAbsolute) == 0xAD, "Qoh98Entity.yAccelAbsolute");
static_assert(offsetof(Qoh98Entity, facing) == 0xAE, "Qoh98Entity.facing");
static_assert(offsetof(Qoh98Entity, side) == 0xAF, "Qoh98Entity.side");
static_assert(offsetof(Qoh98Entity, kind) == 0xB0, "Qoh98Entity.kind");
static_assert(offsetof(Qoh98Entity, unresolved_B1) == 0xB1, "Qoh98Entity.unresolved_B1");
static_assert(offsetof(Qoh98Entity, hitAttrib) == 0xB2, "Qoh98Entity.hitAttrib");
static_assert(offsetof(Qoh98Entity, hitDirection) == 0xB3, "Qoh98Entity.hitDirection");
static_assert(offsetof(Qoh98Entity, unresolved_B4) == 0xB4, "Qoh98Entity.unresolved_B4");
static_assert(offsetof(Qoh98Entity, damageTaken) == 0x374, "Qoh98Entity.damageTaken");
static_assert(offsetof(Qoh98Entity, unresolved_378) == 0x378, "Qoh98Entity.unresolved_378");
static_assert(offsetof(Qoh98Entity, unresolved_37C) == 0x37C, "Qoh98Entity.unresolved_37C");
static_assert(offsetof(Qoh98Entity, guardGauge) == 0x380, "Qoh98Entity.guardGauge");
static_assert(offsetof(Qoh98Entity, unresolved_384) == 0x384, "Qoh98Entity.unresolved_384");
static_assert(offsetof(Qoh98Entity, unresolved_388) == 0x388, "Qoh98Entity.unresolved_388");
static_assert(offsetof(Qoh98Entity, knockMode) == 0x38C, "Qoh98Entity.knockMode");
static_assert(offsetof(Qoh98Entity, unresolved_390) == 0x390, "Qoh98Entity.unresolved_390");
static_assert(offsetof(Qoh98Entity, edgeFlags) == 0x3A0, "Qoh98Entity.edgeFlags");
static_assert(offsetof(Qoh98Entity, unresolved_3A1) == 0x3A1, "Qoh98Entity.unresolved_3A1");
static_assert(offsetof(Qoh98Entity, lastHitResult) == 0x3A4, "Qoh98Entity.lastHitResult");
static_assert(offsetof(Qoh98Entity, unresolved_3A8) == 0x3A8, "Qoh98Entity.unresolved_3A8");
static_assert(offsetof(Qoh98Entity, previousFacing) == 0x3B0, "Qoh98Entity.previousFacing");
static_assert(offsetof(Qoh98Entity, unresolved_3B4) == 0x3B4, "Qoh98Entity.unresolved_3B4");

static const Han2EnumValue kQoh98TileXformValues[] = {
	{"Q98XF_IDENTITY", (int64_t)(0)},
	{"Q98XF_ROT_90_CW", (int64_t)(1)},
	{"Q98XF_ROT_180", (int64_t)(2)},
	{"Q98XF_ROT_90_CCW", (int64_t)(3)},
	{"Q98XF_FLIP_H", (int64_t)(4)},
	{"Q98XF_TRANSPOSE", (int64_t)(5)},
	{"Q98XF_FLIP_V", (int64_t)(6)},
	{"Q98XF_ANTI_TRANSPOSE", (int64_t)(7)},
};
static const Han2EnumValue kQoh98SpriteMoveFlagsValues[] = {
	{"Q98SMF_SET_X_ACCEL", (int64_t)(1)},
	{"Q98SMF_SET_Y_ACCEL", (int64_t)(2)},
	{"Q98SMF_ON_LAND_JUMP_TO_ANIM", (int64_t)(4)},
};
static const Han2EnumValue kQoh98SpriteFxFlagsValues[] = {
	{"Q98FX_SOUND_SLOT_MASK", (int64_t)(0xF)},
	{"Q98FX_SOUND_BANK_MASK", (int64_t)(0xF0)},
	{"Q98FX_SPAWN_FX_A", (int64_t)(0x10000)},
	{"Q98FX_SPAWN_THROW_FX", (int64_t)(0x20000)},
	{"Q98FX_SET_SCREEN_MODE_4", (int64_t)(0x40000)},
	{"Q98FX_CLEAR_COMBO_STATE", (int64_t)(0x80000)},
	{"Q98FX_SPAWN_FX_B", (int64_t)(0x200000)},
};
static const Han2EnumInfo kQoh98TypesEnums[] = {
	{"Qoh98TileXform", kQoh98TileXformValues, 8, false},
	{"Qoh98SpriteMoveFlags", kQoh98SpriteMoveFlagsValues, 3, true},
	{"Qoh98SpriteFxFlags", kQoh98SpriteFxFlagsValues, 7, true},
};

static const Han2FieldInfo kQoh98DatHeaderFields[] = {
	{"version", 0x0, 4, 1, 0, nullptr, "+0x00 T: read into a throwaway buffer, never compared; 5 in all 14 files"},
	{"imageCount", 0x4, 4, 1, 0, nullptr, "+0x04 T: c0 = TIM path entries = image table entries"},
	{"tileCount", 0x8, 4, 1, 0, nullptr, "+0x08 T: c1 = 260-byte tile blocks"},
	{"animCount", 0xC, 4, 1, 0, nullptr, "+0x0C T: c2 = 24-byte animation records (256 in every file)"},
	{"spriteCount", 0x10, 4, 1, 0, nullptr, "+0x10 T: c3 = 52-byte sprite (frame) records"},
	{"bodyRectCount", 0x14, 4, 1, 0, nullptr, "+0x14 T: c4 = 8-byte body/hurt rectangles"},
	{"hitBoxCount", 0x18, 4, 1, 0, nullptr, "+0x18 T: c5 = 24-byte attack boxes"},
};
static const Han2FieldInfo kQoh98TimPathEntryFields[] = {
	{"shortName", 0x0, 1, 8, 5, nullptr, "+0x00 D: NUL terminated \"Aka0000\", rest of the 8 bytes is 0xCD fill"},
	{"sjisAndPath", 0x8, 1, 252, 5, nullptr, "+0x08 D: CP932 display text then the original build path (\"...\\AKARI\\Aka0000.tim\"), NUL then 0xCD fill; split not read by the game"},
};
static const Han2FieldInfo kQoh98ImageTileRangeFields[] = {
	{"firstTile", 0x0, 4, 1, 1, nullptr, "+0x00 T: first tile index of this image (ranges are contiguous and sum to tileCount) (sub_416EB0: *(a2[2] + 8*img))"},
	{"tileCount", 0x4, 4, 1, 1, nullptr, "+0x04 T: number of tiles drawn for this image (a2[2] + 8*img + 4)"},
};
static const Han2FieldInfo kQoh98TileFields[] = {
	{"x", 0x0, 2, 1, 1, nullptr, "+0x00 T: destination column of the tile inside the 256x256 sprite canvas (multiple of 16, 0..240)"},
	{"y", 0x2, 2, 1, 1, nullptr, "+0x02 T: destination row (multiple of 16, 0..240)"},
	{"pixels", 0x4, 1, 256, 0, nullptr, "+0x04 T: 16x16 palette indices, row-major, values 0..15 (index 0 = transparent) D"},
};
static const Han2FieldInfo kQoh98AnimRecordFields[] = {
	{"firstSprite", 0x0, 4, 1, 1, nullptr, "+0x00 T: index of the first sprite record, -1 = animation unused"},
	{"frameCount", 0x4, 4, 1, 1, nullptr, "+0x04 T: number of sprite records; the step code resets to frame 0 when frameCount < nextFrame (sub_419470) D: next anim firstSprite == firstSprite + frameCount in order"},
	{"bodyRectBase", 0x8, 4, 1, 1, nullptr, "+0x08 T: base index into the body rectangle table; sprite fields +0x17/+0x19/+0x1D are offsets from it; -1 when none"},
	{"bodyRectCount", 0xC, 4, 1, 1, nullptr, "+0x0C D: rectangle count of this animation (contiguous ranges); not read by the game"},
	{"hitBoxBase", 0x10, 4, 1, 1, nullptr, "+0x10 T: base index into the hit box table; sprite field +0x1F is an offset from it; -1 when none"},
	{"hitBoxCount", 0x14, 4, 1, 1, nullptr, "+0x14 D: box count of this animation (contiguous ranges); not read by the game"},
};
static const Han2FieldInfo kQoh98SpriteFields[] = {
	{"imageIndex", 0x0, 4, 1, 1, nullptr, "+0x00 T: index into the image table (a2[2]); out of range = draw nothing (sub_416EB0: v13 < 0 || a2[3] <= v13)"},
	{"drawX", 0x4, 2, 1, 1, nullptr, "+0x04 T: x offset of the 256x256 canvas relative to the entity position (negated when facing left)"},
	{"drawY", 0x6, 2, 1, 1, nullptr, "+0x06 T: y offset (sub_416EB0 divides it by 3 for the shadow pass)"},
	{"duration", 0x8, 4, 1, 1, nullptr, "+0x08 T: copied to entity +0x38 frameTimer (sub_419470)"},
	{"nextFrame", 0xC, 2, 1, 0, nullptr, "+0x0C T: next frame index inside the animation; 0xFFFF = frame+1, 0xFFFE = animation ends (entity +0x34 = 0xFFFE)"},
	{"attackLevelAndFlags", 0xE, 2, 1, 0, nullptr, "+0x0E T: low nibble -> entity +0x9E; bit 0x10 arms the hit boxes (entity flags |= 1)"},
	{"moveFlags", 0x10, 1, 1, 0, nullptr, "+0x10 T: Qoh98SpriteMoveFlags (1 = apply x accel +0x22/+0x26, 2 = apply y accel +0x24/+0x28, 4 = on landing jump to anim +0x16)"},
	{"clearVelX", 0x11, 1, 1, 0, nullptr, "+0x11 T: non-zero zeroes entity velX"},
	{"clearVelY", 0x12, 1, 1, 0, nullptr, "+0x12 T: non-zero zeroes entity velY"},
	{"xAccelAbsolute", 0x13, 1, 1, 0, nullptr, "+0x13 T: copied to entity +0xAC"},
	{"yAccelAbsolute", 0x14, 1, 1, 0, nullptr, "+0x14 T: copied to entity +0xAD"},
	{"tileXform", 0x15, 1, 1, 0, nullptr, "+0x15 T: Qoh98TileXform applied to the tile positions (xor 4 when facing left)"},
	{"landAnim", 0x16, 1, 1, 0, nullptr, "+0x16 T: animation entered on landing when moveFlags & 4 (entity nextFrame = this, else 0xFFFE)"},
	{"anchorRect", 0x17, 1, 1, 0, nullptr, "+0x17 T: body rectangle offset (from anim bodyRectBase) used to align the entity when it turns or leaves the screen (sub_409850, sub_40A780)"},
	{"anchorMode", 0x18, 1, 1, 0, nullptr, "+0x18 T: 0xFF = no anchor (sub_409850 returns 0); 0/1/2 observed"},
	{"hurtRectFirst", 0x19, 1, 1, 0, nullptr, "+0x19 T: first hurt body rectangle, offset from anim bodyRectBase"},
	{"hurtRectCount", 0x1A, 1, 1, 0, nullptr, "+0x1A T: number of hurt rectangles; 0 = invulnerable to hits (sub_40BB30)"},
	{"unused_1B", 0x1B, 1, 1, 0, nullptr, "+0x1B D: 0 in all 14 files, never read"},
	{"unused_1C", 0x1C, 1, 1, 0, nullptr, "+0x1C D: 0 in all 14 files, never read"},
	{"grabRectFirst", 0x1D, 1, 1, 0, nullptr, "+0x1D T: first grab-vulnerable body rectangle, offset from anim bodyRectBase (sub_40B9B0)"},
	{"grabRectCount", 0x1E, 1, 1, 0, nullptr, "+0x1E T: number of grab rectangles; non-zero sets entity flags |= 2"},
	{"hitBoxFirst", 0x1F, 1, 1, 0, nullptr, "+0x1F T: first attack box, offset from anim hitBoxBase"},
	{"hitBoxCountHere", 0x20, 1, 1, 0, nullptr, "+0x20 T: number of attack boxes (0 = none)"},
	{"stanceBits", 0x21, 1, 1, 0, nullptr, "+0x21 T: copied whole to entity +0x9C (low 3 bits = stance class, 0x40 = turn toward opponent via sub_40A780, 0x20/0x80 read by the hit code)"},
	{"xAccel", 0x22, 2, 1, 1, nullptr, "+0x22 T: entity +0x64 when moveFlags & 1 (negated when facing left)"},
	{"yAccel", 0x24, 2, 1, 1, nullptr, "+0x24 T: entity +0x66 when moveFlags & 2"},
	{"xJerk", 0x26, 2, 1, 1, nullptr, "+0x26 T: entity +0x68 when moveFlags & 1"},
	{"yJerk", 0x28, 2, 1, 1, nullptr, "+0x28 T: entity +0x6A when moveFlags & 2"},
	{"unused_2A", 0x2A, 1, 1, 0, nullptr, "+0x2A D: 0xCD in 7106 of 8256 sprites, else 0 (uninitialised build fill), never read"},
	{"unused_2B", 0x2B, 1, 1, 0, nullptr, "+0x2B D: same as +0x2A"},
	{"aiMoveClass", 0x2C, 4, 1, 1, nullptr, "+0x2C T: read by the CPU player code (sub_404300 and 21 more) through *(a2[6] + 52*frame + 44); values 0..11 observed"},
	{"fxFlags", 0x30, 4, 1, 0, nullptr, "+0x30 T: Qoh98SpriteFxFlags: low nibble = sound slot (+16*side), bits 4..7 = second sound, high bits = effects (sub_419470)"},
};
static const Han2FieldInfo kQoh98BodyRectFields[] = {
	{"left", 0x0, 2, 1, 1, nullptr, "+0x00 T: sub_409550 (mirrored as 256 - left when facing left)"},
	{"top", 0x2, 2, 1, 1, nullptr, "+0x02 T"},
	{"right", 0x4, 2, 1, 1, nullptr, "+0x04 T"},
	{"bottom", 0x6, 2, 1, 1, nullptr, "+0x06 T"},
};
static const Han2FieldInfo kQoh98HitBoxFields[] = {
	{"left", 0x0, 2, 1, 1, nullptr, "+0x00 T: sub_409630"},
	{"top", 0x2, 2, 1, 1, nullptr, "+0x02 T"},
	{"right", 0x4, 2, 1, 1, nullptr, "+0x04 T"},
	{"bottom", 0x6, 2, 1, 1, nullptr, "+0x06 T"},
	{"damage", 0x8, 2, 1, 1, nullptr, "+0x08 T: life removed (0 = no damage hit); stance 1 divides by 4, stance 2 multiplies by 125/100 (sub_40BF60)"},
	{"unresolved_0A", 0xA, 2, 1, 1, nullptr, "+0x0A D: 0..10 (999 of 1031 are 0); no reader found"},
	{"guardDamage", 0xC, 2, 1, 1, nullptr, "+0x0C T: subtracted from the defender's guard gauge (entity +0x380) on guard"},
	{"meterGain", 0xE, 2, 1, 1, nullptr, "+0x0E T: passed to sub_41C260 (super gauge gain of the attacker side)"},
	{"flags", 0x10, 1, 1, 0, nullptr, "+0x10 T: bit0 = damaging hit (affects knock back / hit stop)"},
	{"defenderStateMask", 0x11, 1, 1, 0, nullptr, "+0x11 T: bit0/bit1/bit2 = may hit a defender in state 0x12 / 0x13 / 0x14 (sub_40BF60 case 0x12..0x14)"},
	{"hitClass", 0x12, 1, 1, 0, nullptr, "+0x12 T: 0..15; 0..9 select the reaction anim (21..25/33/36), 10 and 11 special (anim 36 / 35), 13..15 projectile clash rules (sub_40A8B0)"},
	{"unused_13", 0x13, 1, 1, 0, nullptr, "+0x13 D: 0 in all 14 files, never read"},
	{"knockMode", 0x14, 2, 1, 0, nullptr, "+0x14 T: bits 0..1 -> defender entity +0x38C (1 = turn defender away); bit0 also tested in sub_40BF60"},
	{"unresolved_16", 0x16, 1, 1, 0, nullptr, "+0x16 D: 0 or 1 (102 of 1031 boxes), no reader found"},
	{"unused_17", 0x17, 1, 1, 0, nullptr, "+0x17 D: 0 in all 14 files"},
};
static const Han2FieldInfo kQoh98CharDataFields[] = {
	{"tiles", 0x0, 4, 1, 4, nullptr, "+0x00 T: 260 * tileCount"},
	{"tileCount", 0x4, 4, 1, 1, nullptr, "+0x04 T: header c1"},
	{"images", 0x8, 4, 1, 4, nullptr, "+0x08 T: 8 * imageCount"},
	{"imageCount", 0xC, 4, 1, 1, nullptr, "+0x0C T: header c0"},
	{"anims", 0x10, 4, 1, 4, nullptr, "+0x10 T: 24 * animCount (a1[4])"},
	{"animCount", 0x14, 4, 1, 1, nullptr, "+0x14 T: header c2"},
	{"sprites", 0x18, 4, 1, 4, nullptr, "+0x18 T: 52 * spriteCount (a1[6])"},
	{"spriteCount", 0x1C, 4, 1, 1, nullptr, "+0x1C T: header c3"},
	{"bodyRects", 0x20, 4, 1, 4, nullptr, "+0x20 T: 8 * bodyRectCount (a1[8])"},
	{"bodyRectCount", 0x24, 4, 1, 1, nullptr, "+0x24 T: header c4"},
	{"hitBoxes", 0x28, 4, 1, 4, nullptr, "+0x28 T: 24 * hitBoxCount (a1[10])"},
	{"hitBoxCount", 0x2C, 4, 1, 1, nullptr, "+0x2C T: header c5"},
};
static const Han2FieldInfo kQoh98EntityFields[] = {
	{"data", 0x0, 48, 1, 4, nullptr, "+0x00 T: sprite/animation data of the owner (copied by value into spawned objects)"},
	{"animId", 0x30, 4, 1, 1, nullptr, "+0x30 T: current animation (index into data.anims)"},
	{"nextFrame", 0x34, 4, 1, 1, nullptr, "+0x34 T: frame that follows the current one; 0xFFFE = animation ends (sub_419470)"},
	{"frameTimer", 0x38, 4, 1, 1, nullptr, "+0x38 T: counts down from sprite.duration"},
	{"unresolved_3C", 0x3C, 4, 1, 1, nullptr, "+0x3C not traced"},
	{"frameIndex", 0x40, 4, 1, 1, nullptr, "+0x40 T: current frame inside the animation (sprite = anim.firstSprite + frameIndex)"},
	{"unresolved_44", 0x44, 4, 1, 1, nullptr, "+0x44 not traced"},
	{"unresolved_48", 0x48, 4, 1, 1, nullptr, "+0x48 T: switch value in sub_40BF60 (0, 0x12, 0x13, 0x14); meaning not resolved"},
	{"unresolved_4C", 0x4C, 4, 1, 1, nullptr, "+0x4C T: read/written by 98 sites; meaning not resolved"},
	{"unresolved_50", 0x50, 4, 1, 1, nullptr, "+0x50 not traced"},
	{"unresolved_54", 0x54, 4, 1, 1, nullptr, "+0x54 T: 50 sites, value 34 compared in the hit code"},
	{"animEnded", 0x58, 4, 1, 1, nullptr, "+0x58 T: set to 1 when the animation ran out (sub_419A10)"},
	{"reactionAnim", 0x5C, 4, 1, 1, nullptr, "+0x5C T: reaction animation requested by the hit code (21..25, 33, 35, 36)"},
	{"velX", 0x60, 2, 1, 1, nullptr, "+0x60 T: 8.8 fixed point, added to posX/256 each tick (sub_419A10)"},
	{"velY", 0x62, 2, 1, 1, nullptr, "+0x62 T: velY"},
	{"accelX", 0x64, 2, 1, 1, nullptr, "+0x64 T: added to velX; loaded from sprite.xAccel"},
	{"accelY", 0x66, 2, 1, 1, nullptr, "+0x66 T: loaded from sprite.yAccel"},
	{"jerkX", 0x68, 2, 1, 1, nullptr, "+0x68 T: added to accelX; loaded from sprite.xJerk"},
	{"jerkY", 0x6A, 2, 1, 1, nullptr, "+0x6A T: loaded from sprite.yJerk"},
	{"pushVelX", 0x6C, 2, 1, 1, nullptr, "+0x6C T: knock back x velocity group (cleared on hit)"},
	{"pushVelY", 0x6E, 2, 1, 1, nullptr, "+0x6E T"},
	{"pushAccelX", 0x70, 2, 1, 1, nullptr, "+0x70 T"},
	{"pushAccelY", 0x72, 2, 1, 1, nullptr, "+0x72 T"},
	{"pushJerkX", 0x74, 2, 1, 1, nullptr, "+0x74 T"},
	{"pushJerkY", 0x76, 2, 1, 1, nullptr, "+0x76 T"},
	{"slideVelX", 0x78, 2, 1, 1, nullptr, "+0x78 T: second x group with a countdown"},
	{"unresolved_7A", 0x7A, 2, 1, 1, nullptr, "+0x7A not touched by sub_419A10"},
	{"slideAccelX", 0x7C, 2, 1, 1, nullptr, "+0x7C T"},
	{"unresolved_7E", 0x7E, 2, 1, 1, nullptr, "+0x7E not touched by sub_419A10"},
	{"slideJerkX", 0x80, 2, 1, 1, nullptr, "+0x80 T"},
	{"unresolved_82", 0x82, 2, 1, 1, nullptr, "+0x82 not touched by sub_419A10"},
	{"slideTimer", 0x84, 2, 1, 1, nullptr, "+0x84 T: decremented each tick while non-zero"},
	{"unresolved_86", 0x86, 2, 1, 1, nullptr, "+0x86 not touched"},
	{"posX", 0x88, 4, 1, 1, nullptr, "+0x88 T: world x, rectangles are relative to this"},
	{"posY", 0x8C, 4, 1, 1, nullptr, "+0x8C T: world y"},
	{"unresolved_90", 0x90, 4, 1, 1, nullptr, "+0x90 not traced"},
	{"unresolved_94", 0x94, 4, 1, 1, nullptr, "+0x94 not traced"},
	{"unresolved_98", 0x98, 4, 1, 1, nullptr, "+0x98 T: 1 site"},
	{"stanceBits", 0x9C, 1, 1, 0, nullptr, "+0x9C T: sprite.stanceBits copy"},
	{"reactionHeight", 0x9D, 1, 1, 0, nullptr, "+0x9D T: 0/1/2 written by the hit code (high / mid / low)"},
	{"attackLevel", 0x9E, 2, 1, 0, nullptr, "+0x9E T: sprite.attackLevelAndFlags & 0xF"},
	{"boxFlags", 0xA0, 2, 1, 0, nullptr, "+0xA0 T: bit0 = hit boxes armed, bit1 = grab rectangles present"},
	{"unresolved_A2", 0xA2, 1, 2, 0, nullptr, "+0xA2 not traced"},
	{"controlBlock", 0xA4, 4, 1, 4, nullptr, "+0xA4 T: pointer used by 275 sites (input/controller block of the owner); *(ptr+408) and *(ptr+412) cleared when an animation ends"},
	{"hitTaken", 0xA8, 4, 1, 1, nullptr, "+0xA8 T: set to 1 once the entity has been hit (sub_40AF70)"},
	{"xAccelAbsolute", 0xAC, 1, 1, 0, nullptr, "+0xAC T: sprite.xAccelAbsolute"},
	{"yAccelAbsolute", 0xAD, 1, 1, 0, nullptr, "+0xAD T: sprite.yAccelAbsolute"},
	{"facing", 0xAE, 1, 1, 0, nullptr, "+0xAE T: 0 = faces right, 1 = faces left"},
	{"side", 0xAF, 1, 1, 0, nullptr, "+0xAF T: owner player 0 or 1"},
	{"kind", 0xB0, 1, 1, 0, nullptr, "+0xB0 T: 0xFF = free slot in the object pools; otherwise object/move kind"},
	{"unresolved_B1", 0xB1, 1, 1, 0, nullptr, "+0xB1 T: 6 sites"},
	{"hitAttrib", 0xB2, 1, 1, 0, nullptr, "+0xB2 T: set to 9 by the hit code (27 sites)"},
	{"hitDirection", 0xB3, 1, 1, 0, nullptr, "+0xB3 T: 0 / 3 / 1.. relative direction of the last hit"},
	{"unresolved_B4", 0xB4, 1, 704, 0, nullptr, "+0xB4 not resolved (fields around +0xD0..+0xE8 are read by the AI and hit code; +0x344..+0x370 hit-effect state)"},
	{"damageTaken", 0x374, 4, 1, 1, nullptr, "+0x374 T: accumulated by the hit code (+= damage); alive while unresolved life terms at +0x370/+0x378 minus this >= 0"},
	{"unresolved_378", 0x378, 4, 1, 1, nullptr, "+0x378 T: 3 sites, enters the life test"},
	{"unresolved_37C", 0x37C, 4, 1, 1, nullptr, "+0x37C T: 7 sites (reduced by 6 on a guarded hit in some states)"},
	{"guardGauge", 0x380, 4, 1, 1, nullptr, "+0x380 T: decreased by hit.guardDamage"},
	{"unresolved_384", 0x384, 1, 4, 0, nullptr, "+0x384"},
	{"unresolved_388", 0x388, 4, 1, 1, nullptr, "+0x388 T: set to 20 on a hit"},
	{"knockMode", 0x38C, 4, 1, 1, nullptr, "+0x38C T: hit.knockMode & 3"},
	{"unresolved_390", 0x390, 1, 16, 0, nullptr, "+0x390"},
	{"edgeFlags", 0x3A0, 1, 1, 0, nullptr, "+0x3A0 T: bit0 set by Entity_ScreenEdgeCheck when the entity is pushed against the screen edge"},
	{"unresolved_3A1", 0x3A1, 1, 3, 0, nullptr, "+0x3A1"},
	{"lastHitResult", 0x3A4, 4, 1, 1, nullptr, "+0x3A4 T: value returned by sub_40ACF0 (damage scaling result)"},
	{"unresolved_3A8", 0x3A8, 1, 8, 0, nullptr, "+0x3A8 (+0x3A8 is read by 48 sites, meaning not resolved)"},
	{"previousFacing", 0x3B0, 4, 1, 1, nullptr, "+0x3B0 T: facing before the last turn (Entity_FlipFacingKeepAnchor)"},
	{"unresolved_3B4", 0x3B4, 1, 64, 0, nullptr, "+0x3B4"},
};
