// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"


#pragma pack(push, 1)
struct RboSection4Record {
	int32_t event_type;  // +0x0 D: record kind.
	int32_t param0;  // +0x4 D: first parameter, 0..512, meaning depends on event_type
	int32_t param1;  // +0x8 D: second parameter, 0..10011 (type 1 holds CG-image-id style values 10008/10011 = 10000+n like frame spriteId)
	int32_t param2;  // +0xC D: third parameter, 0..75
	int32_t param3;  // +0x10 D: fourth parameter, only {0:2948, 3:114, 10:47, 1:6}: type 1:0..3, 6:1..3, 7:3, 14:0..3, 15:0 or 10, 249:0..3; others always 0.
	int32_t unused_14;  // +0x14 Z: 0 in 3115/3115 records; no reader in any of the 4 executables.
	int32_t unused_18;  // +0x18 Z: 0 in 3115/3115 records; no reader in any of the 4 executables.
};
struct RboSection5Record {
	uint8_t event_type;  // +0x0 D: record kind {1:826, 3:685, 249:356, 6:319, 4:252, 9:46, 2:29, 254:4, 235:3, 250:2}; 249 = "none" (all fields 0 except event_id 0/1 in a few).
	uint8_t event_id;  // +0x1 D: 0..126, 53 distinct
	int16_t value0;  // +0x2 D: signed
	int16_t value1;  // +0x4 D: signed
	int16_t value2;  // +0x6 D: 0..309, 16 distinct, 0 in 1980/2522 (type 1:0..64, 3:0..30, 6:0..30, 2:0..309).
	int16_t value3;  // +0x8 D: 0..445, 13 distinct, 0 in 2281/2522 (type 3:0..50, 6:0..30, 2:0..445, 1:0..4).
	int16_t value4;  // +0xA D: 0..15, 8 distinct, 0 in 2296/2522 (type 3:0..15, 4:0..10, 6:0..10, 1:0..3).
	int32_t unused_0C;  // +0xC Z: 0 in 2522/2522 records; no reader in any of the 4 executables.
	int32_t unused_10;  // +0x10 Z: 0 in 2522/2522 records; no reader in any of the 4 executables.
};
#pragma pack(pop)

static_assert(sizeof(RboSection4Record) == 0x1C, "RboSection4Record size");
static_assert(offsetof(RboSection4Record, event_type) == 0x0, "RboSection4Record.event_type");
static_assert(offsetof(RboSection4Record, param0) == 0x4, "RboSection4Record.param0");
static_assert(offsetof(RboSection4Record, param1) == 0x8, "RboSection4Record.param1");
static_assert(offsetof(RboSection4Record, param2) == 0xC, "RboSection4Record.param2");
static_assert(offsetof(RboSection4Record, param3) == 0x10, "RboSection4Record.param3");
static_assert(offsetof(RboSection4Record, unused_14) == 0x14, "RboSection4Record.unused_14");
static_assert(offsetof(RboSection4Record, unused_18) == 0x18, "RboSection4Record.unused_18");
static_assert(sizeof(RboSection5Record) == 0x14, "RboSection5Record size");
static_assert(offsetof(RboSection5Record, event_type) == 0x0, "RboSection5Record.event_type");
static_assert(offsetof(RboSection5Record, event_id) == 0x1, "RboSection5Record.event_id");
static_assert(offsetof(RboSection5Record, value0) == 0x2, "RboSection5Record.value0");
static_assert(offsetof(RboSection5Record, value1) == 0x4, "RboSection5Record.value1");
static_assert(offsetof(RboSection5Record, value2) == 0x6, "RboSection5Record.value2");
static_assert(offsetof(RboSection5Record, value3) == 0x8, "RboSection5Record.value3");
static_assert(offsetof(RboSection5Record, value4) == 0xA, "RboSection5Record.value4");
static_assert(offsetof(RboSection5Record, unused_0C) == 0xC, "RboSection5Record.unused_0C");
static_assert(offsetof(RboSection5Record, unused_10) == 0x10, "RboSection5Record.unused_10");

static const Han2EnumInfo kRboSec45Enums[] = {
};

static const Han2FieldInfo kRboSection4RecordFields[] = {
	{"event_type", 0x0, 4, 1, 1, nullptr, "+0x0 D: record kind."},
	{"param0", 0x4, 4, 1, 1, nullptr, "+0x4 D: first parameter, 0..512, meaning depends on event_type"},
	{"param1", 0x8, 4, 1, 1, nullptr, "+0x8 D: second parameter, 0..10011 (type 1 holds CG-image-id style values 10008/10011 = 10000+n like frame spriteId)"},
	{"param2", 0xC, 4, 1, 1, nullptr, "+0xC D: third parameter, 0..75"},
	{"param3", 0x10, 4, 1, 1, nullptr, "+0x10 D: fourth parameter, only {0:2948, 3:114, 10:47, 1:6}: type 1:0..3, 6:1..3, 7:3, 14:0..3, 15:0 or 10, 249:0..3; others always 0."},
	{"unused_14", 0x14, 4, 1, 1, nullptr, "+0x14 Z: 0 in 3115/3115 records; no reader in any of the 4 executables."},
	{"unused_18", 0x18, 4, 1, 1, nullptr, "+0x18 Z: 0 in 3115/3115 records; no reader in any of the 4 executables."},
};
static const Han2FieldInfo kRboSection5RecordFields[] = {
	{"event_type", 0x0, 1, 1, 0, nullptr, "+0x0 D: record kind {1:826, 3:685, 249:356, 6:319, 4:252, 9:46, 2:29, 254:4, 235:3, 250:2}; 249 = \"none\" (all fields 0 except event_id 0/1 in a few)."},
	{"event_id", 0x1, 1, 1, 0, nullptr, "+0x1 D: 0..126, 53 distinct"},
	{"value0", 0x2, 2, 1, 1, nullptr, "+0x2 D: signed"},
	{"value1", 0x4, 2, 1, 1, nullptr, "+0x4 D: signed"},
	{"value2", 0x6, 2, 1, 1, nullptr, "+0x6 D: 0..309, 16 distinct, 0 in 1980/2522 (type 1:0..64, 3:0..30, 6:0..30, 2:0..309)."},
	{"value3", 0x8, 2, 1, 1, nullptr, "+0x8 D: 0..445, 13 distinct, 0 in 2281/2522 (type 3:0..50, 6:0..30, 2:0..445, 1:0..4)."},
	{"value4", 0xA, 2, 1, 1, nullptr, "+0xA D: 0..15, 8 distinct, 0 in 2296/2522 (type 3:0..15, 4:0..10, 6:0..10, 1:0..3)."},
	{"unused_0C", 0xC, 4, 1, 1, nullptr, "+0xC Z: 0 in 2522/2522 records; no reader in any of the 4 executables."},
	{"unused_10", 0x10, 4, 1, 1, nullptr, "+0x10 Z: 0 in 2522/2522 records; no reader in any of the 4 executables."},
};
