// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>

enum RboAniFlag : uint8_t {
	ANI_END_TO_PATTERN = 0,
	ANI_NEXT = 1,
	ANI_JUMP_TO_FRAME = 2,
	ANI_NEXT_LAND_TO_PATTERN = 3,
	ANI_JUMP_TO_FRAME_LAND_TO_PATTERN = 4,
	ANI_LOOP_COUNTED = 5,
	ANI_STEP_BACK = 6,
	ANI_NEXT_WHILE_CHANNEL_ACTIVE = 7,
	ANI_LOOP_COUNTED_TO_LOOP_FRAME = 8,
	ANI_NEXT_UNTIL_CHANNEL_ENDS = 9,
};
enum RboFlipMode : uint8_t {
	FLIP_NONE = 0,
	FLIP_H = 1,
	FLIP_V = 2,
	ROT_90 = 3,
	ROT_180 = 4,
	ROT_270 = 5,
	FLIP_H_ROT_90 = 6,
	FLIP_H_ROT_270 = 7,
	ROT_FREE = 8,
	FLIP_H_ROT_FREE = 9,
};
enum RboBlendMode : uint8_t {
	BLEND_OPAQUE = 0,
	BLEND_ALPHA = 1,
	BLEND_ADDITIVE = 2,
	BLEND_SUBTRACTIVE = 3,
};
enum RboFrameFxFlags : uint8_t {
	FXF_USE_ZOOM = 1,
	FXF_USE_ALPHA_FADE = 2,
};
enum RboMoveFlags : uint8_t {
	MOVE_CLEAR_VEL_X = 1,
	MOVE_CLEAR_VEL_Y = 2,
	MOVE_ADD_X = 4,
	MOVE_ADD_Y = 8,
};
enum RboStanceClass : uint8_t {
	STANCE_NONE = 0,
	STANCE_GROUND = 1,
	STANCE_CROUCH = 2,
	STANCE_AIR = 4,
};
enum RboCancelPermission : uint8_t {
	CANCEL_NONE = 0,
	CANCEL_ON_INPUT_MATCH = 1,
	CANCEL_ALWAYS = 2,
};
enum RboAttackEventFlags : uint8_t {
	ATKEV_BEGIN = 1,
	ATKEV_END = 2,
	ATKEV_KASANARI_BEGIN = 4,
	ATKEV_KASANARI_END = 8,
	ATKEV_KEEP_HIT_MEMORY = 0x10,
};
enum RboHurtMaskFlags : uint32_t {
	HMF_NO_CLASS_8 = 0x100,
	HMF_NO_CLASS_9 = 0x200,
	HMF_NO_CLASS_0 = 0x10000,
	HMF_NO_CLASS_1 = 0x20000,
	HMF_NO_CLASS_2 = 0x40000,
	HMF_NO_CLASS_3 = 0x80000,
	HMF_NO_CLASS_4 = 0x100000,
	HMF_NO_CLASS_5 = 0x400000,
	HMF_NO_CLASS_6 = 0x800000,
};
enum RboMotionFlags : uint8_t {
	MOTF_BRAKE_ON_ENTER = 4,
};
enum RboScriptOrderFlags : uint8_t {
	SCRIPTORD_LIST_A_FIRST = 1,
};
enum RboPatternFlags : uint32_t {
	PATF_NONE = 0,
	PATF_FLAG_2 = 2,
	PATF_ALT_DRAW_MODE = 0x40,
	PATF_FLAG_80 = 0x80,
};
enum RboHan2Kind : uint32_t {
	HAN2_KIND_FULL_DAT = 0,
	HAN2_KIND_PATTERN_ONLY_DT2 = 3,
};

#pragma pack(push, 1)
struct RboFrameRecord {
	int16_t spriteId;  // +0x00 CG image = id-10000 when >=10000, else PAT pose index (Actor_GetFrameSpriteId 0x440B10, Actor_DrawTree 0x4483E0)
	int16_t offsetX;  // +0x02 Actor_DrawTree: draw offset X
	int16_t offsetY;  // +0x04 Actor_DrawTree: draw offset Y
	uint16_t duration;  // +0x06 Actor_TickFrame 0x43F830: ticks before advance
	RboFlipMode flipMode;  // +0x08 Actor_DrawTree indexes the draw-mode table dword_48AE2C
	RboBlendMode blendMode;  // +0x09 Actor_EnterFrame copies non-zero to actor+744
	uint8_t alpha;  // +0x0A alpha fade target when fxFlags.USE_ALPHA_FADE (Actor_EnterFrame)
	RboAniFlag aniFlag;  // +0x0B Actor_AdvanceByAniFlag 0x43F640
	uint8_t jumpTarget;  // +0x0C pattern (ANI_END_TO_PATTERN) or frame to jump to
	uint8_t landJumpTarget;  // +0x0D Actor_ApplyLandJump 0x440A50
	uint8_t drawPriorityCode;  // +0x0E sub_440DF0 (1..11 set layer, 12..19 add depth, 20..61 offset table dword_48A3B8)
	uint8_t unused_0F;  // +0x0F zero in all 57786 RBO frames, no reader found
	uint16_t zoom;  // +0x10 256 = 1.0; Actor_EnterFrame -> sub_4496A0 when fxFlags.USE_ZOOM
	uint8_t loopCount;  // +0x12 ANI_LOOP_COUNTED repeat count (Actor_EnterFrame -> actor+108)
	uint8_t loopEndFrame;  // +0x13 frame jumped to when the loop is exhausted (Actor_ResolveNextFrameRecord 0x440970)
	uint8_t unused_14[4];  // +0x14 zero in all frames, no reader found
	uint8_t interpolationMode;  // +0x18 non-zero = tween toward next frame (Actor_GetFrameInterpolation 0x445A50)
	RboFrameFxFlags fxFlags;  // +0x19 Actor_EnterFrame
	uint8_t unused_1A[2];  // +0x1A zero in all frames, no reader found
	uint8_t unused_1C[12];  // +0x1C..0x27 zero in all frames, no reader found
	RboMoveFlags moveFlags;  // +0x28 Actor_FrameMoveClearAxes 0x44B390, Actor_FrameMoveAddSpeed 0x44B3D0
	uint8_t unused_29[3];  // +0x29 zero in all frames (the flags byte is never read as a dword)
	int16_t speedX;  // +0x2C added to velocity X when MOVE_ADD_X (flip-aware)
	int16_t speedY;  // +0x2E added to velocity Y when MOVE_ADD_Y
	int16_t accelX;  // +0x30 added to acceleration X when MOVE_ADD_X
	int16_t accelY;  // +0x32 added to acceleration Y when MOVE_ADD_Y
	RboStanceClass stanceClass;  // +0x34 becomes actor+2072, tested by script condition sub_4187C0
	RboCancelPermission normalCancel;  // +0x35 sub_4189E0, sub_43DBE0, sub_43DC70
	RboCancelPermission specialCancel;  // +0x36 sub_4189E0
	uint8_t unused_37;  // +0x37 zero in all frames, no reader found
	RboAttackEventFlags attackEventFlags;  // +0x38 Actor_UpdateAttackState 0x441060, Actor_UpdateBoxes272State 0x4412A0
	uint8_t unused_39[3];  // +0x39 zero in all frames, no reader found
	uint32_t hurtMaskEnable;  // +0x3C 0 = actor hurt mask forced to 0 (Actor_ApplyFrameStatusFlags 0x441330)
	RboHurtMaskFlags hurtMaskFlags;  // +0x40 Actor_ApplyFrameStatusFlags
	uint8_t unused_44[4];  // +0x44 non-zero in only 22 of 57786 frames; no reader found
	uint32_t hitLimitFlags;  // +0x48 copied to the hit limiter flags on ATKEV_BEGIN (sub_441020 0x441020, sub_4429E0)
	uint32_t hitLimitCount;  // +0x4C copied to the hit limiter hit count
	uint8_t unused_50[12];  // +0x50..0x5B zero in all frames, no reader found
	RboMotionFlags motionFlags;  // +0x5C sub_43F0E0 0x43F0E0
	uint8_t unused_5D[3];  // +0x5D zero in all frames, no reader found
	uint8_t unused_60[88];  // +0x60..0xB7 zero in all 57786 RBO frames, no reader found
	RboScriptOrderFlags scriptOrderFlags;  // +0xB8 Actor_EnterFrame
	uint8_t unused_B9[3];  // +0xB9 zero in all frames
	uint32_t scriptListIndexA;  // +0xBC index into pattern-area section 6 (Actor_RunFrameScriptList6 0x41DA50), 0 = none
	uint32_t scriptListIndexB;  // +0xC0 index into section 7 (Actor_RunFrameScriptList7 0x41F900), 0 = none
	uint32_t hasAttack;  // +0xC4 1 when attackRecordIdx is valid
	int32_t attackRecordIdx;  // +0xC8 index into section 3 (120-byte AT records, Actor_CollectAttackBoxes2 0x440F40), -1 none
	uint8_t unused_CC[4];  // +0xCC not read by the RBO engine; 0/-1/small values, 0xCDCD uninitialised fill in 1873 frames
	int32_t sousaiBoxCount;  // +0xD0 clash boxes (CAppHanteiSousai in GOF2); RBO engine never reads this group
	int32_t sousaiBoxIdx[3];  // +0xD4 section 2 box indices, -1 = empty
	int32_t tobiBoxCount;  // +0xE0 projectile-hit boxes (CAppHanteiTobi in GOF2); RBO engine never reads this group
	int32_t tobiBoxIdx[4];  // +0xE4
	int32_t effectBoxEnable;  // +0xF4 Actor_PickBoxRect_244 0x442190: >0 use effectBoxIdx as hit-spark rect, else random hurt box
	int32_t effectBoxIdx;  // +0xF8
	int32_t hurtBoxCount;  // +0xFC Actor_CollectHurtBoxes3 0x441120
	int32_t hurtBoxIdx[3];  // +0x100
	int32_t kasanariBoxEnable;  // +0x10C overlap/push box present (Actor_CollectBoxes2_272 0x4411E0)
	int32_t kasanariBoxIdx[4];  // +0x110 engine reads the first 2; GOF2 CAppHanteiKasanari reads 1
	int32_t attackBoxCount;  // +0x120 Actor_CollectAttackBoxes2
	int32_t attackBoxIdx[2];  // +0x124
};
struct RboPatternEntry {
	uint32_t frameCount;  // +0x0 0 = pattern absent (Actor_GetFrameSpriteId)
	RboPatternFlags flags;  // +0x4 Actor_CacheCurrentFrame 0x440920; values seen 0,2,0x40,0x80
	uint32_t firstFrameIndex;  // +0x8 index into section 1 (frames are packed in pattern order)
};
struct RboHan2AreaRef {
	uint32_t offset;  // +0x0 absolute file offset (a .DT2 keeps the .DAT's offsets for areas it does not carry)
	uint32_t size;  // +0x4 0 = area absent
};
struct RboHan2FileHeader {
	char signature[8];  // +0x00 "HAN2RBO " (never checked by the RBO engine; tools check it)
	RboHan2Kind kind;  // +0x08 not read by the engine; 0 = full .DAT, 3 = pattern-area-only .DT2
	uint32_t unused_0C;  // +0x0C zero in all 346 RBO / 68 GOF2 files, not read
	uint32_t version;  // +0x10 always 2, not read by the RBO engine
	uint32_t unused_14;  // +0x14 zero in all files, not read
	uint32_t subVersion;  // +0x18 1 = RBO layout (300-byte frames, 8 sections), 2 = GOF2 layout; not read by the RBO engine
	uint32_t xorFlag;  // +0x1C non-zero = pattern area is XOR-obfuscated (Han2Dat_DecryptBlockIfFlag 0x403430); 0 in every shipped file
	RboHan2AreaRef patternArea;  // +0x20 section table + sections (Han2Dat_LoadPatternAreaAndResolve 0x403630); taken from the .DT2 when it exists
	RboHan2AreaRef partsPat;  // +0x28 PAT v3 block (Han2Dat_LoadPartsPatBlock 0x4037D0), always from the .DAT
	RboHan2AreaRef cgBank;  // +0x30 BMP Cutter3 bank (Han2Dat_LoadCgBank 0x4038F0), always from the .DAT
	RboHan2AreaRef patternNames;  // +0x38 256 x 64-byte CP932 names; not read by the engine (editor data)
};
struct RboPatternAreaHeader {
	uint32_t unused_00;  // +0x00 zero in all 346 files, not read
	uint32_t editorMark1;  // +0x04 3 in 345 files, 2 in one; not read by the engine (GOF2 stores 8)
	uint32_t unused_08;  // +0x08 zero in all files, not read
	uint32_t editorMark2;  // +0x0C 1 in all RBO files; not read by the engine (GOF2 stores 5)
	uint32_t unused_10[7];  // +0x10..0x2B zero in all files, not read
	uint32_t sectionSize[8];  // +0x2C section byte sizes (Han2Dat_ComputeSectionPointers a1[11..18]); 0 = absent
	uint32_t unused_4C[3];  // +0x4C zero in all files, not read
};
struct RboPatternAreaView {
	uint32_t base;  // +0x00 GlobalAlloc block holding the whole pattern area
	uint32_t patterns;  // +0x04 section 0: 256 x 12 bytes
	uint32_t frames;  // +0x08 section 1: 300-byte records
	uint32_t boxes;  // +0x0C section 2: 8-byte i16 x1,y1,x2,y2 rectangles
	uint32_t attackRecords;  // +0x10 section 3: 120-byte AT records
	uint32_t section4;  // +0x14 section 4 (196 bytes in ACOLYTE_F)
	uint32_t section5;  // +0x18 section 5 (40 bytes in ACOLYTE_F)
	uint32_t scriptListsA;  // +0x1C section 6: 20-byte script id lists
	uint32_t scriptListsB;  // +0x20 section 7: 20-byte script id lists
};
struct RboBoxRect {
	int16_t x1;  // +0x0 Actor_PickBoxRect_244 0x442190 copies four shorts
	int16_t y1;  // +0x2
	int16_t x2;  // +0x4
	int16_t y2;  // +0x6
};
#pragma pack(pop)

static_assert(sizeof(RboFrameRecord) == 0x12C, "RboFrameRecord size");
static_assert(offsetof(RboFrameRecord, spriteId) == 0x0, "RboFrameRecord.spriteId");
static_assert(offsetof(RboFrameRecord, offsetX) == 0x2, "RboFrameRecord.offsetX");
static_assert(offsetof(RboFrameRecord, offsetY) == 0x4, "RboFrameRecord.offsetY");
static_assert(offsetof(RboFrameRecord, duration) == 0x6, "RboFrameRecord.duration");
static_assert(offsetof(RboFrameRecord, flipMode) == 0x8, "RboFrameRecord.flipMode");
static_assert(offsetof(RboFrameRecord, blendMode) == 0x9, "RboFrameRecord.blendMode");
static_assert(offsetof(RboFrameRecord, alpha) == 0xA, "RboFrameRecord.alpha");
static_assert(offsetof(RboFrameRecord, aniFlag) == 0xB, "RboFrameRecord.aniFlag");
static_assert(offsetof(RboFrameRecord, jumpTarget) == 0xC, "RboFrameRecord.jumpTarget");
static_assert(offsetof(RboFrameRecord, landJumpTarget) == 0xD, "RboFrameRecord.landJumpTarget");
static_assert(offsetof(RboFrameRecord, drawPriorityCode) == 0xE, "RboFrameRecord.drawPriorityCode");
static_assert(offsetof(RboFrameRecord, unused_0F) == 0xF, "RboFrameRecord.unused_0F");
static_assert(offsetof(RboFrameRecord, zoom) == 0x10, "RboFrameRecord.zoom");
static_assert(offsetof(RboFrameRecord, loopCount) == 0x12, "RboFrameRecord.loopCount");
static_assert(offsetof(RboFrameRecord, loopEndFrame) == 0x13, "RboFrameRecord.loopEndFrame");
static_assert(offsetof(RboFrameRecord, unused_14) == 0x14, "RboFrameRecord.unused_14");
static_assert(offsetof(RboFrameRecord, interpolationMode) == 0x18, "RboFrameRecord.interpolationMode");
static_assert(offsetof(RboFrameRecord, fxFlags) == 0x19, "RboFrameRecord.fxFlags");
static_assert(offsetof(RboFrameRecord, unused_1A) == 0x1A, "RboFrameRecord.unused_1A");
static_assert(offsetof(RboFrameRecord, unused_1C) == 0x1C, "RboFrameRecord.unused_1C");
static_assert(offsetof(RboFrameRecord, moveFlags) == 0x28, "RboFrameRecord.moveFlags");
static_assert(offsetof(RboFrameRecord, unused_29) == 0x29, "RboFrameRecord.unused_29");
static_assert(offsetof(RboFrameRecord, speedX) == 0x2C, "RboFrameRecord.speedX");
static_assert(offsetof(RboFrameRecord, speedY) == 0x2E, "RboFrameRecord.speedY");
static_assert(offsetof(RboFrameRecord, accelX) == 0x30, "RboFrameRecord.accelX");
static_assert(offsetof(RboFrameRecord, accelY) == 0x32, "RboFrameRecord.accelY");
static_assert(offsetof(RboFrameRecord, stanceClass) == 0x34, "RboFrameRecord.stanceClass");
static_assert(offsetof(RboFrameRecord, normalCancel) == 0x35, "RboFrameRecord.normalCancel");
static_assert(offsetof(RboFrameRecord, specialCancel) == 0x36, "RboFrameRecord.specialCancel");
static_assert(offsetof(RboFrameRecord, unused_37) == 0x37, "RboFrameRecord.unused_37");
static_assert(offsetof(RboFrameRecord, attackEventFlags) == 0x38, "RboFrameRecord.attackEventFlags");
static_assert(offsetof(RboFrameRecord, unused_39) == 0x39, "RboFrameRecord.unused_39");
static_assert(offsetof(RboFrameRecord, hurtMaskEnable) == 0x3C, "RboFrameRecord.hurtMaskEnable");
static_assert(offsetof(RboFrameRecord, hurtMaskFlags) == 0x40, "RboFrameRecord.hurtMaskFlags");
static_assert(offsetof(RboFrameRecord, unused_44) == 0x44, "RboFrameRecord.unused_44");
static_assert(offsetof(RboFrameRecord, hitLimitFlags) == 0x48, "RboFrameRecord.hitLimitFlags");
static_assert(offsetof(RboFrameRecord, hitLimitCount) == 0x4C, "RboFrameRecord.hitLimitCount");
static_assert(offsetof(RboFrameRecord, unused_50) == 0x50, "RboFrameRecord.unused_50");
static_assert(offsetof(RboFrameRecord, motionFlags) == 0x5C, "RboFrameRecord.motionFlags");
static_assert(offsetof(RboFrameRecord, unused_5D) == 0x5D, "RboFrameRecord.unused_5D");
static_assert(offsetof(RboFrameRecord, unused_60) == 0x60, "RboFrameRecord.unused_60");
static_assert(offsetof(RboFrameRecord, scriptOrderFlags) == 0xB8, "RboFrameRecord.scriptOrderFlags");
static_assert(offsetof(RboFrameRecord, unused_B9) == 0xB9, "RboFrameRecord.unused_B9");
static_assert(offsetof(RboFrameRecord, scriptListIndexA) == 0xBC, "RboFrameRecord.scriptListIndexA");
static_assert(offsetof(RboFrameRecord, scriptListIndexB) == 0xC0, "RboFrameRecord.scriptListIndexB");
static_assert(offsetof(RboFrameRecord, hasAttack) == 0xC4, "RboFrameRecord.hasAttack");
static_assert(offsetof(RboFrameRecord, attackRecordIdx) == 0xC8, "RboFrameRecord.attackRecordIdx");
static_assert(offsetof(RboFrameRecord, unused_CC) == 0xCC, "RboFrameRecord.unused_CC");
static_assert(offsetof(RboFrameRecord, sousaiBoxCount) == 0xD0, "RboFrameRecord.sousaiBoxCount");
static_assert(offsetof(RboFrameRecord, sousaiBoxIdx) == 0xD4, "RboFrameRecord.sousaiBoxIdx");
static_assert(offsetof(RboFrameRecord, tobiBoxCount) == 0xE0, "RboFrameRecord.tobiBoxCount");
static_assert(offsetof(RboFrameRecord, tobiBoxIdx) == 0xE4, "RboFrameRecord.tobiBoxIdx");
static_assert(offsetof(RboFrameRecord, effectBoxEnable) == 0xF4, "RboFrameRecord.effectBoxEnable");
static_assert(offsetof(RboFrameRecord, effectBoxIdx) == 0xF8, "RboFrameRecord.effectBoxIdx");
static_assert(offsetof(RboFrameRecord, hurtBoxCount) == 0xFC, "RboFrameRecord.hurtBoxCount");
static_assert(offsetof(RboFrameRecord, hurtBoxIdx) == 0x100, "RboFrameRecord.hurtBoxIdx");
static_assert(offsetof(RboFrameRecord, kasanariBoxEnable) == 0x10C, "RboFrameRecord.kasanariBoxEnable");
static_assert(offsetof(RboFrameRecord, kasanariBoxIdx) == 0x110, "RboFrameRecord.kasanariBoxIdx");
static_assert(offsetof(RboFrameRecord, attackBoxCount) == 0x120, "RboFrameRecord.attackBoxCount");
static_assert(offsetof(RboFrameRecord, attackBoxIdx) == 0x124, "RboFrameRecord.attackBoxIdx");
static_assert(sizeof(RboPatternEntry) == 0xC, "RboPatternEntry size");
static_assert(offsetof(RboPatternEntry, frameCount) == 0x0, "RboPatternEntry.frameCount");
static_assert(offsetof(RboPatternEntry, flags) == 0x4, "RboPatternEntry.flags");
static_assert(offsetof(RboPatternEntry, firstFrameIndex) == 0x8, "RboPatternEntry.firstFrameIndex");
static_assert(sizeof(RboHan2AreaRef) == 0x8, "RboHan2AreaRef size");
static_assert(offsetof(RboHan2AreaRef, offset) == 0x0, "RboHan2AreaRef.offset");
static_assert(offsetof(RboHan2AreaRef, size) == 0x4, "RboHan2AreaRef.size");
static_assert(sizeof(RboHan2FileHeader) == 0x40, "RboHan2FileHeader size");
static_assert(offsetof(RboHan2FileHeader, signature) == 0x0, "RboHan2FileHeader.signature");
static_assert(offsetof(RboHan2FileHeader, kind) == 0x8, "RboHan2FileHeader.kind");
static_assert(offsetof(RboHan2FileHeader, unused_0C) == 0xC, "RboHan2FileHeader.unused_0C");
static_assert(offsetof(RboHan2FileHeader, version) == 0x10, "RboHan2FileHeader.version");
static_assert(offsetof(RboHan2FileHeader, unused_14) == 0x14, "RboHan2FileHeader.unused_14");
static_assert(offsetof(RboHan2FileHeader, subVersion) == 0x18, "RboHan2FileHeader.subVersion");
static_assert(offsetof(RboHan2FileHeader, xorFlag) == 0x1C, "RboHan2FileHeader.xorFlag");
static_assert(offsetof(RboHan2FileHeader, patternArea) == 0x20, "RboHan2FileHeader.patternArea");
static_assert(offsetof(RboHan2FileHeader, partsPat) == 0x28, "RboHan2FileHeader.partsPat");
static_assert(offsetof(RboHan2FileHeader, cgBank) == 0x30, "RboHan2FileHeader.cgBank");
static_assert(offsetof(RboHan2FileHeader, patternNames) == 0x38, "RboHan2FileHeader.patternNames");
static_assert(sizeof(RboPatternAreaHeader) == 0x58, "RboPatternAreaHeader size");
static_assert(offsetof(RboPatternAreaHeader, unused_00) == 0x0, "RboPatternAreaHeader.unused_00");
static_assert(offsetof(RboPatternAreaHeader, editorMark1) == 0x4, "RboPatternAreaHeader.editorMark1");
static_assert(offsetof(RboPatternAreaHeader, unused_08) == 0x8, "RboPatternAreaHeader.unused_08");
static_assert(offsetof(RboPatternAreaHeader, editorMark2) == 0xC, "RboPatternAreaHeader.editorMark2");
static_assert(offsetof(RboPatternAreaHeader, unused_10) == 0x10, "RboPatternAreaHeader.unused_10");
static_assert(offsetof(RboPatternAreaHeader, sectionSize) == 0x2C, "RboPatternAreaHeader.sectionSize");
static_assert(offsetof(RboPatternAreaHeader, unused_4C) == 0x4C, "RboPatternAreaHeader.unused_4C");
static_assert(sizeof(RboPatternAreaView) == 0x24, "RboPatternAreaView size");
static_assert(offsetof(RboPatternAreaView, base) == 0x0, "RboPatternAreaView.base");
static_assert(offsetof(RboPatternAreaView, patterns) == 0x4, "RboPatternAreaView.patterns");
static_assert(offsetof(RboPatternAreaView, frames) == 0x8, "RboPatternAreaView.frames");
static_assert(offsetof(RboPatternAreaView, boxes) == 0xC, "RboPatternAreaView.boxes");
static_assert(offsetof(RboPatternAreaView, attackRecords) == 0x10, "RboPatternAreaView.attackRecords");
static_assert(offsetof(RboPatternAreaView, section4) == 0x14, "RboPatternAreaView.section4");
static_assert(offsetof(RboPatternAreaView, section5) == 0x18, "RboPatternAreaView.section5");
static_assert(offsetof(RboPatternAreaView, scriptListsA) == 0x1C, "RboPatternAreaView.scriptListsA");
static_assert(offsetof(RboPatternAreaView, scriptListsB) == 0x20, "RboPatternAreaView.scriptListsB");
static_assert(sizeof(RboBoxRect) == 0x8, "RboBoxRect size");
static_assert(offsetof(RboBoxRect, x1) == 0x0, "RboBoxRect.x1");
static_assert(offsetof(RboBoxRect, y1) == 0x2, "RboBoxRect.y1");
static_assert(offsetof(RboBoxRect, x2) == 0x4, "RboBoxRect.x2");
static_assert(offsetof(RboBoxRect, y2) == 0x6, "RboBoxRect.y2");

struct Han2FieldInfo { const char *name; uint16_t offset; uint8_t size; uint8_t count; uint8_t kind; const char *enumName; const char *comment; };
static const Han2FieldInfo kRboFrameRecordFields[] = {
	{"spriteId", 0x0, 2, 1, 1, nullptr, "+0x00 CG image = id-10000 when >=10000, else PAT pose index (Actor_GetFrameSpriteId 0x440B10, Actor_DrawTree 0x4483E0)"},
	{"offsetX", 0x2, 2, 1, 1, nullptr, "+0x02 Actor_DrawTree: draw offset X"},
	{"offsetY", 0x4, 2, 1, 1, nullptr, "+0x04 Actor_DrawTree: draw offset Y"},
	{"duration", 0x6, 2, 1, 0, nullptr, "+0x06 Actor_TickFrame 0x43F830: ticks before advance"},
	{"flipMode", 0x8, 1, 1, 2, "RboFlipMode", "+0x08 Actor_DrawTree indexes the draw-mode table dword_48AE2C"},
	{"blendMode", 0x9, 1, 1, 2, "RboBlendMode", "+0x09 Actor_EnterFrame copies non-zero to actor+744"},
	{"alpha", 0xA, 1, 1, 0, nullptr, "+0x0A alpha fade target when fxFlags.USE_ALPHA_FADE (Actor_EnterFrame)"},
	{"aniFlag", 0xB, 1, 1, 2, "RboAniFlag", "+0x0B Actor_AdvanceByAniFlag 0x43F640"},
	{"jumpTarget", 0xC, 1, 1, 0, nullptr, "+0x0C pattern (ANI_END_TO_PATTERN) or frame to jump to"},
	{"landJumpTarget", 0xD, 1, 1, 0, nullptr, "+0x0D Actor_ApplyLandJump 0x440A50"},
	{"drawPriorityCode", 0xE, 1, 1, 0, nullptr, "+0x0E sub_440DF0 (1..11 set layer, 12..19 add depth, 20..61 offset table dword_48A3B8)"},
	{"unused_0F", 0xF, 1, 1, 0, nullptr, "+0x0F zero in all 57786 RBO frames, no reader found"},
	{"zoom", 0x10, 2, 1, 0, nullptr, "+0x10 256 = 1.0; Actor_EnterFrame -> sub_4496A0 when fxFlags.USE_ZOOM"},
	{"loopCount", 0x12, 1, 1, 0, nullptr, "+0x12 ANI_LOOP_COUNTED repeat count (Actor_EnterFrame -> actor+108)"},
	{"loopEndFrame", 0x13, 1, 1, 0, nullptr, "+0x13 frame jumped to when the loop is exhausted (Actor_ResolveNextFrameRecord 0x440970)"},
	{"unused_14", 0x14, 1, 4, 0, nullptr, "+0x14 zero in all frames, no reader found"},
	{"interpolationMode", 0x18, 1, 1, 0, nullptr, "+0x18 non-zero = tween toward next frame (Actor_GetFrameInterpolation 0x445A50)"},
	{"fxFlags", 0x19, 1, 1, 2, "RboFrameFxFlags", "+0x19 Actor_EnterFrame"},
	{"unused_1A", 0x1A, 1, 2, 0, nullptr, "+0x1A zero in all frames, no reader found"},
	{"unused_1C", 0x1C, 1, 12, 0, nullptr, "+0x1C..0x27 zero in all frames, no reader found"},
	{"moveFlags", 0x28, 1, 1, 2, "RboMoveFlags", "+0x28 Actor_FrameMoveClearAxes 0x44B390, Actor_FrameMoveAddSpeed 0x44B3D0"},
	{"unused_29", 0x29, 1, 3, 0, nullptr, "+0x29 zero in all frames (the flags byte is never read as a dword)"},
	{"speedX", 0x2C, 2, 1, 1, nullptr, "+0x2C added to velocity X when MOVE_ADD_X (flip-aware)"},
	{"speedY", 0x2E, 2, 1, 1, nullptr, "+0x2E added to velocity Y when MOVE_ADD_Y"},
	{"accelX", 0x30, 2, 1, 1, nullptr, "+0x30 added to acceleration X when MOVE_ADD_X"},
	{"accelY", 0x32, 2, 1, 1, nullptr, "+0x32 added to acceleration Y when MOVE_ADD_Y"},
	{"stanceClass", 0x34, 1, 1, 2, "RboStanceClass", "+0x34 becomes actor+2072, tested by script condition sub_4187C0"},
	{"normalCancel", 0x35, 1, 1, 2, "RboCancelPermission", "+0x35 sub_4189E0, sub_43DBE0, sub_43DC70"},
	{"specialCancel", 0x36, 1, 1, 2, "RboCancelPermission", "+0x36 sub_4189E0"},
	{"unused_37", 0x37, 1, 1, 0, nullptr, "+0x37 zero in all frames, no reader found"},
	{"attackEventFlags", 0x38, 1, 1, 2, "RboAttackEventFlags", "+0x38 Actor_UpdateAttackState 0x441060, Actor_UpdateBoxes272State 0x4412A0"},
	{"unused_39", 0x39, 1, 3, 0, nullptr, "+0x39 zero in all frames, no reader found"},
	{"hurtMaskEnable", 0x3C, 4, 1, 0, nullptr, "+0x3C 0 = actor hurt mask forced to 0 (Actor_ApplyFrameStatusFlags 0x441330)"},
	{"hurtMaskFlags", 0x40, 4, 1, 2, "RboHurtMaskFlags", "+0x40 Actor_ApplyFrameStatusFlags"},
	{"unused_44", 0x44, 1, 4, 0, nullptr, "+0x44 non-zero in only 22 of 57786 frames; no reader found"},
	{"hitLimitFlags", 0x48, 4, 1, 0, nullptr, "+0x48 copied to the hit limiter flags on ATKEV_BEGIN (sub_441020 0x441020, sub_4429E0)"},
	{"hitLimitCount", 0x4C, 4, 1, 0, nullptr, "+0x4C copied to the hit limiter hit count"},
	{"unused_50", 0x50, 1, 12, 0, nullptr, "+0x50..0x5B zero in all frames, no reader found"},
	{"motionFlags", 0x5C, 1, 1, 2, "RboMotionFlags", "+0x5C sub_43F0E0 0x43F0E0"},
	{"unused_5D", 0x5D, 1, 3, 0, nullptr, "+0x5D zero in all frames, no reader found"},
	{"unused_60", 0x60, 1, 88, 0, nullptr, "+0x60..0xB7 zero in all 57786 RBO frames, no reader found"},
	{"scriptOrderFlags", 0xB8, 1, 1, 2, "RboScriptOrderFlags", "+0xB8 Actor_EnterFrame"},
	{"unused_B9", 0xB9, 1, 3, 0, nullptr, "+0xB9 zero in all frames"},
	{"scriptListIndexA", 0xBC, 4, 1, 0, nullptr, "+0xBC index into pattern-area section 6 (Actor_RunFrameScriptList6 0x41DA50), 0 = none"},
	{"scriptListIndexB", 0xC0, 4, 1, 0, nullptr, "+0xC0 index into section 7 (Actor_RunFrameScriptList7 0x41F900), 0 = none"},
	{"hasAttack", 0xC4, 4, 1, 0, nullptr, "+0xC4 1 when attackRecordIdx is valid"},
	{"attackRecordIdx", 0xC8, 4, 1, 1, nullptr, "+0xC8 index into section 3 (120-byte AT records, Actor_CollectAttackBoxes2 0x440F40), -1 none"},
	{"unused_CC", 0xCC, 1, 4, 0, nullptr, "+0xCC not read by the RBO engine; 0/-1/small values, 0xCDCD uninitialised fill in 1873 frames"},
	{"sousaiBoxCount", 0xD0, 4, 1, 1, nullptr, "+0xD0 clash boxes (CAppHanteiSousai in GOF2); RBO engine never reads this group"},
	{"sousaiBoxIdx", 0xD4, 4, 3, 1, nullptr, "+0xD4 section 2 box indices, -1 = empty"},
	{"tobiBoxCount", 0xE0, 4, 1, 1, nullptr, "+0xE0 projectile-hit boxes (CAppHanteiTobi in GOF2); RBO engine never reads this group"},
	{"tobiBoxIdx", 0xE4, 4, 4, 1, nullptr, "+0xE4"},
	{"effectBoxEnable", 0xF4, 4, 1, 1, nullptr, "+0xF4 Actor_PickBoxRect_244 0x442190: >0 use effectBoxIdx as hit-spark rect, else random hurt box"},
	{"effectBoxIdx", 0xF8, 4, 1, 1, nullptr, "+0xF8"},
	{"hurtBoxCount", 0xFC, 4, 1, 1, nullptr, "+0xFC Actor_CollectHurtBoxes3 0x441120"},
	{"hurtBoxIdx", 0x100, 4, 3, 1, nullptr, "+0x100"},
	{"kasanariBoxEnable", 0x10C, 4, 1, 1, nullptr, "+0x10C overlap/push box present (Actor_CollectBoxes2_272 0x4411E0)"},
	{"kasanariBoxIdx", 0x110, 4, 4, 1, nullptr, "+0x110 engine reads the first 2; GOF2 CAppHanteiKasanari reads 1"},
	{"attackBoxCount", 0x120, 4, 1, 1, nullptr, "+0x120 Actor_CollectAttackBoxes2"},
	{"attackBoxIdx", 0x124, 4, 2, 1, nullptr, "+0x124"},
};
static const Han2FieldInfo kRboPatternEntryFields[] = {
	{"frameCount", 0x0, 4, 1, 0, nullptr, "+0x0 0 = pattern absent (Actor_GetFrameSpriteId)"},
	{"flags", 0x4, 4, 1, 2, "RboPatternFlags", "+0x4 Actor_CacheCurrentFrame 0x440920; values seen 0,2,0x40,0x80"},
	{"firstFrameIndex", 0x8, 4, 1, 0, nullptr, "+0x8 index into section 1 (frames are packed in pattern order)"},
};
static const Han2FieldInfo kRboHan2AreaRefFields[] = {
	{"offset", 0x0, 4, 1, 0, nullptr, "+0x0 absolute file offset (a .DT2 keeps the .DAT's offsets for areas it does not carry)"},
	{"size", 0x4, 4, 1, 0, nullptr, "+0x4 0 = area absent"},
};
static const Han2FieldInfo kRboHan2FileHeaderFields[] = {
	{"signature", 0x0, 1, 8, 0, nullptr, "+0x00 \"HAN2RBO \" (never checked by the RBO engine; tools check it)"},
	{"kind", 0x8, 4, 1, 2, "RboHan2Kind", "+0x08 not read by the engine; 0 = full .DAT, 3 = pattern-area-only .DT2"},
	{"unused_0C", 0xC, 4, 1, 0, nullptr, "+0x0C zero in all 346 RBO / 68 GOF2 files, not read"},
	{"version", 0x10, 4, 1, 0, nullptr, "+0x10 always 2, not read by the RBO engine"},
	{"unused_14", 0x14, 4, 1, 0, nullptr, "+0x14 zero in all files, not read"},
	{"subVersion", 0x18, 4, 1, 0, nullptr, "+0x18 1 = RBO layout (300-byte frames, 8 sections), 2 = GOF2 layout; not read by the RBO engine"},
	{"xorFlag", 0x1C, 4, 1, 0, nullptr, "+0x1C non-zero = pattern area is XOR-obfuscated (Han2Dat_DecryptBlockIfFlag 0x403430); 0 in every shipped file"},
	{"patternArea", 0x20, 8, 1, 4, nullptr, "+0x20 section table + sections (Han2Dat_LoadPatternAreaAndResolve 0x403630); taken from the .DT2 when it exists"},
	{"partsPat", 0x28, 8, 1, 4, nullptr, "+0x28 PAT v3 block (Han2Dat_LoadPartsPatBlock 0x4037D0), always from the .DAT"},
	{"cgBank", 0x30, 8, 1, 4, nullptr, "+0x30 BMP Cutter3 bank (Han2Dat_LoadCgBank 0x4038F0), always from the .DAT"},
	{"patternNames", 0x38, 8, 1, 4, nullptr, "+0x38 256 x 64-byte CP932 names; not read by the engine (editor data)"},
};
static const Han2FieldInfo kRboPatternAreaHeaderFields[] = {
	{"unused_00", 0x0, 4, 1, 0, nullptr, "+0x00 zero in all 346 files, not read"},
	{"editorMark1", 0x4, 4, 1, 0, nullptr, "+0x04 3 in 345 files, 2 in one; not read by the engine (GOF2 stores 8)"},
	{"unused_08", 0x8, 4, 1, 0, nullptr, "+0x08 zero in all files, not read"},
	{"editorMark2", 0xC, 4, 1, 0, nullptr, "+0x0C 1 in all RBO files; not read by the engine (GOF2 stores 5)"},
	{"unused_10", 0x10, 4, 7, 0, nullptr, "+0x10..0x2B zero in all files, not read"},
	{"sectionSize", 0x2C, 4, 8, 0, nullptr, "+0x2C section byte sizes (Han2Dat_ComputeSectionPointers a1[11..18]); 0 = absent"},
	{"unused_4C", 0x4C, 4, 3, 0, nullptr, "+0x4C zero in all files, not read"},
};
static const Han2FieldInfo kRboPatternAreaViewFields[] = {
	{"base", 0x0, 4, 1, 4, nullptr, "+0x00 GlobalAlloc block holding the whole pattern area"},
	{"patterns", 0x4, 4, 1, 4, nullptr, "+0x04 section 0: 256 x 12 bytes"},
	{"frames", 0x8, 4, 1, 4, nullptr, "+0x08 section 1: 300-byte records"},
	{"boxes", 0xC, 4, 1, 4, nullptr, "+0x0C section 2: 8-byte i16 x1,y1,x2,y2 rectangles"},
	{"attackRecords", 0x10, 4, 1, 4, nullptr, "+0x10 section 3: 120-byte AT records"},
	{"section4", 0x14, 4, 1, 4, nullptr, "+0x14 section 4 (196 bytes in ACOLYTE_F)"},
	{"section5", 0x18, 4, 1, 4, nullptr, "+0x18 section 5 (40 bytes in ACOLYTE_F)"},
	{"scriptListsA", 0x1C, 4, 1, 4, nullptr, "+0x1C section 6: 20-byte script id lists"},
	{"scriptListsB", 0x20, 4, 1, 4, nullptr, "+0x20 section 7: 20-byte script id lists"},
};
static const Han2FieldInfo kRboBoxRectFields[] = {
	{"x1", 0x0, 2, 1, 1, nullptr, "+0x0 Actor_PickBoxRect_244 0x442190 copies four shorts"},
	{"y1", 0x2, 2, 1, 1, nullptr, "+0x2"},
	{"x2", 0x4, 2, 1, 1, nullptr, "+0x4"},
	{"y2", 0x6, 2, 1, 1, nullptr, "+0x6"},
};
