// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"

enum RboHitClass : uint32_t {
	RBO_HC_FLINCH_0 = 0x0,
	RBO_HC_FLINCH_1 = 0x1,
	RBO_HC_FLINCH_2 = 0x2,
	RBO_HC_MEDIUM_3 = 0x3,
	RBO_HC_MEDIUM_4 = 0x4,
	RBO_HC_MEDIUM_5 = 0x5,
	RBO_HC_HEAVY_6 = 0x6,
	RBO_HC_HEAVY_7 = 0x7,
	RBO_HC_HEAVY_8 = 0x8,
	RBO_HC_SWEEP_9 = 0x9,
	RBO_HC_LAUNCH_10 = 0xA,
	RBO_HC_LAUNCH_11 = 0xB,
	RBO_HC_LAUNCH_12 = 0xC,
	RBO_HC_LAUNCH_13 = 0xD,
	RBO_HC_MEDIUM_14 = 0xE,
	RBO_HC_LAUNCH_15 = 0xF,
	RBO_HC_FLINCH_16 = 0x10,
	RBO_HC_SPECIAL_NOREACT = 0x11,
};
enum RboHitSfxSet : uint32_t {
	RBO_HITSFX_0 = 0x0,
	RBO_HITSFX_1 = 0x1,
	RBO_HITSFX_2 = 0x2,
	RBO_HITSFX_3 = 0x3,
	RBO_HITSFX_4 = 0x4,
	RBO_HITSFX_5 = 0x5,
	RBO_HITSFX_6 = 0x6,
};
enum RboAtGateMode : uint32_t {
	RBO_GATE_NORMAL = 0x0,
	RBO_GATE_1 = 0x1,
	RBO_GATE_2 = 0x2,
	RBO_GATE_3 = 0x3,
	RBO_GATE_ONLY_VS_SPECIAL_GUARD = 0x4,
};
enum RboAtKnockDirMode : uint32_t {
	RBO_KDIR_ATTACKER_FACING = 0x0,
	RBO_KDIR_REVERSED = 0x1,
	RBO_KDIR_BY_POSITION = 0x2,
	RBO_KDIR_BY_POSITION_REVERSED = 0x3,
	RBO_KDIR_NONE = 0x4,
};
enum RboAtFacingMode : uint32_t {
	RBO_FACE_BY_POSITION = 0x0,
	RBO_FACE_BY_POSITION_REVERSED = 0x1,
	RBO_FACE_ATTACKER = 0x2,
	RBO_FACE_ATTACKER_REVERSED = 0x3,
	RBO_FACE_VICTIM = 0x4,
};
enum RboAtElementSource : uint32_t {
	RBO_ELEM_ATTACKER_PRIMARY = 0x0,
	RBO_ELEM_ATTACKER_SECONDARY = 0x1,
	RBO_ELEM_FIXED = 0x2,
};
enum RboAtDamageMode : uint32_t {
	RBO_DMGMODE_NORMAL = 0x0,
	RBO_DMGMODE_HEAL = 0x1,
	RBO_DMGMODE_STATUS_DOT = 0x3,
	RBO_DMGMODE_4 = 0x4,
};
enum RboAtDamageType : uint32_t {
	RBO_DT_0 = 0x0,
	RBO_DT_1 = 0x1,
	RBO_DT_2 = 0x2,
	RBO_DT_3 = 0x3,
	RBO_DT_6 = 0x6,
	RBO_DT_7 = 0x7,
	RBO_DT_MAGIC = 0x8,
	RBO_DT_TRUE = 0xA,
};
enum RboGuardOutcome : uint32_t {
	RBO_GUARD_BLOCKED = 0x0,
	RBO_GUARD_HIT = 0x1,
	RBO_GUARD_JUST = 0x2,
	RBO_GUARD_3 = 0x3,
	RBO_GUARD_INVULN = 0x4,
	RBO_GUARD_INVULN_B = 0x5,
};
enum RboAtFlags76 : uint32_t {
	RBO_AT76_PLAY_EXTRA_SFX = 0x1,
	RBO_AT76_UNREAD_0002 = 0x2,
	RBO_AT76_HIT_TEAMMATES = 0x10,
	RBO_AT76_CAN_HIT_SELF = 0x20,
	RBO_AT76_HIT_BOTH_TEAMS = 0x40,
	RBO_AT76_SELF_ONLY_TARGET = 0x80,
	RBO_AT76_UNREAD_0100 = 0x100,
	RBO_AT76_PUSHBACK_GATE_INVERT = 0x400,
	RBO_AT76_UNREAD_2000 = 0x2000,
	RBO_AT76_SUPPRESS_HIT_SFX = 0x10000,
	RBO_AT76_RANGED_ATTACK = 0x100000,
};
enum RboAtFlags80 : uint32_t {
	RBO_AT80_UNREAD_0001 = 0x1,
	RBO_AT80_NON_LETHAL = 0x2,
	RBO_AT80_UNREAD_0010 = 0x10,
	RBO_AT80_UNREAD_0020 = 0x20,
	RBO_AT80_UNREAD_0200 = 0x200,
	RBO_AT80_NO_JUST_GUARD = 0x1000,
	RBO_AT80_UNEVADABLE = 0x2000,
	RBO_AT80_NO_DAMAGE_POPUP = 0x1000000,
	RBO_AT80_UNREAD_20000000 = 0x20000000,
	RBO_AT80_UNREAD_40000000 = 0x40000000,
};
enum RboHitSkillId : uint32_t {
	RBO_HITSKILL_NONE = 0x0,
	RBO_HITSKILL_09 = 0x9,
	RBO_HITSKILL_10 = 0xA,
	RBO_HITSKILL_14 = 0xE,
	RBO_HITSKILL_17 = 0x11,
	RBO_HITSKILL_18 = 0x12,
	RBO_HITSKILL_22 = 0x16,
	RBO_HITSKILL_25 = 0x19,
	RBO_HITSKILL_28 = 0x1C,
	RBO_HITSKILL_31 = 0x1F,
	RBO_HITSKILL_34 = 0x22,
	RBO_HITSKILL_43 = 0x2B,
	RBO_HITSKILL_44 = 0x2C,
	RBO_HITSKILL_47 = 0x2F,
	RBO_HITSKILL_52 = 0x34,
	RBO_HITSKILL_54 = 0x36,
	RBO_HITSKILL_57 = 0x39,
	RBO_HITSKILL_69 = 0x45,
	RBO_HITSKILL_71 = 0x47,
	RBO_HITSKILL_73_NOHANDLER = 0x49,
	RBO_HITSKILL_75_NOHANDLER = 0x4B,
};

#pragma pack(push, 1)
struct RboAtRecord {
	RboHitClass hit_class;  // +0x0
	RboHitSfxSet hit_sfx_set;  // +0x4
	int32_t hit_spark_kind;  // +0x8
	RboAtGateMode hit_gate_mode;  // +0xC
	int32_t base_power;  // +0x10
	int32_t unused_14;  // +0x14
	int32_t guard_damage;  // +0x18
	int32_t status_duration;  // +0x1C
	int32_t victim_shake_mode;  // +0x20
	int32_t reserved_flag_24;  // +0x24
	int32_t sound_bank_select;  // +0x28
	int32_t hit_sound_id;  // +0x2C
	int32_t hit_sound_random_range;  // +0x30
	RboAtKnockDirMode knock_dir_mode;  // +0x34
	RboAtFacingMode victim_facing_mode;  // +0x38
	RboAtElementSource element_source;  // +0x3C
	int32_t fixed_element;  // +0x40
	RboAtDamageType damage_type;  // +0x44
	RboAtDamageMode damage_mode;  // +0x48
	RboAtFlags76 target_fx_flags;  // +0x4C
	RboAtFlags80 damage_rule_flags;  // +0x50
	int32_t hit_script_enable;  // +0x54
	int32_t hit_script_type;  // +0x58
	int32_t hit_script_id;  // +0x5C
	int32_t unused_60;  // +0x60
	int32_t unused_64;  // +0x64
	int32_t unused_68;  // +0x68
	uint16_t skill_param_a;  // +0x6C
	uint16_t skill_param_b;  // +0x6E
	RboHitSkillId hit_skill_id;  // +0x70
	int32_t unused_74;  // +0x74
};
struct RboScriptListEntry {
	int32_t script_id[5];  // +0x0
};
#pragma pack(pop)

static_assert(sizeof(RboAtRecord) == 0x78, "RboAtRecord size");
static_assert(offsetof(RboAtRecord, hit_class) == 0x0, "RboAtRecord.hit_class");
static_assert(offsetof(RboAtRecord, hit_sfx_set) == 0x4, "RboAtRecord.hit_sfx_set");
static_assert(offsetof(RboAtRecord, hit_spark_kind) == 0x8, "RboAtRecord.hit_spark_kind");
static_assert(offsetof(RboAtRecord, hit_gate_mode) == 0xC, "RboAtRecord.hit_gate_mode");
static_assert(offsetof(RboAtRecord, base_power) == 0x10, "RboAtRecord.base_power");
static_assert(offsetof(RboAtRecord, unused_14) == 0x14, "RboAtRecord.unused_14");
static_assert(offsetof(RboAtRecord, guard_damage) == 0x18, "RboAtRecord.guard_damage");
static_assert(offsetof(RboAtRecord, status_duration) == 0x1C, "RboAtRecord.status_duration");
static_assert(offsetof(RboAtRecord, victim_shake_mode) == 0x20, "RboAtRecord.victim_shake_mode");
static_assert(offsetof(RboAtRecord, reserved_flag_24) == 0x24, "RboAtRecord.reserved_flag_24");
static_assert(offsetof(RboAtRecord, sound_bank_select) == 0x28, "RboAtRecord.sound_bank_select");
static_assert(offsetof(RboAtRecord, hit_sound_id) == 0x2C, "RboAtRecord.hit_sound_id");
static_assert(offsetof(RboAtRecord, hit_sound_random_range) == 0x30, "RboAtRecord.hit_sound_random_range");
static_assert(offsetof(RboAtRecord, knock_dir_mode) == 0x34, "RboAtRecord.knock_dir_mode");
static_assert(offsetof(RboAtRecord, victim_facing_mode) == 0x38, "RboAtRecord.victim_facing_mode");
static_assert(offsetof(RboAtRecord, element_source) == 0x3C, "RboAtRecord.element_source");
static_assert(offsetof(RboAtRecord, fixed_element) == 0x40, "RboAtRecord.fixed_element");
static_assert(offsetof(RboAtRecord, damage_type) == 0x44, "RboAtRecord.damage_type");
static_assert(offsetof(RboAtRecord, damage_mode) == 0x48, "RboAtRecord.damage_mode");
static_assert(offsetof(RboAtRecord, target_fx_flags) == 0x4C, "RboAtRecord.target_fx_flags");
static_assert(offsetof(RboAtRecord, damage_rule_flags) == 0x50, "RboAtRecord.damage_rule_flags");
static_assert(offsetof(RboAtRecord, hit_script_enable) == 0x54, "RboAtRecord.hit_script_enable");
static_assert(offsetof(RboAtRecord, hit_script_type) == 0x58, "RboAtRecord.hit_script_type");
static_assert(offsetof(RboAtRecord, hit_script_id) == 0x5C, "RboAtRecord.hit_script_id");
static_assert(offsetof(RboAtRecord, unused_60) == 0x60, "RboAtRecord.unused_60");
static_assert(offsetof(RboAtRecord, unused_64) == 0x64, "RboAtRecord.unused_64");
static_assert(offsetof(RboAtRecord, unused_68) == 0x68, "RboAtRecord.unused_68");
static_assert(offsetof(RboAtRecord, skill_param_a) == 0x6C, "RboAtRecord.skill_param_a");
static_assert(offsetof(RboAtRecord, skill_param_b) == 0x6E, "RboAtRecord.skill_param_b");
static_assert(offsetof(RboAtRecord, hit_skill_id) == 0x70, "RboAtRecord.hit_skill_id");
static_assert(offsetof(RboAtRecord, unused_74) == 0x74, "RboAtRecord.unused_74");
static_assert(sizeof(RboScriptListEntry) == 0x14, "RboScriptListEntry size");
static_assert(offsetof(RboScriptListEntry, script_id) == 0x0, "RboScriptListEntry.script_id");

static const Han2EnumValue kRboHitClassValues[] = {
	{"RBO_HC_FLINCH_0", (int64_t)(0x0)},
	{"RBO_HC_FLINCH_1", (int64_t)(0x1)},
	{"RBO_HC_FLINCH_2", (int64_t)(0x2)},
	{"RBO_HC_MEDIUM_3", (int64_t)(0x3)},
	{"RBO_HC_MEDIUM_4", (int64_t)(0x4)},
	{"RBO_HC_MEDIUM_5", (int64_t)(0x5)},
	{"RBO_HC_HEAVY_6", (int64_t)(0x6)},
	{"RBO_HC_HEAVY_7", (int64_t)(0x7)},
	{"RBO_HC_HEAVY_8", (int64_t)(0x8)},
	{"RBO_HC_SWEEP_9", (int64_t)(0x9)},
	{"RBO_HC_LAUNCH_10", (int64_t)(0xA)},
	{"RBO_HC_LAUNCH_11", (int64_t)(0xB)},
	{"RBO_HC_LAUNCH_12", (int64_t)(0xC)},
	{"RBO_HC_LAUNCH_13", (int64_t)(0xD)},
	{"RBO_HC_MEDIUM_14", (int64_t)(0xE)},
	{"RBO_HC_LAUNCH_15", (int64_t)(0xF)},
	{"RBO_HC_FLINCH_16", (int64_t)(0x10)},
	{"RBO_HC_SPECIAL_NOREACT", (int64_t)(0x11)},
};
static const Han2EnumValue kRboHitSfxSetValues[] = {
	{"RBO_HITSFX_0", (int64_t)(0x0)},
	{"RBO_HITSFX_1", (int64_t)(0x1)},
	{"RBO_HITSFX_2", (int64_t)(0x2)},
	{"RBO_HITSFX_3", (int64_t)(0x3)},
	{"RBO_HITSFX_4", (int64_t)(0x4)},
	{"RBO_HITSFX_5", (int64_t)(0x5)},
	{"RBO_HITSFX_6", (int64_t)(0x6)},
};
static const Han2EnumValue kRboAtGateModeValues[] = {
	{"RBO_GATE_NORMAL", (int64_t)(0x0)},
	{"RBO_GATE_1", (int64_t)(0x1)},
	{"RBO_GATE_2", (int64_t)(0x2)},
	{"RBO_GATE_3", (int64_t)(0x3)},
	{"RBO_GATE_ONLY_VS_SPECIAL_GUARD", (int64_t)(0x4)},
};
static const Han2EnumValue kRboAtKnockDirModeValues[] = {
	{"RBO_KDIR_ATTACKER_FACING", (int64_t)(0x0)},
	{"RBO_KDIR_REVERSED", (int64_t)(0x1)},
	{"RBO_KDIR_BY_POSITION", (int64_t)(0x2)},
	{"RBO_KDIR_BY_POSITION_REVERSED", (int64_t)(0x3)},
	{"RBO_KDIR_NONE", (int64_t)(0x4)},
};
static const Han2EnumValue kRboAtFacingModeValues[] = {
	{"RBO_FACE_BY_POSITION", (int64_t)(0x0)},
	{"RBO_FACE_BY_POSITION_REVERSED", (int64_t)(0x1)},
	{"RBO_FACE_ATTACKER", (int64_t)(0x2)},
	{"RBO_FACE_ATTACKER_REVERSED", (int64_t)(0x3)},
	{"RBO_FACE_VICTIM", (int64_t)(0x4)},
};
static const Han2EnumValue kRboAtElementSourceValues[] = {
	{"RBO_ELEM_ATTACKER_PRIMARY", (int64_t)(0x0)},
	{"RBO_ELEM_ATTACKER_SECONDARY", (int64_t)(0x1)},
	{"RBO_ELEM_FIXED", (int64_t)(0x2)},
};
static const Han2EnumValue kRboAtDamageModeValues[] = {
	{"RBO_DMGMODE_NORMAL", (int64_t)(0x0)},
	{"RBO_DMGMODE_HEAL", (int64_t)(0x1)},
	{"RBO_DMGMODE_STATUS_DOT", (int64_t)(0x3)},
	{"RBO_DMGMODE_4", (int64_t)(0x4)},
};
static const Han2EnumValue kRboAtDamageTypeValues[] = {
	{"RBO_DT_0", (int64_t)(0x0)},
	{"RBO_DT_1", (int64_t)(0x1)},
	{"RBO_DT_2", (int64_t)(0x2)},
	{"RBO_DT_3", (int64_t)(0x3)},
	{"RBO_DT_6", (int64_t)(0x6)},
	{"RBO_DT_7", (int64_t)(0x7)},
	{"RBO_DT_MAGIC", (int64_t)(0x8)},
	{"RBO_DT_TRUE", (int64_t)(0xA)},
};
static const Han2EnumValue kRboGuardOutcomeValues[] = {
	{"RBO_GUARD_BLOCKED", (int64_t)(0x0)},
	{"RBO_GUARD_HIT", (int64_t)(0x1)},
	{"RBO_GUARD_JUST", (int64_t)(0x2)},
	{"RBO_GUARD_3", (int64_t)(0x3)},
	{"RBO_GUARD_INVULN", (int64_t)(0x4)},
	{"RBO_GUARD_INVULN_B", (int64_t)(0x5)},
};
static const Han2EnumValue kRboAtFlags76Values[] = {
	{"RBO_AT76_PLAY_EXTRA_SFX", (int64_t)(0x1)},
	{"RBO_AT76_UNREAD_0002", (int64_t)(0x2)},
	{"RBO_AT76_HIT_TEAMMATES", (int64_t)(0x10)},
	{"RBO_AT76_CAN_HIT_SELF", (int64_t)(0x20)},
	{"RBO_AT76_HIT_BOTH_TEAMS", (int64_t)(0x40)},
	{"RBO_AT76_SELF_ONLY_TARGET", (int64_t)(0x80)},
	{"RBO_AT76_UNREAD_0100", (int64_t)(0x100)},
	{"RBO_AT76_PUSHBACK_GATE_INVERT", (int64_t)(0x400)},
	{"RBO_AT76_UNREAD_2000", (int64_t)(0x2000)},
	{"RBO_AT76_SUPPRESS_HIT_SFX", (int64_t)(0x10000)},
	{"RBO_AT76_RANGED_ATTACK", (int64_t)(0x100000)},
};
static const Han2EnumValue kRboAtFlags80Values[] = {
	{"RBO_AT80_UNREAD_0001", (int64_t)(0x1)},
	{"RBO_AT80_NON_LETHAL", (int64_t)(0x2)},
	{"RBO_AT80_UNREAD_0010", (int64_t)(0x10)},
	{"RBO_AT80_UNREAD_0020", (int64_t)(0x20)},
	{"RBO_AT80_UNREAD_0200", (int64_t)(0x200)},
	{"RBO_AT80_NO_JUST_GUARD", (int64_t)(0x1000)},
	{"RBO_AT80_UNEVADABLE", (int64_t)(0x2000)},
	{"RBO_AT80_NO_DAMAGE_POPUP", (int64_t)(0x1000000)},
	{"RBO_AT80_UNREAD_20000000", (int64_t)(0x20000000)},
	{"RBO_AT80_UNREAD_40000000", (int64_t)(0x40000000)},
};
static const Han2EnumValue kRboHitSkillIdValues[] = {
	{"RBO_HITSKILL_NONE", (int64_t)(0x0)},
	{"RBO_HITSKILL_09", (int64_t)(0x9)},
	{"RBO_HITSKILL_10", (int64_t)(0xA)},
	{"RBO_HITSKILL_14", (int64_t)(0xE)},
	{"RBO_HITSKILL_17", (int64_t)(0x11)},
	{"RBO_HITSKILL_18", (int64_t)(0x12)},
	{"RBO_HITSKILL_22", (int64_t)(0x16)},
	{"RBO_HITSKILL_25", (int64_t)(0x19)},
	{"RBO_HITSKILL_28", (int64_t)(0x1C)},
	{"RBO_HITSKILL_31", (int64_t)(0x1F)},
	{"RBO_HITSKILL_34", (int64_t)(0x22)},
	{"RBO_HITSKILL_43", (int64_t)(0x2B)},
	{"RBO_HITSKILL_44", (int64_t)(0x2C)},
	{"RBO_HITSKILL_47", (int64_t)(0x2F)},
	{"RBO_HITSKILL_52", (int64_t)(0x34)},
	{"RBO_HITSKILL_54", (int64_t)(0x36)},
	{"RBO_HITSKILL_57", (int64_t)(0x39)},
	{"RBO_HITSKILL_69", (int64_t)(0x45)},
	{"RBO_HITSKILL_71", (int64_t)(0x47)},
	{"RBO_HITSKILL_73_NOHANDLER", (int64_t)(0x49)},
	{"RBO_HITSKILL_75_NOHANDLER", (int64_t)(0x4B)},
};
static const Han2EnumInfo kRboAtEnums[] = {
	{"RboHitClass", kRboHitClassValues, 18, false},
	{"RboHitSfxSet", kRboHitSfxSetValues, 7, false},
	{"RboAtGateMode", kRboAtGateModeValues, 5, false},
	{"RboAtKnockDirMode", kRboAtKnockDirModeValues, 5, false},
	{"RboAtFacingMode", kRboAtFacingModeValues, 5, false},
	{"RboAtElementSource", kRboAtElementSourceValues, 3, false},
	{"RboAtDamageMode", kRboAtDamageModeValues, 4, false},
	{"RboAtDamageType", kRboAtDamageTypeValues, 8, false},
	{"RboGuardOutcome", kRboGuardOutcomeValues, 6, false},
	{"RboAtFlags76", kRboAtFlags76Values, 11, true},
	{"RboAtFlags80", kRboAtFlags80Values, 10, true},
	{"RboHitSkillId", kRboHitSkillIdValues, 21, false},
};

static const Han2FieldInfo kRboAtRecordFields[] = {
	{"hit_class", 0x0, 4, 1, 2, "RboHitClass", "+0x0"},
	{"hit_sfx_set", 0x4, 4, 1, 2, "RboHitSfxSet", "+0x4"},
	{"hit_spark_kind", 0x8, 4, 1, 1, nullptr, "+0x8"},
	{"hit_gate_mode", 0xC, 4, 1, 2, "RboAtGateMode", "+0xC"},
	{"base_power", 0x10, 4, 1, 1, nullptr, "+0x10"},
	{"unused_14", 0x14, 4, 1, 1, nullptr, "+0x14"},
	{"guard_damage", 0x18, 4, 1, 1, nullptr, "+0x18"},
	{"status_duration", 0x1C, 4, 1, 1, nullptr, "+0x1C"},
	{"victim_shake_mode", 0x20, 4, 1, 1, nullptr, "+0x20"},
	{"reserved_flag_24", 0x24, 4, 1, 1, nullptr, "+0x24"},
	{"sound_bank_select", 0x28, 4, 1, 1, nullptr, "+0x28"},
	{"hit_sound_id", 0x2C, 4, 1, 1, nullptr, "+0x2C"},
	{"hit_sound_random_range", 0x30, 4, 1, 1, nullptr, "+0x30"},
	{"knock_dir_mode", 0x34, 4, 1, 2, "RboAtKnockDirMode", "+0x34"},
	{"victim_facing_mode", 0x38, 4, 1, 2, "RboAtFacingMode", "+0x38"},
	{"element_source", 0x3C, 4, 1, 2, "RboAtElementSource", "+0x3C"},
	{"fixed_element", 0x40, 4, 1, 1, nullptr, "+0x40"},
	{"damage_type", 0x44, 4, 1, 2, "RboAtDamageType", "+0x44"},
	{"damage_mode", 0x48, 4, 1, 2, "RboAtDamageMode", "+0x48"},
	{"target_fx_flags", 0x4C, 4, 1, 2, "RboAtFlags76", "+0x4C"},
	{"damage_rule_flags", 0x50, 4, 1, 2, "RboAtFlags80", "+0x50"},
	{"hit_script_enable", 0x54, 4, 1, 1, nullptr, "+0x54"},
	{"hit_script_type", 0x58, 4, 1, 1, nullptr, "+0x58"},
	{"hit_script_id", 0x5C, 4, 1, 1, nullptr, "+0x5C"},
	{"unused_60", 0x60, 4, 1, 1, nullptr, "+0x60"},
	{"unused_64", 0x64, 4, 1, 1, nullptr, "+0x64"},
	{"unused_68", 0x68, 4, 1, 1, nullptr, "+0x68"},
	{"skill_param_a", 0x6C, 2, 1, 0, nullptr, "+0x6C"},
	{"skill_param_b", 0x6E, 2, 1, 0, nullptr, "+0x6E"},
	{"hit_skill_id", 0x70, 4, 1, 2, "RboHitSkillId", "+0x70"},
	{"unused_74", 0x74, 4, 1, 1, nullptr, "+0x74"},
};
static const Han2FieldInfo kRboScriptListEntryFields[] = {
	{"script_id", 0x0, 4, 5, 1, nullptr, "+0x0"},
};
