// GOF1 (gof.exe) runtime actor + fighter slot + CT file types, IDA-parsable (idc.parse_decls). GENERATED by tools/ida/make_gof1_actor.py - edit the generator, not this file.
// Evidence: T = access traced in gof.exe (function names are IDB names), I = inferred, U = never accessed by any function (zero-filled at spawn). Zero unmapped bytes: the generator aborts on any gap/overlap.
// Uses the record types of gof1_types.h (Gof1FrameRecord pieces, Gof1AtRecord, Gof1Box, Gof1RectI32, Gof1IfRecord, Gof1EfRecord, Gof1PatternHeader, Gof1CharDatHead, Gof1Stance, Gof1StatusEffect, Gof1CounterCommand).
enum Gof1ObjKind : unsigned char { G1OBJ_FIGHTER=0, G1OBJ_GHOST_TRAIL=31, G1OBJ_CHILD_8F=143, G1OBJ_CHILD=255 };
enum Gof1ControlType : unsigned char { G1CTRL_HUMAN=0, G1CTRL_CPU=1 };
enum Gof1RunState : unsigned char { G1RUN_IDLE=0, G1RUN_PENDING=1, G1RUN_FORCED=2 };
enum Gof1ObjFlagsA : unsigned short { G1OF_A_FOLLOW_PARENT_STATE=1, G1OF_A_NO_MIRROR=2, G1OF_A_FOLLOW_PARENT_EDGE_PUSH=4, G1OF_A_FREEZE_WITH_PARENT_HITSTOP=8, G1OF_A_END_ON_PARENT_ACTION_CHANGE=0x20, G1OF_A_NO_GROUND_LANDING=0x40 };
enum Gof1ObjFlagsB : unsigned short { G1OF_B_DRAW_SHADOW=1, G1OF_B_ADVANCE_WITH_PARENT=2, G1OF_B_END_WHEN_PARENT_AIRBORNE=4, G1OF_B_HITSTOP_TO_OWNER=8, G1OF_B_RENDERER_BIT7=0x80 };
enum Gof1DecorFlags : unsigned short { G1DECOR_DEPTH_BUMP=1 };
enum Gof1HomingMode : unsigned char { G1HOME_NONE=0, G1HOME_EASE_TO_TARGET=1, G1HOME_CONSTANT_SPEED=2 };
enum Gof1AttackResultFlags : unsigned char { G1HITRES_HIT=1, G1HITRES_GUARDED=2, G1HITRES_TESTED_BIT4=4, G1HITRES_EVADED_STRIKE=8, G1HITRES_VICTIM_GROUND=0x10, G1HITRES_VICTIM_AIR=0x20 };
enum Gof1FlashMode : unsigned char { G1FLASH_BLUE_BLINK=0, G1FLASH_WHITE_BLINK=1, G1FLASH_YELLOW_BLINK=2, G1FLASH_GREEN_BLINK=3, G1FLASH_GREY_BLINK=4, G1FLASH_WHITE_FADE=5, G1FLASH_BLUE_FADE=6, G1FLASH_RED_FADE=7, G1FLASH_CYAN_FADE=8 };
enum Gof1InputDirection : unsigned char { G1DIR_NEUTRAL=0, G1DIR_DOWN_LEFT=1, G1DIR_DOWN=2, G1DIR_DOWN_RIGHT=3, G1DIR_LEFT=4, G1DIR_RIGHT=6, G1DIR_UP_LEFT=7, G1DIR_UP=8, G1DIR_UP_RIGHT=9 };
enum Gof1InputButtonFlags : unsigned int { G1BTN_A=1, G1BTN_B=2, G1BTN_C=4, G1BTN_D=8, G1BTN_E=0x10, G1BTN_F=0x20, G1BTN_A_PRESSED=0x1000, G1BTN_B_PRESSED=0x2000, G1BTN_C_PRESSED=0x4000, G1BTN_D_PRESSED=0x8000, G1BTN_E_PRESSED=0x10000, G1BTN_F_PRESSED=0x20000 };
enum Gof1CommandMoveClass : unsigned char { G1MOVE_SYSTEM=0, G1MOVE_SPECIAL=1, G1MOVE_SUPER=2 };
enum Gof1CommandFlags : unsigned char { G1CMD_STANCE_GROUND=1, G1CMD_STANCE_AIR=2, G1CMD_STANCE_CROUCH=4, G1CMD_IGNORE_CANCEL_RULE=8, G1CMD_CLEAR_HISTORY_ON_ACTION=0x10, G1CMD_SCRIPT_ONLY=0x20, G1CMD_NEEDS_GUARD_CANCEL=0x40 };
enum Gof1CommandFlags2 : unsigned char { G1CMD2_USE_RING_B=1, G1CMD2_STRICT_SEQUENCE=2, G1CMD2_EVADE_MOVE=0x80 };
enum Gof1CtFlags : unsigned char { G1CT_RESTRICT_REPEAT_MOVES=1, G1CT_EVADE_ENABLED=2, G1CT_JUST_GUARD_ENABLED=8, G1CT_UNREAD_BIT4=0x10, G1CT_UNREAD_BIT5=0x20 };
struct Gof1Actor;
struct Gof1FighterSlot;
struct Gof1Actor {  // 656 bytes; fighters live in Gof1FighterSlot.actor, spawned objects in Gof1ObjectSlot.actor (memset 0x290 by InitChildObject / SpawnEffectFromActorFrame)
 unsigned char slotIndex; // +0x000 T: fighter slot / owner player index 0..3 (SetupFighterSlot sub_403A90 stores the slot id; per-player tables dword_18645A0[130*i]; EfType9 sound bank arg0+50*(i+8); children copy it in InitChildObject)
 unsigned char characterId; // +0x001 T: roster character id (sub_403A90: dword_17919D4[42*sel]); copied through InitFighterSlotForRound; only reader ObjRunActionScript compares it with 34
 enum Gof1ControlType controlType; // +0x002 T: 0 human, 1 CPU (sub_403A90 a5 == 1; Battle_UpdateAllCharactersInputAndAI, Actor_RunFrameIfRecord IF 11, Damage_ScaleByComboAndLife, sub_43A120)
 unsigned char unreferenced_03; // +0x003 U: no access in any function
 enum Gof1ObjKind objKind; // +0x004 T: 0 fighter; 31 ghost trail (SpawnEffectFromActorFrame); 0xFF/0x8F spawned child (InitChildObject, SpawnChildEffectFromParent); >= 0xF0 is non-fighter (sub_4242C0, sub_424560, ObjScreenEdgeOverlap); bit 7 = child (many tests)
 unsigned char paletteIndex; // +0x005 T: colour palette chosen at character select (sub_403A90 byte_16224B9 = a4); preserved by InitFighterSlotForRound
 unsigned char pattern; // +0x006 T: current pattern (action) id; Actor_ResolveFrameDataPointers indexes charData.patternOffset with it (doc actor+6)
 unsigned char frame; // +0x007 T: current frame number inside the pattern (Actor_ResolveFrameDataPointers, ObjRunActionScript)
 unsigned __int16 spriteId; // +0x008 T: sprite id of the current frame, written by ObjEnterCurrentAction via Pattern_GetFrameSpriteId, read by DrawFighterSprite / PushFighterAfterimage
 enum Gof1RunState ifRunState; // +0x00A T: IF-table run gate: ObjEnterCurrentAction sets 1 (2 stays), sub_4242C0 sets 2 on action change, Actor_TickWordTimers clears it each tick; sub_426BD0/EffectObjects_UpdateAll test it
 enum Gof1RunState efRunState; // +0x00B T: EF-table run gate, same protocol as ifRunState; Actor_RunFrameEFs clears it after running the frame effects
 unsigned char airReactionActive; // +0x00C T: 1 while a launch/air hit-reaction stage (hitStage >= 240) is running: set by Actor_StartKnockback and by ObjRunActionScript on landing, tested/cleared in Actor_ApplyFrameMotionFlags
 unsigned char unreferenced_0D; // +0x00D U: no access in any function
 unsigned __int16 frameTicks; // +0x00E T: ticks spent on the current frame, compared with AF.duration (ObjRunActionScript); the grab code copies the grabber value (DrawFighterSprite)
 unsigned __int16 lifeTimer; // +0x010 T: remaining life of a ghost trail object (EffectObjects_UpdateAll decrements it, sets endConditionMet at 0; sub_413FD0 fades by it)
 unsigned char animationEnded; // +0x012 T: set by ObjRunActionScript when the animation reached its last frame (aniFlag 3/4 branch); read by IF 2 END_CONDITION p2 (Actor_RunFrameIfRecord)
 unsigned char unreferenced_13; // +0x013 U: no access in any function
 unsigned char loopCounter; // +0x014 T: AF.loopCount is loaded here (ObjEnterCurrentAction); IF 9/10 set/test it (Actor_RunFrameIfRecord); aniFlag 2/5 consume it (ObjRunActionScript)
 unsigned char unreferenced_15; // +0x015 U: no access in any function
 enum Gof1ObjFlagsA spawnFlagsA; // +0x016 T: child flags from EF arg2 (InitChildObject); EffectObjects_UpdateAll, ObjIntegrateMotion (0x40), sub_413FD0 / sub_4144C0 (2), Render_QueueFighterSprite pass them on
 enum Gof1ObjFlagsB spawnFlagsB; // +0x018 T: child flags from EF arg3 (InitChildObject); EffectObjects_UpdateAll (2, 4), Actor_SetHitstopFrames / ObjFighterStateAndHitReaction (8), sub_413FD0 (1 draws a shadow with sub_42E0D0)
 enum Gof1HomingMode homingMode; // +0x01A T: EF arg4 low byte (InitChildObject); sub_413940 homing object update
 unsigned char homingBaseAction; // +0x01B T: EF subType = first of the homing action family (sub_413940 requests base+1..3 with ObjRequestAction)
 unsigned char homingReserved_1C; // +0x01C U: only written (0) by InitChildObject, never read
 unsigned char unreferenced_1D; // +0x01D U: no access in any function
 unsigned __int16 homingTick; // +0x01E T: counts up while homingTimeout != 0 (sub_413940)
 unsigned __int16 homingTimeout; // +0x020 T: EfType30_SetActorParams sub 0 arg2; sub_413940 ends the homing when homingTick reaches it
 __int16 homingOffsetX; // +0x022 T: EF arg0 / EfType30 arg0; target offset X, 128 = centred (sub_413940 v3 = +-(f022 - 128) << 8)
 __int16 homingOffsetY; // +0x024 T: EF arg1 / EfType30 arg1; target offset Y, 224 = baseline (sub_413940 (f024 - 224) << 8)
 unsigned __int16 homingCooldown; // +0x026 T: sub_413940 sets 40 after a hit and counts it down
 __int16 homingParam[10]; // +0x028 T: word table written by EfType30_SetActorParams sub 1 (word[40 + 2*arg0] = arg1) and cleared by InitChildObject; sub_413940 reads [0] as the speed
 unsigned __int16 aiActionTimer; // +0x03C T: CPU AI: frames left in the running AI script command (FighterCpuAiStep decrements it when not in hit-stop, then calls FighterCpuAi_ApplyScriptCommand)
 unsigned __int16 aiReactCooldown; // +0x03E T: CPU AI: frames before the next decision / guard reaction (FighterCpuAiStep loads the difficulty delay v28 or v28 >> 2 and counts it down)
 __int16 aiScriptIndex; // +0x040 T: CPU AI: index of the running AI script, -1 = none (FighterCpuAiStep, FighterCpuAi_ApplyScriptCommand)
 __int16 aiScriptStep; // +0x042 T: CPU AI: step inside the AI script (FighterCpuAiStep increments it, sub_403C10 / ApplyScriptCommand)
 unsigned char cpuCommandReady; // +0x044 T: CPU command request latch: IF 11/25 consume it when controlType == CPU (Actor_RunFrameIfRecord); cleared by ObjRunActionScript
 unsigned char unreferenced_45[3]; // +0x045 U: no access in any function
 int superMeter; // +0x048 T: super meter, 10000 per level, capped 90000 (AddSuperMeter, EfType6 op 4, Actor_SpawnEffectById spends 10000*cost; IF 11 compares f048/10000 with the move cost); preserved across rounds
 unsigned char superMeterFlash; // +0x04C T: AddSuperMeter sets 10 when a 30000 threshold is crossed (no reader in the traced set)
 unsigned char unreferenced_4D[3]; // +0x04D U: no access in any function
 int reserveGauge; // +0x050 T: third gauge 0..10000: EfType6 op 4 adds arg2 and clamps, sub_4252A0 adds the pending combo gauge, sub_424980 clears it at round start; preserved across rounds by InitFighterSlotForRound
 unsigned char unreferenced_54[4]; // +0x054 U: no access in any function
 int reservePending; // +0x058 T: reserve gauge gain waiting to be banked: sub_4252A0 adds it to reserveGauge (capped 10000) when g_combo_guard_flags[teamIndex] is set and clears it; no writer found in the traced set
 int life; // +0x05C T: hit points, 11400 at round start (InitFighterSlotForRound); Damage_*, ObjFighterStateAndHitReaction, EfType5/6 modify it; <= 0 is KO
 int lifeInitCopy; // +0x060 U: written with 11400 by InitFighterSlotForRound / FighterSlot_ResetKeepingDataPointers, never read
 unsigned char unreferenced_64[2]; // +0x064 U: no access in any function
 unsigned char superMoveState; // +0x066 T: 2 while a super move is active (sub_4242C0 sets it when superMoveFlag; sub_424980 clears it; ObjFighterStateAndHitReaction halves guard damage by the attacker owner state)
 unsigned char superMoveFlag; // +0x067 T: armed by sub_426BD0 when a command move is accepted, consumed by sub_4242C0
 unsigned char clearHistoryOnAction; // +0x068 T: set from command flag 0x10 (sub_426BD0); sub_4242C0 then clears both input rings with sub_4266D0
 unsigned char unreferenced_69[3]; // +0x069 U: no access in any function
 int guardGauge; // +0x06C T: guard gauge, guard break above 10000 (ObjFighterStateAndHitReaction adds AT.guardBreakValue; Actor_DecayGuardGauge decays it in steps of 7..15; DrawFighterSprite flashes above 8000)
 unsigned char unreferenced_70[4]; // +0x070 U: no access in any function
 int guardRegenDelay; // +0x074 T: frames before the guard gauge starts to decay (45/60/90 set by ObjFighterStateAndHitReaction, 120 by sub_426BD0; Actor_DecayGuardGauge)
 int posX; // +0x078 T: world X in 1/128 pixel units (sub_413940, ObjIntegrateMotion, Actor_RunFrameIfRecord, InitChildObject, camera code)
 int posY; // +0x07C T: world Y in 1/128 pixel units, 0 = ground, negative = up (ObjIntegrateMotion lands at > 0)
 unsigned char unreferenced_80[4]; // +0x080 U: no access in any function
 int posXAtTickEnd; // +0x084 T: posX copy written at the end of ObjIntegrateMotion; never read
 int posXAtTickStart; // +0x088 T: posX before the tick (ObjIntegrateMotion, sub_413940); EffectObjects_UpdateAll and ObjResolvePushboxCollision read it back
 int posYAtTickStart; // +0x08C T: posY before the tick (ObjIntegrateMotion, sub_413940, EffectObjects_UpdateAll)
 int velX; // +0x090 T: velocity X (Actor_ApplyFrameMotionFlags adds AS.velX, ObjIntegrateMotion integrates it)
 int velY; // +0x094 T: velocity Y
 __int16 accelX; // +0x098 T: acceleration X (AS.accelX, ObjIntegrateMotion)
 __int16 accelY; // +0x09A T: acceleration Y (gravity, AS.accelY)
 __int16 maxVelX; // +0x09C T: X speed clamp (AS.maxVelX, ObjIntegrateMotion)
 unsigned char unreferenced_9E[2]; // +0x09E U: no access in any function
 int knockVelX; // +0x0A0 T: knockback velocity X (Actor_StartKnockback, ObjIntegrateMotion adds knockAccelX and zeroes it on sign change)
 int knockVelY; // +0x0A4 T: knockback velocity Y
 __int16 knockAccelX; // +0x0A8 T: knockback friction X (g_HitVectorTable, ObjIntegrateMotion)
 __int16 knockAccelY; // +0x0AA T: knockback gravity Y
 int inertiaX; // +0x0AC T: carried inertia added to posX each tick, decays by inertiaDecay (Actor_ApplyFrameMotionFlags, ObjIntegrateMotion; divided by 3 when entering the air)
 int carriedVelX; // +0x0B0 T: velX saved when AS.flags1 bit 0 is set, turned into inertiaX on the next pattern (Actor_ApplyFrameMotionFlags)
 __int16 inertiaDecay; // +0x0B4 T: carriedVelX / 16 (Actor_ApplyFrameMotionFlags); ObjIntegrateMotion subtracts it from inertiaX
 unsigned __int16 carryPattern; // +0x0B6 T: pattern in which carriedVelX was saved (Actor_ApplyFrameMotionFlags, ObjIntegrateMotion)
 __int16 grabDrawOffsetX0; // +0x0B8 T: start draw offset X of a grabbed actor (EfType4/5 write it, DrawFighterSprite lerps to grabDrawOffsetX1 by the grabber progress, scaled 0.75)
 __int16 grabDrawOffsetY0; // +0x0BA T: start draw offset Y of a grabbed actor
 __int16 zoomOriginX0; // +0x0BC T: zoom/rotation origin X at the start of the grab animation, 320 by default (Render_QueueFighterSprite lerps it with zoomOriginX1)
 __int16 zoomOriginY0; // +0x0BE T: origin Y, 240 by default
 __int16 grabDrawOffsetX1; // +0x0C0 T: end draw offset X of a grabbed actor (EfType4/5, DrawFighterSprite)
 __int16 grabDrawOffsetY1; // +0x0C2 T: end draw offset Y
 __int16 zoomOriginX1; // +0x0C4 T: zoom/rotation origin X at the end, 320 by default
 __int16 zoomOriginY1; // +0x0C6 T: origin Y at the end, 240 by default
 __int16 rotAngleA; // +0x0C8 T: rotation angle, 1/10000 turn: ObjRunActionScript adds 950 per tick while thrown; passed to sub_42FEF0 by Render_QueueFighterSprite; EfType5 sets it from EF arg4
 __int16 rotAngleB; // +0x0CA T: second rotation angle passed to sub_42FEF0 (set together with rotAngleA)
 unsigned char clearInertiaRequest; // +0x0CC T: set by Actor_StartKnockback; Actor_ApplyFrameMotionFlags then clears inertiaX/inertiaDecay
 enum Gof1AttackResultFlags attackResult; // +0x0CD T: result of this actor attack on its victim (doc actor+205): ObjFighterStateAndHitReaction sets 1/2 and 0x10/0x20 by the victim stance, ObjCheckAttackVsFighters sets 8; reset by ObjEnterCurrentAction; tested by IF 3/6, Actor_RequestLocomotionFromInput
 enum Gof1AttackResultFlags ownerAttackResult; // +0x0CE T: copy of a child attack result written into its owner (ObjFighterStateAndHitReaction f22C->f0CE = f0CD)
 unsigned char drawDepth; // +0x0CF T: draw order key 5..255 (Actor_ApplyDrawPriority; SpawnEffectFromActorFrame; Render_QueueFighterSprite)
 unsigned char drawModeVariant; // +0x0D0 T: row offset into g_DrawModeRemapTable while grabbed (EfType4 sets frame/1000; DrawFighterSprite, Box_ApplyDrawModeTransform)
 unsigned char activeMoveMeterCost; // +0x0D1 T: meter levels of the running command move (IF 11 copies command+36; Actor_SpawnEffectById spends it, sub_426BD0)
 unsigned char superCancelFlag; // +0x0D2 T: sub_426BD0 sets it when a super is started out of a non-actionable frame (v20); ObjRunActionScript stops voice class 10 with sub_42C5B0 and clears it on the next action change
 unsigned char hitstopFrames; // +0x0D3 T: remaining hit-stop frames (Actor_SetHitstopFrames; ObjRunActionScript / ObjIntegrateMotion skip while non-zero)
 unsigned char hitstopTrailing; // +0x0D4 T: set to 1 by ObjFighterStateAndHitReaction; ObjRunActionScript counts it down with hitstopFrames and clears landed when it runs out
 unsigned char contactMark; // +0x0D5 T: set to 1 by ObjCheckAttackVsFighters / ObjCheckAttackVsObjects / ObjCheckReflectBoxVsAttacks when this actor attack box touched something; read by FighterCpuAiStep to chain AI script steps
 unsigned char grabState; // +0x0D6 T: 0 free, 1 held by a fighter, 2 held by a child object (Actor_TryGrabFighter); gates ObjRunActionScript, ObjIntegrateMotion, hit detection
 unsigned char inputLock; // +0x0D7 T: EfType6 op 9 sets it (doc SET_FLAG_215); blocks input dispatch (Actor_DispatchInputByStance, sub_43A120, sub_426BD0)
 unsigned char freezeTimerA; // +0x0D8 T: EfType6 op 2 arg0; Actor_TickFreezeTimers counts it down; also set to 2/8/10 by Actor_ApplyFrameMotionFlags
 unsigned char freezeTimerB; // +0x0D9 T: EfType6 op 2 arg1; counted down by Actor_TickFreezeTimers; checked by ObjCheckAttackVs*
 unsigned char koFlag; // +0x0DA T: set at KO by ObjFighterStateAndHitReaction (EfType6 op 252 writes it, doc SET_BYTE_218); tested by sub_424780, ObjResolvePushboxCollision, Camera_UpdateFixedScreen
 unsigned char cameraExcludeFlag; // +0x0DB T: Camera_UpdateFixedScreen skips fighters with it set; no writer in the traced set
 unsigned char attackHitsLeft; // +0x0DC T: hits the current attack may still land (AS.attackHitCount loaded by ObjEnterCurrentAction; ObjCheckAttackVs* decrement; doc actor+220)
 unsigned char guardState; // +0x0DD T: non-zero while guarding (ObjFighterStateAndHitReaction sets 1; DrawFighterSprite flashes when > 4; sub_426BD0 gates guard-cancel moves on > 4)
 unsigned char cpuGuardRequest; // +0x0DE T: written by FighterCpuAiStep (random guard decision by difficulty); ObjFighterStateAndHitReaction treats the hit as guardable when set (a human actor never sets it)
 unsigned char unreferenced_DF[3]; // +0x0DF U: no access in any function
 unsigned char recoverMode; // +0x0E2 T: wake-up/recovery selector set by ObjFighterStateAndHitReaction (0, 1, 25), Actor_WallBounceReaction, cleared by EfType4
 unsigned char recoverReserved; // +0x0E3 U: only written (0) by ObjRunActionScript / ObjFighterStateAndHitReaction, never read
 unsigned char bounceCount; // +0x0E4 T: wall/ground bounces taken (Actor_WallBounceReaction increments; ObjRunActionScript wraps > 2 to -16)
 unsigned char recoveryTimer; // +0x0E5 T: frames since the last hit (ObjRunActionScript increments, ObjFighterStateAndHitReaction resets; Actor_TryTechOrCrouchGuardSwitch window < 16)
 unsigned char throwTechSeen; // +0x0E6 T: set on the grabber by sub_425E10 when a throw tech succeeds; ComboRecord_RegisterHit flags the combo
 unsigned char stageEdgeSide; // +0x0E7 T: 1/2 = pushed past the right/left stage edge by sub_425A50; sub_424780 / ObjResolvePushboxCollision use it for wall bounce
 unsigned char airComboStarterLatch; // +0x0E8 T: set by ObjFighterStateAndHitReaction when AT.flagsB 0x10 hit lands, cleared by ObjRunActionScript / Actor_StartKnockback test
 unsigned char throwTechAllowed; // +0x0E9 T: ObjFighterStateAndHitReaction sets !(AT.flagsB & 0x20) ...; sub_425E10 requires it
 unsigned char inputBlockFlag; // +0x0EA T: sub_43A120 refuses input while set; cleared by ObjRunActionScript; no writer in the traced set
 unsigned char counterHitSide; // +0x0EB T: 1 = this actor landed a counter-hit (set on the attacker owner), 2 = this actor was counter-hit (set on the victim) by ObjFighterStateAndHitReaction; Actor_StartKnockback and sub_4242C0 clear it; sub_426BD0 (counter-hit cancels, evade moves) and Actor_RequestLocomotionFromInput read it
 unsigned __int16 scriptTimer[5]; // +0x0EC T: five countdown words (Actor_TickWordTimers); EfType6 op 10 (doc SET_WORD_VAR_236) sets [arg0]; [0] = hyper armor window and [2] = counter-hit window are read by ObjFighterStateAndHitReaction
 unsigned char hitQueueClear; // +0x0F6 T: ObjCheckAttackVs* set 1 to discard last tick hit queue; ObjFighterStateAndHitReaction zeroes hitQueueCount when set
 unsigned char hitQueueCount; // +0x0F7 T: number of valid hitAt/hitRect/hitAttacker entries, max 8 (ObjCheckAttackVsFighters, ObjCheckAttackVsObjects, Actor_TryGrabFighter)
 enum Gof1StatusEffect tintMode; // +0x0F8 T: AT.statusEffect written by ObjFighterStateAndHitReaction; DrawFighterSprite tints by it (1 red pulse, 2 random shimmer, 3 yellow/black/grey)
 unsigned char shakeTimer; // +0x0F9 T: draw shake after a hit (DrawFighterSprite offsets Y by f0F9>>2 on odd ticks); counted down by Actor_TickFreezeTimers
 __int16 hitStage; // +0x0FA T: 0 = not in hit-stun; 1..239 = remaining stun frames; 240..255 = launch/air stages dispatched by Actor_ApplyFrameMotionFlags (byte_425734); set from g_HitVectorTable by Actor_StartKnockback
 __int16 juggleState; // +0x0FC T: non-zero while the victim is in an air juggle (halves damage in Damage_ScaleByComboAndLife; sub_424780 wall bounce rule); cleared by Actor_TryGrabFighter
 unsigned __int16 hitReactionId; // +0x0FE T: reaction index passed to Actor_StartKnockback (g_HitVectorTable row); sub_424780 / Actor_WallBounceReaction compare 9, 13, 27
 __int16 hitStageAtHit; // +0x100 T: copy of hitStage taken by Actor_StartKnockback (read by sub_426BD0 as < 240)
 unsigned char hitRecoverFrames; // +0x102 T: recovery frames after a hit, computed by ObjFighterStateAndHitReaction from hitStage and hitsTakenInCombo, cleared by EfType4_ControlGrabbedOpponent; no reader in the traced set
 unsigned char unreferenced_103; // +0x103 U: no access in any function
 unsigned char invulnFlags; // +0x104 T: non-zero = takes no damage (ObjFighterStateAndHitReaction, sub_43A120); EfType6 op 255 sets 0x10 (doc SET_FLAG_260)
 unsigned char scriptFlag105; // +0x105 T: EfType6 op 254 sets 1 (doc SET_FLAG_261); cleared by Battle_InitRoundFighters / Round_IntroStateMachine; no reader in the traced set
 unsigned char koMoveType; // +0x106 T: (attacker move type & 0x7F) + 1 when the actor is KO by it (ObjFighterStateAndHitReaction); non-zero blocks recovery (Actor_StartKnockback, sub_426BD0)
 unsigned char inputHeldFlags; // +0x107 T: Actor_DispatchInputByStance sets bit 7 when the direction is neutral and clears it for crouch/air; ObjRunActionScript clears it; no reader in the traced set
 unsigned char inputReserved_108; // +0x108 U: only written (0) by ObjRunActionScript, never read
 unsigned char guardRecoveryFlag; // +0x109 T: 1 after a guard-cancel/early guard (Actor_StartKnockback special case), read by Actor_CanGuardAttack and Actor_TryTechOrCrouchGuardSwitch
 unsigned __int16 mashCounter; // +0x10A T: counts button presses while in hit-stun (Actor_TryTechOrCrouchGuardSwitch); Damage_ScaleByComboAndLife reduces damage by 0.3% each; sub_426BD0 tests it
 signed char tobiCount[10]; // +0x10C T: ten projectile ("TOBI") counters shown by Debug_DrawEntityInfo as "TOBI %03d"; EfType6 op 100/101 add/subtract (arg0 tens digit = index, units = amount), sub_426BD0 refuses a command when the counter is too low
 unsigned char dashCount; // +0x116 T: shown by Debug_DrawEntityInfo as "DASH %03d"; EfType6 op 102/103 add/subtract (doc ADD_BYTE_278); cleared by ObjRunActionScript
 unsigned char unreferenced_117; // +0x117 U: no access in any function
 __int16 paramVar[10]; // +0x118 T: ten word variables shown by Debug_DrawEntityInfo as "PARAM %05d"; EfType6 op 105 sets/adds [arg0]; IF 25/31 compare/write them (Actor_RunFrameIfRecord); Actor_SpawnEffectById reads [1],[2]; SpawnCommonEffectObject copies a 20-byte defaults block here
 unsigned char trailMode; // +0x12C T: ghost trail colour mode + 1 (EfType6 op 0; DrawFighterSprite spawns SpawnEffectFromActorFrame every 7th tick); on a ghost object (objKind 31) it is the colour mode read by sub_413FD0
 unsigned char unreferenced_12D; // +0x12D U: no access in any function
 unsigned __int16 decorLifeTotal; // +0x12E T: ghost object total life (SpawnEffectFromActorFrame a5; sub_413FD0 fades alpha by lifeTimer / this)
 enum Gof1DecorFlags decorFlags; // +0x130 T: ghost object flags (SpawnEffectFromActorFrame a6; sub_413FD0 adds 10 to the depth when bit 0)
 __int16 decorZoomGrowX; // +0x132 T: ghost zoom change per remaining tick X (SpawnEffectFromActorFrame a3; sub_413FD0)
 __int16 decorZoomGrowY; // +0x134 T: ghost zoom change per remaining tick Y (a4)
 unsigned char afterimageMode; // +0x136 T: afterimage config id + 1 (EfType6 op 3); DrawFighterAfterimage switches on it, 0 = off
 unsigned char afterimageSteps; // +0x137 T: number of afterimage steps <= 119 (EfType6 op 3 arg1; DrawFighterAfterimage)
 unsigned char afterimageSpacing; // +0x138 T: spacing of the steps (EfType6 op 3 arg2; DrawFighterAfterimage)
 unsigned char afterimageRestart; // +0x139 T: set to 1 by EfType6 op 3 when the mode changes; no reader in the traced set
 unsigned char justGuardActive; // +0x13A T: set when a just-guard (button bit 7 and CT flag 8) absorbs a hit (ObjFighterStateAndHitReaction); Actor_StartKnockback then pushes the attacker back instead
 unsigned char unreferenced_13B; // +0x13B U: no access in any function
 unsigned __int16 locomotionUsedMask; // +0x13C T: bit n = pattern n (1..9 walk/run/dash/jump) used since the last landing (ObjRunActionScript); Actor_RequestLocomotionFromInput tests bits 1,2,4,0x10,0x20,0x80,0x100
 unsigned char commandUsedMask[14]; // +0x13E T: bit i = command move i already used in this chain (ObjRunActionScript sets it, sub_426BD0 refuses repeats, sub_43BE80 counts the bits)
 unsigned char pendingCommandId; // +0x14C T: command move accepted by sub_426BD0 this tick (0xFF = none); ObjRunActionScript moves it into commandUsedMask
 unsigned char lastCommandId; // +0x14D T: previous pendingCommandId (ObjRunActionScript writes it); no reader in the traced set
 __int16 hitsTakenInCombo; // +0x14E T: consecutive hits taken (ObjFighterStateAndHitReaction increments; ObjRunActionScript indexes byte_463FE0 with it to time recovery)
 unsigned __int16 attackHitsConnected; // +0x150 T: hits landed by the current action (ObjCheckAttackVsFighters/Objects increment; IF 17 compares with p1; sub_4242C0 clears)
 unsigned char evadeDir; // +0x152 T: 1 forward / 2 back double-tap evade detected by sub_427040; ObjFighterStateAndHitReaction picks the evade-high/low answer from it
 unsigned char evadeTimer; // +0x153 T: evade window counter (sub_427040 loads 8, then -8 cooldown; ObjFighterStateAndHitReaction)
 unsigned char unreferenced_154[2]; // +0x154 U: no access in any function
 enum Gof1FlashMode flashMode; // +0x156 T: colour flash mode (Actor_SetColorFlash; DrawFighterSprite / sub_413FD0 switch)
 unsigned char flashTimer; // +0x157 T: remaining flash frames (Actor_TickFreezeTimers decrements)
 unsigned char flashDuration; // +0x158 T: total flash frames, denominator of the fade modes
 unsigned char requestParam; // +0x159 T: argument a5 of ObjRequestAction, cleared by ObjRunActionScript, set from command byte +38 by sub_426BD0; no reader in the traced set
 enum Gof1CounterCommand counterWindowState; // +0x15A T: counter-hit window set by frame flags2 bits 20..23 (ObjEnterCurrentAction); ObjFighterStateAndHitReaction reads it to apply the counter bonus
 unsigned char unreferenced_15B; // +0x15B U: no access in any function
 __int16 launchVelX; // +0x15C T: stage-2 launch velocity X loaded when hitStage advances (Actor_StartKnockback fills it from g_HitVectorTable, Actor_ApplyFrameMotionFlags consumes it)
 __int16 launchVelY; // +0x15E T: stage-2 launch velocity Y
 __int16 launchAccelX; // +0x160 T: stage-2 acceleration X
 __int16 launchAccelY; // +0x162 T: stage-2 acceleration Y
 struct Gof1AtRecord *hitAt[8]; // +0x164 T: AT record of each hit received this tick (ObjCheckAttackVsFighters writes *(a+4*count+356); ObjFighterStateAndHitReaction reads)
 struct Gof1RectI32 hitRect[8]; // +0x184 T: world rectangle of each overlap (ObjCheckAttackVsFighters writes 16 bytes at +388+16*count; used to place the hit spark)
 struct Gof1Actor *hitAttacker[8]; // +0x204 T: attacking actor of each hit (ObjCheckAttackVsFighters writes *(a+4*count+516))
 struct Gof1Actor *lastAttacker; // +0x224 T: attacker of the last accepted hit (ObjFighterStateAndHitReaction); Actor_StartKnockback applies the push to it on a just-guard; ObjResolvePushboxCollision
 struct Gof1Actor *grabbedBy; // +0x228 T: grabber while grabState != 0 (Actor_TryGrabFighter victim->f228 = grabber; ObjIntegrateMotion drags the grabber position along)
 struct Gof1Actor *ownerFighter; // +0x22C T: owning fighter of a child object (InitChildObject via sub_424560, SpawnChildEffectFromParent); homing target in sub_413940; 0 for fighters
 struct Gof1Actor *linkedActor; // +0x230 T: parent actor of a child (InitChildObject, SpawnChildEffectFromParent; read by EffectObjects_UpdateAll, Actor_SetHitstopFrames, DrawFighterSprite) / grab victim of a fighter (Actor_TryGrabFighter and sub_425E10 write it)
 enum Gof1InputDirection inputDir; // +0x234 T: numpad direction facing-corrected (ReadBattleInputForPlayer; mirrored by Actor_MirrorInputDirection via dword_463FB8; recorded by ReplayRecordOrPlaybackFighterInput)
 unsigned char unreferenced_235[3]; // +0x235 U: no access in any function
 enum Gof1InputButtonFlags inputButtons; // +0x238 T: buttons held (bits 0..5) and pressed this tick (bits 12..17) (ReadBattleInputForPlayer a3; replay recorder; Actor_RequestLocomotionFromInput, sub_425E10 tests & 0xF)
 enum Gof1InputButtonFlags inputButtonsReleased; // +0x23C T: buttons released this tick (bits 0..5) (ReadBattleInputForPlayer a4); input ring B ORs it in (UpdateFighterInputHistoryRings)
 unsigned char teamIndex; // +0x240 T: side/team 0 or 1 (InitFighterSlotForRound a2; children copy it); same-team test in ObjCheckAttackVsFighters, indexes per-team stats (dword_1552F70[15*i])
 unsigned char endConditionMet; // +0x241 T: set by IF 2 END_CONDITION and by EffectObjects_UpdateAll (doc actor+577); the object is removed on the next tick
 unsigned __int16 pendingPattern; // +0x242 T: pattern requested by ObjRequestAction, 0xFFFF = none (ObjRunActionScript consumes it)
 __int16 pendingPatternPriority; // +0x244 T: priority of the pending request, -1 = none; a request wins when its priority is higher (ObjRequestAction)
 unsigned __int16 pendingFrame; // +0x246 T: frame requested by sub_424510 / IF jumps, 0xFFFF = none
 __int16 pendingFramePriority; // +0x248 T: priority of the pending frame jump, -1 = none
 unsigned char facingLeft; // +0x24A T: 0 faces right, 1 faces left (read by ~70 functions: sub_413940, DrawFighterSprite, Actor_ApplyFrameMotionFlags, InitChildObject)
 unsigned char nextFacingLeft; // +0x24B T: facing to turn to when the action changes (ObjRunActionScript copies it into facingLeft; Actor_WallBounceReaction, EfType6 op 5, sub_413940)
 unsigned char facingReserved_24C; // +0x24C U: only written (0xFF) by InitFighterSlotForRound / FighterSlot_ResetKeepingDataPointers, never read
 unsigned char mirrorHistoryPending; // +0x24D T: read by UpdateFighterInputHistoryRings and sub_426910: when the facing changed and it is 1 the recorded directions are mirrored (dword_463FB8) and it is cleared
 unsigned char inputActionLatch; // +0x24E T: set 1 by IF 6/7 input jumps with flag 4 (doc actor+590); ObjRunActionScript steps it 1 -> 2 -> 0; EffectObjects_UpdateAll kills children when the parent shows 2
 unsigned char actionChangedFlag; // +0x24F T: sub_4242C0 sets 1 on every action change, Actor_TickWordTimers clears it; children with spawnFlagsA bit 0x20 die when the parent shows 1
 unsigned char landed; // +0x250 T: 1 when posY reached the ground (ObjIntegrateMotion; doc actor+592): drives aniFlag 3/4 landing jumps, IF 2 p1, Actor_ApplyFrameMotionFlags
 unsigned char actionEnded; // +0x251 T: ObjRunActionScript sets it when a landing/animation end finished the action; EffectObjects_UpdateAll ends children whose parent shows it
 enum Gof1Stance stanceCopy; // +0x252 T: AS.stance of the previous tick (ObjRunActionScript); ObjIntegrateMotion divides inertiaX by 3 on a ground-to-air change
 unsigned char unreferenced_253; // +0x253 U: no access in any function
 struct Gof1Box *boxTable; // +0x254 T: pattern + boxTableOffset or 0 (Actor_ResolveFrameDataPointers; doc actor+596)
 struct Gof1CharDatHead *charData; // +0x258 T: character pattern block (Slot_BindCharacterData from g_CharPatternData; Pattern_Get* read patternOffset[] through it)
 struct Gof1PatternHeader *patternHeader; // +0x25C T: current pattern header (Actor_ResolveFrameDataPointers; Actor_GetPatternFrameRecords)
 struct Gof1FrameRecord *frameRecord; // +0x260 T: current 116-byte frame record (Actor_ResolveFrameDataPointers; ObjCheckAttackVsFighters reads atIndex at +80)
 struct Gof1AnimFrame *animFrame; // +0x264 T: same address as frameRecord, typed as the AF half (DrawFighterSprite, ObjRunActionScript)
 struct Gof1StateFrame *stateFrame; // +0x268 T: frameRecord + 40, the AS half (ObjIntegrateMotion, Actor_ApplyFrameMotionFlags)
 struct Gof1IfRecord *ifTable; // +0x26C T: pattern + ifTableOffset or 0 (ObjRunFrameEventsForPhase)
 struct Gof1EfRecord *efTable; // +0x270 T: pattern + efTableOffset or 0 (Actor_RunFrameEFs)
 __int16 *boxIndex; // +0x274 T: frameRecord + 96, the 10 box indices (Actor_FindOverlappingTarget, ObjCheckAttackVs*)
 void *partsData; // +0x278 T: character parts blob (Slot_BindCharacterData from g_CharPartsData; Render_QueueFighterSprite)
 void *cgData; // +0x27C T: character CG blob (Slot_BindCharacterData from g_CharCgData; Render_QueueFighterSprite)
 struct Gof1FighterSlot *fighterSlot; // +0x280 T: pointer to the owning fighter slot (InitFighterSlotForRound stores the slot itself); 0 for child objects; gates AddSuperMeter and gives access to the CT data
 unsigned char unreferenced_284[4]; // +0x284 U: no access in any function
 int actionTicks; // +0x288 T: ticks since the action started (ObjRunActionScript increments, sub_4242C0 clears; DrawFighterSprite flickers on % 3 / % 7)
 unsigned char ranThisTick; // +0x28C T: ObjRunActionScript sets 1 once it passed all gates, 0 at its start; Battle_UpdateAllCharactersInputAndAI, hit detection and DrawFighterSprite test it
 unsigned char unreferenced_28D[3]; // +0x28D U: no access in any function
};
struct Gof1HitVectorRow {  // 18 bytes, row r of g_HitVectorTable[32] (0x17F9208), loaded at start-up from the first section of VECTOR.TXT (HitVectors_LoadFromVectorTxt 0x42C1D0, 9 whitespace separated integers per row, rows end at END); row = reaction id passed to Actor_StartKnockback
 __int16 velX; // +0x000 T: knockback velocity X, multiplied by the attack direction sign (Actor_StartKnockback -> actor.knockVelX); vector.txt column 0
 __int16 velY; // +0x002 T: knockback velocity Y, scaled by the combo decay factor (-> actor.knockVelY); column 1
 __int16 accelX; // +0x004 T: knockback friction X, signed by direction (-> actor.knockAccelX); column 2
 __int16 accelY; // +0x006 T: knockback gravity Y (-> actor.knockAccelY); column 3
 __int16 launchVelX; // +0x008 T: velocity X of the launch stage reached when hitStage >= 240 (-> actor.launchVelX); column 4
 __int16 launchVelY; // +0x00A T: velocity Y of the launch stage (-> actor.launchVelY); column 5
 __int16 launchAccelX; // +0x00C T: acceleration X of the launch stage (-> actor.launchAccelX); column 6
 __int16 launchAccelY; // +0x00E T: acceleration Y of the launch stage (-> actor.launchAccelY); column 7
 __int16 hitStage; // +0x010 T: stun frames (< 240) or launch stage code 240..255 (-> actor.hitStage); column 8; 255 = air launch, 248 = ground slide
};
struct Gof1CommandMove {  // 46 bytes, record i of the CT file / Gof1FighterSlot.command[i]
 unsigned char commandId; // +0x000 T: own index, 0xFF = unused slot (sub_426FC0, sub_426BD0 test it)
 unsigned char unreferenced_01; // +0x001 U: zero in every record of all 8 characters, never accessed
 unsigned char sequence[32]; // +0x002 T: input token string 0xFF terminated: 0..9 direction, 0x41..0x46 buttons A..F, 0x2B + joiner, 0x54 T hold; parsed backwards from the last token by sub_4266F0 / sub_4267F0 (sub_426910). Bytes 16..31 are cleared by InitFighterSlotForRound
 unsigned char targetPattern; // +0x022 T: pattern requested when the command fires (sub_426BD0 -> ObjRequestAction; compared with the current pattern)
 enum Gof1CommandMoveClass moveClass; // +0x023 T: 0 system, 1 special, 2 super: selects the move-level rule in sub_426BD0
 unsigned __int16 meterCostLevels; // +0x024 T: super meter levels needed (compared with superMeter / 10000 in IF 11 and sub_426BD0; low byte -> activeMoveMeterCost)
 unsigned char requestParam; // +0x026 T: stored in actor requestParam (sub_426BD0)
 unsigned char unreferenced_27; // +0x027 U: zero in every record of all 8 characters, never accessed
 unsigned __int16 counterRequirement; // +0x028 T: tens digit = counter[] index and units = amount (< 100), or 100+ = global counter bank dword_1864EA0 (sub_426BD0 refuses when not enough)
 unsigned char unreferenced_2A[2]; // +0x02A U: zero in every record of all 8 characters, never accessed
 enum Gof1CommandFlags flags; // +0x02C T: see Gof1CommandFlags (sub_426BD0 stance/cancel gating, sub_426FC0 skips SCRIPT_ONLY)
 enum Gof1CommandFlags2 flags2; // +0x02D T: see Gof1CommandFlags2 (sub_426910 ring select / strictness, sub_426BD0 evade moves)
};
struct Gof1CtHeader {  // 28 bytes at CT file +4604 / Gof1FighterSlot.ct
 unsigned char unreferenced_00; // +0x000 U: zero in all 8 CT files, never accessed
 unsigned char unreferenced_01; // +0x001 U: 9 in all 8 CT files, never accessed
 unsigned char recoveryStyle; // +0x002 T: 1 in all files; ObjRunActionScript (0x424F23) switches the hit recovery handling on it
 unsigned char unreferenced_03; // +0x003 U: zero in all 8 CT files, never accessed
 unsigned char unreferenced_04; // +0x004 U: zero in all 8 CT files; sub_426BD0 reads the word at +4 but only tests bit 8 (= flags bit 0)
 enum Gof1CtFlags flags; // +0x005 T: 0x39 / 0x3B in the data; ObjRunActionScript (bit 0), sub_426BD0 (bit 0), ObjFighterStateAndHitReaction (bits 1, 3)
 unsigned char unreferenced_06[2]; // +0x006 U: zero in all 8 CT files, never accessed
 float knockbackScale; // +0x008 T: 1.0 in all files; Actor_StartKnockback multiplies the vertical knockback (0 means 1.0)
 float damageScaleByLifeTier[4]; // +0x00C T: 1.1 (AKIKO) / 0.9 (others) in all files; Damage_ScaleByComboAndLife picks it by the victim life tier (2850 / 5700 / 8550)
};
struct Gof1CtFile {  // 4632 bytes: the .CT file (<CHAR>_C.CT in gof_03.p) Character_LoadCtFile 0x4266A0 splits into slot.commandCount, slot.command[100] and slot.ct
 unsigned int commandCount; // +0x000 T: number of defined commands (Character_LoadCtFile a1[172]); the loop in InitFighterSlotForRound runs to it
 struct Gof1CommandMove command[100]; // +0x004 T: command table copied (0x11F8 bytes) to slot+692
 struct Gof1CtHeader ct; // +0x11FC T: 28 bytes copied to slot+660
};
struct Gof1InputRing {  // 512 bytes; 64 entries newest first, shifted by UpdateFighterInputHistoryRings
 unsigned int state[64]; // +0x000 T: (direction << 24) | buttons for each distinct input state (ring A: inputButtons, ring B: inputButtons | inputButtonsReleased); matched backwards by sub_426910
 unsigned int age[64]; // +0x100 T: frames spent in state[i] (capped at 1000000; sub_4266D0 sets 1000000 to invalidate the history)
};
struct Gof1FighterSlot {  // 6316 bytes; g_PlayerSlots[4] at 0x16224B0 (array ends exactly at g_DemoAttractMode 0x1628760)
 unsigned char active; // +0x000 T: 1 = slot in use (Slot_BindCharacterData, InitFighterSlotForRound set 1, FighterSlot_ResetKeepingDataPointers 0; all loops test it)
 unsigned char unreferenced_01[3]; // +0x001 U: no access in any function (pool stride 660 = 1 + 3 + 656)
 struct Gof1Actor actor; // +0x004 T: the actor (actor = slot + 4; memset 0x290 at InitFighterSlotForRound)
 struct Gof1CtHeader ct; // +0x294 T: CT header copied by Character_LoadCtFile (Actor_StartKnockback reads +8, Damage_ScaleByComboAndLife +12, ObjRunActionScript +2/+5)
 int commandCount; // +0x2B0 T: Character_LoadCtFile a1[172]; InitFighterSlotForRound clears the runtime tail of each of these commands
 struct Gof1CommandMove command[100]; // +0x2B4 T: command-move table (sub_426FC0 scans all 100; IF 11 indexes it)
 struct Gof1InputRing ringA; // +0x14AC T: input history A (UpdateFighterInputHistoryRings at +5292/+5548)
 struct Gof1InputRing ringB; // +0x16AC T: input history B with releases (+5804/+6060)
};
struct Gof1ObjectSlot {  // 660 bytes; g_EffectPool[1000] at 0x1628770 (660000 bytes, ends at 0x16C9990)
 unsigned char active; // +0x000 T: 1 = slot in use (Slot_BindCharacterData, InitFighterSlotForRound set 1, FighterSlot_ResetKeepingDataPointers 0; all loops test it)
 unsigned char unreferenced_01[3]; // +0x001 U: no access in any function (pool stride 660 = 1 + 3 + 656)
 struct Gof1Actor actor; // +0x004 T: the actor (InitChildObject: memset(slot + 4, 0, 0x290))
};
