# Gof2 Obj part B: bytes 0x620..0xC3F (decimal 1568..3135) of the 0x1264-byte pool slot, plus the tail of the one field that STRADDLES 0xC3F.
# MERGE NOTES
#  * 1568..1743 are members of the embedded CAppHanteiKougeki object, which BEGINS at 1556 (0x614, part A's range). They are listed flat here
#    because this range is required to start at 1568; the same layout as one nested struct is Gof2ObjAttackBoxSet (188 B, gof2obj_partB_types.h).
#    The merger should use ONE of the two (nested struct at 1556 replaces fields 1568..1743 below).
#  * hitHistoryByAttackerPattern (1976, 2048 B) ends at 4023 (0xFB7), i.e. beyond 0xC3F; it belongs to this range (first byte rule). Part C must start at 4024.
#  * 1776..4063 is ONE embedded object (vtable CAppHanteiYarare, 2288 B in total); this file owns class offsets 0..1359 of it. Class offset = Obj offset - 1776.
# Tuple: (decimal_offset, size_bytes, 'c type', 'name', 'comment: proving function(s) + [traced]/[inferred]/[unused]')
# [traced] = I read the code that reads/writes it; [inferred] = role deduced from usage pattern; [unused] = no operand with an Obj-based [reg+disp] / class-relative access found.
FIELDS = [
 # ---- CAppHanteiKougeki tail (class offset +12..+187, object starts at 1556) ----
 (1568, 4, 'struct Gof2AtRecord *', 'attackRecord', '[traced] CAppHanteiKougeki_BuildFromFrame 0x449250 (+0x0C = view->attackRecords + 236*frame.attackRecordIdx); read as *(obj+1568) by every HitJudge_* routine, sub_43BA00, sub_43C530'),
 (1572, 32, 'struct Gof2BoxRect *', 'attackBoxPtr[8]', '[traced] BuildFromFrame writes view->boxes[idx] for each non -1 frame.attackBoxIdx[0..7]; read through the vtable box getters (vf2 0x43E370, sub_43BB30, sub_49ABE0)'),
 (1604, 32, 'int', 'attackBoxSlot[8]', '[traced] BuildFromFrame writes the frame slot number (0..7) of box i next to attackBoxPtr[i]; read by the vtable getters'),
 (1636, 4, 'unsigned int', 'hitLimitFlags', '[traced] BuildFromFrame on ATKEV_BEGIN copies frame.hitLimitFlags (+0x48); cleared by CAppHanteiKougeki__vf4 0x43E2B0 (never read directly; zero in all frames)'),
 (1640, 4, 'unsigned int', 'hitLimitCount', '[traced] BuildFromFrame copies frame.hitLimitCount; sub_436280 (transition-rule type 1) compares it with +1644 ([410] vs [411])'),
 (1644, 4, 'unsigned int', 'hitsLandedForLimit', '[traced reads only] only reader is ObjEvent_ConditionalRuleSelectJump 0x436280 case 1 (0x4362F3) (`obj[411] < obj[410]` -> rule fails); no writer exists in the exe (all [reg+0x58] stores in the Kougeki vtable methods and no Obj-base store at 1644), so it stays at its zero default'),
 (1648, 4, 'int', 'attackEndLatch', '[traced writer only] CAppHanteiKougeki__vf5 0x449230 and vf6 0x43E2A0 clear it (class +0x5C); no reader found'),
 (1652, 8, 'unsigned char', 'unused_674[8]', '[unused] class +0x60/+0x64: no Kougeki method touches them and no Obj-base [reg+1652/1656] operand exists outside CharaSelect scene structs (scene hits are different objects)'),
 (1660, 4, 'int', 'attackActive', '[traced writer only] BuildFromFrame sets 1 when frame.attackEventFlags has ATKEV_BEGIN; CAppHanteiKougeki__vf3 0x449220 clears it; no reader found'),
 (1664, 4, 'int', 'boxJitterX', '[traced] CAppHanteiKougeki__vf7 0x43E320 = Rng_Range(g_RngStream_Game, ControllerManage+1324) after a successful build; CAppHanteiKougeki__vf2 0x43E370 widens the returned attack rect horizontally by it'),
 (1668, 4, 'int', 'boxJitterY', '[traced] vf7 (Rng_Range with ControllerManage+1328); vf2 widens the rect vertically by it'),
 (1672, 4, 'int', 'moveHitCount', '[traced] -1 = disabled; ++ on every connected hit (HitJudge_ApplyHit 0x4983A0, HitJudge_ResolveHitsOnGuardingVictim) and Obj_ExecCmdListBetween 0x43AAF0; cleared by Obj_ResetHanteiBoxObjects 0x4356A0; >1 scales gauge gain by ControllerManage+1232/1000 (sub_494B60, sub_494C70, sub_494E20)'),
 (1676, 4, 'int', 'counterHitSeen', '[traced] ObjHitFlags_RecordHit 0x43C210 sets 1 when variant==1; Obj_GetNormalCancelState 0x4302E0, Obj_IsSpecialCancelAllowed 0x430120, Obj_GetNormalCancelStateScriptGated 0x4301C0 test ==1 (cancel allowed after a counter hit)'),
 (1680, 4, 'Gof2ObjHitFlagBits', 'hitFlags', '[traced] ObjHitFlags_RecordHit 0x43C210 (variant 0): |=1 on self, |=2 on every ancestor (obj+560 chain); rule matching in Obj_HitFlagRuleMatches 0x42F5B0 (rule bit 1); Obj_AnyHitFlagSet 0x42F570'),
 (1684, 4, 'Gof2ObjHitFlagBits', 'counterHitFlags', '[traced] ObjHitFlags_RecordHit (variant != 0); rule bit 0x10000 in 0x42F5B0'),
 (1688, 4, 'Gof2ObjHitFlagBits', 'guardStunHitFlags', '[traced] ObjHitFlags_RecordGuardStunHit 0x43C2A0 (kind 0, caller HitJudge_ResolveHitsOnGuardingVictim: hit on a victim already in a guard state 21/22/23/54/55/57 that did not crush the guard); rule bit 2'),
 (1692, 4, 'Gof2ObjHitFlagBits', 'guardCrushHitFlags', '[traced] same function with variant != 0 (HitJudge_ResolveHitsOnGuardingVictim passes the sub_440E60 guard-gauge result); rule bit 0x20000'),
 (1696, 4, 'Gof2ObjHitFlagBits', 'clashFlags', '[traced] ObjHitFlags_RecordClash 0x43C320 from Obj_ApplyContactEventList 0x43C530 (event kind 2) and sub_49B2E0 (box clash); rule bit 4'),
 (1700, 4, 'Gof2ObjHitFlagBits', 'guardedFlags', '[traced] ObjHitFlags_RecordGuarded 0x43C360 from HitJudge_OnAttackGuarded 0x4967C0, sub_49BB70 and event kind 3; rule bit 8'),
 (1704, 4, 'unsigned int', 'counterHitStanceMask', '[traced] ObjHitFlags_RecordHit ORs the victim stanceClass (Gof2StanceClass, obj+660) here for variant != 0, ancestors get it <<8; read by 0x42F5B0 as the stance filter of counterHitFlags'),
 (1708, 4, 'unsigned int', 'hitStanceMask', '[traced] same for variant 0 (partner of hitFlags)'),
 (1712, 4, 'unsigned int', 'guardStunHitStanceMask', '[traced] ObjHitFlags_RecordGuardStunHit, variant 0 (partner of guardStunHitFlags)'),
 (1716, 4, 'unsigned int', 'guardCrushHitStanceMask', '[traced] ObjHitFlags_RecordGuardStunHit, variant != 0 (partner of guardCrushHitFlags)'),
 (1720, 4, 'unsigned int', 'clashStanceMask', '[traced] ObjHitFlags_RecordClash (partner of clashFlags)'),
 (1724, 4, 'unsigned int', 'guardedStanceMask', '[traced] ObjHitFlags_RecordGuarded (partner of guardedFlags)'),
 (1728, 4, 'int', 'clashState', '[traced] ObjHitFlags_MarkAttackClash 0x43C420: 1 on self, 2 on every ancestor (event kind 8 in Obj_ApplyContactEventList); read by sub_433100 and sub_433D00'),
 (1732, 4, 'int', 'framesSinceHit', '[traced] -1 at reset (CAppHanteiKougeki__vf4); 0 on every connected hit/guard/clash (HitJudge_ApplyHit, HitJudge_OnAttackGuarded, sub_49B2E0, sub_49BB70); ++ per tick, saturating at -1/0x7FFFFFFF (Obj_TickTimersRecursive 0x49E120); sub_430280 compares it with ControllerManage+1152'),
 (1736, 8, 'int', 'alreadyHitVictim[2]', '[traced] one-hit-per-victim latch, index victim.side(+1488)+victim.team(+1492): set 1 by HitJudge_ApplyHit, HitJudge_OnAttackGuarded, sub_49B360, sub_43C530; tested by HitJudge_CollectPairs, ObjScan_IsBlockableAttackFrame 0x432420, sub_49B520; cleared by vf4 (index range assumes team index 0; with team 1 the read would hit +1744)'),
 # ---- CAppHanteiKasanari (push/body box set, vtable 0x573CE0), 16 bytes ----
 (1744, 16, 'struct Gof2ObjPushBoxSet', 'pushBoxSet', '[traced] CAppHanteiKasanari__vf5 0x449620 (build from frame.kasanariBoxIdx), vf6 0x449680 / vf2 0x4496D0 (rect getters); used by Obj_ResolveBodyPushOverlap 0x49DB20 (a1+1744)'),
 (1760, 4, 'int', 'pushIgnore', '[traced] set by script command 27 sub 0 in Obj_ExecStateCmdList; Obj_ResolveBodyPushOverlap skips other objects whose value is non-zero; zeroed by Obj_InitDefaults'),
 (1764, 4, 'Gof2ObjPushMode', 'pushMode', '[traced] script command 27 sub 1; switch in Obj_ResolveBodyPushOverlap 0x49DB20'),
 (1768, 4, 'int', 'pushOpposingSideOnly', '[traced] script command 27 sub 2; value 1 = only push objects of another side (Obj_ResolveBodyPushOverlap checks +1488 differs)'),
 (1772, 4, 'int', 'pushImmovable', '[traced] script command 30 (Obj_ExecStateCmdList), forced to 1 temporarily by sub_43C530 event option; when 1 the object is never displaced by Obj_ResolveBodyPushOverlap (the other one absorbs the whole overlap)'),
 # ---- CAppHanteiYarare (hurt box set, vtable 0x573D00): class +0..+67; the object continues as the victim state ----
 (1776, 68, 'struct Gof2ObjHurtBoxSet', 'hurtBoxSet', '[traced] CAppHanteiYarare__vf6 0x4494F0 (build), vf2 0x449460 (rect), vf3 0x43E3C0, vf4 0x4494D0; users HitJudge_CollectPairs, HitJudge_ResolveHitsOnGuardingVictim, sub_49BB70, HitJudge_DefenderGuardsAttack'),
 # ---- victim / hit-reaction state (class +68..+199, Obj +1844..+1975); reset block = Yarare_ResetHitState (Yarare_ResetHitState) + Obj_ResetVictimReactionState 0x430770 ----
 (1844, 4, 'Gof2ObjReactionKind', 'reactionKind', '[traced] 0 = hit reaction (Victim_StartHitReactionFromScript 0x43D9F0), 1 = guard reaction (Victim_StartGuardReactionFromScript 0x43DBE0); Obj_ScriptTick 0x434AD0 picks the recovery path from it (0: sub_4317B0/sub_434A30, 1: state 55)'),
 (1848, 4, 'int', 'hitstunTicks', '[traced] script-returned stun length +1 (0 = none); counts down to 1 in Obj_TickTimersRecursive 0x49E120; Obj_ScriptTick treats 1 as expired; Victim_ExtendHitstun 0x49A2F0 adds ControllerManage+460'),
 (1852, 4, 'int', 'hitstunExtendBase', '[traced] 0 at start; Victim_ExtendHitstun stores the pre-extension value; counts down to 1 beside hitstunTicks; Obj_ScriptTick tests ==1 (v14 = 2 path)'),
 (1856, 4, 'int', 'recoverWhenMoverDone', '[traced] script result unk_5E76F4 (Victim_StartHitReactionFromScript); Obj_ScriptTick: when set and the knock mover (obj+712) reports finished -> clear and go to neutral (sub_434A30)'),
 (1860, 4, 'int', 'recoverOnLanding', '[traced] script result dword_5E76F8; Obj_ScriptTick: when set and the stance (obj+444) shows landing for the knock direction -> applies pending recover flags, sub_42F340, hit class 1896 = -1, neutral'),
 (1864, 4, 'Gof2ObjKnockXMode', 'knockSpeedXMode', '[traced reads only] passed as a4 of Victim_StartHitReactionFromScript (1 -> x speed 1200 permil, 2 -> 800); every writer only clears it (HitJudge_SetKnockDirection, HitJudge_ResolveGuardPassAndCrush, HitJudge_CommitPendingReactions), so only a script/zero can set it'),
 (1868, 4, 'Gof2ObjKnockYMode', 'knockSpeedYMode', '[traced] HitJudge_ApplyKnockDirAndFacing 0x435B10 sets 1/2 from the attacker status flags (+8 & 0xC = 4/8); Victim_StartHitReactionFromScript picks ControllerManage+204/+208 y scale'),
 (1872, 4, 'Gof2ObjKnockFlags', 'knockFlags', '[traced] HitJudge_ApplyKnockDirAndFacing |=1 when the attack record has G2AT_RF_HALVE_KNOCK_SCALE (0x8000000); sub_43D9F0 halves the x speed (a7 & 1)'),
 (1876, 4, 'unsigned int', 'attackerGuardMask', '[traced] copy of the attack record guardMask (+0x7C) written by HitJudge_ApplyKnockDirAndFacing[NoFlipCheck]; mask&3 selects the knock speed factor in sub_43D9F0 (ControllerManage+212/+216/+220); cleared after use'),
 (1880, 4, 'int', 'totalHitsTaken', '[traced] ++ (capped 0xF423F) in HitJudge_ApplyHit; also Obj_ExecCmdListBetween 0x43AAF0; x DefStatus+668 builds the gauge-gain bonus; cleared by Yarare_ResetHitState'),
 (1884, 8, 'int', 'hitsTakenByAttackKind[2]', '[traced] HitJudge_ApplyHit ++ [attackKind (record+0x80)] (cap 0xF423F); sub_495890 (HitJudge_ScaleDamageByComboHits) indexes the combo scaling table with it; cleared by Yarare_ResetHitState'),
 (1892, 4, 'Gof2AtHitClass', 'lastHitClass', '[traced] -1 none; copy of pendingHitClass in HitJudge_CommitPendingReactions 0x49A090; Obj_ScriptTick (case 2) tests != -1 to start the combat timer; Obj_SpawnFrameEffectRecord/HitJudge_ResolveGuardPassAndCrush write 11 (Gof2AtHitClass)'),
 (1896, 4, 'Gof2AtHitClass', 'activeHitClass', '[traced] -1 none; copy of pendingHitClass (0x49A090); HitJudge_StartVictimReaction tests its HitClass_ReactionPriority >= 8 for the in-progress reaction; reset to -1 on landing recovery (Obj_ScriptTick)'),
 (1900, 4, 'Gof2AtHitClass', 'pendingHitClass', '[traced] hit class chosen by HitJudge_StartVictimReaction -> Victim_EnterReactionState; -1 none, -2 = guard-crush special (HitJudge_ResolveHitsOnGuardingVictim), -3 temp in Obj_SpawnFrameEffectRecord; consumed (-> -1) by HitJudge_CommitPendingReactions 0x49A090 / HitJudge_ResolveGuardPassAndCrush'),
 (1904, 4, 'int', 'knockDirSign', '[traced] -1/0/+1 horizontal knock direction set by HitJudge_SetKnockDirection 0x435A80 (record knockDirMode 0..4) and sub_4993F0/HitJudge_ApplyHit; scales the knock mover x (sub_43D600/43D6E0/43D790/43D8A0); used by Obj_ApplyLandingFrameJump and Obj_ScriptTick'),
 (1908, 4, 'int', 'victimFacingSign', '[traced] -1/+1 facing the victim takes (HitJudge_SetVictimFacing 0x4359E0, ...NoFlipCheck); sub_43D5B0 turns it into obj+708; cleared by HitJudge_ApplyHit on a first counter hit'),
 (1912, 4, 'int', 'knockFacingRelation', '[traced] +1 if knockDirSign equals the victim facing sign else -1 (Victim_StartHitReactionFromScript/GuardReaction); Obj_ApplyFrameMoveFlags multiplies the frame x velocity by it*facing; Obj_ResetVictimReactionState sets 1'),
 (1916, 4, 'int', 'guardCrushLatch', '[traced writer only] Victim_MarkGuardCrush 0x496EA0 sets 1 (called when sub_440E60 reports the guard gauge crushed in HitJudge_ResolveHitsOnGuardingVictim); no reader found'),
 (1920, 4, 'int', 'guardCrushPending', '[traced] Victim_MarkGuardCrush sets 1; HitJudge_ResolveGuardPassAndCrush 0x4964D0 turns it into the crush reaction (state 56 on ground, 37 airborne) and clears it; HitJudge_CommitPendingReactions / HitJudge_ResolveHitsOnGuardingVictim test it'),
 (1924, 4, 'Gof2ObjRecoverFlags', 'recoverFlags', '[traced] Victim_SetRecoverBlockFlags 0x43DD00 (3, |=0x10/0x20 when the attack blocks recovery A/B), Victim_EnterReactionState 0x435EA0, sub_499EE0, Obj_SpawnFrameEffectRecord; Obj_CanTechRecover 0x433990 and Yarare_CanTechRecover 0x43E4B0 test (flags&0x22)==2'),
 (1928, 4, 'Gof2ObjRecoverFlags', 'pendingRecoverFlags', '[traced] deferred value of recoverFlags: Obj_ScriptTick copies it to 1924 on landing and clears it; Victim_SetRecoverBlockFlags/Victim_EnterReactionState zero it'),
 (1932, 4, 'struct Gof2Obj *', 'pushbackAttackerRoot', '[traced] root attacker object of the reaction, set by HitJudge_ResolveTick 0x4996A0 (by hit type) and HitJudge_ResolveHitsOnGuardingVictim; Obj_ApplyLandingFrameJump 0x430A40 pushes it (+4592 x) when this object is stopped by the screen edge; 0 = none'),
 (1936, 4, 'int', 'launchAttackerSide', '[traced] attacker side index recorded by Victim_EnterReactionState for launch/sweep states 36..39 (-1 = none, sub_499EE0); Obj_ExecCmdListBetween indexes g_PlayerCharaObj[] with it'),
 (1940, 4, 'int', 'launchAttackerValid', '[traced] 1 when launchAttackerSide is meaningful (states 36..39), 0 otherwise; consumed (-> 0) by sub_495620; tested in Obj_ExecCmdListBetween'),
 (1944, 4, 'int', 'comboStarted', '[traced] set 1 by HitJudge_ApplyHit on the first received hit (and for attacker states 60/62/../78 of the player); HitJudge_ApplyHit/Obj_ExecCmdListBetween read it (`ctl==1 || comboStarted==0`) as the first-hit damage flag; cleared by Yarare_ResetHitState'),
 (1948, 4, 'int', 'counterHitCount', '[traced] ++ on the victim root for each hit with a7==1 (counter/back hit) in HitJudge_ApplyHit; ==1 -> first one resets victimFacingSign; cleared by Yarare_ResetHitState'),
 (1952, 4, 'int', 'launchedByState36', '[traced] HitJudge_CommitPendingReactions sets 1 when the reaction pattern is 36 (launch); HitJudge_StartVictimReaction turns a second airborne launch (36) into 37 while it is 1'),
 (1956, 4, 'int', 'launchDamageScaleApplied', '[traced] sub_495890 (HitJudge_ScaleDamageByComboHits): first damage in states 36/37 is scaled by ControllerManage+336/+340 and the flag set to 1; cleared by Obj_ResetVictimReactionState'),
 (1960, 4, 'int', 'airGuardStunChain', '[traced] HitJudge_ResolveGuardPassAndCrush: ++ each time the guard reaction state is 57 (airborne/high classes), reset to 0 for state 54; sub_43DBE0 halves the speed at ==2 (state 57); HitJudge_ResolveHitsOnGuardingVictim tests ==0/<2'),
 (1964, 4, 'int', 'airHitLatch', '[traced] sub_4339F0 (Obj_TestAirRecoverableHit) sets 1 when the victim is airborne, recover-capable and not ignored; Obj_ExecCmdListBetween / HitJudge_ApplyHit use ==1 to show the HUD popup'),
 (1968, 4, 'int', 'gaugeBonusGranted', '[traced] Obj_ExecStateOpList 0x438A70 script command 39 (0x438C49): on the opposing player object, `if (gaugeBonusGranted == 0) { add DefStatus+484/+488 bonuses to obj+0xFC0/0xFC4; ++gaugeBonusGranted }` (reader = the guard cmp at 0x438C61, writer = add at 0x438CD9); cleared by Yarare_ResetHitState 0x43E3D0 (`yarare->gaugeBonusGranted = 0`)'),
 (1972, 4, 'int', 'juggleHitCount', '[traced] HitJudge_ApplyHit: ++ while the victim is in launch states 36/38/39 (37 < state <= 39), else 0; sub_495620 subtracts count*ControllerManage+780 (capped by +784) from the launch damage'),
 # ---- hit history: which attacker patterns have already hit this victim (class +200..+2247) ----
 (1976, 2048, 'int', 'hitHistoryByAttackerPattern[512]', '[traced] [2 sides][256 patterns]: Yarare_RegisterHit 0x43E500 / sub_43E590 index 4*(attackerSide*256+attackerPattern)+class200, store 1 and report "already hit" for the repeat-move penalty; memset 0x800 in HitJudge_ResolveHitsOnGuardingVictim and Yarare_ResetHitState 0x43E3D0. Extends to Obj+4023 (beyond this range)'),
]
