// GENERATED by tools/ida/gen_cpp_types.py from docs/formats/ida/*_types.h. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include "han2_reflect.h"


#pragma pack(push, 1)
#pragma pack(pop)


static const Han2EnumInfo kMbrTypes.hEnums[] = {
};

